# **Instalasi Library**

In [ ]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **Import Library dan Fungsi Cocoa Time**

In [ ]:
import sqlite3
import os
from datetime import datetime, timedelta, timezone
import pandas as pd
from pathlib import Path


# ------------------------------------------------------------
# Apple Cocoa Time / Mac Absolute Time
#
# Epoch Apple:
# 1 Januari 2001 00:00:00 UTC
# ------------------------------------------------------------

COCOA_EPOCH = datetime(
    2001, 1, 1,
    0, 0, 0,
    tzinfo=timezone.utc
)


def parse_cocoa_time(timestamp):
    """
    Mengonversi Apple Cocoa Time / Mac Absolute Time
    menjadi format tanggal dan waktu UTC.

    Contoh output:
    2020-03-15 10:30:25 UTC
    """

    if timestamp is None:
        return None

    try:
        timestamp = float(timestamp)

        datetime_value = (
            COCOA_EPOCH +
            timedelta(seconds=timestamp)
        )

        return datetime_value.strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        )

    except (
        ValueError,
        TypeError,
        OverflowError
    ):
        return str(timestamp)


print(
    "✅ Library berhasil di-import "
    "dan fungsi Cocoa Time siap digunakan."
)

✅ Library berhasil di-import dan fungsi Cocoa Time siap digunakan.

# **Mount Google Drive**

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

print("✅ Google Drive berhasil dihubungkan.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Google Drive berhasil dihubungkan.

# **Lokasi Dataset Apple Health**

In [ ]:
base_path = (
    "/content/drive/MyDrive/"
    "Colab Notebooks/"
    "Journal Software Impact/"
    "Database iOS Health"
)


mapping_folder = {

    "iOS 13.3.1":
        "iOS_13_3_1",

    "iOS 13.4.1":
        "iOS_13_4_1",

    "iOS 15":
        "iOS_15",

    "iOS 16":
        "iOS_16",

    "iOS 17":
        "iOS_17"
}


print("📁 Base dataset:")
print(base_path)

📁 Base dataset:
/content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health

# **Memilih Versi iOS**

In [ ]:
# @title 🎯 Pilih Versi iOS yang Ingin Diekstrak

pilihan_ios = "Semua Versi (Semua Dataset)" # @param ["Semua Versi (Semua Dataset)", "iOS 13.3.1", "iOS 13.4.1", "iOS 15", "iOS 16", "iOS 17"]


target_datasets = []


if pilihan_ios == "Semua Versi (Semua Dataset)":

    for label, folder in mapping_folder.items():

        target_datasets.append({
            "version": label,
            "path": os.path.join(
                base_path,
                folder
            )
        })

else:

    folder = mapping_folder[pilihan_ios]

    target_datasets.append({
        "version": pilihan_ios,
        "path": os.path.join(
            base_path,
            folder
        )
    })


print()
print("=" * 60)
print("🎯 TARGET EKSTRAKSI")
print("=" * 60)

print(f"Versi iOS : {pilihan_ios}")
print(
    f"Jumlah dataset yang akan diproses : "
    f"{len(target_datasets)}"
)

print("=" * 60)

============================================================
🎯 TARGET EKSTRAKSI
============================================================
Versi iOS : Semua Versi (Semua Dataset)
Jumlah dataset yang akan diproses : 5
============================================================

# **Mencari Kedua Database**

In [ ]:
# ============================================================
# VERIFIKASI DATABASE APPLE HEALTH
# ============================================================

print()
print("=" * 70)
print("🔍 VERIFIKASI DATABASE APPLE HEALTH")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]
    folder_path = dataset["path"]


    print()
    print(f"📱 {version}")
    print(f"📁 {folder_path}")


    # --------------------------------------------------------
    # Periksa folder
    # --------------------------------------------------------

    if not os.path.exists(folder_path):

        print("   ❌ Folder dataset tidak ditemukan.")

        dataset["healthdb"] = None
        dataset["healthdb_secure"] = None

        continue


    # --------------------------------------------------------
    # Ambil daftar file
    # --------------------------------------------------------

    files = os.listdir(folder_path)


    healthdb_path = None
    healthdb_secure_path = None


    # --------------------------------------------------------
    # Cari healthdb dan healthdb_secure
    # --------------------------------------------------------

    for filename in files:

        filename_lower = filename.lower()


        # healthdb_secure.sqlite
        if filename_lower.endswith(
            "healthdb_secure.sqlite"
        ):

            healthdb_secure_path = os.path.join(
                folder_path,
                filename
            )


        # healthdb.sqlite
        elif filename_lower.endswith(
            "healthdb.sqlite"
        ):

            healthdb_path = os.path.join(
                folder_path,
                filename
            )


    # --------------------------------------------------------
    # Simpan path ke target_datasets
    # --------------------------------------------------------

    dataset["healthdb"] = healthdb_path

    dataset["healthdb_secure"] = (
        healthdb_secure_path
    )


    # --------------------------------------------------------
    # Tampilkan hasil
    # --------------------------------------------------------

    if healthdb_path:

        print(
            "   ├─ healthdb.sqlite"
            "        : ✅ Ditemukan"
        )

        print(
            f"   │  └─ {os.path.basename(healthdb_path)}"
        )

    else:

        print(
            "   ├─ healthdb.sqlite"
            "        : ❌ Tidak ditemukan"
        )


    if healthdb_secure_path:

        print(
            "   └─ healthdb_secure.sqlite"
            " : ✅ Ditemukan"
        )

        print(
            f"      └─ "
            f"{os.path.basename(healthdb_secure_path)}"
        )

    else:

        print(
            "   └─ healthdb_secure.sqlite"
            " : ❌ Tidak ditemukan"
        )


print()
print("=" * 70)

======================================================================
🔍 VERIFIKASI DATABASE APPLE HEALTH
======================================================================

📱 iOS 13.3.1
📁 /content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health/iOS_13_3_1
   ├─ healthdb.sqlite        : ✅ Ditemukan
   │  └─ healthdb.sqlite
   └─ healthdb_secure.sqlite : ✅ Ditemukan
      └─ healthdb_secure.sqlite

📱 iOS 13.4.1
📁 /content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health/iOS_13_4_1
   ├─ healthdb.sqlite        : ✅ Ditemukan
   │  └─ healthdb.sqlite
   └─ healthdb_secure.sqlite : ✅ Ditemukan
      └─ healthdb_secure.sqlite

📱 iOS 15
📁 /content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health/iOS_15
   ├─ healthdb.sqlite        : ✅ Ditemukan
   │  └─ healthdb.sqlite
   └─ healthdb_secure.sqlite : ✅ Ditemukan
      └─ healthdb_secure.sqlite

📱 iOS 16
📁 /content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health/iOS_16
   ├─ healthdb.sqlite        : ✅ Ditemukan
   │  └─ healthdb.sqlite
   └─ healthdb_secure.sqlite : ✅ Ditemukan
      └─ healthdb_secure.sqlite

📱 iOS 17
📁 /content/drive/MyDrive/Colab Notebooks/Journal Software Impact/Database iOS Health/iOS_17
   ├─ healthdb.sqlite        : ✅ Ditemukan
   │  └─ healthdb.sqlite
   └─ healthdb_secure.sqlite : ✅ Ditemukan
      └─ healthdb_secure.sqlite

======================================================================

# **Ringkasan Dataset Siap Ekstraksi**

In [ ]:
print()
print("=" * 70)
print("📋 DATASET SIAP UNTUK EKSTRAKSI")
print("=" * 70)


dataset_siap = 0


for dataset in target_datasets:

    version = dataset["version"]

    healthdb = dataset.get("healthdb")

    healthdb_secure = dataset.get(
        "healthdb_secure"
    )


    if healthdb and healthdb_secure:

        status = "✅ SIAP"

        dataset_siap += 1

    else:

        status = "❌ BELUM LENGKAP"


    print(
        f"{version:<12} : {status}"
    )


print("-" * 70)

print(
    f"Dataset siap diproses: "
    f"{dataset_siap}/"
    f"{len(target_datasets)}"
)

print("=" * 70)

======================================================================
📋 DATASET SIAP UNTUK EKSTRAKSI
======================================================================
iOS 13.3.1   : ✅ SIAP
iOS 13.4.1   : ✅ SIAP
iOS 15       : ✅ SIAP
iOS 16       : ✅ SIAP
iOS 17       : ✅ SIAP
----------------------------------------------------------------------
Dataset siap diproses: 5/5
======================================================================

# **Fungsi membuka SQLite Secara Read-only**

In [ ]:
def open_sqlite_readonly(database_path):
    """
    Membuka database SQLite dalam mode read-only.

    Mode ini mencegah script melakukan perubahan terhadap
    database evidence.
    """

    db_path = Path(database_path)

    # Mengubah path menjadi URI yang aman
    db_uri = db_path.resolve().as_uri() + "?mode=ro"

    conn = sqlite3.connect(
        db_uri,
        uri=True
    )

    # Agar hasil query bisa diakses berdasarkan nama kolom
    conn.row_factory = sqlite3.Row

    # Memastikan query bersifat read-only
    conn.execute("PRAGMA query_only = ON")

    return conn


print("✅ Fungsi koneksi SQLite read-only siap digunakan.")

✅ Fungsi koneksi SQLite read-only siap digunakan.

# **Validasi Database SQLite**

In [ ]:
print()
print("=" * 70)
print("🔍 VALIDASI DATABASE SQLITE")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    healthdb_path = dataset.get("healthdb")
    healthdb_secure_path = dataset.get(
        "healthdb_secure"
    )

    print()
    print(f"📱 {version}")


    # --------------------------------------------------------
    # HEALTHDB.SQLITE
    # --------------------------------------------------------

    if healthdb_path:

        try:

            conn = open_sqlite_readonly(
                healthdb_path
            )

            result = conn.execute(
                "PRAGMA quick_check;"
            ).fetchone()

            conn.close()

            print(
                f"   ├─ healthdb.sqlite        : "
                f"✅ SQLite valid ({result[0]})"
            )

        except Exception as e:

            print(
                f"   ├─ healthdb.sqlite        : "
                f"❌ Error"
            )

            print(
                f"   │  └─ {e}"
            )


    # --------------------------------------------------------
    # HEALTHDB_SECURE.SQLITE
    # --------------------------------------------------------

    if healthdb_secure_path:

        try:

            conn = open_sqlite_readonly(
                healthdb_secure_path
            )

            result = conn.execute(
                "PRAGMA quick_check;"
            ).fetchone()

            conn.close()

            print(
                f"   └─ healthdb_secure.sqlite : "
                f"✅ SQLite valid ({result[0]})"
            )

        except Exception as e:

            print(
                f"   └─ healthdb_secure.sqlite : "
                f"❌ Error"
            )

            print(
                f"      └─ {e}"
            )


print()
print("=" * 70)

======================================================================
🔍 VALIDASI DATABASE SQLITE
======================================================================

📱 iOS 13.3.1
   ├─ healthdb.sqlite        : ✅ SQLite valid (ok)
   └─ healthdb_secure.sqlite : ✅ SQLite valid (ok)

📱 iOS 13.4.1
   ├─ healthdb.sqlite        : ✅ SQLite valid (ok)
   └─ healthdb_secure.sqlite : ✅ SQLite valid (ok)

📱 iOS 15
   ├─ healthdb.sqlite        : ✅ SQLite valid (ok)
   └─ healthdb_secure.sqlite : ✅ SQLite valid (ok)

📱 iOS 16
   ├─ healthdb.sqlite        : ✅ SQLite valid (ok)
   └─ healthdb_secure.sqlite : ✅ SQLite valid (ok)

📱 iOS 17
   ├─ healthdb.sqlite        : ✅ SQLite valid (ok)
   └─ healthdb_secure.sqlite : ✅ SQLite valid (ok)

======================================================================

# **Melihat Jumlah dan Daftar Tabel**

In [ ]:
def get_sqlite_tables(database_path):
    """
    Mengambil seluruh nama tabel dari database SQLite.
    """

    conn = open_sqlite_readonly(
        database_path
    )

    query = """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
    """

    rows = conn.execute(query).fetchall()

    tables = [
        row["name"]
        for row in rows
    ]

    conn.close()

    return tables


print("✅ Fungsi pembacaan tabel siap digunakan.")

✅ Fungsi pembacaan tabel siap digunakan.

In [ ]:
print()
print("=" * 70)
print("📊 STRUKTUR DATABASE APPLE HEALTH")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    healthdb_path = dataset["healthdb"]

    healthdb_secure_path = dataset[
        "healthdb_secure"
    ]


    print()
    print(f"📱 {version}")
    print("-" * 70)


    # --------------------------------------------------------
    # HEALTHDB
    # --------------------------------------------------------

    healthdb_tables = get_sqlite_tables(
        healthdb_path
    )

    print(
        f"📂 healthdb.sqlite"
        f" → {len(healthdb_tables)} tabel"
    )


    # --------------------------------------------------------
    # HEALTHDB SECURE
    # --------------------------------------------------------

    secure_tables = get_sqlite_tables(
        healthdb_secure_path
    )

    print(
        f"🔐 healthdb_secure.sqlite"
        f" → {len(secure_tables)} tabel"
    )


    # Simpan hasil ke dataset agar dapat dipakai selanjutnya
    dataset["healthdb_tables"] = (
        healthdb_tables
    )

    dataset["healthdb_secure_tables"] = (
        secure_tables
    )


print()
print("=" * 70)

======================================================================
📊 STRUKTUR DATABASE APPLE HEALTH
======================================================================

📱 iOS 13.3.1
----------------------------------------------------------------------
📂 healthdb.sqlite → 25 tabel
🔐 healthdb_secure.sqlite → 52 tabel

📱 iOS 13.4.1
----------------------------------------------------------------------
📂 healthdb.sqlite → 25 tabel
🔐 healthdb_secure.sqlite → 52 tabel

📱 iOS 15
----------------------------------------------------------------------
📂 healthdb.sqlite → 30 tabel
🔐 healthdb_secure.sqlite → 84 tabel

📱 iOS 16
----------------------------------------------------------------------
📂 healthdb.sqlite → 35 tabel
🔐 healthdb_secure.sqlite → 108 tabel

📱 iOS 17
----------------------------------------------------------------------
📂 healthdb.sqlite → 41 tabel
🔐 healthdb_secure.sqlite → 118 tabel

======================================================================

In [ ]:
for dataset in target_datasets:

    print()
    print("=" * 70)
    print(f"📱 {dataset['version']}")
    print("=" * 70)


    print()
    print("📂 TABEL healthdb.sqlite")
    print("-" * 70)

    for table in dataset[
        "healthdb_tables"
    ]:

        print(table)


    print()
    print("🔐 TABEL healthdb_secure.sqlite")
    print("-" * 70)

    for table in dataset[
        "healthdb_secure_tables"
    ]:

        print(table)

======================================================================
📱 iOS 13.3.1
======================================================================

📂 TABEL healthdb.sqlite
----------------------------------------------------------------------
HealthRecordsPlugin_api_reminders
alarm_events
authorization
cloud_sync_stores
datatype_source_order
key_value
nano_pairing
schema_user_versions
series_builders
source_devices
sources
sqlite_sequence
subscription
subscription_app_launch
sync_anchors
sync_stores
workout_builder_associated_objects
workout_builder_associated_series
workout_builder_data_sources
workout_builder_events
workout_builder_statistics
workout_builders
workout_session_controllers
workout_session_events
workout_sessions

🔐 TABEL healthdb_secure.sqlite
----------------------------------------------------------------------
ACHAchievementsPlugin_earned_instances
ACHAchievementsPlugin_templates
account_owner_samples
activity_caches
activitysharing_competition_lists
activitysharing_competitions
allergy_record_samples
binary_samples
category_samples
cda_documents
clinical_accounts
clinical_authorization_sessions
clinical_credentials
clinical_deleted_accounts
clinical_gateways
clinical_record_samples
concept_index
condition_record_samples
correlations
data_provenances
data_series
devices
diagnostic_test_report_samples
diagnostic_test_result_samples
external_sync_ids
fitness_friend_achievements
fitness_friend_activity_snapshots
fitness_friend_workouts
key_value_secure
medical_records
medication_dispense_record_samples
medication_order_samples
medication_record_samples
metadata_keys
metadata_values
object_authorizations
objects
original_fhir_resources
original_fhir_resources_last_seen
pending_associations
procedure_record_samples
quantity_sample_series
quantity_sample_statistics
quantity_samples
samples
schema_user_versions
sqlite_sequence
unit_strings
unknown_record_samples
vaccination_record_samples
workout_events
workouts

======================================================================
📱 iOS 13.4.1
======================================================================

📂 TABEL healthdb.sqlite
----------------------------------------------------------------------
HealthRecordsPlugin_api_reminders
alarm_events
authorization
cloud_sync_stores
datatype_source_order
key_value
nano_pairing
schema_user_versions
series_builders
source_devices
sources
sqlite_sequence
subscription
subscription_app_launch
sync_anchors
sync_stores
workout_builder_associated_objects
workout_builder_associated_series
workout_builder_data_sources
workout_builder_events
workout_builder_statistics
workout_builders
workout_session_controllers
workout_session_events
workout_sessions

🔐 TABEL healthdb_secure.sqlite
----------------------------------------------------------------------
ACHAchievementsPlugin_earned_instances
ACHAchievementsPlugin_templates
account_owner_samples
activity_caches
activitysharing_competition_lists
activitysharing_competitions
allergy_record_samples
binary_samples
category_samples
cda_documents
clinical_accounts
clinical_authorization_sessions
clinical_credentials
clinical_deleted_accounts
clinical_gateways
clinical_record_samples
concept_index
condition_record_samples
correlations
data_provenances
data_series
devices
diagnostic_test_report_samples
diagnostic_test_result_samples
external_sync_ids
fitness_friend_achievements
fitness_friend_activity_snapshots
fitness_friend_workouts
key_value_secure
medical_records
medication_dispense_record_samples
medication_order_samples
medication_record_samples
metadata_keys
metadata_values
object_authorizations
objects
original_fhir_resources
original_fhir_resources_last_seen
pending_associations
procedure_record_samples
quantity_sample_series
quantity_sample_statistics
quantity_samples
samples
schema_user_versions
sqlite_sequence
unit_strings
unknown_record_samples
vaccination_record_samples
workout_events
workouts

======================================================================
📱 iOS 15
======================================================================

📂 TABEL healthdb.sqlite
----------------------------------------------------------------------
HealthRecordsPlugin_api_reminders
alarm_events
authorization
ck_database_cache
ck_record_cache
ck_record_zone_cache
cloud_sync_stores
datatype_source_order
hearing_headphone_audio_exposure_statistics
key_value
nano_pairing
onboarding_completions
schema_user_versions
series_builders
source_devices
sources
sqlite_sequence
subscription
subscription_app_launch
sync_anchors
sync_stores
workout_builder_associated_objects
workout_builder_associated_series
workout_builder_data_sources
workout_builder_events
workout_builder_statistics
workout_builders
workout_session_controllers
workout_session_events
workout_sessions

🔐 TABEL healthdb_secure.sqlite
----------------------------------------------------------------------
ACHAchievementsPlugin_earned_instances
ACHAchievementsPlugin_templates
account_owner_samples
activity_caches
activitysharing_competition_lists
activitysharing_competitions
ad_hoc_concepts
allergy_record_samples
binary_samples
cached_queries
category_samples
cda_documents
ck_record_cache_secure
clinical_accounts
clinical_authorization_sessions
clinical_credentials
clinical_deleted_accounts
clinical_gateways
clinical_record_samples
concept_index
condition_record_samples
contributors
correlations
coverage_record_samples
data_provenances
data_series
devices
diagnostic_test_report_samples
diagnostic_test_result_samples
ecg_samples
external_sync_ids
fitness_friend_achievements
fitness_friend_activity_snapshots
fitness_friend_workouts
heart_sample_classifications
key_value_secure
list_user_domain_concepts
location_series_data
medical_records
medical_user_domain_concept_category_types
medical_user_domain_concept_mappings
medical_user_domain_concepts
medication_dispense_record_samples
medication_order_samples
medication_record_samples
metadata_keys
metadata_values
object_authorizations
objects
original_fhir_resources
original_fhir_resources_last_seen
original_signed_clinical_data_records
pending_associations
procedure_record_samples
quantity_sample_series
quantity_sample_statistics
quantity_samples
quantity_series_data
sample_aggregate_caches
samples
schema_user_versions
shared_summaries
shared_summary_authorization_categories
shared_summary_object_types
shared_summary_transaction_metadata
shared_summary_transactions
sharing_authorizations
sharing_relationship
signed_clinical_data_issuer
signed_clinical_data_record_samples
sleep_schedule_samples
sqlite_sequence
summary_sharing_entry
unit_strings
unknown_record_samples
user_domain_concept_links
user_domain_concept_properties
user_domain_concepts
user_domain_medical_coding_strings
user_domain_medical_codings
vaccination_record_samples
verifiable_clinical_record_samples
workout_events
workouts

======================================================================
📱 iOS 16
======================================================================

📂 TABEL healthdb.sqlite
----------------------------------------------------------------------
HealthRecordsPlugin_api_reminders
WorkoutHealthPlugin_workout_configurations
alarm_events
authorization
ck_database_cache
ck_record_cache
ck_record_zone_cache
cloud_sync_stores
datatype_source_order
hearing_headphone_audio_exposure_statistics
key_value
logical_source_order
logical_sources
nano_pairing
onboarding_completions
schema_user_versions
series_builders
source_devices
sources
sqlite_sequence
subscription
subscription_app_launch
sync_anchors
sync_identities
sync_stores
workout_builder_activities
workout_builder_associated_objects
workout_builder_associated_series
workout_builder_data_sources
workout_builder_events
workout_builder_statistics
workout_builders
workout_session_controllers
workout_session_events
workout_sessions

🔐 TABEL healthdb_secure.sqlite
----------------------------------------------------------------------
ACHAchievementsPlugin_earned_instances
ACHAchievementsPlugin_templates
RacePreviousRoute_concrete_cluster
RacePreviousRoute_generation_queue
RacePreviousRoute_location_series
RacePreviousRoute_route_snapshot
RacePreviousRoute_workout_cluster
RacePreviousRoute_workout_cluster_components
account_owner_samples
activity_caches
activitysharing_competition_lists
activitysharing_competitions
ad_hoc_concepts
allergy_record_samples
attachment_references
attachments
binary_samples
cached_queries
category_samples
cda_documents
ck_record_cache_secure
clinical_account_events
clinical_accounts
clinical_authorization_sessions
clinical_credentials
clinical_deleted_accounts
clinical_gateways
clinical_record_samples
concept_index
condition_record_samples
contributors
correlations
coverage_record_samples
data_provenances
data_series
devices
diagnostic_test_report_samples
diagnostic_test_result_samples
ecg_samples
external_sync_ids
fitness_friend_achievements
fitness_friend_activity_snapshots
fitness_friend_workouts
heart_sample_classifications
key_value_secure
list_user_domain_concepts
location_series_data
medical_records
medical_user_domain_concept_category_types
medical_user_domain_concept_mappings
medical_user_domain_concepts
medication_dismissed_interactions
medication_dispense_record_samples
medication_dose_event_samples
medication_order_samples
medication_record_samples
medication_schedule_interval_data
medication_schedule_items
medication_schedules
medication_user_domain_concepts
metadata_keys
metadata_values
object_authorizations
objects
original_fhir_resources
original_fhir_resources_last_seen
original_signed_clinical_data_records
pending_associations
procedure_record_samples
quantity_sample_series
quantity_sample_statistics
quantity_samples
quantity_series_data
sample_aggregate_caches
samples
schema_user_versions
shared_summaries
shared_summary_authorization_categories
shared_summary_object_types
shared_summary_transaction_metadata
shared_summary_transactions
sharing_authorizations
sharing_relationship
signed_clinical_data_issuer
signed_clinical_data_record_samples
sleep_schedule_samples
sqlite_sequence
summary_sharing_entry
unit_strings
unknown_record_samples
user_domain_concept_education_content
user_domain_concept_education_content_section_data
user_domain_concept_education_content_section_data_strings
user_domain_concept_education_content_sections
user_domain_concept_links
user_domain_concept_localized_strings
user_domain_concept_named_quantities
user_domain_concept_properties
user_domain_concepts
user_domain_medical_coding_strings
user_domain_medical_codings
vaccination_record_samples
verifiable_clinical_record_samples
vision_prescription
workout_activities
workout_events
workout_statistics
workouts

======================================================================
📱 iOS 17
======================================================================

📂 TABEL healthdb.sqlite
----------------------------------------------------------------------
HealthRecordsPlugin_api_reminders
WorkoutHealthPlugin_workout_configurations
WorkoutHealthPlugin_workout_external_configuration_providers
WorkoutHealthPlugin_workout_managed_configurations
alarm_events
authorization
cached_sync_requests
ck_database_cache
ck_record_cache
ck_record_zone_cache
cloud_sync_stores
datatype_source_order
device_context
hearing_headphone_audio_exposure_statistics
key_value
kv_device_storage
logical_source_order
logical_sources
nano_pairing
notification_instructions
onboarding_completions
schema_user_versions
series_builders
source_devices
sources
sqlite_sequence
subscription
subscription_app_launch
sync_anchors
sync_identities
sync_stores
workout_builder_activities
workout_builder_associated_objects
workout_builder_associated_series
workout_builder_data_sources
workout_builder_events
workout_builder_statistics
workout_builders
workout_session_controllers
workout_session_events
workout_sessions

🔐 TABEL healthdb_secure.sqlite
----------------------------------------------------------------------
ACHAchievementsPlugin_earned_instances
ACHAchievementsPlugin_templates
RacePreviousRoute_concrete_cluster
RacePreviousRoute_generation_queue
RacePreviousRoute_location_series
RacePreviousRoute_route_snapshot
RacePreviousRoute_workout
RacePreviousRoute_workout_cluster
RacePreviousRoute_workout_cluster_components
account_owner_samples
activity_caches
activitysharing_competition_lists
activitysharing_competitions
ad_hoc_concepts
allergy_record_samples
associations
attachment_references
attachments
binary_samples
cached_queries
category_samples
cda_documents
ck_record_cache_secure
clinical_account_events
clinical_accounts
clinical_authorization_sessions
clinical_credentials
clinical_deleted_accounts
clinical_gateways
clinical_note_record_samples
clinical_record_samples
concept_index
condition_record_samples
contributors
coverage_record_samples
data_provenances
data_series
devices
diagnostic_test_report_samples
diagnostic_test_result_samples
ecg_samples
external_sync_ids
fitness_friend_achievements
fitness_friend_activity_snapshots
fitness_friend_workouts
heart_sample_classifications
key_value_secure
list_user_domain_concepts
location_series_data
medical_downloadable_attachments
medical_records
medical_user_domain_concept_category_types
medical_user_domain_concept_mappings
medical_user_domain_concepts
medication_dismissed_interactions
medication_dispense_record_samples
medication_dose_event_samples
medication_order_samples
medication_record_samples
medication_schedule_interval_data
medication_schedule_items
medication_schedules
medication_user_domain_concepts
metadata_keys
metadata_values
object_authorizations
objects
original_fhir_resources
original_fhir_resources_last_seen
original_signed_clinical_data_records
pending_associations
procedure_record_samples
quantity_sample_series
quantity_sample_statistics
quantity_samples
quantity_series_data
sample_aggregate_caches
samples
schema_user_versions
scored_assessment_samples
secure_kv_device_storage
shared_summaries
shared_summary_authorization_categories
shared_summary_object_types
shared_summary_transaction_metadata
shared_summary_transactions
sharing_authorizations
sharing_relationship
signed_clinical_data_issuer
signed_clinical_data_record_samples
sleep_schedule_samples
sqlite_sequence
state_of_mind_domains
state_of_mind_labels
state_of_mind_samples
summary_sharing_entry
unit_strings
unknown_record_samples
user_domain_concept_education_content
user_domain_concept_education_content_section_data
user_domain_concept_education_content_section_data_strings
user_domain_concept_education_content_sections
user_domain_concept_links
user_domain_concept_localized_strings
user_domain_concept_named_quantities
user_domain_concept_properties
user_domain_concepts
user_domain_medical_coding_strings
user_domain_medical_codings
vaccination_record_samples
verifiable_clinical_record_samples
vision_prescription
workout_activities
workout_events
workout_statistics
workout_zones_associations
workout_zones_samples
workouts

# **Fitur Achievements**

In [ ]:
# ============================================================
# CEK TABEL ACHIEVEMENTS
# ============================================================

ACHIEVEMENT_TABLE = (
    "ACHAchievementsPlugin_earned_instances"
)


print()
print("=" * 70)
print("🏆 PEMERIKSAAN TABEL ACHIEVEMENTS")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    if ACHIEVEMENT_TABLE in secure_tables:

        print(
            f"{version:<12} : "
            f"✅ Tabel ditemukan"
        )

    else:

        print(
            f"{version:<12} : "
            f"❌ Tabel tidak ditemukan"
        )


print("=" * 70)

======================================================================
🏆 PEMERIKSAAN TABEL ACHIEVEMENTS
======================================================================
iOS 13.3.1   : ✅ Tabel ditemukan
iOS 13.4.1   : ✅ Tabel ditemukan
iOS 15       : ✅ Tabel ditemukan
iOS 16       : ✅ Tabel ditemukan
iOS 17       : ✅ Tabel ditemukan
======================================================================

In [ ]:
# ============================================================
# MEMBACA KOLOM TABEL
# ============================================================

def get_table_columns(
    database_path,
    table_name
):

    conn = open_sqlite_readonly(
        database_path
    )

    query = (
        f'PRAGMA table_info("{table_name}");'
    )

    rows = conn.execute(
        query
    ).fetchall()

    conn.close()


    columns = []

    for row in rows:

        columns.append({
            "cid": row["cid"],
            "name": row["name"],
            "type": row["type"],
            "notnull": row["notnull"],
            "pk": row["pk"]
        })


    return columns

In [ ]:
# ============================================================
# LIHAT STRUKTUR TABEL ACHIEVEMENTS
# ============================================================

for dataset in target_datasets:

    version = dataset["version"]

    secure_path = dataset[
        "healthdb_secure"
    ]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    print()
    print("=" * 70)
    print(f"🏆 ACHIEVEMENTS - {version}")
    print("=" * 70)


    if ACHIEVEMENT_TABLE not in secure_tables:

        print(
            "❌ Tabel Achievements "
            "tidak ditemukan."
        )

        continue


    columns = get_table_columns(
        secure_path,
        ACHIEVEMENT_TABLE
    )


    df_columns = pd.DataFrame(
        columns
    )


    display(df_columns)

======================================================================
🏆 ACHIEVEMENTS - iOS 13.3.1
======================================================================

   cid                     name     type  notnull  pk
0    0                    ROWID  INTEGER        0   1
1    1     template_unique_name     TEXT        0   0
2    2             created_date     REAL        0   0
3    3              earned_date     TEXT        0   0
4    4  value_in_canonical_unit     REAL        0   0
5    5     value_canonical_unit     TEXT        0   0
6    6           creator_device  INTEGER        0   0
7    7          sync_provenance  INTEGER        0   0

======================================================================
🏆 ACHIEVEMENTS - iOS 13.4.1
======================================================================

   cid                     name     type  notnull  pk
0    0                    ROWID  INTEGER        0   1
1    1     template_unique_name     TEXT        0   0
2    2             created_date     REAL        0   0
3    3              earned_date     TEXT        0   0
4    4  value_in_canonical_unit     REAL        0   0
5    5     value_canonical_unit     TEXT        0   0
6    6           creator_device  INTEGER        0   0
7    7          sync_provenance  INTEGER        0   0

======================================================================
🏆 ACHIEVEMENTS - iOS 15
======================================================================

   cid                     name     type  notnull  pk
0    0                    ROWID  INTEGER        0   1
1    1     template_unique_name     TEXT        0   0
2    2             created_date     REAL        0   0
3    3              earned_date     TEXT        0   0
4    4  value_in_canonical_unit     REAL        0   0
5    5     value_canonical_unit     TEXT        0   0
6    6           creator_device  INTEGER        0   0
7    7          sync_provenance  INTEGER        0   0

======================================================================
🏆 ACHIEVEMENTS - iOS 16
======================================================================

   cid                     name     type  notnull  pk
0    0                    ROWID  INTEGER        0   1
1    1     template_unique_name     TEXT        0   0
2    2             created_date     REAL        0   0
3    3              earned_date     TEXT        0   0
4    4  value_in_canonical_unit     REAL        0   0
5    5     value_canonical_unit     TEXT        0   0
6    6      external_identifier     TEXT        0   0
7    7           creator_device  INTEGER        0   0
8    8          sync_provenance  INTEGER        0   0

======================================================================
🏆 ACHIEVEMENTS - iOS 17
======================================================================

   cid                     name     type  notnull  pk
0    0                    ROWID  INTEGER        0   1
1    1     template_unique_name     TEXT        0   0
2    2             created_date     REAL        0   0
3    3              earned_date     TEXT        0   0
4    4  value_in_canonical_unit     REAL        0   0
5    5     value_canonical_unit     TEXT        0   0
6    6      external_identifier     TEXT        0   0
7    7           creator_device  INTEGER        0   0
8    8          sync_provenance  INTEGER        0   0
9    9            sync_identity  INTEGER        1   0

In [ ]:
# ============================================================
# EKSTRAKSI DATA ACHIEVEMENTS
# ============================================================

def extract_achievements(database_path):
    """
    Mengekstrak data Apple Health Achievements dari
    tabel ACHAchievementsPlugin_earned_instances.

    Database dibuka secara read-only.
    """

    conn = open_sqlite_readonly(database_path)

    query = """
    SELECT
        ROWID,
        template_unique_name,
        created_date,
        earned_date,
        value_in_canonical_unit,
        value_canonical_unit,
        creator_device,
        sync_provenance

    FROM
        ACHAchievementsPlugin_earned_instances
    """

    df = pd.read_sql_query(
        query,
        conn
    )

    conn.close()

    return df


print("✅ Fungsi extractor Achievements siap digunakan.")

✅ Fungsi extractor Achievements siap digunakan.

In [ ]:
# ============================================================
# MENJALANKAN EXTRACTOR ACHIEVEMENTS
# ============================================================

achievement_results = {}


for dataset in target_datasets:

    version = dataset["version"]

    secure_path = dataset[
        "healthdb_secure"
    ]

    print()
    print("=" * 70)
    print(f"🏆 EKSTRAKSI ACHIEVEMENTS - {version}")
    print("=" * 70)


    try:

        df_achievements = extract_achievements(
            secure_path
        )


        achievement_results[
            version
        ] = df_achievements


        print(
            f"✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total event ditemukan: "
            f"{len(df_achievements)}"
        )


    except Exception as e:

        print(
            f"❌ Ekstraksi gagal: {e}"
        )

======================================================================
🏆 EKSTRAKSI ACHIEVEMENTS - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total event ditemukan: 8

======================================================================
🏆 EKSTRAKSI ACHIEVEMENTS - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total event ditemukan: 8

======================================================================
🏆 EKSTRAKSI ACHIEVEMENTS - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total event ditemukan: 0

======================================================================
🏆 EKSTRAKSI ACHIEVEMENTS - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total event ditemukan: 30

======================================================================
🏆 EKSTRAKSI ACHIEVEMENTS - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total event ditemukan: 38

In [ ]:
# ============================================================
# PREVIEW DATA MENTAH ACHIEVEMENTS
# ============================================================

for version, df in achievement_results.items():

    print()
    print("=" * 70)
    print(f"🏆 RAW ACHIEVEMENTS DATA - {version}")
    print("=" * 70)

    display(
        df.head(10)
    )

======================================================================
🏆 RAW ACHIEVEMENTS DATA - iOS 13.3.1
======================================================================

,ROWID,template_unique_name,created_date,earned_date,value_in_canonical_unit,value_canonical_unit,creator_device,sync_provenance
0,1,NewMoveGoalAchieved,6.066932e+08,2020-03-23,480.000000,kcal,1,1
1,2,FirstWorkout-HKWorkoutActivityTypeRunning,6.070293e+08,2020-03-27,NaN,None,1,1
2,3,PerfectWeekStand,6.072095e+08,2020-03-29,8.000000,count,1,1
3,20,NewMoveRecord,6.073159e+08,2020-03-30,881.534000,kcal,1,1
4,21,NewExerciseRecord,6.073151e+08,2020-03-30,77.000000,min,1,1
5,22,LongestMoveStreak,6.075430e+08,2020-04-02,8.000000,count,1,1
6,23,LongestMoveStreak,6.076346e+08,2020-04-03,9.000000,count,1,1
7,24,BestWorkout-HKWorkoutActivityTypeRunning,6.076355e+08,2020-04-03,369.850771,kcal,1,1

======================================================================
🏆 RAW ACHIEVEMENTS DATA - iOS 13.4.1
======================================================================

,ROWID,template_unique_name,created_date,earned_date,value_in_canonical_unit,value_canonical_unit,creator_device,sync_provenance
0,1,NewMoveGoalAchieved,6.066932e+08,2020-03-23,480.000000,kcal,1,1
1,2,FirstWorkout-HKWorkoutActivityTypeRunning,6.070293e+08,2020-03-27,NaN,None,1,1
2,3,PerfectWeekStand,6.072095e+08,2020-03-29,8.000000,count,1,1
3,20,NewMoveRecord,6.073159e+08,2020-03-30,881.534000,kcal,1,1
4,21,NewExerciseRecord,6.073151e+08,2020-03-30,77.000000,min,1,1
5,22,LongestMoveStreak,6.075430e+08,2020-04-02,8.000000,count,1,1
6,23,LongestMoveStreak,6.076346e+08,2020-04-03,9.000000,count,1,1
7,24,BestWorkout-HKWorkoutActivityTypeRunning,6.076355e+08,2020-04-03,369.850771,kcal,1,1

======================================================================
🏆 RAW ACHIEVEMENTS DATA - iOS 15
======================================================================

Empty DataFrame
Columns: [ROWID, template_unique_name, created_date, earned_date, value_in_canonical_unit, value_canonical_unit, creator_device, sync_provenance]
Index: []

======================================================================
🏆 RAW ACHIEVEMENTS DATA - iOS 16
======================================================================

,ROWID,template_unique_name,created_date,earned_date,value_in_canonical_unit,value_canonical_unit,creator_device,sync_provenance
0,1,BestWorkoutDistance-HKWorkoutActivityTypeRunning,7.099360e+08,2021-01-30,4977.984474,m,2,0
1,2,BestWorkoutDistance-HKWorkoutActivityTypeRunning,7.099360e+08,2021-01-24,4889.448696,m,2,0
2,3,FirstWorkout-HKWorkoutActivityTypeWalking,7.099360e+08,2021-01-30,NaN,None,2,0
3,4,FirstWorkout-HKWorkoutActivityTypeRunning,7.099360e+08,2020-03-27,NaN,None,2,0
4,5,BestWorkout-HKWorkoutActivityTypeRunning,7.099360e+08,2020-04-03,369.850771,kcal,2,0
5,6,PerfectWeekMove,7.099364e+08,2021-01-10,11.000000,count,2,0
6,7,PerfectWeekStand,7.099364e+08,2021-01-10,11.000000,count,2,0
7,8,PerfectWeekStand,7.099364e+08,2020-03-29,8.000000,count,2,0
8,9,NewExerciseRecord,7.099364e+08,2020-03-30,77.000000,min,2,0
9,10,NewExerciseRecord,7.099364e+08,2021-01-30,91.000000,min,2,0

======================================================================
🏆 RAW ACHIEVEMENTS DATA - iOS 17
======================================================================

,ROWID,template_unique_name,created_date,earned_date,value_in_canonical_unit,value_canonical_unit,creator_device,sync_provenance
0,1,BestWorkoutDistance-HKWorkoutActivityTypeRunning,7.099360e+08,2021-01-30,4977.984474,m,2,0
1,2,BestWorkoutDistance-HKWorkoutActivityTypeRunning,7.099360e+08,2021-01-24,4889.448696,m,2,0
2,3,FirstWorkout-HKWorkoutActivityTypeWalking,7.099360e+08,2021-01-30,NaN,None,2,0
3,4,FirstWorkout-HKWorkoutActivityTypeRunning,7.099360e+08,2020-03-27,NaN,None,2,0
4,5,BestWorkout-HKWorkoutActivityTypeRunning,7.099360e+08,2020-04-03,369.850771,kcal,2,0
5,6,PerfectWeekMove,7.099364e+08,2021-01-10,11.000000,count,2,0
6,7,PerfectWeekStand,7.099364e+08,2021-01-10,11.000000,count,2,0
7,8,PerfectWeekStand,7.099364e+08,2020-03-29,8.000000,count,2,0
8,9,NewExerciseRecord,7.099364e+08,2020-03-30,77.000000,min,2,0
9,10,NewExerciseRecord,7.099364e+08,2021-01-30,91.000000,min,2,0

In [ ]:
# ============================================================
# FORMAT OUTPUT ACHIEVEMENTS SEPERTI iLEAPP
# ============================================================

def parse_cocoa_datetime(timestamp):
    """
    Mengonversi Apple Cocoa Time menjadi datetime UTC
    timezone-aware.

    Contoh output:
    2020-04-03 19:37:50+00:00
    """

    if timestamp is None:
        return pd.NaT

    try:
        timestamp = float(timestamp)

        dt = (
            COCOA_EPOCH
            + timedelta(seconds=timestamp)
        )

        return dt

    except (
        ValueError,
        TypeError,
        OverflowError
    ):
        return pd.NaT


achievement_reports = {}


for version, df in achievement_results.items():

    # Membuat DataFrame baru untuk laporan
    # sehingga data mentah tidak berubah
    df_report = pd.DataFrame()

    df_report["Created Timestamp"] = (
        df["created_date"]
        .apply(parse_cocoa_datetime)
    )

    df_report["Earned Date"] = (
        df["earned_date"]
    )

    df_report["Achievement"] = (
        df["template_unique_name"]
    )

    df_report["Value"] = (
        df["value_in_canonical_unit"]
    )

    df_report["Unit"] = (
        df["value_canonical_unit"]
    )

    df_report["Creator Device"] = (
        df["creator_device"]
    )

    df_report["Sync Provenance"] = (
        df["sync_provenance"]
    )

    # Menambahkan sumber database
    df_report["Source"] = (
        "healthdb_secure.sqlite"
    )

    achievement_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Achievements "
    "berhasil dibuat."
)

✅ Format laporan Achievements berhasil dibuat.

In [ ]:
# ============================================================
# PREVIEW LAPORAN ACHIEVEMENTS
# ============================================================

for version, df_report in achievement_reports.items():

    print()
    print("=" * 70)
    print(f"🏆 ACHIEVEMENTS - {version}")
    print("=" * 70)

    display(
        df_report.head(20)
    )

    print()
    print(
        f"📊 Total Achievements Events: "
        f"{len(df_report)}"
    )

======================================================================
🏆 ACHIEVEMENTS - iOS 13.3.1
======================================================================

,Created Timestamp,Earned Date,Achievement,Value,Unit,Creator Device,Sync Provenance,Source
0,2020-03-23 21:53:00.233905+00:00,2020-03-23,NewMoveGoalAchieved,480.000000,kcal,1,1,healthdb_secure.sqlite
1,2020-03-27 19:15:40.337785+00:00,2020-03-27,FirstWorkout-HKWorkoutActivityTypeRunning,NaN,None,1,1,healthdb_secure.sqlite
2,2020-03-29 21:19:09.184229+00:00,2020-03-29,PerfectWeekStand,8.000000,count,1,1,healthdb_secure.sqlite
3,2020-03-31 02:50:55.595727+00:00,2020-03-30,NewMoveRecord,881.534000,kcal,1,1,healthdb_secure.sqlite
4,2020-03-31 02:38:35.803085+00:00,2020-03-30,NewExerciseRecord,77.000000,min,1,1,healthdb_secure.sqlite
5,2020-04-02 17:56:07.162647+00:00,2020-04-02,LongestMoveStreak,8.000000,count,1,1,healthdb_secure.sqlite
6,2020-04-03 19:23:54.321824+00:00,2020-04-03,LongestMoveStreak,9.000000,count,1,1,healthdb_secure.sqlite
7,2020-04-03 19:37:50.841831+00:00,2020-04-03,BestWorkout-HKWorkoutActivityTypeRunning,369.850771,kcal,1,1,healthdb_secure.sqlite

📊 Total Achievements Events: 8

======================================================================
🏆 ACHIEVEMENTS - iOS 13.4.1
======================================================================

,Created Timestamp,Earned Date,Achievement,Value,Unit,Creator Device,Sync Provenance,Source
0,2020-03-23 21:53:00.233905+00:00,2020-03-23,NewMoveGoalAchieved,480.000000,kcal,1,1,healthdb_secure.sqlite
1,2020-03-27 19:15:40.337785+00:00,2020-03-27,FirstWorkout-HKWorkoutActivityTypeRunning,NaN,None,1,1,healthdb_secure.sqlite
2,2020-03-29 21:19:09.184229+00:00,2020-03-29,PerfectWeekStand,8.000000,count,1,1,healthdb_secure.sqlite
3,2020-03-31 02:50:55.595727+00:00,2020-03-30,NewMoveRecord,881.534000,kcal,1,1,healthdb_secure.sqlite
4,2020-03-31 02:38:35.803085+00:00,2020-03-30,NewExerciseRecord,77.000000,min,1,1,healthdb_secure.sqlite
5,2020-04-02 17:56:07.162647+00:00,2020-04-02,LongestMoveStreak,8.000000,count,1,1,healthdb_secure.sqlite
6,2020-04-03 19:23:54.321824+00:00,2020-04-03,LongestMoveStreak,9.000000,count,1,1,healthdb_secure.sqlite
7,2020-04-03 19:37:50.841831+00:00,2020-04-03,BestWorkout-HKWorkoutActivityTypeRunning,369.850771,kcal,1,1,healthdb_secure.sqlite

📊 Total Achievements Events: 8

======================================================================
🏆 ACHIEVEMENTS - iOS 15
======================================================================

Empty DataFrame
Columns: [Created Timestamp, Earned Date, Achievement, Value, Unit, Creator Device, Sync Provenance, Source]
Index: []

📊 Total Achievements Events: 0

======================================================================
🏆 ACHIEVEMENTS - iOS 16
======================================================================

,Created Timestamp,Earned Date,Achievement,Value,Unit,Creator Device,Sync Provenance,Source
0,2023-07-01 20:26:07.108580+00:00,2021-01-30,BestWorkoutDistance-HKWorkoutActivityTypeRunning,4977.984474,m,2,0,healthdb_secure.sqlite
1,2023-07-01 20:26:07.108580+00:00,2021-01-24,BestWorkoutDistance-HKWorkoutActivityTypeRunning,4889.448696,m,2,0,healthdb_secure.sqlite
2,2023-07-01 20:26:07.108580+00:00,2021-01-30,FirstWorkout-HKWorkoutActivityTypeWalking,NaN,None,2,0,healthdb_secure.sqlite
3,2023-07-01 20:26:07.389037+00:00,2020-03-27,FirstWorkout-HKWorkoutActivityTypeRunning,NaN,None,2,0,healthdb_secure.sqlite
4,2023-07-01 20:26:07.389037+00:00,2020-04-03,BestWorkout-HKWorkoutActivityTypeRunning,369.850771,kcal,2,0,healthdb_secure.sqlite
5,2023-07-01 20:33:15.883982+00:00,2021-01-10,PerfectWeekMove,11.000000,count,2,0,healthdb_secure.sqlite
6,2023-07-01 20:33:15.883982+00:00,2021-01-10,PerfectWeekStand,11.000000,count,2,0,healthdb_secure.sqlite
7,2023-07-01 20:33:15.883982+00:00,2020-03-29,PerfectWeekStand,8.000000,count,2,0,healthdb_secure.sqlite
8,2023-07-01 20:33:15.883982+00:00,2020-03-30,NewExerciseRecord,77.000000,min,2,0,healthdb_secure.sqlite
9,2023-07-01 20:33:15.883982+00:00,2021-01-30,NewExerciseRecord,91.000000,min,2,0,healthdb_secure.sqlite
10,2023-07-01 20:33:15.883982+00:00,2021-01-24,NewExerciseRecord,83.000000,min,2,0,healthdb_secure.sqlite
11,2023-07-01 20:33:15.883982+00:00,2021-01-09,LongestMoveStreak,10.000000,count,2,0,healthdb_secure.sqlite
12,2023-07-01 20:33:15.883982+00:00,2021-01-11,LongestMoveStreak,12.000000,count,2,0,healthdb_secure.sqlite
13,2023-07-01 20:33:15.883982+00:00,2021-01-12,LongestMoveStreak,13.000000,count,2,0,healthdb_secure.sqlite
14,2023-07-01 20:33:15.883982+00:00,2021-01-15,LongestMoveStreak,16.000000,count,2,0,healthdb_secure.sqlite
15,2023-07-01 20:33:15.883982+00:00,2020-04-02,LongestMoveStreak,8.000000,count,2,0,healthdb_secure.sqlite
16,2023-07-01 20:33:15.883982+00:00,2021-01-13,LongestMoveStreak,14.000000,count,2,0,healthdb_secure.sqlite
17,2023-07-01 20:33:15.883982+00:00,2020-04-03,LongestMoveStreak,9.000000,count,2,0,healthdb_secure.sqlite
18,2023-07-01 20:33:15.883982+00:00,2021-01-10,LongestMoveStreak,11.000000,count,2,0,healthdb_secure.sqlite
19,2023-07-01 20:33:15.883982+00:00,2021-01-14,LongestMoveStreak,15.000000,count,2,0,healthdb_secure.sqlite

📊 Total Achievements Events: 30

======================================================================
🏆 ACHIEVEMENTS - iOS 17
======================================================================

,Created Timestamp,Earned Date,Achievement,Value,Unit,Creator Device,Sync Provenance,Source
0,2023-07-01 20:26:07.108580+00:00,2021-01-30,BestWorkoutDistance-HKWorkoutActivityTypeRunning,4977.984474,m,2,0,healthdb_secure.sqlite
1,2023-07-01 20:26:07.108580+00:00,2021-01-24,BestWorkoutDistance-HKWorkoutActivityTypeRunning,4889.448696,m,2,0,healthdb_secure.sqlite
2,2023-07-01 20:26:07.108580+00:00,2021-01-30,FirstWorkout-HKWorkoutActivityTypeWalking,NaN,None,2,0,healthdb_secure.sqlite
3,2023-07-01 20:26:07.389037+00:00,2020-03-27,FirstWorkout-HKWorkoutActivityTypeRunning,NaN,None,2,0,healthdb_secure.sqlite
4,2023-07-01 20:26:07.389037+00:00,2020-04-03,BestWorkout-HKWorkoutActivityTypeRunning,369.850771,kcal,2,0,healthdb_secure.sqlite
5,2023-07-01 20:33:15.883982+00:00,2021-01-10,PerfectWeekMove,11.000000,count,2,0,healthdb_secure.sqlite
6,2023-07-01 20:33:15.883982+00:00,2021-01-10,PerfectWeekStand,11.000000,count,2,0,healthdb_secure.sqlite
7,2023-07-01 20:33:15.883982+00:00,2020-03-29,PerfectWeekStand,8.000000,count,2,0,healthdb_secure.sqlite
8,2023-07-01 20:33:15.883982+00:00,2020-03-30,NewExerciseRecord,77.000000,min,2,0,healthdb_secure.sqlite
9,2023-07-01 20:33:15.883982+00:00,2021-01-30,NewExerciseRecord,91.000000,min,2,0,healthdb_secure.sqlite
10,2023-07-01 20:33:15.883982+00:00,2021-01-24,NewExerciseRecord,83.000000,min,2,0,healthdb_secure.sqlite
11,2023-07-01 20:33:15.883982+00:00,2021-01-09,LongestMoveStreak,10.000000,count,2,0,healthdb_secure.sqlite
12,2023-07-01 20:33:15.883982+00:00,2021-01-11,LongestMoveStreak,12.000000,count,2,0,healthdb_secure.sqlite
13,2023-07-01 20:33:15.883982+00:00,2021-01-12,LongestMoveStreak,13.000000,count,2,0,healthdb_secure.sqlite
14,2023-07-01 20:33:15.883982+00:00,2021-01-15,LongestMoveStreak,16.000000,count,2,0,healthdb_secure.sqlite
15,2023-07-01 20:33:15.883982+00:00,2020-04-02,LongestMoveStreak,8.000000,count,2,0,healthdb_secure.sqlite
16,2023-07-01 20:33:15.883982+00:00,2021-01-13,LongestMoveStreak,14.000000,count,2,0,healthdb_secure.sqlite
17,2023-07-01 20:33:15.883982+00:00,2020-04-03,LongestMoveStreak,9.000000,count,2,0,healthdb_secure.sqlite
18,2023-07-01 20:33:15.883982+00:00,2021-01-10,LongestMoveStreak,11.000000,count,2,0,healthdb_secure.sqlite
19,2023-07-01 20:33:15.883982+00:00,2021-01-14,LongestMoveStreak,15.000000,count,2,0,healthdb_secure.sqlite

📊 Total Achievements Events: 38

# **Fitur All Watch Sleep**

In [ ]:
# ============================================================
# FUNGSI KONVERSI DURASI KE HH:MM:SS
# ============================================================

def seconds_to_hms(seconds_value):
    """
    Mengonversi durasi dalam detik menjadi HH:MM:SS.

    Contoh:
    3665 detik -> 01:01:05
    """

    if seconds_value is None:
        return None

    try:
        total = int(float(seconds_value))

    except (TypeError, ValueError):
        return None


    hours = total // 3600

    minutes = (
        total % 3600
    ) // 60

    seconds = total % 60


    return (
        f"{hours:02d}:"
        f"{minutes:02d}:"
        f"{seconds:02d}"
    )


print(
    "✅ Fungsi konversi durasi siap digunakan."
)

✅ Fungsi konversi durasi siap digunakan.

In [ ]:
# ============================================================
# EXTRACTOR ALL WATCH SLEEP
# ============================================================

def extract_all_watch_sleep(
    database_path,
    ios_version
):
    """
    Mengekstrak data All Watch Sleep dari
    healthdb_secure.sqlite.

    Query:
    - iOS 13.3.1 sampai iOS 16
    - iOS 17

    mengikuti logika plugin Plaso yang telah dibuat.
    """

    conn = open_sqlite_readonly(
        database_path
    )


    # ========================================================
    # iOS 17
    # ========================================================

    if ios_version == "iOS 17":

        query = """
        SELECT
            s.start_date AS start_cocoa,
            s.end_date AS end_cocoa,
            cs.value AS state_code

        FROM samples s

        JOIN category_samples cs
            ON s.data_id = cs.data_id

        ORDER BY
            s.start_date ASC
        """


        df = pd.read_sql_query(
            query,
            conn
        )


        # ----------------------------------------------------
        # Sesuai ParseSleepRow pada plugin Plaso iOS 17:
        #
        # hanya state code:
        # 2, 3, 4, 5
        # ----------------------------------------------------

        df["state_code"] = pd.to_numeric(
            df["state_code"],
            errors="coerce"
        )


        df = df[
            df["state_code"].isin(
                [2, 3, 4, 5]
            )
        ].copy()


        # Ubah menjadi integer
        df["state_code"] = (
            df["state_code"]
            .astype(int)
        )


    # ========================================================
    # iOS 13.3.1 - iOS 16
    # ========================================================

    else:

        query = """
        SELECT
            s.start_date AS start_cocoa,
            s.end_date AS end_cocoa,
            cs.value AS state_code

        FROM samples s

        LEFT JOIN category_samples cs
            ON s.data_id = cs.data_id

        LEFT JOIN objects o
            ON s.data_id = o.data_id

        LEFT JOIN data_provenances dp
            ON o.provenance = dp.rowid
            AND dp.origin_product_type LIKE '%Watch%'

        WHERE
            s.data_type IN (63, '63')
            AND cs.value IN (0, 1)

        ORDER BY
            s.start_date ASC
        """


        df = pd.read_sql_query(
            query,
            conn
        )


    conn.close()


    return df


print(
    "✅ Extractor All Watch Sleep siap digunakan."
)

✅ Extractor All Watch Sleep siap digunakan.

In [ ]:
# ============================================================
# MENJALANKAN EXTRACTOR ALL WATCH SLEEP
# ============================================================

all_watch_sleep_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"😴 ALL WATCH SLEEP - {version}"
    )

    print("=" * 70)


    try:

        df_sleep = (
            extract_all_watch_sleep(
                secure_path,
                version
            )
        )


        all_watch_sleep_results[
            version
        ] = df_sleep


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Events: "
            f"{len(df_sleep)}"
        )


        # Informasi query yang digunakan
        if version == "iOS 17":

            print(
                "📱 Struktur: "
                "iOS 17"
            )

            print(
                "💤 Sleep State: "
                "2, 3, 4, 5"
            )

        else:

            print(
                "📱 Struktur: "
                "iOS 13–16"
            )

            print(
                "💤 Sleep State: "
                "0, 1"
            )


    except Exception as e:

        print(
            f"❌ Ekstraksi gagal: {e}"
        )

======================================================================
😴 ALL WATCH SLEEP - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 16
📱 Struktur: iOS 13–16
💤 Sleep State: 0, 1

======================================================================
😴 ALL WATCH SLEEP - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 16
📱 Struktur: iOS 13–16
💤 Sleep State: 0, 1

======================================================================
😴 ALL WATCH SLEEP - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 210
📱 Struktur: iOS 13–16
💤 Sleep State: 0, 1

======================================================================
😴 ALL WATCH SLEEP - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 388
📱 Struktur: iOS 13–16
💤 Sleep State: 0, 1

======================================================================
😴 ALL WATCH SLEEP - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 93
📱 Struktur: iOS 17
💤 Sleep State: 2, 3, 4, 5

In [ ]:
# ============================================================
# PREVIEW RAW ALL WATCH SLEEP
# ============================================================

for version, df_sleep in all_watch_sleep_results.items():

    print()
    print("=" * 70)

    print(
        f"😴 RAW ALL WATCH SLEEP - {version}"
    )

    print("=" * 70)


    display(
        df_sleep.head(20)
    )


    print()

    print(
        f"📊 Total Events: "
        f"{len(df_sleep)}"
    )

======================================================================
😴 RAW ALL WATCH SLEEP - iOS 13.3.1
======================================================================

    start_cocoa    end_cocoa  state_code
0   607660200.0  607686000.0           1
1   607660200.0  607689420.0           0
2   607747260.0  607771800.0           1
3   607747260.0  607775040.0           0
4   607831980.0  607857900.0           1
5   607831980.0  607861080.0           0
6   607918680.0  607943400.0           1
7   607918680.0  607946700.0           0
8   608007480.0  608029920.0           1
9   608007480.0  608032260.0           0
10  608090760.0  608117280.0           1
11  608090760.0  608120580.0           0
12  608265720.0  608290440.0           1
13  608265720.0  608294160.0           0
14  608352780.0  608377800.0           1
15  608352780.0  608380380.0           0

📊 Total Events: 16

======================================================================
😴 RAW ALL WATCH SLEEP - iOS 13.4.1
======================================================================

    start_cocoa    end_cocoa  state_code
0   607660200.0  607686000.0           1
1   607660200.0  607689420.0           0
2   607747260.0  607771800.0           1
3   607747260.0  607775040.0           0
4   607831980.0  607857900.0           1
5   607831980.0  607861080.0           0
6   607918680.0  607943400.0           1
7   607918680.0  607946700.0           0
8   608007480.0  608029920.0           1
9   608007480.0  608032260.0           0
10  608090760.0  608117280.0           1
11  608090760.0  608120580.0           0
12  608265720.0  608290440.0           1
13  608265720.0  608294160.0           0
14  608352780.0  608377800.0           1
15  608352780.0  608380380.0           0

📊 Total Events: 16

======================================================================
😴 RAW ALL WATCH SLEEP - iOS 15
======================================================================

     start_cocoa     end_cocoa  state_code
0   6.076602e+08  6.076860e+08           1
1   6.076602e+08  6.076894e+08           0
2   6.077473e+08  6.077718e+08           1
3   6.077473e+08  6.077750e+08           0
4   6.078320e+08  6.078579e+08           1
5   6.078320e+08  6.078611e+08           0
6   6.079187e+08  6.079434e+08           1
7   6.079187e+08  6.079467e+08           0
8   6.080075e+08  6.080299e+08           1
9   6.080075e+08  6.080323e+08           0
10  6.080908e+08  6.081173e+08           1
11  6.080908e+08  6.081206e+08           0
12  6.082657e+08  6.082904e+08           1
13  6.082657e+08  6.082942e+08           0
14  6.083528e+08  6.083778e+08           1
15  6.083528e+08  6.083804e+08           0
16  6.310737e+08  6.311097e+08           0
17  6.310798e+08  6.311052e+08           1
18  6.311601e+08  6.311948e+08           0
19  6.311659e+08  6.311854e+08           1

📊 Total Events: 210

======================================================================
😴 RAW ALL WATCH SLEEP - iOS 16
======================================================================

     start_cocoa     end_cocoa  state_code
0   6.076602e+08  6.076860e+08           1
1   6.076602e+08  6.076894e+08           0
2   6.077473e+08  6.077718e+08           1
3   6.077473e+08  6.077750e+08           0
4   6.078320e+08  6.078579e+08           1
5   6.078320e+08  6.078611e+08           0
6   6.079187e+08  6.079434e+08           1
7   6.079187e+08  6.079467e+08           0
8   6.080075e+08  6.080299e+08           1
9   6.080075e+08  6.080323e+08           0
10  6.080908e+08  6.081173e+08           1
11  6.080908e+08  6.081206e+08           0
12  6.082657e+08  6.082904e+08           1
13  6.082657e+08  6.082942e+08           0
14  6.083528e+08  6.083778e+08           1
15  6.083528e+08  6.083804e+08           0
16  6.310737e+08  6.311097e+08           0
17  6.310798e+08  6.311052e+08           1
18  6.311601e+08  6.311948e+08           0
19  6.311659e+08  6.311854e+08           1

📊 Total Events: 388

======================================================================
😴 RAW ALL WATCH SLEEP - iOS 17
======================================================================

       start_cocoa     end_cocoa  state_code
2378  7.433979e+08  7.433991e+08           3
2380  7.433991e+08  7.433997e+08           4
2381  7.433997e+08  7.434002e+08           3
2383  7.434002e+08  7.434010e+08           4
2384  7.434010e+08  7.434020e+08           3
2385  7.434020e+08  7.434030e+08           5
2386  7.434030e+08  7.434044e+08           3
2388  7.434044e+08  7.434051e+08           4
2389  7.434051e+08  7.434053e+08           3
2390  7.434053e+08  7.434060e+08           4
2391  7.434060e+08  7.434078e+08           3
2393  7.434078e+08  7.434104e+08           5
2394  7.434104e+08  7.434126e+08           3
2396  7.434126e+08  7.434151e+08           4
2398  7.434151e+08  7.434157e+08           3
2399  7.434157e+08  7.434170e+08           5
2400  7.434170e+08  7.434209e+08           3
2402  7.434209e+08  7.434223e+08           5
2404  7.434223e+08  7.434224e+08           2
2405  7.434224e+08  7.434225e+08           3

📊 Total Events: 93

In [ ]:
# ============================================================
# FORMAT LAPORAN ALL WATCH SLEEP
# ============================================================

SLEEP_STATE_MAP = {
    0: "In Bed",
    1: "Asleep",
    2: "Awake",
    3: "Core",
    4: "Deep",
    5: "REM"
}


all_watch_sleep_reports = {}


for version, df_sleep in all_watch_sleep_results.items():

    # Buat DataFrame baru
    # RAW data tetap tidak diubah
    df_report = pd.DataFrame()


    # --------------------------------------------------------
    # START TIMESTAMP
    # --------------------------------------------------------

    df_report["Start Timestamp"] = (
        df_sleep["start_cocoa"]
        .apply(parse_cocoa_datetime)
    )


    # --------------------------------------------------------
    # END TIMESTAMP
    # --------------------------------------------------------

    df_report["End Timestamp"] = (
        df_sleep["end_cocoa"]
        .apply(parse_cocoa_datetime)
    )


    # --------------------------------------------------------
    # SLEEP STATE CODE
    # --------------------------------------------------------

    df_report["Sleep State Code"] = (
        df_sleep["state_code"]
    )


    # --------------------------------------------------------
    # SLEEP STATE
    #
    # iOS 13-16:
    # 0 = In Bed
    # 1 = Asleep
    #
    # iOS 17:
    # 2 = Awake
    # 3 = Core
    # 4 = Deep
    # 5 = REM
    # --------------------------------------------------------

    df_report["Sleep State"] = (
        df_sleep["state_code"]
        .map(SLEEP_STATE_MAP)
    )


    # --------------------------------------------------------
    # HITUNG DURASI DALAM DETIK
    # --------------------------------------------------------

    duration_seconds = (
        df_sleep["end_cocoa"]
        -
        df_sleep["start_cocoa"]
    )


    # --------------------------------------------------------
    # UBAH DURASI KE HH:MM:SS
    # --------------------------------------------------------

    df_report["Sleep Duration"] = (
        duration_seconds
        .apply(seconds_to_hms)
    )


    # --------------------------------------------------------
    # SOURCE DATABASE
    # --------------------------------------------------------

    df_report["Source"] = (
        "healthdb_secure.sqlite"
    )


    all_watch_sleep_reports[
        version
    ] = df_report


print(
    "✅ Format laporan All Watch Sleep "
    "berhasil dibuat."
)

✅ Format laporan All Watch Sleep berhasil dibuat.

In [ ]:
# ============================================================
# PREVIEW LAPORAN ALL WATCH SLEEP
# ============================================================

for version, df_report in all_watch_sleep_reports.items():

    print()
    print("=" * 70)

    print(
        f"😴 ALL WATCH SLEEP REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total All Watch Sleep Events: "
        f"{len(df_report)}"
    )

======================================================================
😴 ALL WATCH SLEEP REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Sleep State Code,Sleep State,Sleep Duration,Source
0,2020-04-04 02:30:00+00:00,2020-04-04 09:40:00+00:00,1,Asleep,07:10:00,healthdb_secure.sqlite
1,2020-04-04 02:30:00+00:00,2020-04-04 10:37:00+00:00,0,In Bed,08:07:00,healthdb_secure.sqlite
2,2020-04-05 02:41:00+00:00,2020-04-05 09:30:00+00:00,1,Asleep,06:49:00,healthdb_secure.sqlite
3,2020-04-05 02:41:00+00:00,2020-04-05 10:24:00+00:00,0,In Bed,07:43:00,healthdb_secure.sqlite
4,2020-04-06 02:13:00+00:00,2020-04-06 09:25:00+00:00,1,Asleep,07:12:00,healthdb_secure.sqlite
5,2020-04-06 02:13:00+00:00,2020-04-06 10:18:00+00:00,0,In Bed,08:05:00,healthdb_secure.sqlite
6,2020-04-07 02:18:00+00:00,2020-04-07 09:10:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
7,2020-04-07 02:18:00+00:00,2020-04-07 10:05:00+00:00,0,In Bed,07:47:00,healthdb_secure.sqlite
8,2020-04-08 02:58:00+00:00,2020-04-08 09:12:00+00:00,1,Asleep,06:14:00,healthdb_secure.sqlite
9,2020-04-08 02:58:00+00:00,2020-04-08 09:51:00+00:00,0,In Bed,06:53:00,healthdb_secure.sqlite
10,2020-04-09 02:06:00+00:00,2020-04-09 09:28:00+00:00,1,Asleep,07:22:00,healthdb_secure.sqlite
11,2020-04-09 02:06:00+00:00,2020-04-09 10:23:00+00:00,0,In Bed,08:17:00,healthdb_secure.sqlite
12,2020-04-11 02:42:00+00:00,2020-04-11 09:34:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
13,2020-04-11 02:42:00+00:00,2020-04-11 10:36:00+00:00,0,In Bed,07:54:00,healthdb_secure.sqlite
14,2020-04-12 02:53:00+00:00,2020-04-12 09:50:00+00:00,1,Asleep,06:57:00,healthdb_secure.sqlite
15,2020-04-12 02:53:00+00:00,2020-04-12 10:33:00+00:00,0,In Bed,07:40:00,healthdb_secure.sqlite

📊 Total All Watch Sleep Events: 16

======================================================================
😴 ALL WATCH SLEEP REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Sleep State Code,Sleep State,Sleep Duration,Source
0,2020-04-04 02:30:00+00:00,2020-04-04 09:40:00+00:00,1,Asleep,07:10:00,healthdb_secure.sqlite
1,2020-04-04 02:30:00+00:00,2020-04-04 10:37:00+00:00,0,In Bed,08:07:00,healthdb_secure.sqlite
2,2020-04-05 02:41:00+00:00,2020-04-05 09:30:00+00:00,1,Asleep,06:49:00,healthdb_secure.sqlite
3,2020-04-05 02:41:00+00:00,2020-04-05 10:24:00+00:00,0,In Bed,07:43:00,healthdb_secure.sqlite
4,2020-04-06 02:13:00+00:00,2020-04-06 09:25:00+00:00,1,Asleep,07:12:00,healthdb_secure.sqlite
5,2020-04-06 02:13:00+00:00,2020-04-06 10:18:00+00:00,0,In Bed,08:05:00,healthdb_secure.sqlite
6,2020-04-07 02:18:00+00:00,2020-04-07 09:10:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
7,2020-04-07 02:18:00+00:00,2020-04-07 10:05:00+00:00,0,In Bed,07:47:00,healthdb_secure.sqlite
8,2020-04-08 02:58:00+00:00,2020-04-08 09:12:00+00:00,1,Asleep,06:14:00,healthdb_secure.sqlite
9,2020-04-08 02:58:00+00:00,2020-04-08 09:51:00+00:00,0,In Bed,06:53:00,healthdb_secure.sqlite
10,2020-04-09 02:06:00+00:00,2020-04-09 09:28:00+00:00,1,Asleep,07:22:00,healthdb_secure.sqlite
11,2020-04-09 02:06:00+00:00,2020-04-09 10:23:00+00:00,0,In Bed,08:17:00,healthdb_secure.sqlite
12,2020-04-11 02:42:00+00:00,2020-04-11 09:34:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
13,2020-04-11 02:42:00+00:00,2020-04-11 10:36:00+00:00,0,In Bed,07:54:00,healthdb_secure.sqlite
14,2020-04-12 02:53:00+00:00,2020-04-12 09:50:00+00:00,1,Asleep,06:57:00,healthdb_secure.sqlite
15,2020-04-12 02:53:00+00:00,2020-04-12 10:33:00+00:00,0,In Bed,07:40:00,healthdb_secure.sqlite

📊 Total All Watch Sleep Events: 16

======================================================================
😴 ALL WATCH SLEEP REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Sleep State Code,Sleep State,Sleep Duration,Source
0,2020-04-04 02:30:00+00:00,2020-04-04 09:40:00+00:00,1,Asleep,07:10:00,healthdb_secure.sqlite
1,2020-04-04 02:30:00+00:00,2020-04-04 10:37:00+00:00,0,In Bed,08:07:00,healthdb_secure.sqlite
2,2020-04-05 02:41:00+00:00,2020-04-05 09:30:00+00:00,1,Asleep,06:49:00,healthdb_secure.sqlite
3,2020-04-05 02:41:00+00:00,2020-04-05 10:24:00+00:00,0,In Bed,07:43:00,healthdb_secure.sqlite
4,2020-04-06 02:13:00+00:00,2020-04-06 09:25:00+00:00,1,Asleep,07:12:00,healthdb_secure.sqlite
5,2020-04-06 02:13:00+00:00,2020-04-06 10:18:00+00:00,0,In Bed,08:05:00,healthdb_secure.sqlite
6,2020-04-07 02:18:00+00:00,2020-04-07 09:10:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
7,2020-04-07 02:18:00+00:00,2020-04-07 10:05:00+00:00,0,In Bed,07:47:00,healthdb_secure.sqlite
8,2020-04-08 02:58:00+00:00,2020-04-08 09:12:00+00:00,1,Asleep,06:14:00,healthdb_secure.sqlite
9,2020-04-08 02:58:00+00:00,2020-04-08 09:51:00+00:00,0,In Bed,06:53:00,healthdb_secure.sqlite
10,2020-04-09 02:06:00+00:00,2020-04-09 09:28:00+00:00,1,Asleep,07:22:00,healthdb_secure.sqlite
11,2020-04-09 02:06:00+00:00,2020-04-09 10:23:00+00:00,0,In Bed,08:17:00,healthdb_secure.sqlite
12,2020-04-11 02:42:00+00:00,2020-04-11 09:34:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
13,2020-04-11 02:42:00+00:00,2020-04-11 10:36:00+00:00,0,In Bed,07:54:00,healthdb_secure.sqlite
14,2020-04-12 02:53:00+00:00,2020-04-12 09:50:00+00:00,1,Asleep,06:57:00,healthdb_secure.sqlite
15,2020-04-12 02:53:00+00:00,2020-04-12 10:33:00+00:00,0,In Bed,07:40:00,healthdb_secure.sqlite
16,2020-12-31 02:15:00+00:00,2020-12-31 12:14:10.731790+00:00,0,In Bed,09:59:10,healthdb_secure.sqlite
17,2020-12-31 03:56:28.330995+00:00,2020-12-31 11:00:28.330995+00:00,1,Asleep,07:04:00,healthdb_secure.sqlite
18,2021-01-01 02:15:00+00:00,2021-01-01 11:53:00.500161+00:00,0,In Bed,09:38:00,healthdb_secure.sqlite
19,2021-01-01 03:51:42.763808+00:00,2021-01-01 09:16:12.763808+00:00,1,Asleep,05:24:30,healthdb_secure.sqlite

📊 Total All Watch Sleep Events: 210

======================================================================
😴 ALL WATCH SLEEP REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Sleep State Code,Sleep State,Sleep Duration,Source
0,2020-04-04 02:30:00+00:00,2020-04-04 09:40:00+00:00,1,Asleep,07:10:00,healthdb_secure.sqlite
1,2020-04-04 02:30:00+00:00,2020-04-04 10:37:00+00:00,0,In Bed,08:07:00,healthdb_secure.sqlite
2,2020-04-05 02:41:00+00:00,2020-04-05 09:30:00+00:00,1,Asleep,06:49:00,healthdb_secure.sqlite
3,2020-04-05 02:41:00+00:00,2020-04-05 10:24:00+00:00,0,In Bed,07:43:00,healthdb_secure.sqlite
4,2020-04-06 02:13:00+00:00,2020-04-06 09:25:00+00:00,1,Asleep,07:12:00,healthdb_secure.sqlite
5,2020-04-06 02:13:00+00:00,2020-04-06 10:18:00+00:00,0,In Bed,08:05:00,healthdb_secure.sqlite
6,2020-04-07 02:18:00+00:00,2020-04-07 09:10:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
7,2020-04-07 02:18:00+00:00,2020-04-07 10:05:00+00:00,0,In Bed,07:47:00,healthdb_secure.sqlite
8,2020-04-08 02:58:00+00:00,2020-04-08 09:12:00+00:00,1,Asleep,06:14:00,healthdb_secure.sqlite
9,2020-04-08 02:58:00+00:00,2020-04-08 09:51:00+00:00,0,In Bed,06:53:00,healthdb_secure.sqlite
10,2020-04-09 02:06:00+00:00,2020-04-09 09:28:00+00:00,1,Asleep,07:22:00,healthdb_secure.sqlite
11,2020-04-09 02:06:00+00:00,2020-04-09 10:23:00+00:00,0,In Bed,08:17:00,healthdb_secure.sqlite
12,2020-04-11 02:42:00+00:00,2020-04-11 09:34:00+00:00,1,Asleep,06:52:00,healthdb_secure.sqlite
13,2020-04-11 02:42:00+00:00,2020-04-11 10:36:00+00:00,0,In Bed,07:54:00,healthdb_secure.sqlite
14,2020-04-12 02:53:00+00:00,2020-04-12 09:50:00+00:00,1,Asleep,06:57:00,healthdb_secure.sqlite
15,2020-04-12 02:53:00+00:00,2020-04-12 10:33:00+00:00,0,In Bed,07:40:00,healthdb_secure.sqlite
16,2020-12-31 02:15:00+00:00,2020-12-31 12:14:10.731790+00:00,0,In Bed,09:59:10,healthdb_secure.sqlite
17,2020-12-31 03:56:28.330995+00:00,2020-12-31 11:00:28.330995+00:00,1,Asleep,07:04:00,healthdb_secure.sqlite
18,2021-01-01 02:15:00+00:00,2021-01-01 11:53:00.500161+00:00,0,In Bed,09:38:00,healthdb_secure.sqlite
19,2021-01-01 03:51:42.763808+00:00,2021-01-01 09:16:12.763808+00:00,1,Asleep,05:24:30,healthdb_secure.sqlite

📊 Total All Watch Sleep Events: 388

======================================================================
😴 ALL WATCH SLEEP REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Sleep State Code,Sleep State,Sleep Duration,Source
2378,2024-07-23 03:25:36.786188+00:00,2024-07-23 03:44:36.786188+00:00,3,Core,00:19:00,healthdb_secure.sqlite
2380,2024-07-23 03:44:36.786188+00:00,2024-07-23 03:55:06.786188+00:00,4,Deep,00:10:30,healthdb_secure.sqlite
2381,2024-07-23 03:55:06.786188+00:00,2024-07-23 04:03:36.786188+00:00,3,Core,00:08:30,healthdb_secure.sqlite
2383,2024-07-23 04:03:36.786188+00:00,2024-07-23 04:17:06.786188+00:00,4,Deep,00:13:30,healthdb_secure.sqlite
2384,2024-07-23 04:17:06.786188+00:00,2024-07-23 04:32:36.786188+00:00,3,Core,00:15:30,healthdb_secure.sqlite
2385,2024-07-23 04:32:36.786188+00:00,2024-07-23 04:50:36.786188+00:00,5,REM,00:18:00,healthdb_secure.sqlite
2386,2024-07-23 04:50:36.786188+00:00,2024-07-23 05:14:06.786188+00:00,3,Core,00:23:30,healthdb_secure.sqlite
2388,2024-07-23 05:14:06.786188+00:00,2024-07-23 05:24:36.786188+00:00,4,Deep,00:10:30,healthdb_secure.sqlite
2389,2024-07-23 05:24:36.786188+00:00,2024-07-23 05:27:36.786188+00:00,3,Core,00:03:00,healthdb_secure.sqlite
2390,2024-07-23 05:27:36.786188+00:00,2024-07-23 05:40:36.786188+00:00,4,Deep,00:13:00,healthdb_secure.sqlite
2391,2024-07-23 05:40:36.786188+00:00,2024-07-23 06:09:36.786188+00:00,3,Core,00:29:00,healthdb_secure.sqlite
2393,2024-07-23 06:09:36.786188+00:00,2024-07-23 06:52:36.786188+00:00,5,REM,00:43:00,healthdb_secure.sqlite
2394,2024-07-23 06:52:36.786188+00:00,2024-07-23 07:30:36.786188+00:00,3,Core,00:38:00,healthdb_secure.sqlite
2396,2024-07-23 07:30:36.786188+00:00,2024-07-23 08:11:36.786188+00:00,4,Deep,00:41:00,healthdb_secure.sqlite
2398,2024-07-23 08:11:36.786188+00:00,2024-07-23 08:21:06.786188+00:00,3,Core,00:09:30,healthdb_secure.sqlite
2399,2024-07-23 08:21:06.786188+00:00,2024-07-23 08:43:36.786188+00:00,5,REM,00:22:30,healthdb_secure.sqlite
2400,2024-07-23 08:43:36.786188+00:00,2024-07-23 09:48:36.786188+00:00,3,Core,01:05:00,healthdb_secure.sqlite
2402,2024-07-23 09:48:36.786188+00:00,2024-07-23 10:11:36.786188+00:00,5,REM,00:23:00,healthdb_secure.sqlite
2404,2024-07-23 10:11:36.786188+00:00,2024-07-23 10:12:36.786188+00:00,2,Awake,00:01:00,healthdb_secure.sqlite
2405,2024-07-23 10:12:36.786188+00:00,2024-07-23 10:15:36.786188+00:00,3,Core,00:03:00,healthdb_secure.sqlite

📊 Total All Watch Sleep Events: 93

# **Fitur Headphone Audio Levels**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR HEADPHONE AUDIO LEVELS
# ============================================================

HEADPHONE_SECURE_TABLES = [
    "samples",
    "quantity_samples",
    "metadata_values",
    "metadata_keys",
    "objects",
    "data_provenances"
]

HEADPHONE_HEALTHDB_TABLES = [
    "source_devices"
]


print()
print("=" * 70)
print("🎧 VERIFIKASI HEADPHONE AUDIO LEVELS")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()
    print(f"📱 {version}")


    print("   🔐 healthdb_secure.sqlite")

    for table in HEADPHONE_SECURE_TABLES:

        status = (
            "✅"
            if table in secure_tables
            else "❌"
        )

        print(
            f"      {status} {table}"
        )


    print("   📂 healthdb.sqlite")

    for table in HEADPHONE_HEALTHDB_TABLES:

        status = (
            "✅"
            if table in healthdb_tables
            else "❌"
        )

        print(
            f"      {status} {table}"
        )


print()
print("=" * 70)

======================================================================
🎧 VERIFIKASI HEADPHONE AUDIO LEVELS
======================================================================

📱 iOS 13.3.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ metadata_keys
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices

📱 iOS 13.4.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ metadata_keys
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices

📱 iOS 15
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ metadata_keys
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices

📱 iOS 16
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ metadata_keys
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices

📱 iOS 17
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ metadata_keys
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR HEADPHONE AUDIO LEVELS
# ============================================================

def extract_headphone_audio_levels(
    secure_database_path,
    health_database_path
):
    """
    Mengekstrak Headphone Audio Levels dari dua database:

    healthdb_secure.sqlite:
        samples
        quantity_samples
        metadata_values
        metadata_keys
        objects
        data_provenances

    healthdb.sqlite:
        source_devices

    Kedua hasil digabung berdasarkan:

        data_provenances.device_id
                    =
        source_devices.ROWID
    """


    # ========================================================
    # 1. BACA HEALTHDB_SECURE.SQLITE
    # ========================================================

    secure_conn = open_sqlite_readonly(
        secure_database_path
    )


    secure_query = """
    SELECT

        samples.start_date
            AS start_cocoa,

        samples.end_date
            AS end_cocoa,

        quantity_samples.quantity
            AS decibels,

        metadata_values.string_value
            AS bundle_name,

        metadata_keys.key
            AS key,

        samples.data_id
            AS data_id,

        data_provenances.device_id
            AS device_id

    FROM samples


    LEFT JOIN quantity_samples

        ON quantity_samples.data_id
        = samples.data_id


    LEFT JOIN metadata_values

        ON metadata_values.object_id
        = samples.data_id


    LEFT JOIN metadata_keys

        ON metadata_keys.ROWID
        = metadata_values.key_id


    LEFT JOIN objects

        ON objects.data_id
        = samples.data_id


    LEFT JOIN data_provenances

        ON data_provenances.ROWID
        = objects.provenance


    WHERE

        samples.data_type IN (173, '173')

        AND (

            metadata_keys.key IS NULL

            OR metadata_keys.key !=
            '_HKPrivateMetadataKeyHeadphoneAudioDataIsTransient'

        )


    GROUP BY
        samples.data_id


    ORDER BY
        samples.start_date
    """


    df_secure = pd.read_sql_query(
        secure_query,
        secure_conn
    )


    secure_conn.close()


    # ========================================================
    # 2. BACA SOURCE_DEVICES DARI HEALTHDB.SQLITE
    # ========================================================

    health_conn = open_sqlite_readonly(
        health_database_path
    )


    device_query = """
    SELECT

        ROWID
            AS device_id,

        name
            AS device_name,

        manufacturer
            AS device_manufacturer,

        model
            AS device_model,

        localIdentifier
            AS local_identifier

    FROM source_devices
    """


    df_devices = pd.read_sql_query(
        device_query,
        health_conn
    )


    health_conn.close()


    # ========================================================
    # 3. NORMALISASI DEVICE ID
    # ========================================================

    df_secure["device_id"] = pd.to_numeric(
        df_secure["device_id"],
        errors="coerce"
    ).astype("Int64")


    df_devices["device_id"] = pd.to_numeric(
        df_devices["device_id"],
        errors="coerce"
    ).astype("Int64")


    # ========================================================
    # 4. MERGE KEDUA DATABASE
    # ========================================================

    df_result = df_secure.merge(

        df_devices,

        how="left",

        on="device_id",

        validate="many_to_one"
    )


    return df_result


print(
    "✅ Extractor Headphone Audio Levels "
    "dua database siap digunakan."
)

✅ Extractor Headphone Audio Levels dua database siap digunakan.

In [ ]:
# ============================================================
# MENJALANKAN HEADPHONE AUDIO LEVELS
# ============================================================

headphone_audio_results = {}


for dataset in target_datasets:

    version = dataset["version"]

    secure_path = dataset[
        "healthdb_secure"
    ]

    healthdb_path = dataset[
        "healthdb"
    ]


    print()
    print("=" * 70)
    print(
        f"🎧 HEADPHONE AUDIO LEVELS - {version}"
    )
    print("=" * 70)


    try:

        df_audio = (
            extract_headphone_audio_levels(
                secure_path,
                healthdb_path
            )
        )


        headphone_audio_results[
            version
        ] = df_audio


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Events: "
            f"{len(df_audio)}"
        )


        # -----------------------------------------------
        # Cek hasil relasi device
        # -----------------------------------------------

        device_found = (
            df_audio[
                [
                    "device_name",
                    "device_manufacturer",
                    "device_model",
                    "local_identifier"
                ]
            ]
            .notna()
            .any(axis=1)
            .sum()
        )


        print(
            f"🔗 Event dengan informasi device: "
            f"{device_found}"
        )


        print(
            "🔐 Data utama  : "
            "healthdb_secure.sqlite"
        )

        print(
            "📂 Data device : "
            "healthdb.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Ekstraksi gagal: {e}"
        )

======================================================================
🎧 HEADPHONE AUDIO LEVELS - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 8
🔗 Event dengan informasi device: 8
🔐 Data utama  : healthdb_secure.sqlite
📂 Data device : healthdb.sqlite

======================================================================
🎧 HEADPHONE AUDIO LEVELS - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 8
🔗 Event dengan informasi device: 8
🔐 Data utama  : healthdb_secure.sqlite
📂 Data device : healthdb.sqlite

======================================================================
🎧 HEADPHONE AUDIO LEVELS - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 20
🔗 Event dengan informasi device: 20
🔐 Data utama  : healthdb_secure.sqlite
📂 Data device : healthdb.sqlite

======================================================================
🎧 HEADPHONE AUDIO LEVELS - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 23
🔗 Event dengan informasi device: 23
🔐 Data utama  : healthdb_secure.sqlite
📂 Data device : healthdb.sqlite

======================================================================
🎧 HEADPHONE AUDIO LEVELS - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 27
🔗 Event dengan informasi device: 27
🔐 Data utama  : healthdb_secure.sqlite
📂 Data device : healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW HEADPHONE AUDIO LEVELS
# ============================================================

for version, df_audio in headphone_audio_results.items():

    print()
    print("=" * 70)

    print(
        f"🎧 RAW HEADPHONE AUDIO LEVELS - {version}"
    )

    print("=" * 70)


    display(
        df_audio.head(20)
    )


    print()

    print(
        f"📊 Total Events: "
        f"{len(df_audio)}"
    )

======================================================================
🎧 RAW HEADPHONE AUDIO LEVELS - iOS 13.3.1
======================================================================

,start_cocoa,end_cocoa,decibels,bundle_name,key,data_id,device_id,device_name,device_manufacturer,device_model,local_identifier
0,6.070281e+08,6.070295e+08,70.383001,com.apple.Music,_HKPrivateMediaSourceBundleIdentifier,15025,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
1,6.070992e+08,6.071003e+08,67.953332,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,18162,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
2,6.072649e+08,6.072667e+08,69.823870,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,24657,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
3,6.073739e+08,6.073755e+08,74.539604,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,30231,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
4,6.075416e+08,6.075434e+08,76.202527,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,36812,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
5,6.075434e+08,6.075437e+08,69.529072,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,36813,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
6,6.076337e+08,6.076355e+08,74.955671,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,44814,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
7,6.076355e+08,6.076360e+08,72.035538,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,44815,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl

📊 Total Events: 8

======================================================================
🎧 RAW HEADPHONE AUDIO LEVELS - iOS 13.4.1
======================================================================

,start_cocoa,end_cocoa,decibels,bundle_name,key,data_id,device_id,device_name,device_manufacturer,device_model,local_identifier
0,6.070281e+08,6.070295e+08,70.383001,com.apple.Music,_HKPrivateMediaSourceBundleIdentifier,15025,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
1,6.070992e+08,6.071003e+08,67.953332,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,18162,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
2,6.072649e+08,6.072667e+08,69.823870,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,24657,5,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
3,6.073739e+08,6.073755e+08,74.539604,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,30231,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
4,6.075416e+08,6.075434e+08,76.202527,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,36812,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
5,6.075434e+08,6.075437e+08,69.529072,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,36813,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
6,6.076337e+08,6.076355e+08,74.955671,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,44814,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
7,6.076355e+08,6.076360e+08,72.035538,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,44815,6,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl

📊 Total Events: 8

======================================================================
🎧 RAW HEADPHONE AUDIO LEVELS - iOS 15
======================================================================

,start_cocoa,end_cocoa,decibels,bundle_name,key,data_id,device_id,device_name,device_manufacturer,device_model,local_identifier
0,6.070281e+08,6.070295e+08,70.383001,com.apple.Music,_HKPrivateMediaSourceBundleIdentifier,11933,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
1,6.070992e+08,6.071003e+08,67.953332,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,14504,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
2,6.072649e+08,6.072667e+08,69.823870,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,18006,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
3,6.073739e+08,6.073755e+08,74.539604,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,22289,8,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
4,6.075416e+08,6.075434e+08,76.202527,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,25814,8,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
5,6.075434e+08,6.075437e+08,69.529072,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,25815,8,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
6,6.076337e+08,6.076355e+08,74.955671,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31022,8,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
7,6.076355e+08,6.076360e+08,72.035538,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31023,8,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
8,6.328455e+08,6.328473e+08,62.601885,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,77291,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
9,6.328473e+08,6.328491e+08,65.700429,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,77292,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
10,6.328491e+08,6.328497e+08,59.565432,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,77293,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
11,6.343359e+08,6.343369e+08,63.779438,"SpringBoard,com.spotify.client",_HKPrivateMediaSourceBundleIdentifier,111144,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
12,6.343369e+08,6.343369e+08,64.679573,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,111145,7,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
13,7.062043e+08,7.062045e+08,65.811303,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,134422,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
14,7.062045e+08,7.062045e+08,68.578384,"AllTrails,SpringBoard,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,134424,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
15,7.062045e+08,7.062048e+08,66.968016,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,134426,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
16,7.062048e+08,7.062048e+08,69.423137,"AllTrails,com.apple.Music,com.apple.camera",_HKPrivateMediaSourceBundleIdentifier,134428,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
17,7.062048e+08,7.062061e+08,67.845324,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,134438,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
18,7.062061e+08,7.062067e+08,66.112819,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,134482,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
19,7.062067e+08,7.062069e+08,52.294415,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,134487,25,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl

📊 Total Events: 20

======================================================================
🎧 RAW HEADPHONE AUDIO LEVELS - iOS 16
======================================================================

,start_cocoa,end_cocoa,decibels,bundle_name,key,data_id,device_id,device_name,device_manufacturer,device_model,local_identifier
0,6.070281e+08,6.070295e+08,70.383001,com.apple.Music,_HKPrivateMediaSourceBundleIdentifier,17916,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
1,6.070992e+08,6.071003e+08,67.953332,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,20487,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
2,6.072649e+08,6.072667e+08,69.823870,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,23989,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
3,6.073739e+08,6.073755e+08,74.539604,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,28272,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
4,6.075416e+08,6.075434e+08,76.202527,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31797,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
5,6.075434e+08,6.075437e+08,69.529072,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31798,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
6,6.076337e+08,6.076355e+08,74.955671,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,37005,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
7,6.076355e+08,6.076360e+08,72.035538,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,37006,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
8,6.328455e+08,6.328473e+08,62.601885,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83278,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
9,6.328473e+08,6.328491e+08,65.700429,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83279,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
10,6.328491e+08,6.328497e+08,59.565432,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83280,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
11,6.343359e+08,6.343369e+08,63.779438,"SpringBoard,com.spotify.client",_HKPrivateMediaSourceBundleIdentifier,117131,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
12,6.343369e+08,6.343369e+08,64.679573,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,117132,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
13,7.062043e+08,7.062045e+08,65.811303,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7394,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
14,7.062045e+08,7.062045e+08,68.578384,"AllTrails,SpringBoard,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7395,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
15,7.062045e+08,7.062048e+08,66.968016,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7396,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
16,7.062048e+08,7.062048e+08,69.423137,"AllTrails,com.apple.Music,com.apple.camera",_HKPrivateMediaSourceBundleIdentifier,7397,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
17,7.062061e+08,7.062067e+08,66.112819,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7398,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
18,7.062067e+08,7.062069e+08,52.294415,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,7399,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
19,7.275551e+08,7.275569e+08,52.348076,"com.apple.springboard,com.spotify.client",_HKPrivateMediaSourceBundleIdentifier,208838,31,AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl

📊 Total Events: 23

======================================================================
🎧 RAW HEADPHONE AUDIO LEVELS - iOS 17
======================================================================

,start_cocoa,end_cocoa,decibels,bundle_name,key,data_id,device_id,device_name,device_manufacturer,device_model,local_identifier
0,6.070281e+08,6.070295e+08,70.383001,com.apple.Music,_HKPrivateMediaSourceBundleIdentifier,17916,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
1,6.070992e+08,6.071003e+08,67.953332,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,20487,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
2,6.072649e+08,6.072667e+08,69.823870,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,23989,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
3,6.073739e+08,6.073755e+08,74.539604,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,28272,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
4,6.075416e+08,6.075434e+08,76.202527,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31797,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
5,6.075434e+08,6.075437e+08,69.529072,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,31798,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
6,6.076337e+08,6.076355e+08,74.955671,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,37005,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
7,6.076355e+08,6.076360e+08,72.035538,com.apple.NanoMusic,_HKPrivateMediaSourceBundleIdentifier,37006,11,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl
8,6.328455e+08,6.328473e+08,62.601885,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83278,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
9,6.328473e+08,6.328491e+08,65.700429,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83279,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
10,6.328491e+08,6.328497e+08,59.565432,"SpringBoard,com.apple.podcasts",_HKPrivateMediaSourceBundleIdentifier,83280,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
11,6.343359e+08,6.343369e+08,63.779438,"SpringBoard,com.spotify.client",_HKPrivateMediaSourceBundleIdentifier,117131,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
12,6.343369e+08,6.343369e+08,64.679573,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,117132,10,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl
13,7.062043e+08,7.062045e+08,65.811303,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7394,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
14,7.062045e+08,7.062045e+08,68.578384,"AllTrails,SpringBoard,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7395,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
15,7.062045e+08,7.062048e+08,66.968016,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7396,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
16,7.062048e+08,7.062048e+08,69.423137,"AllTrails,com.apple.Music,com.apple.camera",_HKPrivateMediaSourceBundleIdentifier,7397,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
17,7.062061e+08,7.062067e+08,66.112819,"AllTrails,com.apple.Music",_HKPrivateMediaSourceBundleIdentifier,7398,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
18,7.062067e+08,7.062069e+08,52.294415,SpringBoard,_HKPrivateMediaSourceBundleIdentifier,7399,1,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl
19,7.275551e+08,7.275569e+08,52.348076,"com.apple.springboard,com.spotify.client",_HKPrivateMediaSourceBundleIdentifier,208838,31,AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl

📊 Total Events: 27

In [ ]:
# ============================================================
# FORMAT LAPORAN HEADPHONE AUDIO LEVELS
# ============================================================

headphone_audio_reports = {}


for version, df_audio in headphone_audio_results.items():

    df_report = pd.DataFrame()


    # --------------------------------------------------------
    # START TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "Start Timestamp"
    ] = (
        df_audio["start_cocoa"]
        .apply(parse_cocoa_datetime)
    )


    # --------------------------------------------------------
    # END TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "End Timestamp"
    ] = (
        df_audio["end_cocoa"]
        .apply(parse_cocoa_datetime)
    )


    # --------------------------------------------------------
    # DURATION
    # --------------------------------------------------------

    duration_seconds = (

        df_audio["end_cocoa"]

        -

        df_audio["start_cocoa"]
    )


    df_report[
        "Total Time Duration"
    ] = (
        duration_seconds
        .apply(seconds_to_hms)
    )


    # --------------------------------------------------------
    # AUDIO LEVEL
    # --------------------------------------------------------

    df_report[
        "Decibels"
    ] = (
        df_audio["decibels"]
    )


    # --------------------------------------------------------
    # BUNDLE / SOURCE
    # --------------------------------------------------------

    df_report[
        "Bundle Name"
    ] = (
        df_audio["bundle_name"]
    )


    # --------------------------------------------------------
    # DEVICE INFORMATION
    # --------------------------------------------------------

    df_report[
        "Device Name"
    ] = (
        df_audio["device_name"]
    )


    df_report[
        "Device Manufacturer"
    ] = (
        df_audio["device_manufacturer"]
    )


    df_report[
        "Device Model"
    ] = (
        df_audio["device_model"]
    )


    df_report[
        "Local Identifier"
    ] = (
        df_audio["local_identifier"]
    )


    # --------------------------------------------------------
    # METADATA
    # --------------------------------------------------------

    df_report[
        "Key"
    ] = (
        df_audio["key"]
    )


    df_report[
        "Data ID"
    ] = (
        df_audio["data_id"]
    )


    # --------------------------------------------------------
    # FORENSIC SOURCE
    # --------------------------------------------------------

    df_report[
        "Health Data Source"
    ] = (
        "healthdb_secure.sqlite"
    )


    df_report[
        "Device Metadata Source"
    ] = (
        "healthdb.sqlite"
    )


    headphone_audio_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Headphone Audio Levels "
    "berhasil dibuat."
)

✅ Format laporan Headphone Audio Levels berhasil dibuat.

In [ ]:
# ============================================================
# PREVIEW LAPORAN HEADPHONE AUDIO LEVELS
# ============================================================

for version, df_report in headphone_audio_reports.items():

    print()
    print("=" * 70)

    print(
        f"🎧 HEADPHONE AUDIO LEVELS REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Headphone Audio Events: "
        f"{len(df_report)}"
    )

======================================================================
🎧 HEADPHONE AUDIO LEVELS REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Total Time Duration,Decibels,Bundle Name,Device Name,Device Manufacturer,Device Model,Local Identifier,Key,Data ID,Health Data Source,Device Metadata Source
0,2020-03-27 18:55:14.121678+00:00,2020-03-27 19:19:09.039616+00:00,00:23:54,70.383001,com.apple.Music,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,15025,healthdb_secure.sqlite,healthdb.sqlite
1,2020-03-28 14:39:34.837354+00:00,2020-03-28 14:58:52.919620+00:00,00:19:18,67.953332,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,18162,healthdb_secure.sqlite,healthdb.sqlite
2,2020-03-30 12:41:28.775563+00:00,2020-03-30 13:10:51.633477+00:00,00:29:22,69.823870,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,24657,healthdb_secure.sqlite,healthdb.sqlite
3,2020-03-31 18:58:07.664629+00:00,2020-03-31 19:25:18.001250+00:00,00:27:10,74.539604,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,30231,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-02 17:33:00.120757+00:00,2020-04-02 18:02:55.900469+00:00,00:29:55,76.202527,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,36812,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-02 18:02:55.900470+00:00,2020-04-02 18:09:02.937830+00:00,00:06:07,69.529072,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,36813,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-03 19:08:02.690256+00:00,2020-04-03 19:37:58.937985+00:00,00:29:56,74.955671,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,44814,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-03 19:37:58.937984+00:00,2020-04-03 19:47:12.410047+00:00,00:09:13,72.035538,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,44815,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Headphone Audio Events: 8

======================================================================
🎧 HEADPHONE AUDIO LEVELS REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Total Time Duration,Decibels,Bundle Name,Device Name,Device Manufacturer,Device Model,Local Identifier,Key,Data ID,Health Data Source,Device Metadata Source
0,2020-03-27 18:55:14.121678+00:00,2020-03-27 19:19:09.039616+00:00,00:23:54,70.383001,com.apple.Music,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,15025,healthdb_secure.sqlite,healthdb.sqlite
1,2020-03-28 14:39:34.837354+00:00,2020-03-28 14:58:52.919620+00:00,00:19:18,67.953332,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,18162,healthdb_secure.sqlite,healthdb.sqlite
2,2020-03-30 12:41:28.775563+00:00,2020-03-30 13:10:51.633477+00:00,00:29:22,69.823870,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,24657,healthdb_secure.sqlite,healthdb.sqlite
3,2020-03-31 18:58:07.664629+00:00,2020-03-31 19:25:18.001250+00:00,00:27:10,74.539604,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,30231,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-02 17:33:00.120757+00:00,2020-04-02 18:02:55.900469+00:00,00:29:55,76.202527,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,36812,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-02 18:02:55.900470+00:00,2020-04-02 18:09:02.937830+00:00,00:06:07,69.529072,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,36813,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-03 19:08:02.690256+00:00,2020-04-03 19:37:58.937985+00:00,00:29:56,74.955671,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,44814,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-03 19:37:58.937984+00:00,2020-04-03 19:47:12.410047+00:00,00:09:13,72.035538,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,44815,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Headphone Audio Events: 8

======================================================================
🎧 HEADPHONE AUDIO LEVELS REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Total Time Duration,Decibels,Bundle Name,Device Name,Device Manufacturer,Device Model,Local Identifier,Key,Data ID,Health Data Source,Device Metadata Source
0,2020-03-27 18:55:14.121678+00:00,2020-03-27 19:19:09.039616+00:00,00:23:54,70.383001,com.apple.Music,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,11933,healthdb_secure.sqlite,healthdb.sqlite
1,2020-03-28 14:39:34.837354+00:00,2020-03-28 14:58:52.919620+00:00,00:19:18,67.953332,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,14504,healthdb_secure.sqlite,healthdb.sqlite
2,2020-03-30 12:41:28.775563+00:00,2020-03-30 13:10:51.633477+00:00,00:29:22,69.823870,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,18006,healthdb_secure.sqlite,healthdb.sqlite
3,2020-03-31 18:58:07.664629+00:00,2020-03-31 19:25:18.001250+00:00,00:27:10,74.539604,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,22289,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-02 17:33:00.120757+00:00,2020-04-02 18:02:55.900469+00:00,00:29:55,76.202527,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,25814,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-02 18:02:55.900470+00:00,2020-04-02 18:09:02.937830+00:00,00:06:07,69.529072,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,25815,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-03 19:08:02.690256+00:00,2020-04-03 19:37:58.937985+00:00,00:29:56,74.955671,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31022,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-03 19:37:58.937984+00:00,2020-04-03 19:47:12.410047+00:00,00:09:13,72.035538,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31023,healthdb_secure.sqlite,healthdb.sqlite
8,2021-01-20 14:25:22.351374+00:00,2021-01-20 14:55:17.868731+00:00,00:29:55,62.601885,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,77291,healthdb_secure.sqlite,healthdb.sqlite
9,2021-01-20 14:55:17.868599+00:00,2021-01-20 15:25:14.314699+00:00,00:29:56,65.700429,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,77292,healthdb_secure.sqlite,healthdb.sqlite
10,2021-01-20 15:25:14.314639+00:00,2021-01-20 15:35:28.303127+00:00,00:10:13,59.565432,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,77293,healthdb_secure.sqlite,healthdb.sqlite
11,2021-02-06 20:25:21.383172+00:00,2021-02-06 20:41:30.416222+00:00,00:16:09,63.779438,"SpringBoard,com.spotify.client",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,111144,healthdb_secure.sqlite,healthdb.sqlite
12,2021-02-06 20:41:30.417321+00:00,2021-02-06 20:41:33.425321+00:00,00:00:03,64.679573,SpringBoard,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,111145,healthdb_secure.sqlite,healthdb.sqlite
13,2023-05-19 15:52:00.889683+00:00,2023-05-19 15:54:19.359843+00:00,00:02:18,65.811303,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134422,healthdb_secure.sqlite,healthdb.sqlite
14,2023-05-19 15:54:19.342857+00:00,2023-05-19 15:54:22.352857+00:00,00:00:03,68.578384,"AllTrails,SpringBoard,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134424,healthdb_secure.sqlite,healthdb.sqlite
15,2023-05-19 15:54:22.228314+00:00,2023-05-19 15:59:14.239136+00:00,00:04:52,66.968016,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134426,healthdb_secure.sqlite,healthdb.sqlite
16,2023-05-19 15:59:14.349186+00:00,2023-05-19 15:59:20.369111+00:00,00:00:06,69.423137,"AllTrails,com.apple.Music,com.apple.camera",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134428,healthdb_secure.sqlite,healthdb.sqlite
17,2023-05-19 15:59:20.219067+00:00,2023-05-19 16:21:57.773232+00:00,00:22:37,67.845324,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134438,healthdb_secure.sqlite,healthdb.sqlite
18,2023-05-19 16:21:57.773238+00:00,2023-05-19 16:31:29.759698+00:00,00:09:31,66.112819,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134482,healthdb_secure.sqlite,healthdb.sqlite
19,2023-05-19 16:32:01.575098+00:00,2023-05-19 16:35:11.528911+00:00,00:03:09,52.294415,SpringBoard,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,134487,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Headphone Audio Events: 20

======================================================================
🎧 HEADPHONE AUDIO LEVELS REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Total Time Duration,Decibels,Bundle Name,Device Name,Device Manufacturer,Device Model,Local Identifier,Key,Data ID,Health Data Source,Device Metadata Source
0,2020-03-27 18:55:14.121678+00:00,2020-03-27 19:19:09.039616+00:00,00:23:54,70.383001,com.apple.Music,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,17916,healthdb_secure.sqlite,healthdb.sqlite
1,2020-03-28 14:39:34.837354+00:00,2020-03-28 14:58:52.919620+00:00,00:19:18,67.953332,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,20487,healthdb_secure.sqlite,healthdb.sqlite
2,2020-03-30 12:41:28.775563+00:00,2020-03-30 13:10:51.633477+00:00,00:29:22,69.823870,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,23989,healthdb_secure.sqlite,healthdb.sqlite
3,2020-03-31 18:58:07.664629+00:00,2020-03-31 19:25:18.001250+00:00,00:27:10,74.539604,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,28272,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-02 17:33:00.120757+00:00,2020-04-02 18:02:55.900469+00:00,00:29:55,76.202527,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31797,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-02 18:02:55.900470+00:00,2020-04-02 18:09:02.937830+00:00,00:06:07,69.529072,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31798,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-03 19:08:02.690256+00:00,2020-04-03 19:37:58.937985+00:00,00:29:56,74.955671,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,37005,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-03 19:37:58.937984+00:00,2020-04-03 19:47:12.410047+00:00,00:09:13,72.035538,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,37006,healthdb_secure.sqlite,healthdb.sqlite
8,2021-01-20 14:25:22.351374+00:00,2021-01-20 14:55:17.868731+00:00,00:29:55,62.601885,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83278,healthdb_secure.sqlite,healthdb.sqlite
9,2021-01-20 14:55:17.868599+00:00,2021-01-20 15:25:14.314699+00:00,00:29:56,65.700429,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83279,healthdb_secure.sqlite,healthdb.sqlite
10,2021-01-20 15:25:14.314639+00:00,2021-01-20 15:35:28.303127+00:00,00:10:13,59.565432,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83280,healthdb_secure.sqlite,healthdb.sqlite
11,2021-02-06 20:25:21.383172+00:00,2021-02-06 20:41:30.416222+00:00,00:16:09,63.779438,"SpringBoard,com.spotify.client",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,117131,healthdb_secure.sqlite,healthdb.sqlite
12,2021-02-06 20:41:30.417321+00:00,2021-02-06 20:41:33.425321+00:00,00:00:03,64.679573,SpringBoard,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,117132,healthdb_secure.sqlite,healthdb.sqlite
13,2023-05-19 15:52:00.889683+00:00,2023-05-19 15:54:19.359843+00:00,00:02:18,65.811303,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7394,healthdb_secure.sqlite,healthdb.sqlite
14,2023-05-19 15:54:19.342857+00:00,2023-05-19 15:54:22.352857+00:00,00:00:03,68.578384,"AllTrails,SpringBoard,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7395,healthdb_secure.sqlite,healthdb.sqlite
15,2023-05-19 15:54:22.228314+00:00,2023-05-19 15:59:14.239136+00:00,00:04:52,66.968016,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7396,healthdb_secure.sqlite,healthdb.sqlite
16,2023-05-19 15:59:14.349186+00:00,2023-05-19 15:59:20.369111+00:00,00:00:06,69.423137,"AllTrails,com.apple.Music,com.apple.camera",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7397,healthdb_secure.sqlite,healthdb.sqlite
17,2023-05-19 16:21:57.773238+00:00,2023-05-19 16:31:29.759698+00:00,00:09:31,66.112819,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7398,healthdb_secure.sqlite,healthdb.sqlite
18,2023-05-19 16:32:01.575098+00:00,2023-05-19 16:35:11.528911+00:00,00:03:09,52.294415,SpringBoard,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7399,healthdb_secure.sqlite,healthdb.sqlite
19,2024-01-21 18:39:04.549463+00:00,2024-01-21 19:09:01.472474+00:00,00:29:56,52.348076,"com.apple.springboard,com.spotify.client",AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,208838,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Headphone Audio Events: 23

======================================================================
🎧 HEADPHONE AUDIO LEVELS REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Total Time Duration,Decibels,Bundle Name,Device Name,Device Manufacturer,Device Model,Local Identifier,Key,Data ID,Health Data Source,Device Metadata Source
0,2020-03-27 18:55:14.121678+00:00,2020-03-27 19:19:09.039616+00:00,00:23:54,70.383001,com.apple.Music,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,17916,healthdb_secure.sqlite,healthdb.sqlite
1,2020-03-28 14:39:34.837354+00:00,2020-03-28 14:58:52.919620+00:00,00:19:18,67.953332,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,20487,healthdb_secure.sqlite,healthdb.sqlite
2,2020-03-30 12:41:28.775563+00:00,2020-03-30 13:10:51.633477+00:00,00:29:22,69.823870,com.apple.NanoMusic,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,23989,healthdb_secure.sqlite,healthdb.sqlite
3,2020-03-31 18:58:07.664629+00:00,2020-03-31 19:25:18.001250+00:00,00:27:10,74.539604,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,28272,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-02 17:33:00.120757+00:00,2020-04-02 18:02:55.900469+00:00,00:29:55,76.202527,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31797,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-02 18:02:55.900470+00:00,2020-04-02 18:09:02.937830+00:00,00:06:07,69.529072,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,31798,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-03 19:08:02.690256+00:00,2020-04-03 19:37:58.937985+00:00,00:29:56,74.955671,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,37005,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-03 19:37:58.937984+00:00,2020-04-03 19:47:12.410047+00:00,00:09:13,72.035538,com.apple.NanoMusic,AirPods Pro,Apple Inc.,0x200e,38:EC:0D:E2:49:CF-tacl,_HKPrivateMediaSourceBundleIdentifier,37006,healthdb_secure.sqlite,healthdb.sqlite
8,2021-01-20 14:25:22.351374+00:00,2021-01-20 14:55:17.868731+00:00,00:29:55,62.601885,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83278,healthdb_secure.sqlite,healthdb.sqlite
9,2021-01-20 14:55:17.868599+00:00,2021-01-20 15:25:14.314699+00:00,00:29:56,65.700429,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83279,healthdb_secure.sqlite,healthdb.sqlite
10,2021-01-20 15:25:14.314639+00:00,2021-01-20 15:35:28.303127+00:00,00:10:13,59.565432,"SpringBoard,com.apple.podcasts",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,83280,healthdb_secure.sqlite,healthdb.sqlite
11,2021-02-06 20:25:21.383172+00:00,2021-02-06 20:41:30.416222+00:00,00:16:09,63.779438,"SpringBoard,com.spotify.client",AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,117131,healthdb_secure.sqlite,healthdb.sqlite
12,2021-02-06 20:41:30.417321+00:00,2021-02-06 20:41:33.425321+00:00,00:00:03,64.679573,SpringBoard,AirPods,Apple Inc.,0x2002,7C:04:D0:89:89:A0-tacl,_HKPrivateMediaSourceBundleIdentifier,117132,healthdb_secure.sqlite,healthdb.sqlite
13,2023-05-19 15:52:00.889683+00:00,2023-05-19 15:54:19.359843+00:00,00:02:18,65.811303,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7394,healthdb_secure.sqlite,healthdb.sqlite
14,2023-05-19 15:54:19.342857+00:00,2023-05-19 15:54:22.352857+00:00,00:00:03,68.578384,"AllTrails,SpringBoard,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7395,healthdb_secure.sqlite,healthdb.sqlite
15,2023-05-19 15:54:22.228314+00:00,2023-05-19 15:59:14.239136+00:00,00:04:52,66.968016,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7396,healthdb_secure.sqlite,healthdb.sqlite
16,2023-05-19 15:59:14.349186+00:00,2023-05-19 15:59:20.369111+00:00,00:00:06,69.423137,"AllTrails,com.apple.Music,com.apple.camera",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7397,healthdb_secure.sqlite,healthdb.sqlite
17,2023-05-19 16:21:57.773238+00:00,2023-05-19 16:31:29.759698+00:00,00:09:31,66.112819,"AllTrails,com.apple.Music",This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7398,healthdb_secure.sqlite,healthdb.sqlite
18,2023-05-19 16:32:01.575098+00:00,2023-05-19 16:35:11.528911+00:00,00:03:09,52.294415,SpringBoard,This Is’s AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,7399,healthdb_secure.sqlite,healthdb.sqlite
19,2024-01-21 18:39:04.549463+00:00,2024-01-21 19:09:01.472474+00:00,00:29:56,52.348076,"com.apple.springboard,com.spotify.client",AirPods,Apple Inc.,0x2013,08:65:18:75:5E:75-tacl,_HKPrivateMediaSourceBundleIdentifier,208838,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Headphone Audio Events: 27

# **Fitur Heart Rate**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR HEART RATE
# ============================================================

HEART_RATE_SECURE_TABLES = [
    "samples",
    "quantity_samples",
    "metadata_values",
    "objects",
    "data_provenances"
]

HEART_RATE_HEALTHDB_TABLES = [
    "source_devices",
    "sources"
]


print()
print("=" * 70)
print("❤️ VERIFIKASI STRUKTUR HEART RATE")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()
    print(f"📱 {version}")


    print("   🔐 healthdb_secure.sqlite")

    for table in HEART_RATE_SECURE_TABLES:

        status = (
            "✅"
            if table in secure_tables
            else "❌"
        )

        print(
            f"      {status} {table}"
        )


    print("   📂 healthdb.sqlite")

    for table in HEART_RATE_HEALTHDB_TABLES:

        status = (
            "✅"
            if table in healthdb_tables
            else "❌"
        )

        print(
            f"      {status} {table}"
        )


print()
print("=" * 70)

======================================================================
❤️ VERIFIKASI STRUKTUR HEART RATE
======================================================================

📱 iOS 13.3.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices
      ✅ sources

📱 iOS 13.4.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices
      ✅ sources

📱 iOS 15
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices
      ✅ sources

📱 iOS 16
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices
      ✅ sources

📱 iOS 17
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ metadata_values
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ source_devices
      ✅ sources

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR HEART RATE
# ============================================================

def extract_heart_rate(
    secure_database_path,
    health_database_path
):

    """
    Mengekstrak Heart Rate dari dua database.

    healthdb_secure.sqlite:
        samples
        quantity_samples
        metadata_values
        objects
        data_provenances

    healthdb.sqlite:
        source_devices
        sources
    """


    # ========================================================
    # 1. HEALTHDB_SECURE.SQLITE
    # ========================================================

    secure_conn = open_sqlite_readonly(
        secure_database_path
    )


    secure_query = """
    SELECT

        s.start_date
            AS start_cocoa,

        s.end_date
            AS end_cocoa,

        CAST(
            ROUND(qs.quantity * 60.0)
            AS INTEGER
        )
            AS bpm,

        mv.numerical_value
            AS context_code,

        o.creation_date
            AS added_cocoa,

        dp.device_id
            AS device_id,

        dp.source_id
            AS source_id,

        dp.source_version
            AS software_version,

        dp.tz_name
            AS tz_name,

        s.data_id
            AS data_id

    FROM samples s


    LEFT JOIN quantity_samples qs

        ON qs.data_id
        = s.data_id


    LEFT JOIN metadata_values mv

        ON mv.object_id
        = s.data_id


    LEFT JOIN objects o

        ON o.data_id
        = s.data_id


    LEFT JOIN data_provenances dp

        ON dp.ROWID
        = o.provenance


    WHERE

        s.data_type IN (5, '5')

        AND o.type != 2


    ORDER BY

        s.start_date DESC
    """


    df_secure = pd.read_sql_query(
        secure_query,
        secure_conn
    )


    secure_conn.close()


    # ========================================================
    # 2. SOURCE_DEVICES DARI HEALTHDB.SQLITE
    # ========================================================

    health_conn = open_sqlite_readonly(
        health_database_path
    )


    device_query = """
    SELECT

        ROWID
            AS device_id,

        name
            AS device_name,

        manufacturer
            AS manufacturer,

        hardware
            AS hardware

    FROM source_devices
    """


    df_devices = pd.read_sql_query(
        device_query,
        health_conn
    )


    # ========================================================
    # 3. SOURCES DARI HEALTHDB.SQLITE
    # ========================================================

    source_query = """
    SELECT

        ROWID
            AS source_id,

        name
            AS source_name,

        source_options
            AS source_options

    FROM sources
    """


    df_sources = pd.read_sql_query(
        source_query,
        health_conn
    )


    health_conn.close()


    # ========================================================
    # 4. NORMALISASI ID
    # ========================================================

    for dataframe, column in [

        (df_secure, "device_id"),
        (df_devices, "device_id"),
        (df_secure, "source_id"),
        (df_sources, "source_id")

    ]:

        dataframe[column] = pd.to_numeric(
            dataframe[column],
            errors="coerce"
        ).astype("Int64")


    # ========================================================
    # 5. MERGE SOURCE_DEVICES
    # ========================================================

    df_result = df_secure.merge(

        df_devices,

        how="left",

        on="device_id",

        validate="many_to_one"
    )


    # ========================================================
    # 6. MERGE SOURCES
    # ========================================================

    df_result = df_result.merge(

        df_sources,

        how="left",

        on="source_id",

        validate="many_to_one"
    )


    # ========================================================
    # 7. SESUAI PLASO:
    #
    # CASE sd.name
    # WHEN "**NONE**" THEN ""
    # ========================================================

    df_result["device_name"] = (
        df_result["device_name"]
        .replace("**NONE**", "")
    )


    return df_result


print(
    "✅ Extractor Heart Rate "
    "dua database siap digunakan."
)

✅ Extractor Heart Rate dua database siap digunakan.

In [ ]:
# ============================================================
# MENJALANKAN EXTRACTOR HEART RATE
# ============================================================

heart_rate_results = {}


for dataset in target_datasets:

    version = dataset["version"]

    secure_path = dataset[
        "healthdb_secure"
    ]

    healthdb_path = dataset[
        "healthdb"
    ]


    print()
    print("=" * 70)

    print(
        f"❤️ HEART RATE - {version}"
    )

    print("=" * 70)


    try:

        df_heart_rate = extract_heart_rate(
            secure_path,
            healthdb_path
        )


        heart_rate_results[
            version
        ] = df_heart_rate


        print(
            "✅ Ekstraksi berhasil"
        )


        print(
            f"📊 Total Events: "
            f"{len(df_heart_rate)}"
        )


        # -----------------------------------------------
        # Device berhasil direlasikan
        # -----------------------------------------------

        device_found = (
            df_heart_rate[
                "device_name"
            ]
            .notna()
            .sum()
        )


        # -----------------------------------------------
        # Source berhasil direlasikan
        # -----------------------------------------------

        source_found = (
            df_heart_rate[
                "source_name"
            ]
            .notna()
            .sum()
        )


        print(
            f"⌚ Event dengan Device : "
            f"{device_found}"
        )


        print(
            f"📱 Event dengan Source : "
            f"{source_found}"
        )


        print(
            "🔐 Health Data  : "
            "healthdb_secure.sqlite"
        )


        print(
            "📂 Device/Source: "
            "healthdb.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Ekstraksi gagal: {e}"
        )

======================================================================
❤️ HEART RATE - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 3651
⌚ Event dengan Device : 3651
📱 Event dengan Source : 3651
🔐 Health Data  : healthdb_secure.sqlite
📂 Device/Source: healthdb.sqlite

======================================================================
❤️ HEART RATE - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 4261
⌚ Event dengan Device : 4261
📱 Event dengan Source : 4261
🔐 Health Data  : healthdb_secure.sqlite
📂 Device/Source: healthdb.sqlite

======================================================================
❤️ HEART RATE - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 23485
⌚ Event dengan Device : 23485
📱 Event dengan Source : 23485
🔐 Health Data  : healthdb_secure.sqlite
📂 Device/Source: healthdb.sqlite

======================================================================
❤️ HEART RATE - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 33606
⌚ Event dengan Device : 33606
📱 Event dengan Source : 33606
🔐 Health Data  : healthdb_secure.sqlite
📂 Device/Source: healthdb.sqlite

======================================================================
❤️ HEART RATE - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 35825
⌚ Event dengan Device : 35825
📱 Event dengan Source : 35825
🔐 Health Data  : healthdb_secure.sqlite
📂 Device/Source: healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW HEART RATE
# ============================================================

for version, df_heart_rate in heart_rate_results.items():

    print()
    print("=" * 70)

    print(
        f"❤️ RAW HEART RATE - {version}"
    )

    print("=" * 70)


    display(
        df_heart_rate.head(20)
    )


    print()

    print(
        f"📊 Total Events: "
        f"{len(df_heart_rate)}"
    )

======================================================================
❤️ RAW HEART RATE - iOS 13.3.1
======================================================================

,start_cocoa,end_cocoa,bpm,context_code,added_cocoa,device_id,source_id,software_version,tz_name,data_id,device_name,manufacturer,hardware,source_name,source_options
0,6.084113e+08,6.084113e+08,59,3.0,6.084116e+08,3,4,6.1.3,America/New_York,45994,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
1,6.084111e+08,6.084111e+08,69,3.0,6.084113e+08,3,4,6.1.3,America/New_York,45986,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
2,6.084109e+08,6.084109e+08,63,1.0,6.084110e+08,3,4,6.1.3,America/New_York,45978,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
3,6.084106e+08,6.084106e+08,57,3.0,6.084109e+08,3,4,6.1.3,America/New_York,45973,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
4,6.084103e+08,6.084103e+08,63,3.0,6.084104e+08,3,4,6.1.3,America/New_York,45957,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
5,6.084100e+08,6.084100e+08,56,3.0,6.084101e+08,3,4,6.1.3,America/New_York,45950,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
6,6.084096e+08,6.084096e+08,59,3.0,6.084099e+08,3,4,6.1.3,America/New_York,45944,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
7,6.084094e+08,6.084094e+08,55,3.0,6.084095e+08,3,4,6.1.3,America/New_York,45934,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
8,6.084090e+08,6.084090e+08,58,3.0,6.084092e+08,3,4,6.1.3,America/New_York,45927,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
9,6.084086e+08,6.084086e+08,59,3.0,6.084089e+08,3,4,6.1.3,America/New_York,45919,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
10,6.084083e+08,6.084083e+08,58,3.0,6.084086e+08,3,4,6.1.3,America/New_York,45912,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
11,6.084080e+08,6.084080e+08,75,1.0,6.084083e+08,3,4,6.1.3,America/New_York,45904,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
12,6.084077e+08,6.084077e+08,60,3.0,6.084080e+08,3,4,6.1.3,America/New_York,45896,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
13,6.084075e+08,6.084075e+08,61,3.0,6.084076e+08,3,4,6.1.3,America/New_York,45887,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
14,6.084073e+08,6.084073e+08,58,3.0,6.084074e+08,3,4,6.1.3,America/New_York,45878,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
15,6.084069e+08,6.084069e+08,64,3.0,6.084070e+08,3,4,6.1.3,America/New_York,45873,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
16,6.084066e+08,6.084066e+08,58,3.0,6.084068e+08,3,4,6.1.3,America/New_York,45868,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
17,6.084064e+08,6.084064e+08,59,3.0,6.084067e+08,3,4,6.1.3,America/New_York,45863,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
18,6.084060e+08,6.084060e+08,63,3.0,6.084062e+08,3,4,6.1.3,America/New_York,45856,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
19,6.084058e+08,6.084058e+08,61,3.0,6.084059e+08,3,4,6.1.3,America/New_York,45844,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2

📊 Total Events: 3651

======================================================================
❤️ RAW HEART RATE - iOS 13.4.1
======================================================================

,start_cocoa,end_cocoa,bpm,context_code,added_cocoa,device_id,source_id,software_version,tz_name,data_id,device_name,manufacturer,hardware,source_name,source_options
0,6.087426e+08,6.087426e+08,117,4.0,6.087426e+08,8,4,6.2.1,America/New_York,52279,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
1,6.087424e+08,6.087424e+08,90,4.0,6.087424e+08,8,4,6.2.1,America/New_York,52251,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
2,6.087420e+08,6.087420e+08,88,4.0,6.087421e+08,8,4,6.2.1,America/New_York,52240,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
3,6.087418e+08,6.087418e+08,64,1.0,6.087428e+08,8,4,6.2.1,America/New_York,52297,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
4,6.087414e+08,6.087414e+08,66,1.0,6.087417e+08,8,4,6.2.1,America/New_York,52223,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
5,6.087412e+08,6.087412e+08,62,3.0,6.087414e+08,8,4,6.2.1,America/New_York,52214,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
6,6.087411e+08,6.087411e+08,57,3.0,6.087412e+08,8,4,6.2.1,America/New_York,52204,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
7,6.087408e+08,6.087408e+08,73,4.0,6.087408e+08,8,4,6.2.1,America/New_York,52182,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
8,6.087403e+08,6.087403e+08,64,3.0,6.087409e+08,8,4,6.2.1,America/New_York,52184,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
9,6.087402e+08,6.087402e+08,65,3.0,6.087404e+08,8,4,6.2.1,America/New_York,52163,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
10,6.087396e+08,6.087396e+08,66,3.0,6.087397e+08,8,4,6.2.1,America/New_York,52148,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
11,6.087391e+08,6.087391e+08,76,1.0,6.087393e+08,8,4,6.2.1,America/New_York,52138,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
12,6.087388e+08,6.087388e+08,64,1.0,6.087390e+08,8,4,6.2.1,America/New_York,52128,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
13,6.087386e+08,6.087386e+08,68,1.0,6.087387e+08,8,4,6.2.1,America/New_York,52119,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
14,6.087380e+08,6.087380e+08,69,1.0,6.087386e+08,8,4,6.2.1,America/New_York,52114,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
15,6.087376e+08,6.087376e+08,69,3.0,6.087378e+08,8,4,6.2.1,America/New_York,52095,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
16,6.087372e+08,6.087372e+08,66,3.0,6.087375e+08,8,4,6.2.1,America/New_York,52072,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
17,6.087372e+08,6.087372e+08,62,3.0,6.087373e+08,8,4,6.2.1,America/New_York,52064,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
18,6.087366e+08,6.087366e+08,67,1.0,6.087369e+08,8,4,6.2.1,America/New_York,52058,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
19,6.087364e+08,6.087364e+08,65,1.0,6.087367e+08,8,4,6.2.1,America/New_York,52044,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2

📊 Total Events: 4261

======================================================================
❤️ RAW HEART RATE - iOS 15
======================================================================

,start_cocoa,end_cocoa,bpm,context_code,added_cocoa,device_id,source_id,software_version,tz_name,data_id,device_name,manufacturer,hardware,source_name,source_options
0,703621680.0,703621680.0,64,NaN,7.036218e+08,18,41,36,America/New_York,131995,__NONE__,,,Connect,5
1,703621560.0,703621560.0,66,NaN,7.036218e+08,18,41,36,America/New_York,131994,__NONE__,,,Connect,5
2,703621440.0,703621440.0,65,NaN,7.036218e+08,18,41,36,America/New_York,131993,__NONE__,,,Connect,5
3,703621320.0,703621320.0,66,NaN,7.036218e+08,18,41,36,America/New_York,131992,__NONE__,,,Connect,5
4,703621200.0,703621200.0,66,NaN,7.036218e+08,18,41,36,America/New_York,131991,__NONE__,,,Connect,5
5,703621080.0,703621080.0,63,NaN,7.036218e+08,18,41,36,America/New_York,131990,__NONE__,,,Connect,5
6,703620960.0,703620960.0,57,NaN,7.036218e+08,18,41,36,America/New_York,131989,__NONE__,,,Connect,5
7,703620840.0,703620840.0,71,NaN,7.036218e+08,18,41,36,America/New_York,131988,__NONE__,,,Connect,5
8,703620720.0,703620720.0,81,NaN,7.036218e+08,18,41,36,America/New_York,131987,__NONE__,,,Connect,5
9,703620600.0,703620600.0,66,NaN,7.036218e+08,18,41,36,America/New_York,131986,__NONE__,,,Connect,5
10,703620480.0,703620480.0,74,NaN,7.036218e+08,18,41,36,America/New_York,131985,__NONE__,,,Connect,5
11,703620360.0,703620360.0,70,NaN,7.036218e+08,18,41,36,America/New_York,131984,__NONE__,,,Connect,5
12,703620240.0,703620240.0,69,NaN,7.036218e+08,18,41,36,America/New_York,131983,__NONE__,,,Connect,5
13,703620120.0,703620120.0,65,NaN,7.036218e+08,18,41,36,America/New_York,131982,__NONE__,,,Connect,5
14,703620000.0,703620000.0,60,NaN,7.036218e+08,18,41,36,America/New_York,131981,__NONE__,,,Connect,5
15,703619880.0,703619880.0,57,NaN,7.036218e+08,18,41,36,America/New_York,131980,__NONE__,,,Connect,5
16,703619760.0,703619760.0,57,NaN,7.036218e+08,18,41,36,America/New_York,131979,__NONE__,,,Connect,5
17,703619640.0,703619640.0,61,NaN,7.036218e+08,18,41,36,America/New_York,131978,__NONE__,,,Connect,5
18,703619520.0,703619520.0,76,NaN,7.036218e+08,18,41,36,America/New_York,131977,__NONE__,,,Connect,5
19,703619400.0,703619400.0,61,NaN,7.036218e+08,18,41,36,America/New_York,131976,__NONE__,,,Connect,5

📊 Total Events: 23485

======================================================================
❤️ RAW HEART RATE - iOS 16
======================================================================

,start_cocoa,end_cocoa,bpm,context_code,added_cocoa,device_id,source_id,software_version,tz_name,data_id,device_name,manufacturer,hardware,source_name,source_options
0,713750640.0,713750640.0,75,NaN,7.137508e+08,3,47,5,America/New_York,191283,__NONE__,,,Connect,5
1,713750520.0,713750520.0,72,NaN,7.137508e+08,3,47,5,America/New_York,191282,__NONE__,,,Connect,5
2,713750400.0,713750400.0,61,NaN,7.137508e+08,3,47,5,America/New_York,191281,__NONE__,,,Connect,5
3,713750280.0,713750280.0,58,NaN,7.137508e+08,3,47,5,America/New_York,191280,__NONE__,,,Connect,5
4,713750160.0,713750160.0,58,NaN,7.137508e+08,3,47,5,America/New_York,191279,__NONE__,,,Connect,5
5,713750040.0,713750040.0,60,NaN,7.137508e+08,3,47,5,America/New_York,191278,__NONE__,,,Connect,5
6,713749920.0,713749920.0,67,NaN,7.137508e+08,3,47,5,America/New_York,191277,__NONE__,,,Connect,5
7,713749800.0,713749800.0,69,NaN,7.137508e+08,3,47,5,America/New_York,191276,__NONE__,,,Connect,5
8,713749680.0,713749680.0,68,NaN,7.137508e+08,3,47,5,America/New_York,191275,__NONE__,,,Connect,5
9,713749560.0,713749560.0,60,NaN,7.137508e+08,3,47,5,America/New_York,191274,__NONE__,,,Connect,5
10,713749440.0,713749440.0,57,NaN,7.137508e+08,3,47,5,America/New_York,191273,__NONE__,,,Connect,5
11,713749320.0,713749320.0,57,NaN,7.137508e+08,3,47,5,America/New_York,191272,__NONE__,,,Connect,5
12,713749200.0,713749200.0,56,NaN,7.137508e+08,3,47,5,America/New_York,191271,__NONE__,,,Connect,5
13,713749080.0,713749080.0,55,NaN,7.137508e+08,3,47,5,America/New_York,191270,__NONE__,,,Connect,5
14,713748960.0,713748960.0,53,NaN,7.137508e+08,3,47,5,America/New_York,191269,__NONE__,,,Connect,5
15,713748840.0,713748840.0,55,NaN,7.137508e+08,3,47,5,America/New_York,191268,__NONE__,,,Connect,5
16,713748720.0,713748720.0,63,NaN,7.137508e+08,3,47,5,America/New_York,191267,__NONE__,,,Connect,5
17,713748600.0,713748600.0,77,NaN,7.137508e+08,3,47,5,America/New_York,191266,__NONE__,,,Connect,5
18,713748480.0,713748480.0,69,NaN,7.137508e+08,3,47,5,America/New_York,191265,__NONE__,,,Connect,5
19,713748360.0,713748360.0,66,NaN,7.137508e+08,3,47,5,America/New_York,191264,__NONE__,,,Connect,5

📊 Total Events: 33606

======================================================================
❤️ RAW HEART RATE - iOS 17
======================================================================

,start_cocoa,end_cocoa,bpm,context_code,added_cocoa,device_id,source_id,software_version,tz_name,data_id,device_name,manufacturer,hardware,source_name,source_options
0,7.436923e+08,7.436923e+08,67,1.0,7.436926e+08,33,45,9.6.3,America/New_York,228813,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
1,7.436922e+08,7.436922e+08,87,4.0,7.436923e+08,33,45,9.6.3,America/New_York,228806,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
2,7.436920e+08,7.436920e+08,75,3.0,7.436923e+08,33,45,9.6.3,America/New_York,228807,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
3,7.436918e+08,7.436918e+08,73,3.0,7.436919e+08,33,45,9.6.3,America/New_York,228793,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
4,7.436914e+08,7.436914e+08,79,1.0,7.436917e+08,33,45,9.6.3,America/New_York,228787,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
5,7.436911e+08,7.436911e+08,78,1.0,7.436914e+08,33,45,9.6.3,America/New_York,228779,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
6,7.436908e+08,7.436908e+08,94,4.0,7.436909e+08,33,45,9.6.3,America/New_York,228671,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
7,7.436905e+08,7.436905e+08,79,3.0,7.436911e+08,33,45,9.6.3,America/New_York,228675,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
8,7.436902e+08,7.436902e+08,83,3.0,7.436904e+08,33,45,9.6.3,America/New_York,228659,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
9,7.436901e+08,7.436901e+08,79,3.0,7.436901e+08,33,45,9.6.3,America/New_York,228650,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
10,7.436898e+08,7.436898e+08,71,1.0,7.436898e+08,33,45,9.6.3,America/New_York,228642,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
11,7.436893e+08,7.436893e+08,74,1.0,7.436897e+08,33,45,9.6.3,America/New_York,228639,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
12,7.436889e+08,7.436889e+08,67,1.0,7.436894e+08,33,45,9.6.3,America/New_York,228629,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
13,7.436887e+08,7.436887e+08,65,3.0,7.436889e+08,33,45,9.6.3,America/New_York,228611,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
14,7.436885e+08,7.436885e+08,70,3.0,7.436887e+08,33,45,9.6.3,America/New_York,228606,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
15,7.436882e+08,7.436882e+08,71,3.0,7.436884e+08,33,45,9.6.3,America/New_York,228598,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
16,7.436878e+08,7.436878e+08,70,3.0,7.436880e+08,33,45,9.6.3,America/New_York,228592,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
17,7.436877e+08,7.436877e+08,71,3.0,7.436879e+08,33,45,9.6.3,America/New_York,228586,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
18,7.436872e+08,7.436872e+08,71,3.0,7.436876e+08,33,45,9.6.3,America/New_York,228528,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2
19,7.436870e+08,7.436870e+08,76,3.0,7.436872e+08,33,45,9.6.3,America/New_York,228519,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,2

📊 Total Events: 35825

In [ ]:
# ============================================================
# HEART RATE CONTEXT MAPPING
# ============================================================

HEART_RATE_CONTEXT_MAP = {

    1: "Background",
    2: "Streaming",
    3: "Sedentary",
    4: "Walking",
    5: "Breathe",
    6: "Workout",
    8: "Background",
    9: "ECG",
    10: "Blood Oxygen Saturation"

}


def map_heart_rate_context(value):

    if pd.isna(value):
        return None

    try:

        numeric_value = float(value)

        int_value = int(
            numeric_value
        )

        if numeric_value == int_value:

            if int_value in HEART_RATE_CONTEXT_MAP:

                return HEART_RATE_CONTEXT_MAP[
                    int_value
                ]

        return str(value)

    except (
        TypeError,
        ValueError
    ):

        return str(value)


print(
    "✅ Heart Rate Context Mapping siap."
)

✅ Heart Rate Context Mapping siap.

In [ ]:
# ============================================================
# FORMAT LAPORAN HEART RATE
# ============================================================

heart_rate_reports = {}


for version, df_heart_rate in heart_rate_results.items():

    df_report = pd.DataFrame()


    # --------------------------------------------------------
    # START TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "Start Timestamp"
    ] = (
        df_heart_rate[
            "start_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )
    )


    # --------------------------------------------------------
    # END TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "End Timestamp"
    ] = (
        df_heart_rate[
            "end_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )
    )


    # --------------------------------------------------------
    # ADDED TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "Added Timestamp"
    ] = (
        df_heart_rate[
            "added_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )
    )


    # --------------------------------------------------------
    # BPM
    # --------------------------------------------------------

    df_report[
        "BPM"
    ] = (
        df_heart_rate[
            "bpm"
        ]
    )


    # --------------------------------------------------------
    # CONTEXT
    # --------------------------------------------------------

    df_report[
        "Context"
    ] = (
        df_heart_rate[
            "context_code"
        ]
        .apply(
            map_heart_rate_context
        )
    )


    # --------------------------------------------------------
    # DEVICE INFORMATION
    # --------------------------------------------------------

    df_report[
        "Device Name"
    ] = (
        df_heart_rate[
            "device_name"
        ]
    )


    df_report[
        "Manufacturer"
    ] = (
        df_heart_rate[
            "manufacturer"
        ]
    )


    df_report[
        "Hardware"
    ] = (
        df_heart_rate[
            "hardware"
        ]
    )


    # --------------------------------------------------------
    # SOURCE INFORMATION
    # --------------------------------------------------------

    df_report[
        "Source Name"
    ] = (
        df_heart_rate[
            "source_name"
        ]
    )


    df_report[
        "Software Version"
    ] = (
        df_heart_rate[
            "software_version"
        ]
    )


    df_report[
        "Time Zone"
    ] = (
        df_heart_rate[
            "tz_name"
        ]
    )


    df_report[
        "Source Options"
    ] = (
        df_heart_rate[
            "source_options"
        ]
    )


    # --------------------------------------------------------
    # FORENSIC IDENTIFIER
    # --------------------------------------------------------

    df_report[
        "Data ID"
    ] = (
        df_heart_rate[
            "data_id"
        ]
    )


    # --------------------------------------------------------
    # FORENSIC SOURCE
    # --------------------------------------------------------

    df_report[
        "Health Data Source"
    ] = (
        "healthdb_secure.sqlite"
    )


    df_report[
        "Device & Source Metadata"
    ] = (
        "healthdb.sqlite"
    )


    heart_rate_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Heart Rate "
    "berhasil dibuat."
)

✅ Format laporan Heart Rate berhasil dibuat.

In [ ]:
# ============================================================
# PREVIEW LAPORAN HEART RATE
# ============================================================

for version, df_report in heart_rate_reports.items():

    print()
    print("=" * 70)

    print(
        f"❤️ HEART RATE REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Heart Rate Events: "
        f"{len(df_report)}"
    )

======================================================================
❤️ HEART RATE REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,BPM,Context,Device Name,Manufacturer,Hardware,Source Name,Software Version,Time Zone,Source Options,Data ID,Health Data Source,Device & Source Metadata
0,2020-04-12 19:08:06.815815+00:00,2020-04-12 19:08:06.815815+00:00,2020-04-12 19:12:56.118182+00:00,59,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45994,healthdb_secure.sqlite,healthdb.sqlite
1,2020-04-12 19:05:33.816021+00:00,2020-04-12 19:05:33.816021+00:00,2020-04-12 19:07:30.011305+00:00,69,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45986,healthdb_secure.sqlite,healthdb.sqlite
2,2020-04-12 19:01:00.816262+00:00,2020-04-12 19:01:00.816262+00:00,2020-04-12 19:02:58.444947+00:00,63,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45978,healthdb_secure.sqlite,healthdb.sqlite
3,2020-04-12 18:56:11.316365+00:00,2020-04-12 18:56:11.316365+00:00,2020-04-12 19:01:04.447454+00:00,57,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45973,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-12 18:51:26.816677+00:00,2020-04-12 18:51:26.816677+00:00,2020-04-12 18:53:07.443062+00:00,63,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45957,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-12 18:45:51.817041+00:00,2020-04-12 18:45:51.817041+00:00,2020-04-12 18:48:45.755161+00:00,56,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45950,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-12 18:40:13.814066+00:00,2020-04-12 18:40:13.814066+00:00,2020-04-12 18:44:32.407702+00:00,59,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45944,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-12 18:37:18.316639+00:00,2020-04-12 18:37:18.316639+00:00,2020-04-12 18:37:54.535012+00:00,55,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45934,healthdb_secure.sqlite,healthdb.sqlite
8,2020-04-12 18:29:33.816686+00:00,2020-04-12 18:29:33.816686+00:00,2020-04-12 18:33:19.258305+00:00,58,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45927,healthdb_secure.sqlite,healthdb.sqlite
9,2020-04-12 18:23:38.323431+00:00,2020-04-12 18:23:38.323431+00:00,2020-04-12 18:27:50.162932+00:00,59,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45919,healthdb_secure.sqlite,healthdb.sqlite
10,2020-04-12 18:19:08.823425+00:00,2020-04-12 18:19:08.823425+00:00,2020-04-12 18:23:08.613191+00:00,58,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45912,healthdb_secure.sqlite,healthdb.sqlite
11,2020-04-12 18:14:05.323283+00:00,2020-04-12 18:14:05.323283+00:00,2020-04-12 18:18:26.429169+00:00,75,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45904,healthdb_secure.sqlite,healthdb.sqlite
12,2020-04-12 18:08:57.323342+00:00,2020-04-12 18:08:57.323342+00:00,2020-04-12 18:12:56.595478+00:00,60,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45896,healthdb_secure.sqlite,healthdb.sqlite
13,2020-04-12 18:04:31.818605+00:00,2020-04-12 18:04:31.818605+00:00,2020-04-12 18:07:29.454951+00:00,61,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45887,healthdb_secure.sqlite,healthdb.sqlite
14,2020-04-12 18:01:26.322212+00:00,2020-04-12 18:01:26.322212+00:00,2020-04-12 18:02:48.510788+00:00,58,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45878,healthdb_secure.sqlite,healthdb.sqlite
15,2020-04-12 17:55:35.822124+00:00,2020-04-12 17:55:35.822124+00:00,2020-04-12 17:57:29.463045+00:00,64,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45873,healthdb_secure.sqlite,healthdb.sqlite
16,2020-04-12 17:49:40.321846+00:00,2020-04-12 17:49:40.321846+00:00,2020-04-12 17:52:49.462363+00:00,58,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45868,healthdb_secure.sqlite,healthdb.sqlite
17,2020-04-12 17:47:16.822161+00:00,2020-04-12 17:47:16.822161+00:00,2020-04-12 17:52:25.780636+00:00,59,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45863,healthdb_secure.sqlite,healthdb.sqlite
18,2020-04-12 17:39:50.816404+00:00,2020-04-12 17:39:50.816404+00:00,2020-04-12 17:43:44.558448+00:00,63,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45856,healthdb_secure.sqlite,healthdb.sqlite
19,2020-04-12 17:37:18.319849+00:00,2020-04-12 17:37:18.319849+00:00,2020-04-12 17:38:17.676622+00:00,61,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,2,45844,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Heart Rate Events: 3651

======================================================================
❤️ HEART RATE REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,BPM,Context,Device Name,Manufacturer,Hardware,Source Name,Software Version,Time Zone,Source Options,Data ID,Health Data Source,Device & Source Metadata
0,2020-04-16 15:09:44.211199+00:00,2020-04-16 15:09:44.211199+00:00,2020-04-16 15:09:45.293712+00:00,117,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52279,healthdb_secure.sqlite,healthdb.sqlite
1,2020-04-16 15:06:40.469115+00:00,2020-04-16 15:06:40.469115+00:00,2020-04-16 15:07:15.539481+00:00,90,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52251,healthdb_secure.sqlite,healthdb.sqlite
2,2020-04-16 15:00:38.742903+00:00,2020-04-16 15:00:38.742903+00:00,2020-04-16 15:01:18.826584+00:00,88,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52240,healthdb_secure.sqlite,healthdb.sqlite
3,2020-04-16 14:57:14.547783+00:00,2020-04-16 14:57:14.547783+00:00,2020-04-16 15:12:48.546374+00:00,64,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52297,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-16 14:50:25.821272+00:00,2020-04-16 14:50:25.821272+00:00,2020-04-16 14:55:43.179609+00:00,66,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52223,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-16 14:46:52.821213+00:00,2020-04-16 14:46:52.821213+00:00,2020-04-16 14:50:14.151399+00:00,62,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52214,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-16 14:44:42.321258+00:00,2020-04-16 14:44:42.321258+00:00,2020-04-16 14:46:13.936101+00:00,57,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52204,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-16 14:39:19.259094+00:00,2020-04-16 14:39:19.259094+00:00,2020-04-16 14:39:55.326297+00:00,73,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52182,healthdb_secure.sqlite,healthdb.sqlite
8,2020-04-16 14:31:39.875802+00:00,2020-04-16 14:31:39.875802+00:00,2020-04-16 14:41:39.103096+00:00,64,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52184,healthdb_secure.sqlite,healthdb.sqlite
9,2020-04-16 14:29:32.875802+00:00,2020-04-16 14:29:32.875802+00:00,2020-04-16 14:33:05.549300+00:00,65,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52163,healthdb_secure.sqlite,healthdb.sqlite
10,2020-04-16 14:19:48.376026+00:00,2020-04-16 14:19:48.376026+00:00,2020-04-16 14:21:24.375155+00:00,66,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52148,healthdb_secure.sqlite,healthdb.sqlite
11,2020-04-16 14:11:02.876129+00:00,2020-04-16 14:11:02.876129+00:00,2020-04-16 14:15:08.775581+00:00,76,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52138,healthdb_secure.sqlite,healthdb.sqlite
12,2020-04-16 14:07:14.376104+00:00,2020-04-16 14:07:14.376104+00:00,2020-04-16 14:10:07.881786+00:00,64,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52128,healthdb_secure.sqlite,healthdb.sqlite
13,2020-04-16 14:02:53.376222+00:00,2020-04-16 14:02:53.376222+00:00,2020-04-16 14:05:25.699036+00:00,68,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52119,healthdb_secure.sqlite,healthdb.sqlite
14,2020-04-16 13:53:58.376142+00:00,2020-04-16 13:53:58.376142+00:00,2020-04-16 14:03:00.806480+00:00,69,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52114,healthdb_secure.sqlite,healthdb.sqlite
15,2020-04-16 13:46:20.878647+00:00,2020-04-16 13:46:20.878647+00:00,2020-04-16 13:50:09.011245+00:00,69,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52095,healthdb_secure.sqlite,healthdb.sqlite
16,2020-04-16 13:40:37.378779+00:00,2020-04-16 13:40:37.378779+00:00,2020-04-16 13:45:26.716562+00:00,66,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52072,healthdb_secure.sqlite,healthdb.sqlite
17,2020-04-16 13:39:19.878779+00:00,2020-04-16 13:39:19.878779+00:00,2020-04-16 13:41:33.924484+00:00,62,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52064,healthdb_secure.sqlite,healthdb.sqlite
18,2020-04-16 13:30:30.878170+00:00,2020-04-16 13:30:30.878170+00:00,2020-04-16 13:35:14.291510+00:00,67,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52058,healthdb_secure.sqlite,healthdb.sqlite
19,2020-04-16 13:25:59.878006+00:00,2020-04-16 13:25:59.878006+00:00,2020-04-16 13:30:51.647374+00:00,65,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,6.2.1,America/New_York,2,52044,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Heart Rate Events: 4261

======================================================================
❤️ HEART RATE REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,BPM,Context,Device Name,Manufacturer,Hardware,Source Name,Software Version,Time Zone,Source Options,Data ID,Health Data Source,Device & Source Metadata
0,2023-04-19 18:28:00+00:00,2023-04-19 18:28:00+00:00,2023-04-19 18:30:17.594169+00:00,64,None,__NONE__,,,Connect,36,America/New_York,5,131995,healthdb_secure.sqlite,healthdb.sqlite
1,2023-04-19 18:26:00+00:00,2023-04-19 18:26:00+00:00,2023-04-19 18:30:17.594169+00:00,66,None,__NONE__,,,Connect,36,America/New_York,5,131994,healthdb_secure.sqlite,healthdb.sqlite
2,2023-04-19 18:24:00+00:00,2023-04-19 18:24:00+00:00,2023-04-19 18:30:17.594169+00:00,65,None,__NONE__,,,Connect,36,America/New_York,5,131993,healthdb_secure.sqlite,healthdb.sqlite
3,2023-04-19 18:22:00+00:00,2023-04-19 18:22:00+00:00,2023-04-19 18:30:17.594169+00:00,66,None,__NONE__,,,Connect,36,America/New_York,5,131992,healthdb_secure.sqlite,healthdb.sqlite
4,2023-04-19 18:20:00+00:00,2023-04-19 18:20:00+00:00,2023-04-19 18:30:17.594169+00:00,66,None,__NONE__,,,Connect,36,America/New_York,5,131991,healthdb_secure.sqlite,healthdb.sqlite
5,2023-04-19 18:18:00+00:00,2023-04-19 18:18:00+00:00,2023-04-19 18:30:17.594169+00:00,63,None,__NONE__,,,Connect,36,America/New_York,5,131990,healthdb_secure.sqlite,healthdb.sqlite
6,2023-04-19 18:16:00+00:00,2023-04-19 18:16:00+00:00,2023-04-19 18:30:17.594169+00:00,57,None,__NONE__,,,Connect,36,America/New_York,5,131989,healthdb_secure.sqlite,healthdb.sqlite
7,2023-04-19 18:14:00+00:00,2023-04-19 18:14:00+00:00,2023-04-19 18:30:17.594169+00:00,71,None,__NONE__,,,Connect,36,America/New_York,5,131988,healthdb_secure.sqlite,healthdb.sqlite
8,2023-04-19 18:12:00+00:00,2023-04-19 18:12:00+00:00,2023-04-19 18:30:17.594169+00:00,81,None,__NONE__,,,Connect,36,America/New_York,5,131987,healthdb_secure.sqlite,healthdb.sqlite
9,2023-04-19 18:10:00+00:00,2023-04-19 18:10:00+00:00,2023-04-19 18:30:17.594169+00:00,66,None,__NONE__,,,Connect,36,America/New_York,5,131986,healthdb_secure.sqlite,healthdb.sqlite
10,2023-04-19 18:08:00+00:00,2023-04-19 18:08:00+00:00,2023-04-19 18:30:17.594169+00:00,74,None,__NONE__,,,Connect,36,America/New_York,5,131985,healthdb_secure.sqlite,healthdb.sqlite
11,2023-04-19 18:06:00+00:00,2023-04-19 18:06:00+00:00,2023-04-19 18:30:17.594169+00:00,70,None,__NONE__,,,Connect,36,America/New_York,5,131984,healthdb_secure.sqlite,healthdb.sqlite
12,2023-04-19 18:04:00+00:00,2023-04-19 18:04:00+00:00,2023-04-19 18:30:17.594169+00:00,69,None,__NONE__,,,Connect,36,America/New_York,5,131983,healthdb_secure.sqlite,healthdb.sqlite
13,2023-04-19 18:02:00+00:00,2023-04-19 18:02:00+00:00,2023-04-19 18:30:17.594169+00:00,65,None,__NONE__,,,Connect,36,America/New_York,5,131982,healthdb_secure.sqlite,healthdb.sqlite
14,2023-04-19 18:00:00+00:00,2023-04-19 18:00:00+00:00,2023-04-19 18:30:17.594169+00:00,60,None,__NONE__,,,Connect,36,America/New_York,5,131981,healthdb_secure.sqlite,healthdb.sqlite
15,2023-04-19 17:58:00+00:00,2023-04-19 17:58:00+00:00,2023-04-19 18:30:17.594169+00:00,57,None,__NONE__,,,Connect,36,America/New_York,5,131980,healthdb_secure.sqlite,healthdb.sqlite
16,2023-04-19 17:56:00+00:00,2023-04-19 17:56:00+00:00,2023-04-19 18:30:17.594169+00:00,57,None,__NONE__,,,Connect,36,America/New_York,5,131979,healthdb_secure.sqlite,healthdb.sqlite
17,2023-04-19 17:54:00+00:00,2023-04-19 17:54:00+00:00,2023-04-19 18:30:17.594169+00:00,61,None,__NONE__,,,Connect,36,America/New_York,5,131978,healthdb_secure.sqlite,healthdb.sqlite
18,2023-04-19 17:52:00+00:00,2023-04-19 17:52:00+00:00,2023-04-19 18:30:17.594169+00:00,76,None,__NONE__,,,Connect,36,America/New_York,5,131977,healthdb_secure.sqlite,healthdb.sqlite
19,2023-04-19 17:50:00+00:00,2023-04-19 17:50:00+00:00,2023-04-19 18:30:17.594169+00:00,61,None,__NONE__,,,Connect,36,America/New_York,5,131976,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Heart Rate Events: 23485

======================================================================
❤️ HEART RATE REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,BPM,Context,Device Name,Manufacturer,Hardware,Source Name,Software Version,Time Zone,Source Options,Data ID,Health Data Source,Device & Source Metadata
0,2023-08-15 00:04:00+00:00,2023-08-15 00:04:00+00:00,2023-08-15 00:07:08.065838+00:00,75,None,__NONE__,,,Connect,5,America/New_York,5,191283,healthdb_secure.sqlite,healthdb.sqlite
1,2023-08-15 00:02:00+00:00,2023-08-15 00:02:00+00:00,2023-08-15 00:07:08.065838+00:00,72,None,__NONE__,,,Connect,5,America/New_York,5,191282,healthdb_secure.sqlite,healthdb.sqlite
2,2023-08-15 00:00:00+00:00,2023-08-15 00:00:00+00:00,2023-08-15 00:07:08.065838+00:00,61,None,__NONE__,,,Connect,5,America/New_York,5,191281,healthdb_secure.sqlite,healthdb.sqlite
3,2023-08-14 23:58:00+00:00,2023-08-14 23:58:00+00:00,2023-08-15 00:07:08.065838+00:00,58,None,__NONE__,,,Connect,5,America/New_York,5,191280,healthdb_secure.sqlite,healthdb.sqlite
4,2023-08-14 23:56:00+00:00,2023-08-14 23:56:00+00:00,2023-08-15 00:07:08.065838+00:00,58,None,__NONE__,,,Connect,5,America/New_York,5,191279,healthdb_secure.sqlite,healthdb.sqlite
5,2023-08-14 23:54:00+00:00,2023-08-14 23:54:00+00:00,2023-08-15 00:07:08.065838+00:00,60,None,__NONE__,,,Connect,5,America/New_York,5,191278,healthdb_secure.sqlite,healthdb.sqlite
6,2023-08-14 23:52:00+00:00,2023-08-14 23:52:00+00:00,2023-08-15 00:07:08.065838+00:00,67,None,__NONE__,,,Connect,5,America/New_York,5,191277,healthdb_secure.sqlite,healthdb.sqlite
7,2023-08-14 23:50:00+00:00,2023-08-14 23:50:00+00:00,2023-08-15 00:07:08.065838+00:00,69,None,__NONE__,,,Connect,5,America/New_York,5,191276,healthdb_secure.sqlite,healthdb.sqlite
8,2023-08-14 23:48:00+00:00,2023-08-14 23:48:00+00:00,2023-08-15 00:07:08.065838+00:00,68,None,__NONE__,,,Connect,5,America/New_York,5,191275,healthdb_secure.sqlite,healthdb.sqlite
9,2023-08-14 23:46:00+00:00,2023-08-14 23:46:00+00:00,2023-08-15 00:07:08.065838+00:00,60,None,__NONE__,,,Connect,5,America/New_York,5,191274,healthdb_secure.sqlite,healthdb.sqlite
10,2023-08-14 23:44:00+00:00,2023-08-14 23:44:00+00:00,2023-08-15 00:07:08.065838+00:00,57,None,__NONE__,,,Connect,5,America/New_York,5,191273,healthdb_secure.sqlite,healthdb.sqlite
11,2023-08-14 23:42:00+00:00,2023-08-14 23:42:00+00:00,2023-08-15 00:07:08.065838+00:00,57,None,__NONE__,,,Connect,5,America/New_York,5,191272,healthdb_secure.sqlite,healthdb.sqlite
12,2023-08-14 23:40:00+00:00,2023-08-14 23:40:00+00:00,2023-08-15 00:07:08.065838+00:00,56,None,__NONE__,,,Connect,5,America/New_York,5,191271,healthdb_secure.sqlite,healthdb.sqlite
13,2023-08-14 23:38:00+00:00,2023-08-14 23:38:00+00:00,2023-08-15 00:07:08.065838+00:00,55,None,__NONE__,,,Connect,5,America/New_York,5,191270,healthdb_secure.sqlite,healthdb.sqlite
14,2023-08-14 23:36:00+00:00,2023-08-14 23:36:00+00:00,2023-08-15 00:07:08.065838+00:00,53,None,__NONE__,,,Connect,5,America/New_York,5,191269,healthdb_secure.sqlite,healthdb.sqlite
15,2023-08-14 23:34:00+00:00,2023-08-14 23:34:00+00:00,2023-08-15 00:07:08.065838+00:00,55,None,__NONE__,,,Connect,5,America/New_York,5,191268,healthdb_secure.sqlite,healthdb.sqlite
16,2023-08-14 23:32:00+00:00,2023-08-14 23:32:00+00:00,2023-08-15 00:07:08.065838+00:00,63,None,__NONE__,,,Connect,5,America/New_York,5,191267,healthdb_secure.sqlite,healthdb.sqlite
17,2023-08-14 23:30:00+00:00,2023-08-14 23:30:00+00:00,2023-08-15 00:07:08.065838+00:00,77,None,__NONE__,,,Connect,5,America/New_York,5,191266,healthdb_secure.sqlite,healthdb.sqlite
18,2023-08-14 23:28:00+00:00,2023-08-14 23:28:00+00:00,2023-08-15 00:07:08.065838+00:00,69,None,__NONE__,,,Connect,5,America/New_York,5,191265,healthdb_secure.sqlite,healthdb.sqlite
19,2023-08-14 23:26:00+00:00,2023-08-14 23:26:00+00:00,2023-08-15 00:07:08.065838+00:00,66,None,__NONE__,,,Connect,5,America/New_York,5,191264,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Heart Rate Events: 33606

======================================================================
❤️ HEART RATE REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,BPM,Context,Device Name,Manufacturer,Hardware,Source Name,Software Version,Time Zone,Source Options,Data ID,Health Data Source,Device & Source Metadata
0,2024-07-26 13:12:24.026299+00:00,2024-07-26 13:12:24.026299+00:00,2024-07-26 13:16:07.860034+00:00,67,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228813,healthdb_secure.sqlite,healthdb.sqlite
1,2024-07-26 13:10:38.091341+00:00,2024-07-26 13:10:38.091341+00:00,2024-07-26 13:10:58.940246+00:00,87,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228806,healthdb_secure.sqlite,healthdb.sqlite
2,2024-07-26 13:06:45.683696+00:00,2024-07-26 13:06:45.683696+00:00,2024-07-26 13:11:38.048963+00:00,75,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228807,healthdb_secure.sqlite,healthdb.sqlite
3,2024-07-26 13:02:51.182432+00:00,2024-07-26 13:02:51.182432+00:00,2024-07-26 13:05:29.569515+00:00,73,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228793,healthdb_secure.sqlite,healthdb.sqlite
4,2024-07-26 12:56:56.682759+00:00,2024-07-26 12:56:56.682759+00:00,2024-07-26 13:01:39.829395+00:00,79,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228787,healthdb_secure.sqlite,healthdb.sqlite
5,2024-07-26 12:51:31.682819+00:00,2024-07-26 12:51:31.682819+00:00,2024-07-26 12:55:51.906075+00:00,78,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228779,healthdb_secure.sqlite,healthdb.sqlite
6,2024-07-26 12:46:59.979930+00:00,2024-07-26 12:46:59.979930+00:00,2024-07-26 12:47:41.220358+00:00,94,Walking,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228671,healthdb_secure.sqlite,healthdb.sqlite
7,2024-07-26 12:41:19.183493+00:00,2024-07-26 12:41:19.183493+00:00,2024-07-26 12:51:54.836088+00:00,79,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228675,healthdb_secure.sqlite,healthdb.sqlite
8,2024-07-26 12:37:26.683602+00:00,2024-07-26 12:37:26.683602+00:00,2024-07-26 12:40:31.517113+00:00,83,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228659,healthdb_secure.sqlite,healthdb.sqlite
9,2024-07-26 12:34:23.183828+00:00,2024-07-26 12:34:23.183828+00:00,2024-07-26 12:35:16.413132+00:00,79,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228650,healthdb_secure.sqlite,healthdb.sqlite
10,2024-07-26 12:29:22.933676+00:00,2024-07-26 12:29:22.933676+00:00,2024-07-26 12:30:42.918632+00:00,71,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228642,healthdb_secure.sqlite,healthdb.sqlite
11,2024-07-26 12:22:04.308820+00:00,2024-07-26 12:22:04.308820+00:00,2024-07-26 12:28:16.111742+00:00,74,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228639,healthdb_secure.sqlite,healthdb.sqlite
12,2024-07-26 12:15:06.933989+00:00,2024-07-26 12:15:06.933989+00:00,2024-07-26 12:22:36.647965+00:00,67,Background,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228629,healthdb_secure.sqlite,healthdb.sqlite
13,2024-07-26 12:11:30.934381+00:00,2024-07-26 12:11:30.934381+00:00,2024-07-26 12:15:38.326772+00:00,65,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228611,healthdb_secure.sqlite,healthdb.sqlite
14,2024-07-26 12:09:09.683610+00:00,2024-07-26 12:09:09.683610+00:00,2024-07-26 12:11:52.928596+00:00,70,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228606,healthdb_secure.sqlite,healthdb.sqlite
15,2024-07-26 12:03:19.684746+00:00,2024-07-26 12:03:19.684746+00:00,2024-07-26 12:06:56.334071+00:00,71,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228598,healthdb_secure.sqlite,healthdb.sqlite
16,2024-07-26 11:57:17.559198+00:00,2024-07-26 11:57:17.559198+00:00,2024-07-26 12:00:30.465832+00:00,70,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228592,healthdb_secure.sqlite,healthdb.sqlite
17,2024-07-26 11:55:03.684198+00:00,2024-07-26 11:55:03.684198+00:00,2024-07-26 11:58:10.541771+00:00,71,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228586,healthdb_secure.sqlite,healthdb.sqlite
18,2024-07-26 11:46:22.183877+00:00,2024-07-26 11:46:22.183877+00:00,2024-07-26 11:52:47.916388+00:00,71,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228528,healthdb_secure.sqlite,healthdb.sqlite
19,2024-07-26 11:43:06.183885+00:00,2024-07-26 11:43:06.183885+00:00,2024-07-26 11:45:55.100522+00:00,76,Sedentary,Apple Watch,Apple Inc.,"Watch4,3",This Is’s Apple Watch,9.6.3,America/New_York,2,228519,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Heart Rate Events: 35825

# **Fitur Height**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR HEIGHT
# ============================================================

HEIGHT_REQUIRED_TABLES = [
    "samples",
    "quantity_samples"
]


print()
print("=" * 70)
print("📏 VERIFIKASI STRUKTUR HEIGHT")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    print()
    print(f"📱 {version}")

    for table in HEIGHT_REQUIRED_TABLES:

        status = (
            "✅"
            if table in secure_tables
            else "❌"
        )

        print(
            f"   🔐 {status} {table}"
        )


print()
print("=" * 70)

======================================================================
📏 VERIFIKASI STRUKTUR HEIGHT
======================================================================

📱 iOS 13.3.1
   🔐 ✅ samples
   🔐 ✅ quantity_samples

📱 iOS 13.4.1
   🔐 ✅ samples
   🔐 ✅ quantity_samples

📱 iOS 15
   🔐 ✅ samples
   🔐 ✅ quantity_samples

📱 iOS 16
   🔐 ✅ samples
   🔐 ✅ quantity_samples

📱 iOS 17
   🔐 ✅ samples
   🔐 ✅ quantity_samples

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR HEIGHT
# ============================================================

def extract_height(database_path):

    """
    Mengekstrak data Height dari
    healthdb_secure.sqlite.
    """

    conn = open_sqlite_readonly(
        database_path
    )


    query = """
    SELECT

        samples.start_date
            AS start_cocoa,

        quantity_samples.quantity
            AS height_meters

    FROM samples

    LEFT JOIN quantity_samples

        ON samples.data_id
        = quantity_samples.data_id

    WHERE

        samples.data_type IN (2, '2')

        AND quantity_samples.quantity IS NOT NULL

    ORDER BY
        samples.start_date DESC
    """


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    return df


print(
    "✅ Extractor Height siap digunakan."
)

✅ Extractor Height siap digunakan.

In [ ]:
# ============================================================
# MENJALANKAN EXTRACTOR HEIGHT
# ============================================================

height_results = {}


for dataset in target_datasets:

    version = dataset["version"]

    secure_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"📏 HEIGHT - {version}"
    )

    print("=" * 70)


    try:

        df_height = extract_height(
            secure_path
        )


        height_results[
            version
        ] = df_height


        print(
            "✅ Ekstraksi berhasil"
        )


        print(
            f"📊 Total Events: "
            f"{len(df_height)}"
        )


        print(
            "🔐 Source: "
            "healthdb_secure.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Ekstraksi gagal: {e}"
        )

======================================================================
📏 HEIGHT - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 1
🔐 Source: healthdb_secure.sqlite

======================================================================
📏 HEIGHT - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 1
🔐 Source: healthdb_secure.sqlite

======================================================================
📏 HEIGHT - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 1
🔐 Source: healthdb_secure.sqlite

======================================================================
📏 HEIGHT - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 1
🔐 Source: healthdb_secure.sqlite

======================================================================
📏 HEIGHT - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 1
🔐 Source: healthdb_secure.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW HEIGHT
# ============================================================

for version, df_height in height_results.items():

    print()
    print("=" * 70)

    print(
        f"📏 RAW HEIGHT - {version}"
    )

    print("=" * 70)


    display(
        df_height.head(20)
    )


    print()

    print(
        f"📊 Total Events: "
        f"{len(df_height)}"
    )

======================================================================
📏 RAW HEIGHT - iOS 13.3.1
======================================================================

    start_cocoa  height_meters
0  6.076310e+08          1.778

📊 Total Events: 1

======================================================================
📏 RAW HEIGHT - iOS 13.4.1
======================================================================

    start_cocoa  height_meters
0  6.076310e+08          1.778

📊 Total Events: 1

======================================================================
📏 RAW HEIGHT - iOS 15
======================================================================

    start_cocoa  height_meters
0  6.076310e+08          1.778

📊 Total Events: 1

======================================================================
📏 RAW HEIGHT - iOS 16
======================================================================

    start_cocoa  height_meters
0  6.076310e+08          1.778

📊 Total Events: 1

======================================================================
📏 RAW HEIGHT - iOS 17
======================================================================

    start_cocoa  height_meters
0  6.076310e+08          1.778

📊 Total Events: 1

In [ ]:
# ============================================================
# FUNGSI KONVERSI HEIGHT
# ============================================================

def meters_to_centimeters_int(meters):

    """
    Mengubah meter menjadi integer centimeter.

    Contoh:
    1.70 m → 170 cm
    """

    try:

        return int(
            float(meters) * 100
        )

    except (
        TypeError,
        ValueError
    ):

        return None


def meters_to_feet_inches(meters):

    """
    Mengubah meter menjadi format feet'inches.

    Contoh:
    1.778 m → 5'10"
    """

    if meters is None:

        return None


    try:

        feet_float = (
            float(meters)
            * 3.280839895
        )


        feet = int(
            feet_float
        )


        inches = int(
            (
                (feet_float - feet)
                * 12
            )
            + 0.5
        )


        # Contoh:
        # 5'11.8" dibulatkan menjadi 6'0"
        if inches == 12:

            feet += 1

            inches = 0


        return (
            f"{feet}'{inches}\""
        )


    except (
        TypeError,
        ValueError
    ):

        return None


print(
    "✅ Fungsi konversi Height siap."
)

✅ Fungsi konversi Height siap.

In [ ]:
# ============================================================
# FORMAT LAPORAN HEIGHT
# ============================================================

height_reports = {}


for version, df_height in height_results.items():

    df_report = pd.DataFrame()


    # --------------------------------------------------------
    # TIMESTAMP
    # --------------------------------------------------------

    df_report[
        "Timestamp"
    ] = (
        df_height[
            "start_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )
    )


    # --------------------------------------------------------
    # HEIGHT IN METERS
    # --------------------------------------------------------

    df_report[
        "Height (m)"
    ] = (
        df_height[
            "height_meters"
        ]
    )


    # --------------------------------------------------------
    # HEIGHT IN CENTIMETERS
    # --------------------------------------------------------

    df_report[
        "Height (cm)"
    ] = (
        df_height[
            "height_meters"
        ]
        .apply(
            meters_to_centimeters_int
        )
    )


    # --------------------------------------------------------
    # HEIGHT IN FEET/INCHES
    # --------------------------------------------------------

    df_report[
        "Height (ft/in)"
    ] = (
        df_height[
            "height_meters"
        ]
        .apply(
            meters_to_feet_inches
        )
    )


    # --------------------------------------------------------
    # SOURCE DATABASE
    # --------------------------------------------------------

    df_report[
        "Source"
    ] = (
        "healthdb_secure.sqlite"
    )


    height_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Height berhasil dibuat."
)

✅ Format laporan Height berhasil dibuat.

In [ ]:
# ============================================================
# PREVIEW LAPORAN HEIGHT
# ============================================================

for version, df_report in height_reports.items():

    print()
    print("=" * 70)

    print(
        f"📏 HEIGHT REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Height Events: "
        f"{len(df_report)}"
    )

======================================================================
📏 HEIGHT REPORT - iOS 13.3.1
======================================================================

,Timestamp,Height (m),Height (cm),Height (ft/in),Source
0,2020-04-03 18:23:55.320479+00:00,1.778,177,"5'10""",healthdb_secure.sqlite

📊 Total Height Events: 1

======================================================================
📏 HEIGHT REPORT - iOS 13.4.1
======================================================================

,Timestamp,Height (m),Height (cm),Height (ft/in),Source
0,2020-04-03 18:23:55.320479+00:00,1.778,177,"5'10""",healthdb_secure.sqlite

📊 Total Height Events: 1

======================================================================
📏 HEIGHT REPORT - iOS 15
======================================================================

,Timestamp,Height (m),Height (cm),Height (ft/in),Source
0,2020-04-03 18:23:55.320479+00:00,1.778,177,"5'10""",healthdb_secure.sqlite

📊 Total Height Events: 1

======================================================================
📏 HEIGHT REPORT - iOS 16
======================================================================

,Timestamp,Height (m),Height (cm),Height (ft/in),Source
0,2020-04-03 18:23:55.320479+00:00,1.778,177,"5'10""",healthdb_secure.sqlite

📊 Total Height Events: 1

======================================================================
📏 HEIGHT REPORT - iOS 17
======================================================================

,Timestamp,Height (m),Height (cm),Height (ft/in),Source
0,2020-04-03 18:23:55.320479+00:00,1.778,177,"5'10""",healthdb_secure.sqlite

📊 Total Height Events: 1

# **Fitur Resting Heart Rate**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR RESTING HEART RATE
# ============================================================

RESTING_HR_SECURE_TABLES = [
    "samples",
    "quantity_samples",
    "objects",
    "data_provenances"
]


RESTING_HR_HEALTHDB_TABLES = [
    "sources"
]


print()
print("=" * 70)
print("❤️‍🩹 VERIFIKASI STRUKTUR RESTING HEART RATE")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]


    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()
    print(f"📱 {version}")


    print(
        "   🔐 healthdb_secure.sqlite"
    )


    for table in RESTING_HR_SECURE_TABLES:

        status = (
            "✅"
            if table in secure_tables
            else "❌"
        )

        print(
            f"      {status} {table}"
        )


    print(
        "   📂 healthdb.sqlite"
    )


    for table in RESTING_HR_HEALTHDB_TABLES:

        status = (
            "✅"
            if table in healthdb_tables
            else "❌"
        )


        print(
            f"      {status} {table}"
        )


print()
print("=" * 70)

======================================================================
❤️‍🩹 VERIFIKASI STRUKTUR RESTING HEART RATE
======================================================================

📱 iOS 13.3.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ sources

📱 iOS 13.4.1
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ sources

📱 iOS 15
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ sources

📱 iOS 16
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ sources

📱 iOS 17
   🔐 healthdb_secure.sqlite
      ✅ samples
      ✅ quantity_samples
      ✅ objects
      ✅ data_provenances
   📂 healthdb.sqlite
      ✅ sources

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR RESTING HEART RATE
# ============================================================


def extract_resting_heart_rate(
    secure_database_path,
    health_database_path
):

    """
    Extract Resting Heart Rate

    healthdb_secure.sqlite:
        samples
        quantity_samples
        objects
        data_provenances

    healthdb.sqlite:
        sources
    """


    # ========================================================
    # 1. HEALTHDB_SECURE.SQLITE
    # ========================================================


    secure_conn = open_sqlite_readonly(
        secure_database_path
    )


    secure_query = """

    SELECT


        samples.start_date
            AS start_cocoa,


        samples.end_date
            AS end_cocoa,


        CAST(
            ROUND(quantity_samples.quantity)
            AS INTEGER
        )
            AS resting_heart_rate,


        objects.creation_date
            AS added_cocoa,


        data_provenances.source_id
            AS source_id,


        samples.data_id
            AS data_id



    FROM samples


    LEFT JOIN quantity_samples

        ON samples.data_id =
           quantity_samples.data_id



    LEFT JOIN objects

        ON samples.data_id =
           objects.data_id



    LEFT JOIN data_provenances

        ON objects.provenance =
           data_provenances.ROWID



    WHERE


        samples.data_type IN (118, '118')


        AND quantity_samples.quantity IS NOT NULL



    ORDER BY

        samples.start_date DESC

    """


    df_secure = pd.read_sql_query(
        secure_query,
        secure_conn
    )


    secure_conn.close()



    # ========================================================
    # 2. SOURCES DARI HEALTHDB.SQLITE
    # ========================================================


    health_conn = open_sqlite_readonly(
        health_database_path
    )


    source_query = """

    SELECT


        ROWID
            AS source_id,


        product_type
            AS hardware,


        name
            AS source



    FROM sources

    """


    df_sources = pd.read_sql_query(
        source_query,
        health_conn
    )


    health_conn.close()



    # ========================================================
    # 3. NORMALISASI SOURCE ID
    # ========================================================


    df_secure["source_id"] = pd.to_numeric(
        df_secure["source_id"],
        errors="coerce"
    ).astype("Int64")


    df_sources["source_id"] = pd.to_numeric(
        df_sources["source_id"],
        errors="coerce"
    ).astype("Int64")



    # ========================================================
    # 4. MERGE DATABASE
    # ========================================================


    df_result = df_secure.merge(

        df_sources,

        how="left",

        on="source_id",

        validate="many_to_one"

    )


    return df_result



print(
    "✅ Extractor Resting Heart Rate siap."
)

✅ Extractor Resting Heart Rate siap.

In [ ]:
# ============================================================
# EKSTRAKSI RESTING HEART RATE
# ============================================================


resting_hr_results = {}


for dataset in target_datasets:


    version = dataset["version"]


    secure_path = dataset[
        "healthdb_secure"
    ]


    healthdb_path = dataset[
        "healthdb"
    ]


    print()

    print("=" * 70)


    print(
        f"❤️‍🩹 RESTING HEART RATE - {version}"
    )


    print("=" * 70)



    try:


        df_resting = extract_resting_heart_rate(

            secure_path,

            healthdb_path

        )


        resting_hr_results[
            version
        ] = df_resting



        print(
            "✅ Ekstraksi berhasil"
        )


        print(
            f"📊 Total Events: "
            f"{len(df_resting)}"
        )



        source_found = (

            df_resting["source"]
            .notna()
            .sum()

        )


        print(
            f"📱 Event dengan Source: "
            f"{source_found}"
        )


        print(
            "🔐 Data:"
            " healthdb_secure.sqlite"
        )


        print(
            "📂 Source:"
            " healthdb.sqlite"
        )



    except Exception as e:


        print(
            f"❌ Error: {e}"
        )

======================================================================
❤️‍🩹 RESTING HEART RATE - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 14
📱 Event dengan Source: 14
🔐 Data: healthdb_secure.sqlite
📂 Source: healthdb.sqlite

======================================================================
❤️‍🩹 RESTING HEART RATE - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 18
📱 Event dengan Source: 18
🔐 Data: healthdb_secure.sqlite
📂 Source: healthdb.sqlite

======================================================================
❤️‍🩹 RESTING HEART RATE - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 76
📱 Event dengan Source: 76
🔐 Data: healthdb_secure.sqlite
📂 Source: healthdb.sqlite

======================================================================
❤️‍🩹 RESTING HEART RATE - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 102
📱 Event dengan Source: 102
🔐 Data: healthdb_secure.sqlite
📂 Source: healthdb.sqlite

======================================================================
❤️‍🩹 RESTING HEART RATE - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Events: 107
📱 Event dengan Source: 107
🔐 Data: healthdb_secure.sqlite
📂 Source: healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW RESTING HEART RATE
# ============================================================


for version, df_resting in resting_hr_results.items():


    print()

    print("=" * 70)


    print(
        f"❤️‍🩹 RAW RESTING HEART RATE - {version}"
    )


    print("=" * 70)



    display(
        df_resting.head(20)
    )


    print()


    print(
        f"📊 Total Events: "
        f"{len(df_resting)}"
    )

======================================================================
❤️‍🩹 RAW RESTING HEART RATE - iOS 13.3.1
======================================================================

,start_cocoa,end_cocoa,resting_heart_rate,added_cocoa,source_id,data_id,hardware,source
0,6.083954e+08,6.084042e+08,55,6.084044e+08,4,45804,"Watch4,3",This Is’s Apple Watch
1,6.076034e+08,6.076282e+08,59,6.076284e+08,4,38562,"Watch4,3",This Is’s Apple Watch
2,6.075163e+08,6.075665e+08,60,6.075665e+08,4,37727,"Watch4,3",This Is’s Apple Watch
3,6.074326e+08,6.074767e+08,59,6.074770e+08,4,32809,"Watch4,3",This Is’s Apple Watch
4,6.073430e+08,6.073998e+08,60,6.074001e+08,4,31059,"Watch4,3",This Is’s Apple Watch
5,6.072566e+08,6.073108e+08,61,6.073109e+08,4,26272,"Watch4,3",This Is’s Apple Watch
6,6.071697e+08,6.072234e+08,64,6.072237e+08,4,21447,"Watch4,3",This Is’s Apple Watch
7,6.070856e+08,6.071347e+08,64,6.071350e+08,4,19357,"Watch4,3",This Is’s Apple Watch
8,6.069971e+08,6.070488e+08,65,6.070491e+08,4,15755,"Watch4,3",This Is’s Apple Watch
9,6.069110e+08,6.069685e+08,59,6.069687e+08,4,12024,"Watch4,3",This Is’s Apple Watch
10,6.068250e+08,6.068546e+08,63,6.068550e+08,4,9026,"Watch4,3",This Is’s Apple Watch
11,6.067387e+08,6.067588e+08,58,6.067590e+08,4,6702,"Watch4,3",This Is’s Apple Watch
12,6.066531e+08,6.067072e+08,62,6.067073e+08,4,5951,"Watch4,3",This Is’s Apple Watch
13,6.065699e+08,6.066224e+08,58,6.066529e+08,4,4051,"Watch4,3",This Is’s Apple Watch

📊 Total Events: 14

======================================================================
❤️‍🩹 RAW RESTING HEART RATE - iOS 13.4.1
======================================================================

,start_cocoa,end_cocoa,resting_heart_rate,added_cocoa,source_id,data_id,hardware,source
0,6.087265e+08,6.087330e+08,54,6.087331e+08,4,51841,"Watch4,3",This Is’s Apple Watch
1,6.086400e+08,6.086908e+08,57,6.086911e+08,4,51573,"Watch4,3",This Is’s Apple Watch
2,6.085530e+08,6.086006e+08,54,6.086008e+08,4,49450,"Watch4,3",This Is’s Apple Watch
3,6.084659e+08,6.085184e+08,60,6.085198e+08,4,47863,"Watch4,3",This Is’s Apple Watch
4,6.083954e+08,6.084142e+08,55,6.085198e+08,4,47865,"Watch4,3",This Is’s Apple Watch
5,6.076034e+08,6.076282e+08,59,6.076284e+08,4,38562,"Watch4,3",This Is’s Apple Watch
6,6.075163e+08,6.075665e+08,60,6.075665e+08,4,37727,"Watch4,3",This Is’s Apple Watch
7,6.074326e+08,6.074767e+08,59,6.074770e+08,4,32809,"Watch4,3",This Is’s Apple Watch
8,6.073430e+08,6.073998e+08,60,6.074001e+08,4,31059,"Watch4,3",This Is’s Apple Watch
9,6.072566e+08,6.073108e+08,61,6.073109e+08,4,26272,"Watch4,3",This Is’s Apple Watch
10,6.071697e+08,6.072234e+08,64,6.072237e+08,4,21447,"Watch4,3",This Is’s Apple Watch
11,6.070856e+08,6.071347e+08,64,6.071350e+08,4,19357,"Watch4,3",This Is’s Apple Watch
12,6.069971e+08,6.070488e+08,65,6.070491e+08,4,15755,"Watch4,3",This Is’s Apple Watch
13,6.069110e+08,6.069685e+08,59,6.069687e+08,4,12024,"Watch4,3",This Is’s Apple Watch
14,6.068250e+08,6.068546e+08,63,6.068550e+08,4,9026,"Watch4,3",This Is’s Apple Watch
15,6.067387e+08,6.067588e+08,58,6.067590e+08,4,6702,"Watch4,3",This Is’s Apple Watch
16,6.066531e+08,6.067072e+08,62,6.067073e+08,4,5951,"Watch4,3",This Is’s Apple Watch
17,6.065699e+08,6.066224e+08,58,6.066529e+08,4,4051,"Watch4,3",This Is’s Apple Watch

📊 Total Events: 18

======================================================================
❤️‍🩹 RAW RESTING HEART RATE - iOS 15
======================================================================

,start_cocoa,end_cocoa,resting_heart_rate,added_cocoa,source_id,data_id,hardware,source
0,7.035696e+08,7.035696e+08,60,7.036218e+08,41,131572,,Connect
1,7.034832e+08,7.034832e+08,59,7.036218e+08,41,130853,,Connect
2,7.033968e+08,7.033968e+08,62,7.036218e+08,41,130852,,Connect
3,7.033104e+08,7.033104e+08,58,7.036218e+08,41,130131,,Connect
4,7.032240e+08,7.032240e+08,63,7.036218e+08,41,129410,,Connect
5,6.354036e+08,6.354036e+08,61,6.355226e+08,25,126362,,Connect
6,6.353172e+08,6.353172e+08,61,6.354578e+08,25,125429,,Connect
7,6.352308e+08,6.352308e+08,60,6.353613e+08,25,124537,,Connect
8,6.351444e+08,6.351444e+08,66,6.353613e+08,25,123817,,Connect
9,6.350580e+08,6.350580e+08,58,6.353612e+08,25,122959,,Connect
10,6.349716e+08,6.349716e+08,61,6.351106e+08,25,122113,,Connect
11,6.348852e+08,6.348852e+08,60,6.351106e+08,25,120984,,Connect
12,6.347988e+08,6.347988e+08,44,6.351106e+08,25,120847,,Connect
13,6.347357e+08,6.347475e+08,58,6.347477e+08,21,119799,"Watch4,3",This Is’s Apple Watch
14,6.347124e+08,6.347124e+08,73,6.351106e+08,25,120843,,Connect
15,6.346262e+08,6.347009e+08,58,6.347012e+08,21,118929,"Watch4,3",This Is’s Apple Watch
16,6.345398e+08,6.346107e+08,58,6.346110e+08,21,117211,"Watch4,3",This Is’s Apple Watch
17,6.344534e+08,6.345088e+08,59,6.345090e+08,21,114586,"Watch4,3",This Is’s Apple Watch
18,6.343670e+08,6.344326e+08,58,6.344328e+08,21,112858,"Watch4,3",This Is’s Apple Watch
19,6.342807e+08,6.343387e+08,58,6.343388e+08,21,111143,"Watch4,3",This Is’s Apple Watch

📊 Total Events: 76

======================================================================
❤️‍🩹 RAW RESTING HEART RATE - iOS 16
======================================================================

,start_cocoa,end_cocoa,resting_heart_rate,added_cocoa,source_id,data_id,hardware,source
0,7.136784e+08,7.136784e+08,54,7.137508e+08,47,190687,,Connect
1,7.135920e+08,7.135920e+08,56,7.137508e+08,47,190686,,Connect
2,7.135056e+08,7.135056e+08,54,7.137508e+08,47,189965,,Connect
3,7.134192e+08,7.134192e+08,56,7.137508e+08,47,189244,,Connect
4,7.130736e+08,7.130736e+08,56,7.137508e+08,47,188164,,Connect
5,7.129872e+08,7.129872e+08,53,7.134788e+08,47,187876,,Connect
6,7.129008e+08,7.129008e+08,54,7.134788e+08,47,186444,,Connect
7,7.128144e+08,7.128144e+08,58,7.134788e+08,47,186443,,Connect
8,7.121232e+08,7.121232e+08,60,7.121974e+08,47,185584,,Connect
9,7.118642e+08,7.119292e+08,57,7.119293e+08,45,185287,"Watch4,3",Apple Watch
10,7.117778e+08,7.118213e+08,55,7.118216e+08,45,178875,"Watch4,3",Apple Watch
11,7.116914e+08,7.117583e+08,56,7.117588e+08,45,177920,"Watch4,3",Apple Watch
12,7.116050e+08,7.116618e+08,53,7.116623e+08,45,175949,"Watch4,3",Apple Watch
13,7.115186e+08,7.115634e+08,56,7.115636e+08,45,173708,"Watch4,3",Apple Watch
14,7.114322e+08,7.114871e+08,59,7.114875e+08,45,172310,"Watch4,3",Apple Watch
15,7.113458e+08,7.114184e+08,55,7.114187e+08,45,167751,"Watch4,3",Apple Watch
16,7.112594e+08,7.113051e+08,57,7.113054e+08,45,165311,"Watch4,3",Apple Watch
17,7.111731e+08,7.112196e+08,54,7.112198e+08,45,164032,"Watch4,3",Apple Watch
18,7.110872e+08,7.111520e+08,55,7.111523e+08,45,162665,"Watch4,3",Apple Watch
19,7.110003e+08,7.110499e+08,56,7.110505e+08,45,160632,"Watch4,3",Apple Watch

📊 Total Events: 102

======================================================================
❤️‍🩹 RAW RESTING HEART RATE - iOS 17
======================================================================

,start_cocoa,end_cocoa,resting_heart_rate,added_cocoa,source_id,data_id,hardware,source
0,7.436592e+08,7.436923e+08,59,7.437232e+08,45,228835,"Watch4,3",This Is’s Apple Watch
1,7.435729e+08,7.436589e+08,54,7.437232e+08,45,228837,"Watch4,3",This Is’s Apple Watch
2,7.434865e+08,7.435417e+08,58,7.435421e+08,45,220653,"Watch4,3",This Is’s Apple Watch
3,7.434000e+08,7.434268e+08,56,7.434271e+08,45,213039,"Watch4,3",This Is’s Apple Watch
4,7.433645e+08,7.433770e+08,56,7.433772e+08,45,212248,"Watch4,3",This Is’s Apple Watch
5,7.136784e+08,7.136784e+08,54,7.137508e+08,47,190687,,Connect
6,7.135920e+08,7.135920e+08,56,7.137508e+08,47,190686,,Connect
7,7.135056e+08,7.135056e+08,54,7.137508e+08,47,189965,,Connect
8,7.134192e+08,7.134192e+08,56,7.137508e+08,47,189244,,Connect
9,7.130736e+08,7.130736e+08,56,7.137508e+08,47,188164,,Connect
10,7.129872e+08,7.129872e+08,53,7.134788e+08,47,187876,,Connect
11,7.129008e+08,7.129008e+08,54,7.134788e+08,47,186444,,Connect
12,7.128144e+08,7.128144e+08,58,7.134788e+08,47,186443,,Connect
13,7.121232e+08,7.121232e+08,60,7.121974e+08,47,185584,,Connect
14,7.118642e+08,7.119367e+08,57,7.119377e+08,45,211820,"Watch4,3",This Is’s Apple Watch
15,7.117778e+08,7.118639e+08,55,7.119377e+08,45,211822,"Watch4,3",This Is’s Apple Watch
16,7.116914e+08,7.117583e+08,56,7.117588e+08,45,177920,"Watch4,3",This Is’s Apple Watch
17,7.116050e+08,7.116618e+08,53,7.116623e+08,45,175949,"Watch4,3",This Is’s Apple Watch
18,7.115186e+08,7.115634e+08,56,7.115636e+08,45,173708,"Watch4,3",This Is’s Apple Watch
19,7.114322e+08,7.114871e+08,59,7.114875e+08,45,172310,"Watch4,3",This Is’s Apple Watch

📊 Total Events: 107

In [ ]:
# ============================================================
# FORMAT LAPORAN RESTING HEART RATE
# ============================================================


resting_hr_reports = {}


for version, df_resting in resting_hr_results.items():


    df_report = pd.DataFrame()



    df_report[
        "Start Timestamp"
    ] = (

        df_resting[
            "start_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )



    df_report[
        "End Timestamp"
    ] = (

        df_resting[
            "end_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )



    df_report[
        "Added Timestamp"
    ] = (

        df_resting[
            "added_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )



    df_report[
        "Resting Heart Rate (BPM)"
    ] = (

        df_resting[
            "resting_heart_rate"
        ]

    )



    df_report[
        "Hardware"
    ] = (

        df_resting[
            "hardware"
        ]

    )



    df_report[
        "Source"
    ] = (

        df_resting[
            "source"
        ]

    )



    df_report[
        "Data ID"
    ] = (

        df_resting[
            "data_id"
        ]

    )



    df_report[
        "Health Data Source"
    ] = (
        "healthdb_secure.sqlite"
    )



    df_report[
        "Source Metadata"
    ] = (
        "healthdb.sqlite"
    )



    resting_hr_reports[
        version
    ] = df_report



print(
    "✅ Format laporan Resting Heart Rate selesai."
)

✅ Format laporan Resting Heart Rate selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT RESTING HEART RATE
# ============================================================


for version, df_report in resting_hr_reports.items():


    print()

    print("=" * 70)


    print(
        f"❤️‍🩹 RESTING HEART RATE REPORT - {version}"
    )


    print("=" * 70)



    display(
        df_report.head(20)
    )


    print()


    print(
        f"📊 Total Resting HR Events: "
        f"{len(df_report)}"
    )

======================================================================
❤️‍🩹 RESTING HEART RATE REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Resting Heart Rate (BPM),Hardware,Source,Data ID,Health Data Source,Source Metadata
0,2020-04-12 14:44:08.212772+00:00,2020-04-12 17:10:47.322092+00:00,2020-04-12 17:12:54.702435+00:00,55,"Watch4,3",This Is’s Apple Watch,45804,healthdb_secure.sqlite,healthdb.sqlite
1,2020-04-03 10:43:21.458492+00:00,2020-04-03 17:36:20.677071+00:00,2020-04-03 17:39:53.058683+00:00,59,"Watch4,3",This Is’s Apple Watch,38562,healthdb_secure.sqlite,healthdb.sqlite
2,2020-04-02 10:31:30.470081+00:00,2020-04-03 00:28:26.512620+00:00,2020-04-03 00:28:36.167733+00:00,60,"Watch4,3",This Is’s Apple Watch,37727,healthdb_secure.sqlite,healthdb.sqlite
3,2020-04-01 11:16:06.478110+00:00,2020-04-01 23:32:12.549218+00:00,2020-04-01 23:36:16.582469+00:00,59,"Watch4,3",This Is’s Apple Watch,32809,healthdb_secure.sqlite,healthdb.sqlite
4,2020-03-31 10:22:50.330547+00:00,2020-04-01 02:09:15.125119+00:00,2020-04-01 02:15:16.681050+00:00,60,"Watch4,3",This Is’s Apple Watch,31059,healthdb_secure.sqlite,healthdb.sqlite
5,2020-03-30 10:23:21.219696+00:00,2020-03-31 01:27:23.303391+00:00,2020-03-31 01:29:06.808845+00:00,61,"Watch4,3",This Is’s Apple Watch,26272,healthdb_secure.sqlite,healthdb.sqlite
6,2020-03-29 10:14:54.102708+00:00,2020-03-30 01:10:42.314141+00:00,2020-03-30 01:14:33.656570+00:00,64,"Watch4,3",This Is’s Apple Watch,21447,healthdb_secure.sqlite,healthdb.sqlite
7,2020-03-28 10:52:45.695759+00:00,2020-03-29 00:31:13.528536+00:00,2020-03-29 00:36:45.164251+00:00,64,"Watch4,3",This Is’s Apple Watch,19357,healthdb_secure.sqlite,healthdb.sqlite
8,2020-03-27 10:18:54.806278+00:00,2020-03-28 00:39:28.790970+00:00,2020-03-28 00:44:54.049525+00:00,65,"Watch4,3",This Is’s Apple Watch,15755,healthdb_secure.sqlite,healthdb.sqlite
9,2020-03-26 10:22:38.806569+00:00,2020-03-27 02:21:15.337198+00:00,2020-03-27 02:24:15.596737+00:00,59,"Watch4,3",This Is’s Apple Watch,12024,healthdb_secure.sqlite,healthdb.sqlite
10,2020-03-25 10:29:59.353541+00:00,2020-03-25 18:42:44.443402+00:00,2020-03-25 18:49:37.657062+00:00,63,"Watch4,3",This Is’s Apple Watch,9026,healthdb_secure.sqlite,healthdb.sqlite
11,2020-03-24 10:31:38.778374+00:00,2020-03-24 16:07:22.453954+00:00,2020-03-24 16:10:42.828622+00:00,58,"Watch4,3",This Is’s Apple Watch,6702,healthdb_secure.sqlite,healthdb.sqlite
12,2020-03-23 10:44:47.937204+00:00,2020-03-24 01:46:34.870238+00:00,2020-03-24 01:48:56.661537+00:00,62,"Watch4,3",This Is’s Apple Watch,5951,healthdb_secure.sqlite,healthdb.sqlite
13,2020-03-22 11:37:44.656893+00:00,2020-03-23 02:13:34.627947+00:00,2020-03-23 10:41:56.913973+00:00,58,"Watch4,3",This Is’s Apple Watch,4051,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Resting HR Events: 14

======================================================================
❤️‍🩹 RESTING HEART RATE REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Resting Heart Rate (BPM),Hardware,Source,Data ID,Health Data Source,Source Metadata
0,2020-04-16 10:41:00.919970+00:00,2020-04-16 12:29:16.919832+00:00,2020-04-16 12:31:40.248831+00:00,54,"Watch4,3",This Is’s Apple Watch,51841,healthdb_secure.sqlite,healthdb.sqlite
1,2020-04-15 10:39:26.217982+00:00,2020-04-16 00:46:39.882299+00:00,2020-04-16 00:51:13.344751+00:00,57,"Watch4,3",This Is’s Apple Watch,51573,healthdb_secure.sqlite,healthdb.sqlite
2,2020-04-14 10:29:28.942244+00:00,2020-04-14 23:43:54.238891+00:00,2020-04-14 23:47:25.986667+00:00,54,"Watch4,3",This Is’s Apple Watch,49450,healthdb_secure.sqlite,healthdb.sqlite
3,2020-04-13 10:17:52.527924+00:00,2020-04-14 00:52:57.733477+00:00,2020-04-14 01:16:28.622119+00:00,60,"Watch4,3",This Is’s Apple Watch,47863,healthdb_secure.sqlite,healthdb.sqlite
4,2020-04-12 14:44:08.212772+00:00,2020-04-12 19:56:53.656756+00:00,2020-04-14 01:16:29.064507+00:00,55,"Watch4,3",This Is’s Apple Watch,47865,healthdb_secure.sqlite,healthdb.sqlite
5,2020-04-03 10:43:21.458492+00:00,2020-04-03 17:36:20.677071+00:00,2020-04-03 17:39:53.058683+00:00,59,"Watch4,3",This Is’s Apple Watch,38562,healthdb_secure.sqlite,healthdb.sqlite
6,2020-04-02 10:31:30.470081+00:00,2020-04-03 00:28:26.512620+00:00,2020-04-03 00:28:36.167733+00:00,60,"Watch4,3",This Is’s Apple Watch,37727,healthdb_secure.sqlite,healthdb.sqlite
7,2020-04-01 11:16:06.478110+00:00,2020-04-01 23:32:12.549218+00:00,2020-04-01 23:36:16.582469+00:00,59,"Watch4,3",This Is’s Apple Watch,32809,healthdb_secure.sqlite,healthdb.sqlite
8,2020-03-31 10:22:50.330547+00:00,2020-04-01 02:09:15.125119+00:00,2020-04-01 02:15:16.681050+00:00,60,"Watch4,3",This Is’s Apple Watch,31059,healthdb_secure.sqlite,healthdb.sqlite
9,2020-03-30 10:23:21.219696+00:00,2020-03-31 01:27:23.303391+00:00,2020-03-31 01:29:06.808845+00:00,61,"Watch4,3",This Is’s Apple Watch,26272,healthdb_secure.sqlite,healthdb.sqlite
10,2020-03-29 10:14:54.102708+00:00,2020-03-30 01:10:42.314141+00:00,2020-03-30 01:14:33.656570+00:00,64,"Watch4,3",This Is’s Apple Watch,21447,healthdb_secure.sqlite,healthdb.sqlite
11,2020-03-28 10:52:45.695759+00:00,2020-03-29 00:31:13.528536+00:00,2020-03-29 00:36:45.164251+00:00,64,"Watch4,3",This Is’s Apple Watch,19357,healthdb_secure.sqlite,healthdb.sqlite
12,2020-03-27 10:18:54.806278+00:00,2020-03-28 00:39:28.790970+00:00,2020-03-28 00:44:54.049525+00:00,65,"Watch4,3",This Is’s Apple Watch,15755,healthdb_secure.sqlite,healthdb.sqlite
13,2020-03-26 10:22:38.806569+00:00,2020-03-27 02:21:15.337198+00:00,2020-03-27 02:24:15.596737+00:00,59,"Watch4,3",This Is’s Apple Watch,12024,healthdb_secure.sqlite,healthdb.sqlite
14,2020-03-25 10:29:59.353541+00:00,2020-03-25 18:42:44.443402+00:00,2020-03-25 18:49:37.657062+00:00,63,"Watch4,3",This Is’s Apple Watch,9026,healthdb_secure.sqlite,healthdb.sqlite
15,2020-03-24 10:31:38.778374+00:00,2020-03-24 16:07:22.453954+00:00,2020-03-24 16:10:42.828622+00:00,58,"Watch4,3",This Is’s Apple Watch,6702,healthdb_secure.sqlite,healthdb.sqlite
16,2020-03-23 10:44:47.937204+00:00,2020-03-24 01:46:34.870238+00:00,2020-03-24 01:48:56.661537+00:00,62,"Watch4,3",This Is’s Apple Watch,5951,healthdb_secure.sqlite,healthdb.sqlite
17,2020-03-22 11:37:44.656893+00:00,2020-03-23 02:13:34.627947+00:00,2020-03-23 10:41:56.913973+00:00,58,"Watch4,3",This Is’s Apple Watch,4051,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Resting HR Events: 18

======================================================================
❤️‍🩹 RESTING HEART RATE REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Resting Heart Rate (BPM),Hardware,Source,Data ID,Health Data Source,Source Metadata
0,2023-04-19 04:00:00+00:00,2023-04-19 04:00:00+00:00,2023-04-19 18:30:17.581414+00:00,60,,Connect,131572,healthdb_secure.sqlite,healthdb.sqlite
1,2023-04-18 04:00:00+00:00,2023-04-18 04:00:00+00:00,2023-04-19 18:30:17.303573+00:00,59,,Connect,130853,healthdb_secure.sqlite,healthdb.sqlite
2,2023-04-17 04:00:00+00:00,2023-04-17 04:00:00+00:00,2023-04-19 18:30:17.070447+00:00,62,,Connect,130852,healthdb_secure.sqlite,healthdb.sqlite
3,2023-04-16 04:00:00+00:00,2023-04-16 04:00:00+00:00,2023-04-19 18:30:16.795042+00:00,58,,Connect,130131,healthdb_secure.sqlite,healthdb.sqlite
4,2023-04-15 04:00:00+00:00,2023-04-15 04:00:00+00:00,2023-04-19 18:30:16.426349+00:00,63,,Connect,129410,healthdb_secure.sqlite,healthdb.sqlite
5,2021-02-19 05:00:00+00:00,2021-02-19 05:00:00+00:00,2021-02-20 14:03:18.785025+00:00,61,,Connect,126362,healthdb_secure.sqlite,healthdb.sqlite
6,2021-02-18 05:00:00+00:00,2021-02-18 05:00:00+00:00,2021-02-19 20:03:05.900579+00:00,61,,Connect,125429,healthdb_secure.sqlite,healthdb.sqlite
7,2021-02-17 05:00:00+00:00,2021-02-17 05:00:00+00:00,2021-02-18 17:14:18.860502+00:00,60,,Connect,124537,healthdb_secure.sqlite,healthdb.sqlite
8,2021-02-16 05:00:00+00:00,2021-02-16 05:00:00+00:00,2021-02-18 17:14:15.032420+00:00,66,,Connect,123817,healthdb_secure.sqlite,healthdb.sqlite
9,2021-02-15 05:00:00+00:00,2021-02-15 05:00:00+00:00,2021-02-18 17:14:01.433171+00:00,58,,Connect,122959,healthdb_secure.sqlite,healthdb.sqlite
10,2021-02-14 05:00:00+00:00,2021-02-14 05:00:00+00:00,2021-02-15 19:36:12.846297+00:00,61,,Connect,122113,healthdb_secure.sqlite,healthdb.sqlite
11,2021-02-13 05:00:00+00:00,2021-02-13 05:00:00+00:00,2021-02-15 19:36:09.304074+00:00,60,,Connect,120984,healthdb_secure.sqlite,healthdb.sqlite
12,2021-02-12 05:00:00+00:00,2021-02-12 05:00:00+00:00,2021-02-15 19:36:08.247523+00:00,44,,Connect,120847,healthdb_secure.sqlite,healthdb.sqlite
13,2021-02-11 11:27:57.668408+00:00,2021-02-11 14:44:16.152192+00:00,2021-02-11 14:48:56.901612+00:00,58,"Watch4,3",This Is’s Apple Watch,119799,healthdb_secure.sqlite,healthdb.sqlite
14,2021-02-11 05:00:00+00:00,2021-02-11 05:00:00+00:00,2021-02-15 19:36:07.941528+00:00,73,,Connect,120843,healthdb_secure.sqlite,healthdb.sqlite
15,2021-02-10 05:02:41.668405+00:00,2021-02-11 01:47:52.111504+00:00,2021-02-11 01:53:39.364643+00:00,58,"Watch4,3",This Is’s Apple Watch,118929,healthdb_secure.sqlite,healthdb.sqlite
16,2021-02-09 05:02:35.002686+00:00,2021-02-10 00:45:08.449364+00:00,2021-02-10 00:49:26.429151+00:00,58,"Watch4,3",This Is’s Apple Watch,117211,healthdb_secure.sqlite,healthdb.sqlite
17,2021-02-08 05:02:45.645308+00:00,2021-02-08 20:26:09.397713+00:00,2021-02-08 20:30:17.601018+00:00,59,"Watch4,3",This Is’s Apple Watch,114586,healthdb_secure.sqlite,healthdb.sqlite
18,2021-02-07 05:02:33.437586+00:00,2021-02-07 23:16:51.022871+00:00,2021-02-07 23:19:39.705968+00:00,58,"Watch4,3",This Is’s Apple Watch,112858,healthdb_secure.sqlite,healthdb.sqlite
19,2021-02-06 05:04:59.521754+00:00,2021-02-06 21:11:54.001317+00:00,2021-02-06 21:12:47.412439+00:00,58,"Watch4,3",This Is’s Apple Watch,111143,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Resting HR Events: 76

======================================================================
❤️‍🩹 RESTING HEART RATE REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Resting Heart Rate (BPM),Hardware,Source,Data ID,Health Data Source,Source Metadata
0,2023-08-14 04:00:00+00:00,2023-08-14 04:00:00+00:00,2023-08-15 00:07:08.052404+00:00,54,,Connect,190687,healthdb_secure.sqlite,healthdb.sqlite
1,2023-08-13 04:00:00+00:00,2023-08-13 04:00:00+00:00,2023-08-15 00:07:07.821913+00:00,56,,Connect,190686,healthdb_secure.sqlite,healthdb.sqlite
2,2023-08-12 04:00:00+00:00,2023-08-12 04:00:00+00:00,2023-08-15 00:07:07.208151+00:00,54,,Connect,189965,healthdb_secure.sqlite,healthdb.sqlite
3,2023-08-11 04:00:00+00:00,2023-08-11 04:00:00+00:00,2023-08-15 00:07:06.939674+00:00,56,,Connect,189244,healthdb_secure.sqlite,healthdb.sqlite
4,2023-08-07 04:00:00+00:00,2023-08-07 04:00:00+00:00,2023-08-15 00:07:06.423516+00:00,56,,Connect,188164,healthdb_secure.sqlite,healthdb.sqlite
5,2023-08-06 04:00:00+00:00,2023-08-06 04:00:00+00:00,2023-08-11 20:33:01.230957+00:00,53,,Connect,187876,healthdb_secure.sqlite,healthdb.sqlite
6,2023-08-05 04:00:00+00:00,2023-08-05 04:00:00+00:00,2023-08-11 20:33:00.735955+00:00,54,,Connect,186444,healthdb_secure.sqlite,healthdb.sqlite
7,2023-08-04 04:00:00+00:00,2023-08-04 04:00:00+00:00,2023-08-11 20:33:00.323019+00:00,58,,Connect,186443,healthdb_secure.sqlite,healthdb.sqlite
8,2023-07-27 04:00:00+00:00,2023-07-27 04:00:00+00:00,2023-07-28 00:37:17.567901+00:00,60,,Connect,185584,healthdb_secure.sqlite,healthdb.sqlite
9,2023-07-24 04:03:18.034681+00:00,2023-07-24 22:07:26.027954+00:00,2023-07-24 22:07:46.139413+00:00,57,"Watch4,3",Apple Watch,185287,healthdb_secure.sqlite,healthdb.sqlite
10,2023-07-23 04:02:45.191219+00:00,2023-07-23 16:08:52.789512+00:00,2023-07-23 16:12:43.453819+00:00,55,"Watch4,3",Apple Watch,178875,healthdb_secure.sqlite,healthdb.sqlite
11,2023-07-22 04:02:41.476776+00:00,2023-07-22 22:38:51.582801+00:00,2023-07-22 22:47:09.707931+00:00,56,"Watch4,3",Apple Watch,177920,healthdb_secure.sqlite,healthdb.sqlite
12,2023-07-21 04:03:30.785153+00:00,2023-07-21 19:49:54.931353+00:00,2023-07-21 19:58:50.643811+00:00,53,"Watch4,3",Apple Watch,175949,healthdb_secure.sqlite,healthdb.sqlite
13,2023-07-20 04:02:37.708180+00:00,2023-07-20 16:30:01.440945+00:00,2023-07-20 16:32:38.707518+00:00,56,"Watch4,3",Apple Watch,173708,healthdb_secure.sqlite,healthdb.sqlite
14,2023-07-19 04:02:46.905271+00:00,2023-07-19 19:18:04.780679+00:00,2023-07-19 19:24:42.148152+00:00,59,"Watch4,3",Apple Watch,172310,healthdb_secure.sqlite,healthdb.sqlite
15,2023-07-18 04:02:59.571547+00:00,2023-07-19 00:13:10.618654+00:00,2023-07-19 00:17:46.787277+00:00,55,"Watch4,3",Apple Watch,167751,healthdb_secure.sqlite,healthdb.sqlite
16,2023-07-17 04:02:41.856937+00:00,2023-07-17 16:44:14.136194+00:00,2023-07-17 16:49:54.848095+00:00,57,"Watch4,3",Apple Watch,165311,healthdb_secure.sqlite,healthdb.sqlite
17,2023-07-16 04:04:11.978757+00:00,2023-07-16 16:59:46.839703+00:00,2023-07-16 17:03:30.793570+00:00,54,"Watch4,3",Apple Watch,164032,healthdb_secure.sqlite,healthdb.sqlite
18,2023-07-15 04:13:52.634540+00:00,2023-07-15 22:13:25.952662+00:00,2023-07-15 22:17:56.253580+00:00,55,"Watch4,3",Apple Watch,162665,healthdb_secure.sqlite,healthdb.sqlite
19,2023-07-14 04:04:33.574265+00:00,2023-07-14 17:52:24.556951+00:00,2023-07-14 18:01:49.843372+00:00,56,"Watch4,3",Apple Watch,160632,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Resting HR Events: 102

======================================================================
❤️‍🩹 RESTING HEART RATE REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Resting Heart Rate (BPM),Hardware,Source,Data ID,Health Data Source,Source Metadata
0,2024-07-26 04:00:11.853487+00:00,2024-07-26 13:12:24.026299+00:00,2024-07-26 21:46:58.542147+00:00,59,"Watch4,3",This Is’s Apple Watch,228835,healthdb_secure.sqlite,healthdb.sqlite
1,2024-07-25 04:01:16.968809+00:00,2024-07-26 03:55:19.978487+00:00,2024-07-26 21:46:59.491066+00:00,54,"Watch4,3",This Is’s Apple Watch,228837,healthdb_secure.sqlite,healthdb.sqlite
2,2024-07-24 04:00:51.054016+00:00,2024-07-24 19:21:16.282895+00:00,2024-07-24 19:28:12.198353+00:00,58,"Watch4,3",This Is’s Apple Watch,220653,healthdb_secure.sqlite,healthdb.sqlite
3,2024-07-23 04:00:18.137810+00:00,2024-07-23 11:25:52.532161+00:00,2024-07-23 11:31:54.582206+00:00,56,"Watch4,3",This Is’s Apple Watch,213039,healthdb_secure.sqlite,healthdb.sqlite
4,2024-07-22 18:08:36.855706+00:00,2024-07-22 21:36:15.742235+00:00,2024-07-22 21:40:28.345010+00:00,56,"Watch4,3",This Is’s Apple Watch,212248,healthdb_secure.sqlite,healthdb.sqlite
5,2023-08-14 04:00:00+00:00,2023-08-14 04:00:00+00:00,2023-08-15 00:07:08.052404+00:00,54,,Connect,190687,healthdb_secure.sqlite,healthdb.sqlite
6,2023-08-13 04:00:00+00:00,2023-08-13 04:00:00+00:00,2023-08-15 00:07:07.821913+00:00,56,,Connect,190686,healthdb_secure.sqlite,healthdb.sqlite
7,2023-08-12 04:00:00+00:00,2023-08-12 04:00:00+00:00,2023-08-15 00:07:07.208151+00:00,54,,Connect,189965,healthdb_secure.sqlite,healthdb.sqlite
8,2023-08-11 04:00:00+00:00,2023-08-11 04:00:00+00:00,2023-08-15 00:07:06.939674+00:00,56,,Connect,189244,healthdb_secure.sqlite,healthdb.sqlite
9,2023-08-07 04:00:00+00:00,2023-08-07 04:00:00+00:00,2023-08-15 00:07:06.423516+00:00,56,,Connect,188164,healthdb_secure.sqlite,healthdb.sqlite
10,2023-08-06 04:00:00+00:00,2023-08-06 04:00:00+00:00,2023-08-11 20:33:01.230957+00:00,53,,Connect,187876,healthdb_secure.sqlite,healthdb.sqlite
11,2023-08-05 04:00:00+00:00,2023-08-05 04:00:00+00:00,2023-08-11 20:33:00.735955+00:00,54,,Connect,186444,healthdb_secure.sqlite,healthdb.sqlite
12,2023-08-04 04:00:00+00:00,2023-08-04 04:00:00+00:00,2023-08-11 20:33:00.323019+00:00,58,,Connect,186443,healthdb_secure.sqlite,healthdb.sqlite
13,2023-07-27 04:00:00+00:00,2023-07-27 04:00:00+00:00,2023-07-28 00:37:17.567901+00:00,60,,Connect,185584,healthdb_secure.sqlite,healthdb.sqlite
14,2023-07-24 04:03:18.034681+00:00,2023-07-25 00:12:05.687891+00:00,2023-07-25 00:28:50.934474+00:00,57,"Watch4,3",This Is’s Apple Watch,211820,healthdb_secure.sqlite,healthdb.sqlite
15,2023-07-23 04:02:45.191219+00:00,2023-07-24 03:57:33.034681+00:00,2023-07-25 00:28:55.192745+00:00,55,"Watch4,3",This Is’s Apple Watch,211822,healthdb_secure.sqlite,healthdb.sqlite
16,2023-07-22 04:02:41.476776+00:00,2023-07-22 22:38:51.582801+00:00,2023-07-22 22:47:09.707931+00:00,56,"Watch4,3",This Is’s Apple Watch,177920,healthdb_secure.sqlite,healthdb.sqlite
17,2023-07-21 04:03:30.785153+00:00,2023-07-21 19:49:54.931353+00:00,2023-07-21 19:58:50.643811+00:00,53,"Watch4,3",This Is’s Apple Watch,175949,healthdb_secure.sqlite,healthdb.sqlite
18,2023-07-20 04:02:37.708180+00:00,2023-07-20 16:30:01.440945+00:00,2023-07-20 16:32:38.707518+00:00,56,"Watch4,3",This Is’s Apple Watch,173708,healthdb_secure.sqlite,healthdb.sqlite
19,2023-07-19 04:02:46.905271+00:00,2023-07-19 19:18:04.780679+00:00,2023-07-19 19:24:42.148152+00:00,59,"Watch4,3",This Is’s Apple Watch,172310,healthdb_secure.sqlite,healthdb.sqlite

📊 Total Resting HR Events: 107

# **Fitur Source Devices**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR SOURCE DEVICES
# ============================================================

print()
print("=" * 70)
print("📱 VERIFIKASI SOURCE DEVICES")
print("=" * 70)


for dataset in target_datasets:

    version = dataset["version"]

    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()

    print(
        f"📱 {version}"
    )


    if "source_devices" in healthdb_tables:

        print(
            "   📂 source_devices : ✅ Ditemukan"
        )

    else:

        print(
            "   📂 source_devices : ❌ Tidak ditemukan"
        )


print()
print("=" * 70)

======================================================================
📱 VERIFIKASI SOURCE DEVICES
======================================================================

📱 iOS 13.3.1
   📂 source_devices : ✅ Ditemukan

📱 iOS 13.4.1
   📂 source_devices : ✅ Ditemukan

📱 iOS 15
   📂 source_devices : ✅ Ditemukan

📱 iOS 16
   📂 source_devices : ✅ Ditemukan

📱 iOS 17
   📂 source_devices : ✅ Ditemukan

======================================================================

In [ ]:
# ============================================================
# CEK KOLOM SOURCE DEVICES
# ============================================================


def get_table_columns(
    database_path,
    table_name
):

    conn = open_sqlite_readonly(
        database_path
    )


    cursor = conn.cursor()


    cursor.execute(
        f"PRAGMA table_info({table_name})"
    )


    columns = [

        row[1]

        for row in cursor.fetchall()

    ]


    conn.close()


    return columns



print(
    "✅ Fungsi pengecekan kolom siap."
)

✅ Fungsi pengecekan kolom siap.

In [ ]:
# ============================================================
# EXTRACTOR SOURCE DEVICES
# ============================================================


def extract_source_devices(
    health_database_path
):

    """
    Extract Source Devices.

    iOS 13-15:
        tanpa sync_identity

    iOS 16-17:
        dengan sync_identity

    Database:
        healthdb.sqlite
    """


    columns = get_table_columns(

        health_database_path,

        "source_devices"

    )


    conn = open_sqlite_readonly(
        health_database_path
    )



    # ========================================================
    # DETEKSI VERSI STRUKTUR
    # ========================================================


    if "sync_identity" in columns:


        print(
            "   🔎 Struktur terdeteksi: iOS 16-17"
        )


        query = """

        SELECT


            creation_date,


            name AS device_name,


            manufacturer,


            model,


            hardware,


            firmware,


            software,


            localIdentifier,


            sync_provenance,


            sync_identity



        FROM source_devices



        WHERE


            name NOT LIKE "__NONE__"


            AND localIdentifier NOT LIKE "__NONE__"



        ORDER BY

            creation_date

        """



    else:


        print(
            "   🔎 Struktur terdeteksi: iOS 13-15"
        )


        query = """

        SELECT


            creation_date,


            name AS device_name,


            manufacturer,


            model,


            hardware,


            firmware,


            software,


            localIdentifier,


            sync_provenance



        FROM source_devices



        WHERE


            name NOT LIKE "__NONE__"


            AND localIdentifier NOT LIKE "__NONE__"



        ORDER BY

            creation_date

        """



    df = pd.read_sql_query(

        query,

        conn

    )


    conn.close()



    # Jika iOS 13-15
    # tambahkan kolom kosong

    if "sync_identity" not in df.columns:


        df[
            "sync_identity"
        ] = None



    return df



print(
    "✅ Extractor Source Devices adaptive siap."
)

✅ Extractor Source Devices adaptive siap.

In [ ]:
# ============================================================
# EKSTRAKSI SOURCE DEVICES
# ============================================================


source_devices_results = {}


for dataset in target_datasets:


    version = dataset["version"]


    healthdb_path = dataset[
        "healthdb"
    ]


    print()

    print("=" * 70)


    print(
        f"📱 SOURCE DEVICES - {version}"
    )


    print("=" * 70)



    try:


        df_devices = extract_source_devices(

            healthdb_path

        )


        source_devices_results[
            version
        ] = df_devices



        print(
            "✅ Ekstraksi berhasil"
        )


        print(
            f"📊 Total Devices: "
            f"{len(df_devices)}"
        )


        print(
            "📂 Source:"
            " healthdb.sqlite"
        )



    except Exception as e:


        print(
            f"❌ Error: {e}"
        )

======================================================================
📱 SOURCE DEVICES - iOS 13.3.1
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15
✅ Ekstraksi berhasil
📊 Total Devices: 4
📂 Source: healthdb.sqlite

======================================================================
📱 SOURCE DEVICES - iOS 13.4.1
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15
✅ Ekstraksi berhasil
📊 Total Devices: 6
📂 Source: healthdb.sqlite

======================================================================
📱 SOURCE DEVICES - iOS 15
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15
✅ Ekstraksi berhasil
📊 Total Devices: 19
📂 Source: healthdb.sqlite

======================================================================
📱 SOURCE DEVICES - iOS 16
======================================================================
   🔎 Struktur terdeteksi: iOS 16-17
✅ Ekstraksi berhasil
📊 Total Devices: 23
📂 Source: healthdb.sqlite

======================================================================
📱 SOURCE DEVICES - iOS 17
======================================================================
   🔎 Struktur terdeteksi: iOS 16-17
✅ Ekstraksi berhasil
📊 Total Devices: 25
📂 Source: healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW SOURCE DEVICES
# ============================================================


for version, df_devices in source_devices_results.items():


    print()

    print("=" * 70)


    print(
        f"📱 RAW SOURCE DEVICES - {version}"
    )


    print("=" * 70)



    display(
        df_devices.head(20)
    )



    print()


    print(
        f"📊 Total Devices: "
        f"{len(df_devices)}"
    )

======================================================================
📱 RAW SOURCE DEVICES - iOS 13.3.1
======================================================================

,creation_date,device_name,manufacturer,model,hardware,firmware,software,localIdentifier,sync_provenance,sync_identity
0,6.065153e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,1,None
1,6.065228e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,0,None
2,6.070288e+08,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,0,None
3,6.073745e+08,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,1,None

📊 Total Devices: 4

======================================================================
📱 RAW SOURCE DEVICES - iOS 13.4.1
======================================================================

,creation_date,device_name,manufacturer,model,hardware,firmware,software,localIdentifier,sync_provenance,sync_identity
0,6.065153e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,1,None
1,6.065228e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,0,None
2,6.070288e+08,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,0,None
3,6.073745e+08,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,1,None
4,6.084988e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,0,None
5,6.085198e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,1,None

📊 Total Devices: 6

======================================================================
📱 RAW SOURCE DEVICES - iOS 15
======================================================================

,creation_date,device_name,manufacturer,model,hardware,firmware,software,localIdentifier,sync_provenance,sync_identity
0,6.065153e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,38,None
1,6.065228e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,38,None
2,6.070288e+08,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,38,None
3,6.073745e+08,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,38,None
4,6.084988e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,38,None
5,6.085198e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,38,None
6,6.199807e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,38,None
7,6.200665e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,38,None
8,6.233586e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,38,None
9,6.295534e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,38,None
10,6.310440e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,38,None
11,6.326042e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,38,None
12,6.326097e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,38,None
13,6.363204e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,38,None
14,6.423467e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,38,None
15,6.426226e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,38,None
16,6.541000e+08,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,38,None
17,6.943601e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,32,None
18,7.062050e+08,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,0,None

📊 Total Devices: 19

======================================================================
📱 RAW SOURCE DEVICES - iOS 16
======================================================================

,creation_date,device_name,manufacturer,model,hardware,firmware,software,localIdentifier,sync_provenance,sync_identity
0,6.065153e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,47,1
1,6.065228e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,47,1
2,6.070288e+08,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,47,1
3,6.073745e+08,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,47,1
4,6.084988e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,47,1
5,6.085198e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,47,1
6,6.199807e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,47,1
7,6.200665e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,47,1
8,6.233586e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,47,1
9,6.295534e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,47,1
10,6.310440e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1
11,6.326042e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1
12,6.326097e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,47,1
13,6.347743e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,93,1
14,6.363204e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,47,1
15,6.423467e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,47,1
16,6.426226e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,47,1
17,6.541000e+08,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,47,1
18,6.943601e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,43,1
19,7.062050e+08,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,53,1

📊 Total Devices: 23

======================================================================
📱 RAW SOURCE DEVICES - iOS 17
======================================================================

,creation_date,device_name,manufacturer,model,hardware,firmware,software,localIdentifier,sync_provenance,sync_identity
0,6.065153e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,47,1
1,6.065228e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,47,1
2,6.070288e+08,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,47,1
3,6.073745e+08,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,47,1
4,6.084988e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,47,1
5,6.085198e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,47,1
6,6.199807e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,47,1
7,6.200665e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,47,1
8,6.233586e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,47,1
9,6.295534e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,47,1
10,6.310440e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1
11,6.326042e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1
12,6.326097e+08,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,47,1
13,6.347743e+08,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,93,1
14,6.363204e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,47,1
15,6.423467e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,47,1
16,6.426226e+08,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,47,1
17,6.541000e+08,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,47,1
18,6.943601e+08,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,43,1
19,7.062050e+08,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,53,1

📊 Total Devices: 25

In [ ]:
# ============================================================
# FORMAT LAPORAN SOURCE DEVICES
# ============================================================


source_devices_reports = {}



for version, df_devices in source_devices_results.items():


    df_report = pd.DataFrame()



    df_report[
        "Creation Timestamp"
    ] = (

        df_devices[
            "creation_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )



    df_report[
        "Device Name"
    ] = (

        df_devices[
            "device_name"
        ]

    )



    df_report[
        "Manufacturer"
    ] = (

        df_devices[
            "manufacturer"
        ]

    )



    df_report[
        "Model"
    ] = (

        df_devices[
            "model"
        ]

    )



    df_report[
        "Hardware"
    ] = (

        df_devices[
            "hardware"
        ]

    )



    df_report[
        "Firmware"
    ] = (

        df_devices[
            "firmware"
        ]

    )



    df_report[
        "Software"
    ] = (

        df_devices[
            "software"
        ]

    )



    df_report[
        "Local Identifier"
    ] = (

        df_devices[
            "localIdentifier"
        ]

    )



    df_report[
        "Sync Provenance"
    ] = (

        df_devices[
            "sync_provenance"
        ]

    )



    df_report[
        "Sync Identity"
    ] = (

        df_devices[
            "sync_identity"
        ]

    )



    df_report[
        "Source Database"
    ] = (

        "healthdb.sqlite"

    )



    source_devices_reports[
        version
    ] = df_report



print(
    "✅ Format laporan Source Devices selesai."
)

✅ Format laporan Source Devices selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT SOURCE DEVICES
# ============================================================


for version, df_report in source_devices_reports.items():


    print()

    print("=" * 70)


    print(
        f"📱 SOURCE DEVICES REPORT - {version}"
    )


    print("=" * 70)



    display(
        df_report.head(20)
    )



    print()


    print(
        f"📊 Total Devices: "
        f"{len(df_report)}"
    )

======================================================================
📱 SOURCE DEVICES REPORT - iOS 13.3.1
======================================================================

,Creation Timestamp,Device Name,Manufacturer,Model,Hardware,Firmware,Software,Local Identifier,Sync Provenance,Sync Identity,Source Database
0,2020-03-21 20:28:48.950322+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,1,None,healthdb.sqlite
1,2020-03-21 22:33:20.752680+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,0,None,healthdb.sqlite
2,2020-03-27 19:06:14.240871+00:00,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,0,None,healthdb.sqlite
3,2020-03-31 19:08:08.763455+00:00,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,1,None,healthdb.sqlite

📊 Total Devices: 4

======================================================================
📱 SOURCE DEVICES REPORT - iOS 13.4.1
======================================================================

,Creation Timestamp,Device Name,Manufacturer,Model,Hardware,Firmware,Software,Local Identifier,Sync Provenance,Sync Identity,Source Database
0,2020-03-21 20:28:48.950322+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,1,None,healthdb.sqlite
1,2020-03-21 22:33:20.752680+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,0,None,healthdb.sqlite
2,2020-03-27 19:06:14.240871+00:00,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,0,None,healthdb.sqlite
3,2020-03-31 19:08:08.763455+00:00,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,1,None,healthdb.sqlite
4,2020-04-13 19:26:44.236909+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,0,None,healthdb.sqlite
5,2020-04-14 01:16:00.671350+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,1,None,healthdb.sqlite

📊 Total Devices: 6

======================================================================
📱 SOURCE DEVICES REPORT - iOS 15
======================================================================

,Creation Timestamp,Device Name,Manufacturer,Model,Hardware,Firmware,Software,Local Identifier,Sync Provenance,Sync Identity,Source Database
0,2020-03-21 20:28:48.950322+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,38,None,healthdb.sqlite
1,2020-03-21 22:33:20.752680+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,38,None,healthdb.sqlite
2,2020-03-27 19:06:14.240871+00:00,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,38,None,healthdb.sqlite
3,2020-03-31 19:08:08.763455+00:00,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,38,None,healthdb.sqlite
4,2020-04-13 19:26:44.236909+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,38,None,healthdb.sqlite
5,2020-04-14 01:16:00.671350+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,38,None,healthdb.sqlite
6,2020-08-24 16:51:30.985641+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,38,None,healthdb.sqlite
7,2020-08-25 16:41:48.987626+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,38,None,healthdb.sqlite
8,2020-10-02 19:09:11.750931+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,38,None,healthdb.sqlite
9,2020-12-13 11:56:54.383111+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,38,None,healthdb.sqlite
10,2020-12-30 17:59:31.666058+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,38,None,healthdb.sqlite
11,2021-01-17 19:22:59.534474+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,38,None,healthdb.sqlite
12,2021-01-17 20:54:40.486938+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,38,None,healthdb.sqlite
13,2021-03-01 19:39:23.998170+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,38,None,healthdb.sqlite
14,2021-05-10 13:37:39.103495+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,38,None,healthdb.sqlite
15,2021-05-13 18:17:01.672781+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,38,None,healthdb.sqlite
16,2021-09-23 14:27:08.643061+00:00,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,38,None,healthdb.sqlite
17,2023-01-02 13:47:38.280079+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,32,None,healthdb.sqlite
18,2023-05-19 16:03:01.287088+00:00,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,0,None,healthdb.sqlite

📊 Total Devices: 19

======================================================================
📱 SOURCE DEVICES REPORT - iOS 16
======================================================================

,Creation Timestamp,Device Name,Manufacturer,Model,Hardware,Firmware,Software,Local Identifier,Sync Provenance,Sync Identity,Source Database
0,2020-03-21 20:28:48.950322+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,47,1,healthdb.sqlite
1,2020-03-21 22:33:20.752680+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,47,1,healthdb.sqlite
2,2020-03-27 19:06:14.240871+00:00,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,47,1,healthdb.sqlite
3,2020-03-31 19:08:08.763455+00:00,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,47,1,healthdb.sqlite
4,2020-04-13 19:26:44.236909+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,47,1,healthdb.sqlite
5,2020-04-14 01:16:00.671350+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,47,1,healthdb.sqlite
6,2020-08-24 16:51:30.985641+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,47,1,healthdb.sqlite
7,2020-08-25 16:41:48.987626+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,47,1,healthdb.sqlite
8,2020-10-02 19:09:11.750931+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,47,1,healthdb.sqlite
9,2020-12-13 11:56:54.383111+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,47,1,healthdb.sqlite
10,2020-12-30 17:59:31.666058+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1,healthdb.sqlite
11,2021-01-17 19:22:59.534474+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1,healthdb.sqlite
12,2021-01-17 20:54:40.486938+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,47,1,healthdb.sqlite
13,2021-02-11 22:12:02.857532+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,93,1,healthdb.sqlite
14,2021-03-01 19:39:23.998170+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,47,1,healthdb.sqlite
15,2021-05-10 13:37:39.103495+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,47,1,healthdb.sqlite
16,2021-05-13 18:17:01.672781+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,47,1,healthdb.sqlite
17,2021-09-23 14:27:08.643061+00:00,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,47,1,healthdb.sqlite
18,2023-01-02 13:47:38.280079+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,43,1,healthdb.sqlite
19,2023-05-19 16:03:01.287088+00:00,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,53,1,healthdb.sqlite

📊 Total Devices: 23

======================================================================
📱 SOURCE DEVICES REPORT - iOS 17
======================================================================

,Creation Timestamp,Device Name,Manufacturer,Model,Hardware,Firmware,Software,Local Identifier,Sync Provenance,Sync Identity,Source Database
0,2020-03-21 20:28:48.950322+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.1.3,,47,1,healthdb.sqlite
1,2020-03-21 22:33:20.752680+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.3.1,,47,1,healthdb.sqlite
2,2020-03-27 19:06:14.240871+00:00,AirPods,Apple Inc.,0x2002,,,,7C:04:D0:89:89:A0-tacl,47,1,healthdb.sqlite
3,2020-03-31 19:08:08.763455+00:00,AirPods Pro,Apple Inc.,0x200e,,,,38:EC:0D:E2:49:CF-tacl,47,1,healthdb.sqlite
4,2020-04-13 19:26:44.236909+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,13.4.1,,47,1,healthdb.sqlite
5,2020-04-14 01:16:00.671350+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,6.2.1,,47,1,healthdb.sqlite
6,2020-08-24 16:51:30.985641+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.3.1,,47,1,healthdb.sqlite
7,2020-08-25 16:41:48.987626+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,13.6.1,,47,1,healthdb.sqlite
8,2020-10-02 19:09:11.750931+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.0.1,,47,1,healthdb.sqlite
9,2020-12-13 11:56:54.383111+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.2,,47,1,healthdb.sqlite
10,2020-12-30 17:59:31.666058+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1,healthdb.sqlite
11,2021-01-17 19:22:59.534474+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,47,1,healthdb.sqlite
12,2021-01-17 20:54:40.486938+00:00,iPhone,Apple Inc.,iPhone,"iPhone8,4",,14.3,,47,1,healthdb.sqlite
13,2021-02-11 22:12:02.857532+00:00,Apple Watch,Apple Inc.,Watch,"Watch4,3",,7.2,,93,1,healthdb.sqlite
14,2021-03-01 19:39:23.998170+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,14.4,,47,1,healthdb.sqlite
15,2021-05-10 13:37:39.103495+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.3,,47,1,healthdb.sqlite
16,2021-05-13 18:17:01.672781+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,1",,14.2,,47,1,healthdb.sqlite
17,2021-09-23 14:27:08.643061+00:00,iPhone,Apple Inc.,iPhone,"iPhone11,2",,14.8,,47,1,healthdb.sqlite
18,2023-01-02 13:47:38.280079+00:00,iPhone,Apple Inc.,iPhone,"iPhone10,4",,15.3.1,,43,1,healthdb.sqlite
19,2023-05-19 16:03:01.287088+00:00,This Is’s AirPods,Apple Inc.,0x2013,,,,08:65:18:75:5E:75-tacl,53,1,healthdb.sqlite

📊 Total Devices: 25

# **Fitur Steps**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR STEPS
# ============================================================

print()
print("=" * 70)
print("🚶 VERIFIKASI STEPS")
print("=" * 70)


steps_required_tables = [
    "samples",
    "quantity_samples",
    "objects",
    "data_provenances"
]


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    print()
    print(
        f"📱 {version}"
    )

    for table_name in steps_required_tables:

        if table_name in secure_tables:

            print(
                f"   📂 {table_name:<20}: ✅ Ditemukan"
            )

        else:

            print(
                f"   📂 {table_name:<20}: ❌ Tidak ditemukan"
            )


print()
print("=" * 70)

======================================================================
🚶 VERIFIKASI STEPS
======================================================================

📱 iOS 13.3.1
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 13.4.1
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 15
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 16
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 17
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR STEPS
# ============================================================


def extract_steps(
    secure_database_path
):

    """
    Extract Apple Health Steps data.

    Database:
        healthdb_secure.sqlite

    Tables:
        samples
        quantity_samples
        objects
        data_provenances

    Health data_type:
        7 = Steps
    """

    conn = open_sqlite_readonly(
        secure_database_path
    )


    query = """

    SELECT

        samples.start_date AS start_date,

        samples.end_date AS end_date,

        quantity_samples.quantity AS steps,

        data_provenances.origin_product_type AS device

    FROM samples

    LEFT JOIN quantity_samples
        ON samples.data_id =
           quantity_samples.data_id

    LEFT JOIN objects
        ON samples.data_id =
           objects.data_id

    LEFT JOIN data_provenances
        ON objects.provenance =
           data_provenances.rowid

    WHERE

        samples.data_type = 7

        AND quantity_samples.quantity IS NOT NULL

    ORDER BY

        samples.start_date DESC

    """


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    return df


print(
    "✅ Extractor Steps siap."
)

✅ Extractor Steps siap.

In [ ]:
# ============================================================
# EKSTRAKSI STEPS
# ============================================================


steps_results = {}


for dataset in target_datasets:

    version = dataset["version"]

    secure_db_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"🚶 STEPS - {version}"
    )

    print("=" * 70)


    try:

        df_steps = extract_steps(
            secure_db_path
        )


        steps_results[
            version
        ] = df_steps


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Step Records: "
            f"{len(df_steps)}"
        )

        print(
            "📂 Source: healthdb_secure.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Error: {e}"
        )

======================================================================
🚶 STEPS - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Step Records: 5544
📂 Source: healthdb_secure.sqlite

======================================================================
🚶 STEPS - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Step Records: 6060
📂 Source: healthdb_secure.sqlite

======================================================================
🚶 STEPS - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Step Records: 15502
📂 Source: healthdb_secure.sqlite

======================================================================
🚶 STEPS - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Step Records: 14644
📂 Source: healthdb_secure.sqlite

======================================================================
🚶 STEPS - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Step Records: 17012
📂 Source: healthdb_secure.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW STEPS
# ============================================================


for version, df_steps in steps_results.items():

    print()
    print("=" * 70)

    print(
        f"🚶 RAW STEPS - {version}"
    )

    print("=" * 70)


    display(
        df_steps.head(20)
    )


    print()

    print(
        f"📊 Total Step Records: "
        f"{len(df_steps)}"
    )

======================================================================
🚶 RAW STEPS - iOS 13.3.1
======================================================================

      start_date      end_date  steps     device
0   6.084108e+08  6.084110e+08   51.0   Watch4,3
1   6.084108e+08  6.084108e+08   35.0   Watch4,3
2   6.084107e+08  6.084107e+08    1.0   Watch4,3
3   6.084106e+08  6.084107e+08   55.0   Watch4,3
4   6.084082e+08  6.084082e+08   20.0   Watch4,3
5   6.084057e+08  6.084057e+08   16.0   Watch4,3
6   6.084049e+08  6.084049e+08    8.0   Watch4,3
7   6.084040e+08  6.084040e+08   36.0   Watch4,3
8   6.084033e+08  6.084034e+08   33.0   Watch4,3
9   6.084030e+08  6.084031e+08   32.0  iPhone8,4
10  6.084030e+08  6.084031e+08   34.0   Watch4,3
11  6.084029e+08  6.084029e+08   14.0   Watch4,3
12  6.084028e+08  6.084028e+08   17.0   Watch4,3
13  6.084027e+08  6.084027e+08    8.0   Watch4,3
14  6.084025e+08  6.084026e+08   22.0   Watch4,3
15  6.084025e+08  6.084025e+08   21.0   Watch4,3
16  6.084021e+08  6.084022e+08   35.0   Watch4,3
17  6.084020e+08  6.084020e+08    2.0   Watch4,3
18  6.084020e+08  6.084020e+08   17.0   Watch4,3
19  6.084010e+08  6.084014e+08  150.0   Watch4,3

📊 Total Step Records: 5544

======================================================================
🚶 RAW STEPS - iOS 13.4.1
======================================================================

      start_date      end_date  steps    device
0   6.087425e+08  6.087428e+08  149.0  Watch4,3
1   6.087424e+08  6.087425e+08    8.0  Watch4,3
2   6.087418e+08  6.087424e+08  249.0  Watch4,3
3   6.087418e+08  6.087418e+08   15.0  Watch4,3
4   6.087416e+08  6.087417e+08   32.0  Watch4,3
5   6.087416e+08  6.087416e+08   58.0  Watch4,3
6   6.087415e+08  6.087415e+08   41.0  Watch4,3
7   6.087409e+08  6.087409e+08   38.0  Watch4,3
8   6.087408e+08  6.087409e+08   31.0  Watch4,3
9   6.087407e+08  6.087407e+08   51.0  Watch4,3
10  6.087406e+08  6.087406e+08    4.0  Watch4,3
11  6.087405e+08  6.087405e+08   34.0  Watch4,3
12  6.087405e+08  6.087405e+08    6.0  Watch4,3
13  6.087404e+08  6.087405e+08   11.0  Watch4,3
14  6.087398e+08  6.087399e+08   17.0  Watch4,3
15  6.087397e+08  6.087397e+08    4.0  Watch4,3
16  6.087396e+08  6.087396e+08    3.0  Watch4,3
17  6.087389e+08  6.087389e+08   18.0  Watch4,3
18  6.087384e+08  6.087384e+08    9.0  Watch4,3
19  6.087367e+08  6.087367e+08   18.0  Watch4,3

📊 Total Step Records: 6060

======================================================================
🚶 RAW STEPS - iOS 15
======================================================================

      start_date      end_date  steps      device
0   7.063053e+08  7.063054e+08   64.0  iPhone10,4
1   7.063034e+08  7.063035e+08   75.0  iPhone10,4
2   7.063027e+08  7.063027e+08   49.0  iPhone10,4
3   7.062969e+08  7.062970e+08   17.0  iPhone10,4
4   7.062963e+08  7.062969e+08   94.0  iPhone10,4
5   7.062945e+08  7.062948e+08  227.0  iPhone10,4
6   7.062907e+08  7.062908e+08   23.0  iPhone10,4
7   7.062888e+08  7.062889e+08   38.0  iPhone10,4
8   7.062340e+08  7.062345e+08  203.0  iPhone10,4
9   7.062330e+08  7.062334e+08  182.0  iPhone10,4
10  7.062313e+08  7.062313e+08   10.0  iPhone10,4
11  7.062306e+08  7.062307e+08   27.0  iPhone10,4
12  7.062290e+08  7.062290e+08   39.0  iPhone10,4
13  7.062276e+08  7.062276e+08    6.0  iPhone10,4
14  7.062270e+08  7.062270e+08   15.0  iPhone10,4
15  7.062254e+08  7.062259e+08  155.0  iPhone10,4
16  7.062247e+08  7.062253e+08  143.0  iPhone10,4
17  7.062241e+08  7.062247e+08  327.0  iPhone10,4
18  7.062231e+08  7.062234e+08   69.0  iPhone10,4
19  7.062221e+08  7.062227e+08  165.0  iPhone10,4

📊 Total Step Records: 15502

======================================================================
🚶 RAW STEPS - iOS 16
======================================================================

      start_date      end_date  steps      device
0   7.277163e+08  7.277164e+08   58.0  iPhone12,1
1   7.277094e+08  7.277099e+08  110.0  iPhone12,1
2   7.277062e+08  7.277063e+08   59.0  iPhone12,1
3   7.277050e+08  7.277051e+08   30.0  iPhone12,1
4   7.276488e+08  7.276489e+08   48.0  iPhone12,1
5   7.276482e+08  7.276486e+08  149.0  iPhone12,1
6   7.276292e+08  7.276292e+08   27.0  iPhone12,1
7   7.275685e+08  7.275685e+08   10.0  iPhone12,1
8   7.275593e+08  7.275594e+08   88.0  iPhone12,1
9   7.275493e+08  7.275493e+08   34.0  iPhone12,1
10  7.273094e+08  7.273094e+08   10.0  iPhone12,1
11  7.273088e+08  7.273093e+08  132.0  iPhone12,1
12  7.273078e+08  7.273078e+08   14.0  iPhone12,1
13  7.273071e+08  7.273073e+08   80.0  iPhone12,1
14  7.273065e+08  7.273071e+08  319.0  iPhone12,1
15  7.273053e+08  7.273059e+08  189.0  iPhone12,1
16  7.273041e+08  7.273041e+08   55.0  iPhone12,1
17  7.273024e+08  7.273025e+08   48.0  iPhone12,1
18  7.272989e+08  7.272994e+08  269.0  iPhone12,1
19  7.272209e+08  7.272209e+08    8.0  iPhone12,1

📊 Total Step Records: 14644

======================================================================
🚶 RAW STEPS - iOS 17
======================================================================

      start_date      end_date   steps      device
0   7.438738e+08  7.438759e+08    45.0  iPhone12,1
1   7.437923e+08  7.437929e+08   193.0  iPhone12,1
2   7.437910e+08  7.437923e+08    37.0  iPhone12,1
3   7.437903e+08  7.437910e+08   642.0  iPhone12,1
4   7.437888e+08  7.437903e+08   105.0  iPhone12,1
5   7.437865e+08  7.437888e+08    51.0  iPhone12,1
6   7.437862e+08  7.437865e+08   390.0  iPhone12,1
7   7.437856e+08  7.437862e+08  1074.0  iPhone12,1
8   7.437850e+08  7.437856e+08  1050.0  iPhone12,1
9   7.437844e+08  7.437850e+08  1090.0  iPhone12,1
10  7.437838e+08  7.437844e+08  1016.0  iPhone12,1
11  7.437832e+08  7.437838e+08  1147.0  iPhone12,1
12  7.437826e+08  7.437832e+08  1140.0  iPhone12,1
13  7.437820e+08  7.437826e+08  1133.0  iPhone12,1
14  7.437814e+08  7.437820e+08   766.0  iPhone12,1
15  7.437182e+08  7.437210e+08   110.0  iPhone12,1
16  7.436949e+08  7.436949e+08    26.0  iPhone12,1
17  7.436943e+08  7.436949e+08    95.0  iPhone12,1
18  7.436927e+08  7.436928e+08    73.0    Watch4,3
19  7.436922e+08  7.436923e+08    24.0    Watch4,3

📊 Total Step Records: 17012

In [ ]:
# ============================================================
# FORMAT LAPORAN STEPS
# ============================================================


steps_reports = {}


for version, df_steps in steps_results.items():

    df_report = pd.DataFrame()


    # ========================================================
    # START TIMESTAMP
    # ========================================================

    df_report[
        "Start Timestamp"
    ] = (

        df_steps[
            "start_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    # ========================================================
    # END TIMESTAMP
    # ========================================================

    df_report[
        "End Timestamp"
    ] = (

        df_steps[
            "end_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    # ========================================================
    # DURATION
    # ========================================================

    df_report[
        "Duration (Seconds)"
    ] = (

        pd.to_numeric(
            df_steps["end_date"],
            errors="coerce"
        )

        -

        pd.to_numeric(
            df_steps["start_date"],
            errors="coerce"
        )

    )


    # ========================================================
    # STEPS
    # ========================================================

    df_report[
        "Steps"
    ] = (

        pd.to_numeric(
            df_steps["steps"],
            errors="coerce"
        )

    )


    # ========================================================
    # DEVICE
    # ========================================================

    df_report[
        "Device"
    ] = (

        df_steps[
            "device"
        ]

    )


    # ========================================================
    # SOURCE DATABASE
    # ========================================================

    df_report[
        "Source Database"
    ] = (

        "healthdb_secure.sqlite"

    )


    steps_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Steps selesai."
)

✅ Format laporan Steps selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT STEPS
# ============================================================


for version, df_report in steps_reports.items():

    print()
    print("=" * 70)

    print(
        f"🚶 STEPS REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Step Records: "
        f"{len(df_report)}"
    )

======================================================================
🚶 STEPS REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Duration (Seconds),Steps,Device,Source Database
0,2020-04-12 19:00:15.209773+00:00,2020-04-12 19:03:18.978611+00:00,183.768838,51.0,"Watch4,3",healthdb_secure.sqlite
1,2020-04-12 18:59:31.816501+00:00,2020-04-12 19:00:12.655992+00:00,40.839491,35.0,"Watch4,3",healthdb_secure.sqlite
2,2020-04-12 18:58:20.348131+00:00,2020-04-12 18:58:22.901650+00:00,2.553519,1.0,"Watch4,3",healthdb_secure.sqlite
3,2020-04-12 18:57:16.538361+00:00,2020-04-12 18:58:17.796605+00:00,61.258244,55.0,"Watch4,3",healthdb_secure.sqlite
4,2020-04-12 18:16:13.398446+00:00,2020-04-12 18:16:18.502653+00:00,5.104207,20.0,"Watch4,3",healthdb_secure.sqlite
5,2020-04-12 17:34:37.062802+00:00,2020-04-12 17:34:39.615044+00:00,2.552242,16.0,"Watch4,3",healthdb_secure.sqlite
6,2020-04-12 17:22:27.065405+00:00,2020-04-12 17:22:29.621549+00:00,2.556145,8.0,"Watch4,3",healthdb_secure.sqlite
7,2020-04-12 17:06:47.795659+00:00,2020-04-12 17:07:08.215034+00:00,20.419376,36.0,"Watch4,3",healthdb_secure.sqlite
8,2020-04-12 16:55:39.109508+00:00,2020-04-12 16:55:54.423803+00:00,15.314295,33.0,"Watch4,3",healthdb_secure.sqlite
9,2020-04-12 16:50:47.627570+00:00,2020-04-12 16:51:03.038041+00:00,15.410471,32.0,"iPhone8,4",healthdb_secure.sqlite
10,2020-04-12 16:50:45.599975+00:00,2020-04-12 16:51:11.124738+00:00,25.524763,34.0,"Watch4,3",healthdb_secure.sqlite
11,2020-04-12 16:48:14.987576+00:00,2020-04-12 16:48:55.820971+00:00,40.833394,14.0,"Watch4,3",healthdb_secure.sqlite
12,2020-04-12 16:46:40.557990+00:00,2020-04-12 16:46:50.767552+00:00,10.209562,17.0,"Watch4,3",healthdb_secure.sqlite
13,2020-04-12 16:44:17.630792+00:00,2020-04-12 16:44:20.182425+00:00,2.551633,8.0,"Watch4,3",healthdb_secure.sqlite
14,2020-04-12 16:41:54.701092+00:00,2020-04-12 16:42:53.404789+00:00,58.703697,22.0,"Watch4,3",healthdb_secure.sqlite
15,2020-04-12 16:41:24.071793+00:00,2020-04-12 16:41:36.835072+00:00,12.763279,21.0,"Watch4,3",healthdb_secure.sqlite
16,2020-04-12 16:34:53.573232+00:00,2020-04-12 16:35:52.278808+00:00,58.705576,35.0,"Watch4,3",healthdb_secure.sqlite
17,2020-04-12 16:33:47.208479+00:00,2020-04-12 16:33:49.760988+00:00,2.552509,2.0,"Watch4,3",healthdb_secure.sqlite
18,2020-04-12 16:32:38.291160+00:00,2020-04-12 16:33:39.551299+00:00,61.260138,17.0,"Watch4,3",healthdb_secure.sqlite
19,2020-04-12 16:16:58.968347+00:00,2020-04-12 16:23:37.146874+00:00,398.178526,150.0,"Watch4,3",healthdb_secure.sqlite

📊 Total Step Records: 5544

======================================================================
🚶 STEPS REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Duration (Seconds),Steps,Device,Source Database
0,2020-04-16 15:07:48.291875+00:00,2020-04-16 15:14:01.359456+00:00,373.067581,149.0,"Watch4,3",healthdb_secure.sqlite
1,2020-04-16 15:07:27.784432+00:00,2020-04-16 15:07:30.350219+00:00,2.565788,8.0,"Watch4,3",healthdb_secure.sqlite
2,2020-04-16 14:57:25.080950+00:00,2020-04-16 15:07:17.521693+00:00,592.440743,249.0,"Watch4,3",healthdb_secure.sqlite
3,2020-04-16 14:57:19.973716+00:00,2020-04-16 14:57:25.080950+00:00,5.107234,15.0,"Watch4,3",healthdb_secure.sqlite
4,2020-04-16 14:54:08.525618+00:00,2020-04-16 14:54:34.052120+00:00,25.526502,32.0,"Watch4,3",healthdb_secure.sqlite
5,2020-04-16 14:52:57.043140+00:00,2020-04-16 14:53:48.105513+00:00,51.062374,58.0,"Watch4,3",healthdb_secure.sqlite
6,2020-04-16 14:51:27.701164+00:00,2020-04-16 14:51:53.227273+00:00,25.526109,41.0,"Watch4,3",healthdb_secure.sqlite
7,2020-04-16 14:41:20.120912+00:00,2020-04-16 14:41:43.090466+00:00,22.969554,38.0,"Watch4,3",healthdb_secure.sqlite
8,2020-04-16 14:40:13.746104+00:00,2020-04-16 14:40:59.694887+00:00,45.948782,31.0,"Watch4,3",healthdb_secure.sqlite
9,2020-04-16 14:37:50.795013+00:00,2020-04-16 14:38:52.060611+00:00,61.265598,51.0,"Watch4,3",healthdb_secure.sqlite
10,2020-04-16 14:36:18.898675+00:00,2020-04-16 14:36:24.004935+00:00,5.106260,4.0,"Watch4,3",healthdb_secure.sqlite
11,2020-04-16 14:34:59.770930+00:00,2020-04-16 14:35:25.294393+00:00,25.523463,34.0,"Watch4,3",healthdb_secure.sqlite
12,2020-04-16 14:34:24.028938+00:00,2020-04-16 14:34:26.581382+00:00,2.552444,6.0,"Watch4,3",healthdb_secure.sqlite
13,2020-04-16 14:33:22.761406+00:00,2020-04-16 14:34:24.028938+00:00,61.267531,11.0,"Watch4,3",healthdb_secure.sqlite
14,2020-04-16 14:24:03.682148+00:00,2020-04-16 14:24:11.337332+00:00,7.655184,17.0,"Watch4,3",healthdb_secure.sqlite
15,2020-04-16 14:21:45.846121+00:00,2020-04-16 14:21:48.398636+00:00,2.552514,4.0,"Watch4,3",healthdb_secure.sqlite
16,2020-04-16 14:19:22.899252+00:00,2020-04-16 14:19:25.457928+00:00,2.558675,3.0,"Watch4,3",healthdb_secure.sqlite
17,2020-04-16 14:08:54.972637+00:00,2020-04-16 14:08:57.531175+00:00,2.558538,18.0,"Watch4,3",healthdb_secure.sqlite
18,2020-04-16 14:00:21.875245+00:00,2020-04-16 14:00:39.740219+00:00,17.864975,9.0,"Watch4,3",healthdb_secure.sqlite
19,2020-04-16 13:31:23.523813+00:00,2020-04-16 13:31:31.183234+00:00,7.659421,18.0,"Watch4,3",healthdb_secure.sqlite

📊 Total Step Records: 6060

======================================================================
🚶 STEPS REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Duration (Seconds),Steps,Device,Source Database
0,2023-05-20 19:55:48.242202+00:00,2023-05-20 19:56:44.512526+00:00,56.270324,64.0,"iPhone10,4",healthdb_secure.sqlite
1,2023-05-20 19:23:06.126447+00:00,2023-05-20 19:24:56.100906+00:00,109.974458,75.0,"iPhone10,4",healthdb_secure.sqlite
2,2023-05-20 19:11:17.561771+00:00,2023-05-20 19:11:45.693071+00:00,28.131300,49.0,"iPhone10,4",healthdb_secure.sqlite
3,2023-05-20 17:35:48.000317+00:00,2023-05-20 17:35:55.674866+00:00,7.674549,17.0,"iPhone10,4",healthdb_secure.sqlite
4,2023-05-20 17:25:11.130317+00:00,2023-05-20 17:34:56.848485+00:00,585.718168,94.0,"iPhone10,4",healthdb_secure.sqlite
5,2023-05-20 16:55:20.678484+00:00,2023-05-20 16:59:23.607955+00:00,242.929471,227.0,"iPhone10,4",healthdb_secure.sqlite
6,2023-05-20 15:51:42.957626+00:00,2023-05-20 15:53:35.507595+00:00,112.549969,23.0,"iPhone10,4",healthdb_secure.sqlite
7,2023-05-20 15:20:30.686532+00:00,2023-05-20 15:21:06.483294+00:00,35.796762,38.0,"iPhone10,4",healthdb_secure.sqlite
8,2023-05-20 00:06:18.227289+00:00,2023-05-20 00:14:49.750746+00:00,511.523457,203.0,"iPhone10,4",healthdb_secure.sqlite
9,2023-05-19 23:49:48.361573+00:00,2023-05-19 23:57:21.070377+00:00,452.708804,182.0,"iPhone10,4",healthdb_secure.sqlite
10,2023-05-19 23:22:23.687132+00:00,2023-05-19 23:22:26.243385+00:00,2.556253,10.0,"iPhone10,4",healthdb_secure.sqlite
11,2023-05-19 23:10:04.545191+00:00,2023-05-19 23:11:08.479986+00:00,63.934795,27.0,"iPhone10,4",healthdb_secure.sqlite
12,2023-05-19 22:43:05.490533+00:00,2023-05-19 22:43:54.081660+00:00,48.591127,39.0,"iPhone10,4",healthdb_secure.sqlite
13,2023-05-19 22:20:17.010543+00:00,2023-05-19 22:20:19.566812+00:00,2.556269,6.0,"iPhone10,4",healthdb_secure.sqlite
14,2023-05-19 22:10:03.058120+00:00,2023-05-19 22:10:08.172745+00:00,5.114625,15.0,"iPhone10,4",healthdb_secure.sqlite
15,2023-05-19 21:43:52.609341+00:00,2023-05-19 21:52:29.237847+00:00,516.628506,155.0,"iPhone10,4",healthdb_secure.sqlite
16,2023-05-19 21:31:15.536685+00:00,2023-05-19 21:41:08.899438+00:00,593.362752,143.0,"iPhone10,4",healthdb_secure.sqlite
17,2023-05-19 21:21:14.498770+00:00,2023-05-19 21:31:15.536685+00:00,601.037915,327.0,"iPhone10,4",healthdb_secure.sqlite
18,2023-05-19 21:05:48.592531+00:00,2023-05-19 21:09:15.759604+00:00,207.167073,69.0,"iPhone10,4",healthdb_secure.sqlite
19,2023-05-19 20:48:58.412818+00:00,2023-05-19 20:58:44.040935+00:00,585.628117,165.0,"iPhone10,4",healthdb_secure.sqlite

📊 Total Step Records: 15502

======================================================================
🚶 STEPS REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Duration (Seconds),Steps,Device,Source Database
0,2024-01-23 15:24:51.281370+00:00,2024-01-23 15:26:41.433784+00:00,110.152414,58.0,"iPhone12,1",healthdb_secure.sqlite
1,2024-01-23 13:29:31.893881+00:00,2024-01-23 13:37:41.114075+00:00,489.220194,110.0,"iPhone12,1",healthdb_secure.sqlite
2,2024-01-23 12:37:18.877212+00:00,2024-01-23 12:38:48.519956+00:00,89.642744,59.0,"iPhone12,1",healthdb_secure.sqlite
3,2024-01-23 12:17:20.809744+00:00,2024-01-23 12:17:38.737979+00:00,17.928235,30.0,"iPhone12,1",healthdb_secure.sqlite
4,2024-01-22 20:40:40.985055+00:00,2024-01-22 20:41:09.162213+00:00,28.177158,48.0,"iPhone12,1",healthdb_secure.sqlite
5,2024-01-22 20:29:50.150459+00:00,2024-01-22 20:36:58.075975+00:00,427.925516,149.0,"iPhone12,1",healthdb_secure.sqlite
6,2024-01-22 15:13:33.823775+00:00,2024-01-22 15:13:49.190992+00:00,15.367217,27.0,"iPhone12,1",healthdb_secure.sqlite
7,2024-01-21 22:21:09.827821+00:00,2024-01-21 22:21:12.389246+00:00,2.561425,10.0,"iPhone12,1",healthdb_secure.sqlite
8,2024-01-21 19:48:47.400917+00:00,2024-01-21 19:49:41.195690+00:00,53.794773,88.0,"iPhone12,1",healthdb_secure.sqlite
9,2024-01-21 17:01:37.946077+00:00,2024-01-21 17:01:55.873277+00:00,17.927200,34.0,"iPhone12,1",healthdb_secure.sqlite
10,2024-01-18 22:23:34.066445+00:00,2024-01-18 22:23:39.189839+00:00,5.123394,10.0,"iPhone12,1",healthdb_secure.sqlite
11,2024-01-18 22:13:06.212515+00:00,2024-01-18 22:22:01.780818+00:00,535.568304,132.0,"iPhone12,1",healthdb_secure.sqlite
12,2024-01-18 21:56:21.205520+00:00,2024-01-18 21:56:26.328630+00:00,5.123110,14.0,"iPhone12,1",healthdb_secure.sqlite
13,2024-01-18 21:45:43.013605+00:00,2024-01-18 21:48:19.281548+00:00,156.267943,80.0,"iPhone12,1",healthdb_secure.sqlite
14,2024-01-18 21:35:25.664387+00:00,2024-01-18 21:44:23.603937+00:00,537.939550,319.0,"iPhone12,1",healthdb_secure.sqlite
15,2024-01-18 21:15:49.549734+00:00,2024-01-18 21:25:43.888576+00:00,594.338843,189.0,"iPhone12,1",healthdb_secure.sqlite
16,2024-01-18 20:54:33.723972+00:00,2024-01-18 20:55:17.274730+00:00,43.550758,55.0,"iPhone12,1",healthdb_secure.sqlite
17,2024-01-18 20:27:10.887585+00:00,2024-01-18 20:27:39.069150+00:00,28.181566,48.0,"iPhone12,1",healthdb_secure.sqlite
18,2024-01-18 19:27:32.017490+00:00,2024-01-18 19:37:05.862746+00:00,573.845257,269.0,"iPhone12,1",healthdb_secure.sqlite
19,2024-01-17 21:49:01.181470+00:00,2024-01-17 21:49:03.742945+00:00,2.561475,8.0,"iPhone12,1",healthdb_secure.sqlite

📊 Total Step Records: 14644

======================================================================
🚶 STEPS REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Duration (Seconds),Steps,Device,Source Database
0,2024-07-28 15:36:42.442651+00:00,2024-07-28 16:11:25.646978+00:00,2083.204327,45.0,"iPhone12,1",healthdb_secure.sqlite
1,2024-07-27 16:58:20.081976+00:00,2024-07-27 17:09:08.339734+00:00,648.257758,193.0,"iPhone12,1",healthdb_secure.sqlite
2,2024-07-27 16:37:04.269222+00:00,2024-07-27 16:58:20.081976+00:00,1275.812754,37.0,"iPhone12,1",healthdb_secure.sqlite
3,2024-07-27 16:24:51.516772+00:00,2024-07-27 16:37:04.269222+00:00,732.752450,642.0,"iPhone12,1",healthdb_secure.sqlite
4,2024-07-27 16:00:07.901598+00:00,2024-07-27 16:24:51.516772+00:00,1483.615174,105.0,"iPhone12,1",healthdb_secure.sqlite
5,2024-07-27 15:22:16.100296+00:00,2024-07-27 16:00:07.901598+00:00,2271.801302,51.0,"iPhone12,1",healthdb_secure.sqlite
6,2024-07-27 15:17:13.794466+00:00,2024-07-27 15:22:16.100296+00:00,302.305829,390.0,"iPhone12,1",healthdb_secure.sqlite
7,2024-07-27 15:07:09.181513+00:00,2024-07-27 15:17:13.794466+00:00,604.612953,1074.0,"iPhone12,1",healthdb_secure.sqlite
8,2024-07-27 14:57:04.580890+00:00,2024-07-27 15:07:09.181513+00:00,604.600623,1050.0,"iPhone12,1",healthdb_secure.sqlite
9,2024-07-27 14:46:59.992257+00:00,2024-07-27 14:57:04.580890+00:00,604.588632,1090.0,"iPhone12,1",healthdb_secure.sqlite
10,2024-07-27 14:36:55.441239+00:00,2024-07-27 14:46:59.992257+00:00,604.551019,1016.0,"iPhone12,1",healthdb_secure.sqlite
11,2024-07-27 14:26:50.845048+00:00,2024-07-27 14:36:55.441239+00:00,604.596191,1147.0,"iPhone12,1",healthdb_secure.sqlite
12,2024-07-27 14:16:46.217506+00:00,2024-07-27 14:26:50.845048+00:00,604.627542,1140.0,"iPhone12,1",healthdb_secure.sqlite
13,2024-07-27 14:06:41.540930+00:00,2024-07-27 14:16:46.217506+00:00,604.676576,1133.0,"iPhone12,1",healthdb_secure.sqlite
14,2024-07-27 13:56:36.871200+00:00,2024-07-27 14:06:41.540930+00:00,604.669730,766.0,"iPhone12,1",healthdb_secure.sqlite
15,2024-07-26 20:22:44.387760+00:00,2024-07-26 21:09:40.235825+00:00,2815.848065,110.0,"iPhone12,1",healthdb_secure.sqlite
16,2024-07-26 13:54:47.646592+00:00,2024-07-26 13:55:00.454885+00:00,12.808294,26.0,"iPhone12,1",healthdb_secure.sqlite
17,2024-07-26 13:44:47.676547+00:00,2024-07-26 13:54:47.646592+00:00,599.970044,95.0,"iPhone12,1",healthdb_secure.sqlite
18,2024-07-26 13:17:41.346772+00:00,2024-07-26 13:19:13.280611+00:00,91.933838,73.0,"Watch4,3",healthdb_secure.sqlite
19,2024-07-26 13:10:45.136677+00:00,2024-07-26 13:11:03.011875+00:00,17.875199,24.0,"Watch4,3",healthdb_secure.sqlite

📊 Total Step Records: 17012

# **Fitur Watch by Sleep Period**

In [ ]:
# ============================================================
# VERIFIKASI WATCH BY SLEEP PERIOD
# ============================================================

print()
print("=" * 70)
print("⌚ VERIFIKASI WATCH BY SLEEP PERIOD")
print("=" * 70)


watch_sleep_required_tables = [
    "samples",
    "category_samples",
    "objects",
    "data_provenances"
]


for dataset in target_datasets:

    version = dataset["version"]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    print()
    print(
        f"📱 {version}"
    )

    for table_name in watch_sleep_required_tables:

        if table_name in secure_tables:

            print(
                f"   📂 {table_name:<20}: ✅ Ditemukan"
            )

        else:

            print(
                f"   📂 {table_name:<20}: ❌ Tidak ditemukan"
            )


print()
print("=" * 70)

======================================================================
⌚ VERIFIKASI WATCH BY SLEEP PERIOD
======================================================================

📱 iOS 13.3.1
   📂 samples             : ✅ Ditemukan
   📂 category_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 13.4.1
   📂 samples             : ✅ Ditemukan
   📂 category_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 15
   📂 samples             : ✅ Ditemukan
   📂 category_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 16
   📂 samples             : ✅ Ditemukan
   📂 category_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

📱 iOS 17
   📂 samples             : ✅ Ditemukan
   📂 category_samples    : ✅ Ditemukan
   📂 objects             : ✅ Ditemukan
   📂 data_provenances    : ✅ Ditemukan

======================================================================

In [ ]:
# ============================================================
# IDENTIFIKASI VERSI IOS
# ============================================================

import re


def get_ios_major_version(version):

    """
    Mengambil major version iOS dari label dataset.

    Contoh:
        iOS 17   -> 17
        iOS 16.5 -> 16
        15       -> 15
    """

    version_text = str(
        version
    )

    match = re.search(
        r"(\d+)",
        version_text
    )

    if not match:

        return None

    return int(
        match.group(1)
    )


print(
    "✅ Fungsi identifikasi versi iOS siap."
)

✅ Fungsi identifikasi versi iOS siap.

In [ ]:
# ============================================================
# EXTRACTOR WATCH BY SLEEP PERIOD
# ============================================================


def extract_watch_by_sleep_period(
    secure_database_path,
    ios_version
):

    """
    Extract Apple Health Watch By Sleep Period.

    Database:
        healthdb_secure.sqlite

    iOS 17:
        AWAKE
        CORE
        DEEP
        REM

    Versi sebelumnya:
        IN BED
        ASLEEP
    """

    major_version = get_ios_major_version(
        ios_version
    )


    conn = open_sqlite_readonly(
        secure_database_path
    )


    # ========================================================
    # IOS 17
    # ========================================================

    if major_version == 17:

        print(
            "   🔎 Struktur sleep terdeteksi: "
            "iOS 17 Sleep Stages"
        )


        query = """

        WITH lagged_samples AS (

            SELECT

                s.start_date,

                s.end_date,

                s.data_id,

                s.data_type,

                cs.value,

                LAG(s.data_id)
                    OVER (
                        ORDER BY s.data_id
                    ) AS prev_data_id,

                CASE

                    WHEN cs.value = 2
                        THEN 'AWAKE'

                    WHEN cs.value = 3
                        THEN 'CORE'

                    WHEN cs.value = 4
                        THEN 'DEEP'

                    WHEN cs.value = 5
                        THEN 'REM'

                END AS sleep_value

            FROM samples s

            LEFT JOIN category_samples cs
                ON s.data_id = cs.data_id

            LEFT JOIN objects o
                ON s.data_id = o.data_id

            LEFT JOIN data_provenances dp
                ON o.provenance = dp.rowid

            WHERE

                s.data_type = 63

                AND cs.value NOT IN (0, 1)

                AND dp.origin_product_type
                    LIKE '%Watch%'

        ),


        grouped_samples AS (

            SELECT

                *,

                CASE

                    WHEN data_id - prev_data_id > 1
                        OR prev_data_id IS NULL

                    THEN 1

                    ELSE 0

                END AS is_new_group,


                SUM(

                    CASE

                        WHEN data_id - prev_data_id > 1
                            OR prev_data_id IS NULL

                        THEN 1

                        ELSE 0

                    END

                ) OVER (
                    ORDER BY data_id
                ) AS group_number

            FROM lagged_samples

        )


        SELECT

            MIN(start_date)
                AS start_date,

            MAX(end_date)
                AS end_date,


            SUM(

                CASE

                    WHEN sleep_value IN (
                        'AWAKE',
                        'REM',
                        'CORE',
                        'DEEP'
                    )

                    THEN
                        (end_date - start_date) / 60.0

                    ELSE 0

                END

            ) AS total_duration,


            SUM(

                CASE

                    WHEN sleep_value = 'AWAKE'

                    THEN
                        (end_date - start_date) / 60.0

                    ELSE 0

                END

            ) AS awake_duration,


            SUM(

                CASE

                    WHEN sleep_value = 'REM'

                    THEN
                        (end_date - start_date) / 60.0

                    ELSE 0

                END

            ) AS rem_duration,


            SUM(

                CASE

                    WHEN sleep_value = 'CORE'

                    THEN
                        (end_date - start_date) / 60.0

                    ELSE 0

                END

            ) AS core_duration,


            SUM(

                CASE

                    WHEN sleep_value = 'DEEP'

                    THEN
                        (end_date - start_date) / 60.0

                    ELSE 0

                END

            ) AS deep_duration


        FROM grouped_samples

        GROUP BY group_number

        ORDER BY
            MIN(start_date) ASC

        """


        sleep_structure = (
            "Sleep Stages"
        )


    # ========================================================
    # IOS VERSI SEBELUMNYA
    # ========================================================

    else:

        print(
            "   🔎 Struktur sleep terdeteksi: "
            "Legacy IN BED / ASLEEP"
        )


        query = """

        WITH lagged_samples AS (

            SELECT

                s.data_id,

                s.start_date,

                s.end_date,

                (
                    s.end_date -
                    s.start_date
                ) / 60 AS duration_minutes,

                s.data_type,

                cs.value,

                dp.origin_product_type,


                LAG(s.data_id)
                    OVER (
                        ORDER BY s.data_id
                    ) AS prev_data_id,


                CASE cs.value

                    WHEN 0
                        THEN 'IN BED'

                    WHEN 1
                        THEN 'ASLEEP'

                END AS sleep_value


            FROM samples s


            LEFT JOIN category_samples cs

                ON s.data_id =
                   cs.data_id


            LEFT JOIN objects o

                ON s.data_id =
                   o.data_id


            LEFT JOIN data_provenances dp

                ON o.provenance =
                   dp.rowid


            WHERE

                s.data_type = 63

                AND cs.value IN (0, 1)

                AND dp.origin_product_type
                    LIKE '%Watch%'

        ),


        grouped_samples AS (

            SELECT

                *,

                CASE

                    WHEN prev_data_id IS NULL
                        OR data_id - prev_data_id > 1

                    THEN 1

                    ELSE 0

                END AS is_new_group,


                SUM(

                    CASE

                        WHEN prev_data_id IS NULL
                            OR data_id - prev_data_id > 1

                        THEN 1

                        ELSE 0

                    END

                ) OVER (
                    ORDER BY data_id
                ) AS group_number


            FROM lagged_samples

        )


        SELECT

            MIN(start_date)
                AS start_date,

            MAX(end_date)
                AS end_date,

            MAX(data_type)
                AS data_type_id,

            MAX(origin_product_type)
                AS device_name,


            SUM(

                CASE

                    WHEN sleep_value IN (
                        'IN BED',
                        'ASLEEP'
                    )

                    THEN duration_minutes

                    ELSE 0

                END

            ) AS total_duration,


            SUM(

                CASE

                    WHEN sleep_value = 'IN BED'

                    THEN duration_minutes

                    ELSE 0

                END

            ) AS in_bed_duration,

            SUM(

                CASE

                    WHEN sleep_value = 'ASLEEP'

                    THEN duration_minutes

                    ELSE 0

                END

           ) AS asleep_duration,


            CASE

                WHEN SUM(duration_minutes) > 0

                THEN ROUND(

                    SUM(

                        CASE

                            WHEN sleep_value = 'IN BED'

                            THEN duration_minutes

                            ELSE 0

                        END

                    ) * 100.0
                    /
                    SUM(duration_minutes),

                    2

                )

                ELSE 0

            END AS in_bed_percent,


            CASE

                WHEN SUM(duration_minutes) > 0

                THEN ROUND(

                    SUM(

                        CASE

                            WHEN sleep_value = 'ASLEEP'

                            THEN duration_minutes

                            ELSE 0

                        END

                    ) * 100.0
                    /
                    SUM(duration_minutes),

                    2

                )

                ELSE 0

            END AS asleep_percent


        FROM grouped_samples


        GROUP BY
            group_number


        ORDER BY
            MIN(start_date) ASC

        """


        sleep_structure = (
            "In Bed / Asleep"
        )


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    df[
        "sleep_structure"
    ] = sleep_structure


    return df


print(
    "✅ Extractor Watch By Sleep Period adaptive siap."
)

✅ Extractor Watch By Sleep Period adaptive siap.

In [ ]:
# ============================================================
# EKSTRAKSI WATCH BY SLEEP PERIOD
# ============================================================


watch_sleep_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_db_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"⌚ WATCH BY SLEEP PERIOD - {version}"
    )

    print("=" * 70)


    try:

        df_watch_sleep = (
            extract_watch_by_sleep_period(
                secure_db_path,
                version
            )
        )


        watch_sleep_results[
            version
        ] = df_watch_sleep


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Sleep Periods: "
            f"{len(df_watch_sleep)}"
        )

        print(
            "📂 Source: "
            "healthdb_secure.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Error: {e}"
        )

======================================================================
⌚ WATCH BY SLEEP PERIOD - iOS 13.3.1
======================================================================
   🔎 Struktur sleep terdeteksi: Legacy IN BED / ASLEEP
✅ Ekstraksi berhasil
📊 Total Sleep Periods: 0
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH BY SLEEP PERIOD - iOS 13.4.1
======================================================================
   🔎 Struktur sleep terdeteksi: Legacy IN BED / ASLEEP
✅ Ekstraksi berhasil
📊 Total Sleep Periods: 0
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH BY SLEEP PERIOD - iOS 15
======================================================================
   🔎 Struktur sleep terdeteksi: Legacy IN BED / ASLEEP
✅ Ekstraksi berhasil
📊 Total Sleep Periods: 3
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH BY SLEEP PERIOD - iOS 16
======================================================================
   🔎 Struktur sleep terdeteksi: Legacy IN BED / ASLEEP
✅ Ekstraksi berhasil
📊 Total Sleep Periods: 20
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH BY SLEEP PERIOD - iOS 17
======================================================================
   🔎 Struktur sleep terdeteksi: iOS 17 Sleep Stages
✅ Ekstraksi berhasil
📊 Total Sleep Periods: 4
📂 Source: healthdb_secure.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW WATCH BY SLEEP PERIOD
# ============================================================


for version, df_watch_sleep in watch_sleep_results.items():

    print()
    print("=" * 70)

    print(
        f"⌚ RAW WATCH BY SLEEP PERIOD - {version}"
    )

    print("=" * 70)


    display(
        df_watch_sleep.head(20)
    )


    print()

    print(
        f"📊 Total Sleep Periods: "
        f"{len(df_watch_sleep)}"
    )

======================================================================
⌚ RAW WATCH BY SLEEP PERIOD - iOS 13.3.1
======================================================================

Empty DataFrame
Columns: [start_date, end_date, data_type_id, device_name, total_duration, in_bed_duration, asleep_duration, in_bed_percent, asleep_percent, sleep_structure]
Index: []

📊 Total Sleep Periods: 0

======================================================================
⌚ RAW WATCH BY SLEEP PERIOD - iOS 13.4.1
======================================================================

Empty DataFrame
Columns: [start_date, end_date, data_type_id, device_name, total_duration, in_bed_duration, asleep_duration, in_bed_percent, asleep_percent, sleep_structure]
Index: []

📊 Total Sleep Periods: 0

======================================================================
⌚ RAW WATCH BY SLEEP PERIOD - iOS 15
======================================================================

,start_date,end_date,data_type_id,device_name,total_duration,in_bed_duration,asleep_duration,in_bed_percent,asleep_percent,sleep_structure
0,6.310798e+08,6.325748e+08,63,"Watch4,3",7493.0,0,7493.0,0.0,100.0,In Bed / Asleep
1,6.327222e+08,6.327466e+08,63,"Watch4,3",400.5,0,400.5,0.0,100.0,In Bed / Asleep
2,6.328078e+08,6.346475e+08,63,"Watch4,3",9384.0,0,9384.0,0.0,100.0,In Bed / Asleep

📊 Total Sleep Periods: 3

======================================================================
⌚ RAW WATCH BY SLEEP PERIOD - iOS 16
======================================================================

,start_date,end_date,data_type_id,device_name,total_duration,in_bed_duration,asleep_duration,in_bed_percent,asleep_percent,sleep_structure
0,6.310798e+08,6.325748e+08,63,"Watch4,3",7493.0,0,7493.0,0.0,100.0,In Bed / Asleep
1,6.327222e+08,6.327466e+08,63,"Watch4,3",400.5,0,400.5,0.0,100.0,In Bed / Asleep
2,6.328078e+08,6.346475e+08,63,"Watch4,3",9384.0,0,9384.0,0.0,100.0,In Bed / Asleep
3,7.104786e+08,7.105042e+08,63,"Watch4,3",426.0,0,426.0,0.0,100.0,In Bed / Asleep
4,7.105638e+08,7.105923e+08,63,"Watch4,3",472.0,0,472.0,0.0,100.0,In Bed / Asleep
5,7.106509e+08,7.106782e+08,63,"Watch4,3",452.5,0,452.5,0.0,100.0,In Bed / Asleep
6,7.107365e+08,7.107621e+08,63,"Watch4,3",426.0,0,426.0,0.0,100.0,In Bed / Asleep
7,7.108237e+08,7.108514e+08,63,"Watch4,3",461.0,0,461.0,0.0,100.0,In Bed / Asleep
8,7.109096e+08,7.109360e+08,63,"Watch4,3",440.5,0,440.5,0.0,100.0,In Bed / Asleep
9,7.110002e+08,7.110262e+08,63,"Watch4,3",394.5,0,394.5,0.0,100.0,In Bed / Asleep
10,7.110875e+08,7.111097e+08,63,"Watch4,3",365.5,0,365.5,0.0,100.0,In Bed / Asleep
11,7.111736e+08,7.111968e+08,63,"Watch4,3",384.0,0,384.0,0.0,100.0,In Bed / Asleep
12,7.112569e+08,7.112872e+08,63,"Watch4,3",494.0,0,494.0,0.0,100.0,In Bed / Asleep
13,7.113450e+08,7.113700e+08,63,"Watch4,3",413.0,0,413.0,0.0,100.0,In Bed / Asleep
14,7.114311e+08,7.114557e+08,63,"Watch4,3",409.5,0,409.5,0.0,100.0,In Bed / Asleep
15,7.115173e+08,7.115410e+08,63,"Watch4,3",385.5,0,385.5,0.0,100.0,In Bed / Asleep
16,7.116016e+08,7.116288e+08,63,"Watch4,3",452.0,0,452.0,0.0,100.0,In Bed / Asleep
17,7.116894e+08,7.117151e+08,63,"Watch4,3",418.0,0,418.0,0.0,100.0,In Bed / Asleep
18,7.117729e+08,7.118063e+08,63,"Watch4,3",539.0,0,539.0,0.0,100.0,In Bed / Asleep
19,7.118613e+08,7.118888e+08,63,"Watch4,3",457.0,0,457.0,0.0,100.0,In Bed / Asleep

📊 Total Sleep Periods: 20

======================================================================
⌚ RAW WATCH BY SLEEP PERIOD - iOS 17
======================================================================

,start_date,end_date,total_duration,awake_duration,rem_duration,core_duration,deep_duration,sleep_structure
0,7.433979e+08,7.434225e+08,410.0,1.0,106.5,214.0,88.5,Sleep Stages
1,7.434831e+08,7.435070e+08,398.0,0.5,112.0,228.0,57.5,Sleep Stages
2,7.435692e+08,7.435964e+08,453.0,10.0,125.0,257.5,60.5,Sleep Stages
3,7.436571e+08,7.436851e+08,466.5,3.0,100.5,312.0,51.0,Sleep Stages

📊 Total Sleep Periods: 4

In [ ]:
# ============================================================
# HELPER DURASI WATCH SLEEP
# ============================================================


def sleep_minutes_to_hms(
    minutes_value
):

    """
    Konversi menit menjadi HH:MM:SS.
    """

    try:

        if pd.isna(
            minutes_value
        ):

            return "00:00:00"


        total_seconds = int(
            float(minutes_value) * 60
        )


    except (
        TypeError,
        ValueError
    ):

        return "00:00:00"


    hours = (
        total_seconds // 3600
    )

    minutes = (
        total_seconds % 3600
    ) // 60

    seconds = (
        total_seconds % 60
    )


    return (
        f"{hours:02d}:"
        f"{minutes:02d}:"
        f"{seconds:02d}"
    )



def calculate_sleep_percent(
    part,
    total
):

    """
    Menghitung persentase sleep stage.
    """

    try:

        part_value = float(
            part
        )

        total_value = float(
            total
        )


        if total_value == 0:

            return 0.0


        return round(

            (
                part_value
                /
                total_value
            )
            * 100,

            2

        )


    except (
        TypeError,
        ValueError
    ):

        return 0.0


print(
    "✅ Helper durasi dan persentase siap."
)

✅ Helper durasi dan persentase siap.

In [ ]:
# ============================================================
# TAHAP 79 - FORMAT LAPORAN WATCH BY SLEEP PERIOD
# ============================================================


watch_sleep_reports = {}


for version, df_sleep in watch_sleep_results.items():

    df_report = pd.DataFrame()


    major_version = get_ios_major_version(
        version
    )


    # ========================================================
    # COMMON FIELDS
    # ========================================================

    df_report[
        "Start Timestamp"
    ] = (

        df_sleep[
            "start_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    df_report[
        "End Timestamp"
    ] = (

        df_sleep[
            "end_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    df_report[
        "Sleep Structure"
    ] = (

        df_sleep[
            "sleep_structure"
        ]

    )


    # ========================================================
    # TIME IN BED
    # ========================================================

    df_report[
        "Time in Bed (Minutes)"
    ] = (

        pd.to_numeric(
            df_sleep[
                "total_duration"
            ],
            errors="coerce"
        )

    )


    df_report[
        "Time in Bed (HH:MM:SS)"
    ] = (

        df_sleep[
            "total_duration"
        ]
        .apply(
            sleep_minutes_to_hms
        )

    )


    # ========================================================
    # IOS 17
    # ========================================================

    if major_version == 17:

        # ====================================================
        # TIME ASLEEP
        # REM + CORE + DEEP
        # ====================================================

        rem_minutes = pd.to_numeric(
            df_sleep[
                "rem_duration"
            ],
            errors="coerce"
        ).fillna(0)


        core_minutes = pd.to_numeric(
            df_sleep[
                "core_duration"
            ],
            errors="coerce"
        ).fillna(0)


        deep_minutes = pd.to_numeric(
            df_sleep[
                "deep_duration"
            ],
            errors="coerce"
        ).fillna(0)


        time_asleep_minutes = (

            rem_minutes
            +
            core_minutes
            +
            deep_minutes

        )


        df_report[
            "Time Asleep (Minutes)"
        ] = time_asleep_minutes


        df_report[
            "Time Asleep (HH:MM:SS)"
        ] = (

            time_asleep_minutes
            .apply(
                sleep_minutes_to_hms
            )

        )


        # ====================================================
        # TOTAL
        # ====================================================

        total = pd.to_numeric(
            df_sleep[
                "total_duration"
            ],
            errors="coerce"
        )


        # ====================================================
        # AWAKE
        # ====================================================

        df_report[
            "Awake Duration (Minutes)"
        ] = pd.to_numeric(
            df_sleep[
                "awake_duration"
            ],
            errors="coerce"
        )


        df_report[
            "Awake Duration (HH:MM:SS)"
        ] = (

            df_sleep[
                "awake_duration"
            ]
            .apply(
                sleep_minutes_to_hms
            )

        )


        df_report[
            "Awake Percent"
        ] = [

            calculate_sleep_percent(
                part,
                total_value
            )

            for part, total_value in zip(

                df_sleep[
                    "awake_duration"
                ],

                total

            )

        ]


        # ====================================================
        # REM
        # ====================================================

        df_report[
            "REM Duration (Minutes)"
        ] = rem_minutes


        df_report[
            "REM Duration (HH:MM:SS)"
        ] = (

            rem_minutes
            .apply(
                sleep_minutes_to_hms
            )

        )


        df_report[
            "REM Percent"
        ] = [

            calculate_sleep_percent(
                part,
                total_value
            )

            for part, total_value in zip(

                rem_minutes,

                total

            )

        ]


        # ====================================================
        # CORE
        # ====================================================

        df_report[
            "Core Duration (Minutes)"
        ] = core_minutes


        df_report[
            "Core Duration (HH:MM:SS)"
        ] = (

            core_minutes
            .apply(
                sleep_minutes_to_hms
            )

        )


        df_report[
            "Core Percent"
        ] = [

            calculate_sleep_percent(
                part,
                total_value
            )

            for part, total_value in zip(

                core_minutes,

                total

            )

        ]


        # ====================================================
        # DEEP
        # ====================================================

        df_report[
            "Deep Duration (Minutes)"
        ] = deep_minutes


        df_report[
            "Deep Duration (HH:MM:SS)"
        ] = (

            deep_minutes
            .apply(
                sleep_minutes_to_hms
            )

        )


        df_report[
            "Deep Percent"
        ] = [

            calculate_sleep_percent(
                part,
                total_value
            )

            for part, total_value in zip(

                deep_minutes,

                total

            )

        ]


        # ====================================================
        # LEGACY FIELDS
        # ====================================================

        df_report[
            "Data Type ID"
        ] = None


        df_report[
            "Device"
        ] = None


        df_report[
            "In Bed Duration (Minutes)"
        ] = None


        df_report[
            "In Bed Duration (HH:MM:SS)"
        ] = None


        df_report[
            "In Bed Percent"
        ] = None


        df_report[
            "Asleep Percent"
        ] = (

            [

                calculate_sleep_percent(
                    asleep,
                    total_value
                )

                for asleep, total_value in zip(

                    time_asleep_minutes,

                    total

                )

            ]

        )


    # ========================================================
    # IOS SEBELUM 17
    # ========================================================

    else:

        # ====================================================
        # TIME ASLEEP
        # ====================================================

        asleep_minutes = pd.to_numeric(
            df_sleep[
                "asleep_duration"
            ],
            errors="coerce"
        )


        df_report[
            "Time Asleep (Minutes)"
        ] = asleep_minutes


        df_report[
            "Time Asleep (HH:MM:SS)"
        ] = (

            asleep_minutes
            .apply(
                sleep_minutes_to_hms
            )

        )


        # ====================================================
        # DATA TYPE
        # ====================================================

        df_report[
            "Data Type ID"
        ] = (

            df_sleep[
                "data_type_id"
            ]

        )


        # ====================================================
        # DEVICE
        # ====================================================

        df_report[
            "Device"
        ] = (

            df_sleep[
                "device_name"
            ]

        )


        # ====================================================
        # IN BED
        # ====================================================

        df_report[
            "In Bed Duration (Minutes)"
        ] = (

            pd.to_numeric(
                df_sleep[
                    "in_bed_duration"
                ],
                errors="coerce"
            )

        )


        df_report[
            "In Bed Duration (HH:MM:SS)"
        ] = (

            df_sleep[
                "in_bed_duration"
            ]
            .apply(
                sleep_minutes_to_hms
            )

        )


        df_report[
            "In Bed Percent"
        ] = (

            df_sleep[
                "in_bed_percent"
            ]

        )


        df_report[
            "Asleep Percent"
        ] = (

            df_sleep[
                "asleep_percent"
            ]

        )


        # ====================================================
        # IOS 17 STAGE FIELDS
        # ====================================================

        df_report[
            "Awake Duration (Minutes)"
        ] = None


        df_report[
            "Awake Duration (HH:MM:SS)"
        ] = None


        df_report[
            "Awake Percent"
        ] = None


        df_report[
            "REM Duration (Minutes)"
        ] = None


        df_report[
            "REM Duration (HH:MM:SS)"
        ] = None


        df_report[
            "REM Percent"
        ] = None


        df_report[
            "Core Duration (Minutes)"
        ] = None


        df_report[
            "Core Duration (HH:MM:SS)"
        ] = None


        df_report[
            "Core Percent"
        ] = None


        df_report[
            "Deep Duration (Minutes)"
        ] = None


        df_report[
            "Deep Duration (HH:MM:SS)"
        ] = None


        df_report[
            "Deep Percent"
        ] = None


    # ========================================================
    # SOURCE DATABASE
    # ========================================================

    df_report[
        "Source Database"
    ] = (
        "healthdb_secure.sqlite"
    )


    watch_sleep_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Watch By Sleep Period selesai."
)

✅ Format laporan Watch By Sleep Period selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT WATCH BY SLEEP PERIOD
# ============================================================


for version, df_report in watch_sleep_reports.items():

    print()
    print("=" * 70)

    print(
        f"⌚ WATCH BY SLEEP PERIOD REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Sleep Periods: "
        f"{len(df_report)}"
    )

======================================================================
⌚ WATCH BY SLEEP PERIOD REPORT - iOS 13.3.1
======================================================================

Empty DataFrame
Columns: [Start Timestamp, End Timestamp, Sleep Structure, Time in Bed (Minutes), Time in Bed (HH:MM:SS), Time Asleep (Minutes), Time Asleep (HH:MM:SS), Data Type ID, Device, In Bed Duration (Minutes), In Bed Duration (HH:MM:SS), In Bed Percent, Asleep Percent, Awake Duration (Minutes), Awake Duration (HH:MM:SS), Awake Percent, REM Duration (Minutes), REM Duration (HH:MM:SS), REM Percent, Core Duration (Minutes), Core Duration (HH:MM:SS), Core Percent, Deep Duration (Minutes), Deep Duration (HH:MM:SS), Deep Percent, Source Database]
Index: []

[0 rows x 26 columns]

📊 Total Sleep Periods: 0

======================================================================
⌚ WATCH BY SLEEP PERIOD REPORT - iOS 13.4.1
======================================================================

Empty DataFrame
Columns: [Start Timestamp, End Timestamp, Sleep Structure, Time in Bed (Minutes), Time in Bed (HH:MM:SS), Time Asleep (Minutes), Time Asleep (HH:MM:SS), Data Type ID, Device, In Bed Duration (Minutes), In Bed Duration (HH:MM:SS), In Bed Percent, Asleep Percent, Awake Duration (Minutes), Awake Duration (HH:MM:SS), Awake Percent, REM Duration (Minutes), REM Duration (HH:MM:SS), REM Percent, Core Duration (Minutes), Core Duration (HH:MM:SS), Core Percent, Deep Duration (Minutes), Deep Duration (HH:MM:SS), Deep Percent, Source Database]
Index: []

[0 rows x 26 columns]

📊 Total Sleep Periods: 0

======================================================================
⌚ WATCH BY SLEEP PERIOD REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Sleep Structure,Time in Bed (Minutes),Time in Bed (HH:MM:SS),Time Asleep (Minutes),Time Asleep (HH:MM:SS),Data Type ID,Device,In Bed Duration (Minutes),...,REM Duration (Minutes),REM Duration (HH:MM:SS),REM Percent,Core Duration (Minutes),Core Duration (HH:MM:SS),Core Percent,Deep Duration (Minutes),Deep Duration (HH:MM:SS),Deep Percent,Source Database
0,2020-12-31 03:56:28.330995+00:00,2021-01-17 11:13:30.990109+00:00,In Bed / Asleep,7493.0,124:53:00,7493.0,124:53:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
1,2021-01-19 04:10:12.410271+00:00,2021-01-19 10:56:12.410271+00:00,In Bed / Asleep,400.5,06:40:30,400.5,06:40:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
2,2021-01-20 03:57:29.274203+00:00,2021-02-10 10:58:44.779535+00:00,In Bed / Asleep,9384.0,156:24:00,9384.0,156:24:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite

📊 Total Sleep Periods: 3

======================================================================
⌚ WATCH BY SLEEP PERIOD REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Sleep Structure,Time in Bed (Minutes),Time in Bed (HH:MM:SS),Time Asleep (Minutes),Time Asleep (HH:MM:SS),Data Type ID,Device,In Bed Duration (Minutes),...,REM Duration (Minutes),REM Duration (HH:MM:SS),REM Percent,Core Duration (Minutes),Core Duration (HH:MM:SS),Core Percent,Deep Duration (Minutes),Deep Duration (HH:MM:SS),Deep Percent,Source Database
0,2020-12-31 03:56:28.330995+00:00,2021-01-17 11:13:30.990109+00:00,In Bed / Asleep,7493.0,124:53:00,7493.0,124:53:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
1,2021-01-19 04:10:12.410271+00:00,2021-01-19 10:56:12.410271+00:00,In Bed / Asleep,400.5,06:40:30,400.5,06:40:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
2,2021-01-20 03:57:29.274203+00:00,2021-02-10 10:58:44.779535+00:00,In Bed / Asleep,9384.0,156:24:00,9384.0,156:24:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
3,2023-07-08 03:09:57.812753+00:00,2023-07-08 10:15:57.812753+00:00,In Bed / Asleep,426.0,07:06:00,426.0,07:06:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
4,2023-07-09 02:49:56.037231+00:00,2023-07-09 10:45:26.037231+00:00,In Bed / Asleep,472.0,07:52:00,472.0,07:52:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
5,2023-07-10 03:02:25.130595+00:00,2023-07-10 10:35:55.130595+00:00,In Bed / Asleep,452.5,07:32:30,452.5,07:32:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
6,2023-07-11 02:48:15.502670+00:00,2023-07-11 09:54:15.502670+00:00,In Bed / Asleep,426.0,07:06:00,426.0,07:06:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
7,2023-07-12 03:02:06.250100+00:00,2023-07-12 10:43:06.250100+00:00,In Bed / Asleep,461.0,07:41:00,461.0,07:41:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
8,2023-07-13 02:53:00.086999+00:00,2023-07-13 10:13:30.086999+00:00,In Bed / Asleep,440.5,07:20:30,440.5,07:20:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
9,2023-07-14 04:03:26.327521+00:00,2023-07-14 11:15:56.327521+00:00,In Bed / Asleep,394.5,06:34:30,394.5,06:34:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
10,2023-07-15 04:18:39.769481+00:00,2023-07-15 10:28:09.769481+00:00,In Bed / Asleep,365.5,06:05:30,365.5,06:05:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
11,2023-07-16 04:12:54.495736+00:00,2023-07-16 10:40:24.495736+00:00,In Bed / Asleep,384.0,06:24:00,384.0,06:24:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
12,2023-07-17 03:22:26.961844+00:00,2023-07-17 11:45:56.961844+00:00,In Bed / Asleep,494.0,08:14:00,494.0,08:14:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
13,2023-07-18 03:49:23.325558+00:00,2023-07-18 10:45:53.325558+00:00,In Bed / Asleep,413.0,06:53:00,413.0,06:53:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
14,2023-07-19 03:45:14.540858+00:00,2023-07-19 10:34:44.540858+00:00,In Bed / Asleep,409.5,06:49:30,409.5,06:49:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
15,2023-07-20 03:42:20.506937+00:00,2023-07-20 10:16:20.506937+00:00,In Bed / Asleep,385.5,06:25:30,385.5,06:25:30,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
16,2023-07-21 03:07:28.385366+00:00,2023-07-21 10:40:28.385366+00:00,In Bed / Asleep,452.0,07:32:00,452.0,07:32:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
17,2023-07-22 03:30:19.021468+00:00,2023-07-22 10:37:49.021468+00:00,In Bed / Asleep,418.0,06:58:00,418.0,06:58:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
18,2023-07-23 02:42:02.811243+00:00,2023-07-23 11:58:32.811243+00:00,In Bed / Asleep,539.0,08:59:00,539.0,08:59:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite
19,2023-07-24 03:14:30.725418+00:00,2023-07-24 10:54:00.725418+00:00,In Bed / Asleep,457.0,07:37:00,457.0,07:37:00,63,"Watch4,3",0,...,None,None,None,None,None,None,None,None,None,healthdb_secure.sqlite

📊 Total Sleep Periods: 20

======================================================================
⌚ WATCH BY SLEEP PERIOD REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Sleep Structure,Time in Bed (Minutes),Time in Bed (HH:MM:SS),Time Asleep (Minutes),Time Asleep (HH:MM:SS),Awake Duration (Minutes),Awake Duration (HH:MM:SS),Awake Percent,...,Deep Duration (Minutes),Deep Duration (HH:MM:SS),Deep Percent,Data Type ID,Device,In Bed Duration (Minutes),In Bed Duration (HH:MM:SS),In Bed Percent,Asleep Percent,Source Database
0,2024-07-23 03:25:36.786188+00:00,2024-07-23 10:15:36.786188+00:00,Sleep Stages,410.0,06:50:00,409.0,06:49:00,1.0,00:01:00,0.24,...,88.5,01:28:30,21.59,None,None,None,None,None,99.76,healthdb_secure.sqlite
1,2024-07-24 03:05:22.638216+00:00,2024-07-24 09:43:22.638216+00:00,Sleep Stages,398.0,06:38:00,397.5,06:37:30,0.5,00:00:30,0.13,...,57.5,00:57:30,14.45,None,None,None,None,None,99.87,healthdb_secure.sqlite
2,2024-07-25 03:00:28.775252+00:00,2024-07-25 10:33:28.775252+00:00,Sleep Stages,453.0,07:33:00,443.0,07:23:00,10.0,00:10:00,2.21,...,60.5,01:00:30,13.36,None,None,None,None,None,97.79,healthdb_secure.sqlite
3,2024-07-26 03:25:26.715890+00:00,2024-07-26 11:11:56.715890+00:00,Sleep Stages,466.5,07:46:30,463.5,07:43:30,3.0,00:03:00,0.64,...,51.0,00:51:00,10.93,None,None,None,None,None,99.36,healthdb_secure.sqlite

📊 Total Sleep Periods: 4

# **Fitur Watch Worn Data**

In [ ]:
# ============================================================
# VERIFIKASI WATCH WORN DATA
# ============================================================

print()
print("=" * 70)
print("⌚ VERIFIKASI WATCH WORN DATA")
print("=" * 70)


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    print()
    print(
        f"📱 {version}"
    )


    if "samples" in secure_tables:

        print(
            "   📂 samples              : ✅ Ditemukan"
        )

    else:

        print(
            "   📂 samples              : ❌ Tidak ditemukan"
        )


print()
print("=" * 70)

======================================================================
⌚ VERIFIKASI WATCH WORN DATA
======================================================================

📱 iOS 13.3.1
   📂 samples              : ✅ Ditemukan

📱 iOS 13.4.1
   📂 samples              : ✅ Ditemukan

📱 iOS 15
   📂 samples              : ✅ Ditemukan

📱 iOS 16
   📂 samples              : ✅ Ditemukan

📱 iOS 17
   📂 samples              : ✅ Ditemukan

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR WATCH WORN DATA
# ============================================================


def extract_watch_worn(
    secure_database_path
):

    """
    Extract Apple Health Watch Worn Data.

    Database:
        healthdb_secure.sqlite

    Table:
        samples

    Health data_type:
        70

    Grouping:
        Gap > 3600 seconds creates a new worn period.
    """

    conn = open_sqlite_readonly(
        secure_database_path
    )


    query = """

    WITH TimeData AS (

        SELECT

            s.start_date AS start_cocoa,

            s.end_date AS end_cocoa,

            LAG(
                s.end_date
            ) OVER (
                ORDER BY s.start_date
            ) AS prev_end_cocoa

        FROM samples s

        WHERE
            s.data_type IN (70, '70')

    ),


    PeriodData AS (

        SELECT

            *,

            (
                start_cocoa
                -
                prev_end_cocoa
            ) AS gap_seconds,


            CASE

                WHEN (
                    start_cocoa
                    -
                    prev_end_cocoa
                ) > 3600

                THEN 1

                ELSE 0

            END AS new_period

        FROM TimeData

    ),


    PeriodGroup AS (

        SELECT

            *,

            SUM(
                new_period
            ) OVER (

                ORDER BY start_cocoa

                ROWS BETWEEN
                    UNBOUNDED PRECEDING
                    AND CURRENT ROW

            ) AS period_id

        FROM PeriodData

    ),


    Summary AS (

        SELECT

            period_id,


            MIN(
                start_cocoa
            ) AS period_start_cocoa,


            MAX(
                end_cocoa
            ) AS period_end_cocoa,


            CAST(

                (
                    MAX(end_cocoa)
                    -
                    MIN(start_cocoa)
                ) / 3600

                AS INT

            ) AS hours_worn


        FROM PeriodGroup


        GROUP BY
            period_id

    )


    SELECT

        s1.period_start_cocoa
            AS start_cocoa,


        s1.hours_worn
            AS hours_worn,


        s1.period_end_cocoa
            AS end_cocoa,


        CAST(

            (
                s2.period_start_cocoa
                -
                s1.period_end_cocoa
            ) / 3600

            AS INT

        ) AS hours_off_before_next


    FROM Summary s1


    LEFT JOIN Summary s2

        ON s1.period_id + 1 =
           s2.period_id


    ORDER BY
        s1.period_id

    """


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    return df


print(
    "✅ Extractor Watch Worn Data siap."
)

✅ Extractor Watch Worn Data siap.

In [ ]:
# ============================================================
# EKSTRAKSI WATCH WORN DATA
# ============================================================


watch_worn_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_db_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"⌚ WATCH WORN DATA - {version}"
    )

    print("=" * 70)


    try:

        df_watch_worn = extract_watch_worn(
            secure_db_path
        )


        watch_worn_results[
            version
        ] = df_watch_worn


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Worn Periods: "
            f"{len(df_watch_worn)}"
        )

        print(
            "📂 Source: "
            "healthdb_secure.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Error: {e}"
        )

======================================================================
⌚ WATCH WORN DATA - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Worn Periods: 15
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH WORN DATA - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Worn Periods: 19
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH WORN DATA - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Worn Periods: 37
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH WORN DATA - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Worn Periods: 48
📂 Source: healthdb_secure.sqlite

======================================================================
⌚ WATCH WORN DATA - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Worn Periods: 52
📂 Source: healthdb_secure.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW WATCH WORN DATA
# ============================================================


for version, df_watch_worn in watch_worn_results.items():

    print()
    print("=" * 70)

    print(
        f"⌚ RAW WATCH WORN DATA - {version}"
    )

    print("=" * 70)


    display(
        df_watch_worn.head(20)
    )


    print()

    print(
        f"📊 Total Worn Periods: "
        f"{len(df_watch_worn)}"
    )

======================================================================
⌚ RAW WATCH WORN DATA - iOS 13.3.1
======================================================================

    start_cocoa  hours_worn    end_cocoa  hours_off_before_next
0   606528000.0           3  606538800.0                    8.0
1   606567600.0          16  606625200.0                    7.0
2   606650400.0          17  606711600.0                    7.0
3   606736800.0          17  606798000.0                    7.0
4   606823200.0          16  606880800.0                    8.0
5   606909600.0          17  606970800.0                    7.0
6   606996000.0          15  607050000.0                    9.0
7   607082400.0          16  607140000.0                    8.0
8   607168800.0          16  607226400.0                    8.0
9   607255200.0          17  607316400.0                    7.0
10  607341600.0          17  607402800.0                    8.0
11  607431600.0          15  607485600.0                    8.0
12  607514400.0          15  607568400.0                    9.0
13  607600800.0          11  607640400.0                  209.0
14  608392800.0           5  608410800.0                    NaN

📊 Total Worn Periods: 15

======================================================================
⌚ RAW WATCH WORN DATA - iOS 13.4.1
======================================================================

    start_cocoa  hours_worn    end_cocoa  hours_off_before_next
0   606528000.0           3  606538800.0                    8.0
1   606567600.0          16  606625200.0                    7.0
2   606650400.0          17  606711600.0                    7.0
3   606736800.0          17  606798000.0                    7.0
4   606823200.0          16  606880800.0                    8.0
5   606909600.0          17  606970800.0                    7.0
6   606996000.0          15  607050000.0                    9.0
7   607082400.0          16  607140000.0                    8.0
8   607168800.0          16  607226400.0                    8.0
9   607255200.0          17  607316400.0                    7.0
10  607341600.0          17  607402800.0                    8.0
11  607431600.0          15  607485600.0                    8.0
12  607514400.0          15  607568400.0                    9.0
13  607600800.0          11  607640400.0                  209.0
14  608392800.0           6  608414400.0                   14.0
15  608464800.0          15  608518800.0                    9.0
16  608551200.0          16  608608800.0                    8.0
17  608637600.0          15  608691600.0                    9.0
18  608724000.0           6  608745600.0                    NaN

📊 Total Worn Periods: 19

======================================================================
⌚ RAW WATCH WORN DATA - iOS 15
======================================================================

    start_cocoa  hours_worn    end_cocoa  hours_off_before_next
0   606528000.0           3  606538800.0                    8.0
1   606567600.0          16  606625200.0                    7.0
2   606650400.0          17  606711600.0                    7.0
3   606736800.0          17  606798000.0                    7.0
4   606823200.0          16  606880800.0                    8.0
5   606909600.0          17  606970800.0                    7.0
6   606996000.0          15  607050000.0                    9.0
7   607082400.0          16  607140000.0                    8.0
8   607168800.0          16  607226400.0                    8.0
9   607255200.0          17  607316400.0                    7.0
10  607341600.0          17  607402800.0                    8.0
11  607431600.0          15  607485600.0                    8.0
12  607514400.0          15  607568400.0                    9.0
13  607600800.0          11  607640400.0                  209.0
14  608392800.0           6  608414400.0                   14.0
15  608464800.0          15  608518800.0                    9.0
16  608551200.0          16  608608800.0                    8.0
17  608637600.0          15  608691600.0                    9.0
18  608724000.0          13  608770800.0                 6187.0
19  631044000.0          31  631155600.0                    2.0

📊 Total Worn Periods: 37

======================================================================
⌚ RAW WATCH WORN DATA - iOS 16
======================================================================

    start_cocoa  hours_worn    end_cocoa  hours_off_before_next
0   606528000.0           3  606538800.0                    8.0
1   606567600.0          16  606625200.0                    7.0
2   606650400.0          17  606711600.0                    7.0
3   606736800.0          17  606798000.0                    7.0
4   606823200.0          16  606880800.0                    8.0
5   606909600.0          17  606970800.0                    7.0
6   606996000.0          15  607050000.0                    9.0
7   607082400.0          16  607140000.0                    8.0
8   607168800.0          16  607226400.0                    8.0
9   607255200.0          17  607316400.0                    7.0
10  607341600.0          17  607402800.0                    8.0
11  607431600.0          15  607485600.0                    8.0
12  607514400.0          15  607568400.0                    9.0
13  607600800.0          11  607640400.0                  209.0
14  608392800.0           6  608414400.0                   14.0
15  608464800.0          15  608518800.0                    9.0
16  608551200.0          16  608608800.0                    8.0
17  608637600.0          15  608691600.0                    9.0
18  608724000.0          13  608770800.0                 6187.0
19  631044000.0          31  631155600.0                    2.0

📊 Total Worn Periods: 48

======================================================================
⌚ RAW WATCH WORN DATA - iOS 17
======================================================================

    start_cocoa  hours_worn    end_cocoa  hours_off_before_next
0   606528000.0           3  606538800.0                    8.0
1   606567600.0          16  606625200.0                    7.0
2   606650400.0          17  606711600.0                    7.0
3   606736800.0          17  606798000.0                    7.0
4   606823200.0          16  606880800.0                    8.0
5   606909600.0          17  606970800.0                    7.0
6   606996000.0          15  607050000.0                    9.0
7   607082400.0          16  607140000.0                    8.0
8   607168800.0          16  607226400.0                    8.0
9   607255200.0          17  607316400.0                    7.0
10  607341600.0          17  607402800.0                    8.0
11  607431600.0          15  607485600.0                    8.0
12  607514400.0          15  607568400.0                    9.0
13  607600800.0          11  607640400.0                  209.0
14  608392800.0           6  608414400.0                   14.0
15  608464800.0          15  608518800.0                    9.0
16  608551200.0          16  608608800.0                    8.0
17  608637600.0          15  608691600.0                    9.0
18  608724000.0          13  608770800.0                 6187.0
19  631044000.0          31  631155600.0                    2.0

📊 Total Worn Periods: 52

In [ ]:
# ============================================================
# FORMAT LAPORAN WATCH WORN DATA
# ============================================================


watch_worn_reports = {}


for version, df_watch_worn in watch_worn_results.items():

    df_report = pd.DataFrame()


    # ========================================================
    # START TIME
    # ========================================================

    df_report[
        "Start Time"
    ] = (

        df_watch_worn[
            "start_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    # ========================================================
    # LAST WORN TIME
    # ========================================================

    df_report[
        "Last Worn Time"
    ] = (

        df_watch_worn[
            "end_cocoa"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    # ========================================================
    # HOURS WORN
    # ========================================================

    df_report[
        "Hours Worn"
    ] = (

        pd.to_numeric(
            df_watch_worn[
                "hours_worn"
            ],
            errors="coerce"
        )

    )


    # ========================================================
    # HOURS OFF BEFORE NEXT
    # ========================================================

    df_report[
        "Hours Off Before Next"
    ] = (

        pd.to_numeric(
            df_watch_worn[
                "hours_off_before_next"
            ],
            errors="coerce"
        )

    )


    # ========================================================
    # SOURCE DATABASE
    # ========================================================

    df_report[
        "Source Database"
    ] = (
        "healthdb_secure.sqlite"
    )


    watch_worn_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Watch Worn Data selesai."
)

✅ Format laporan Watch Worn Data selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT WATCH WORN DATA
# ============================================================


for version, df_report in watch_worn_reports.items():

    print()
    print("=" * 70)

    print(
        f"⌚ WATCH WORN DATA REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Worn Periods: "
        f"{len(df_report)}"
    )

======================================================================
⌚ WATCH WORN DATA REPORT - iOS 13.3.1
======================================================================

,Start Time,Last Worn Time,Hours Worn,Hours Off Before Next,Source Database
0,2020-03-22 00:00:00+00:00,2020-03-22 03:00:00+00:00,3,8.0,healthdb_secure.sqlite
1,2020-03-22 11:00:00+00:00,2020-03-23 03:00:00+00:00,16,7.0,healthdb_secure.sqlite
2,2020-03-23 10:00:00+00:00,2020-03-24 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
3,2020-03-24 10:00:00+00:00,2020-03-25 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
4,2020-03-25 10:00:00+00:00,2020-03-26 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
5,2020-03-26 10:00:00+00:00,2020-03-27 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
6,2020-03-27 10:00:00+00:00,2020-03-28 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
7,2020-03-28 10:00:00+00:00,2020-03-29 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
8,2020-03-29 10:00:00+00:00,2020-03-30 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
9,2020-03-30 10:00:00+00:00,2020-03-31 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
10,2020-03-31 10:00:00+00:00,2020-04-01 03:00:00+00:00,17,8.0,healthdb_secure.sqlite
11,2020-04-01 11:00:00+00:00,2020-04-02 02:00:00+00:00,15,8.0,healthdb_secure.sqlite
12,2020-04-02 10:00:00+00:00,2020-04-03 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
13,2020-04-03 10:00:00+00:00,2020-04-03 21:00:00+00:00,11,209.0,healthdb_secure.sqlite
14,2020-04-12 14:00:00+00:00,2020-04-12 19:00:00+00:00,5,NaN,healthdb_secure.sqlite

📊 Total Worn Periods: 15

======================================================================
⌚ WATCH WORN DATA REPORT - iOS 13.4.1
======================================================================

,Start Time,Last Worn Time,Hours Worn,Hours Off Before Next,Source Database
0,2020-03-22 00:00:00+00:00,2020-03-22 03:00:00+00:00,3,8.0,healthdb_secure.sqlite
1,2020-03-22 11:00:00+00:00,2020-03-23 03:00:00+00:00,16,7.0,healthdb_secure.sqlite
2,2020-03-23 10:00:00+00:00,2020-03-24 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
3,2020-03-24 10:00:00+00:00,2020-03-25 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
4,2020-03-25 10:00:00+00:00,2020-03-26 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
5,2020-03-26 10:00:00+00:00,2020-03-27 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
6,2020-03-27 10:00:00+00:00,2020-03-28 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
7,2020-03-28 10:00:00+00:00,2020-03-29 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
8,2020-03-29 10:00:00+00:00,2020-03-30 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
9,2020-03-30 10:00:00+00:00,2020-03-31 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
10,2020-03-31 10:00:00+00:00,2020-04-01 03:00:00+00:00,17,8.0,healthdb_secure.sqlite
11,2020-04-01 11:00:00+00:00,2020-04-02 02:00:00+00:00,15,8.0,healthdb_secure.sqlite
12,2020-04-02 10:00:00+00:00,2020-04-03 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
13,2020-04-03 10:00:00+00:00,2020-04-03 21:00:00+00:00,11,209.0,healthdb_secure.sqlite
14,2020-04-12 14:00:00+00:00,2020-04-12 20:00:00+00:00,6,14.0,healthdb_secure.sqlite
15,2020-04-13 10:00:00+00:00,2020-04-14 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
16,2020-04-14 10:00:00+00:00,2020-04-15 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
17,2020-04-15 10:00:00+00:00,2020-04-16 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
18,2020-04-16 10:00:00+00:00,2020-04-16 16:00:00+00:00,6,NaN,healthdb_secure.sqlite

📊 Total Worn Periods: 19

======================================================================
⌚ WATCH WORN DATA REPORT - iOS 15
======================================================================

,Start Time,Last Worn Time,Hours Worn,Hours Off Before Next,Source Database
0,2020-03-22 00:00:00+00:00,2020-03-22 03:00:00+00:00,3,8.0,healthdb_secure.sqlite
1,2020-03-22 11:00:00+00:00,2020-03-23 03:00:00+00:00,16,7.0,healthdb_secure.sqlite
2,2020-03-23 10:00:00+00:00,2020-03-24 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
3,2020-03-24 10:00:00+00:00,2020-03-25 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
4,2020-03-25 10:00:00+00:00,2020-03-26 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
5,2020-03-26 10:00:00+00:00,2020-03-27 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
6,2020-03-27 10:00:00+00:00,2020-03-28 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
7,2020-03-28 10:00:00+00:00,2020-03-29 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
8,2020-03-29 10:00:00+00:00,2020-03-30 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
9,2020-03-30 10:00:00+00:00,2020-03-31 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
10,2020-03-31 10:00:00+00:00,2020-04-01 03:00:00+00:00,17,8.0,healthdb_secure.sqlite
11,2020-04-01 11:00:00+00:00,2020-04-02 02:00:00+00:00,15,8.0,healthdb_secure.sqlite
12,2020-04-02 10:00:00+00:00,2020-04-03 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
13,2020-04-03 10:00:00+00:00,2020-04-03 21:00:00+00:00,11,209.0,healthdb_secure.sqlite
14,2020-04-12 14:00:00+00:00,2020-04-12 20:00:00+00:00,6,14.0,healthdb_secure.sqlite
15,2020-04-13 10:00:00+00:00,2020-04-14 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
16,2020-04-14 10:00:00+00:00,2020-04-15 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
17,2020-04-15 10:00:00+00:00,2020-04-16 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
18,2020-04-16 10:00:00+00:00,2020-04-16 23:00:00+00:00,13,6187.0,healthdb_secure.sqlite
19,2020-12-30 18:00:00+00:00,2021-01-01 01:00:00+00:00,31,2.0,healthdb_secure.sqlite

📊 Total Worn Periods: 37

======================================================================
⌚ WATCH WORN DATA REPORT - iOS 16
======================================================================

,Start Time,Last Worn Time,Hours Worn,Hours Off Before Next,Source Database
0,2020-03-22 00:00:00+00:00,2020-03-22 03:00:00+00:00,3,8.0,healthdb_secure.sqlite
1,2020-03-22 11:00:00+00:00,2020-03-23 03:00:00+00:00,16,7.0,healthdb_secure.sqlite
2,2020-03-23 10:00:00+00:00,2020-03-24 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
3,2020-03-24 10:00:00+00:00,2020-03-25 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
4,2020-03-25 10:00:00+00:00,2020-03-26 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
5,2020-03-26 10:00:00+00:00,2020-03-27 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
6,2020-03-27 10:00:00+00:00,2020-03-28 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
7,2020-03-28 10:00:00+00:00,2020-03-29 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
8,2020-03-29 10:00:00+00:00,2020-03-30 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
9,2020-03-30 10:00:00+00:00,2020-03-31 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
10,2020-03-31 10:00:00+00:00,2020-04-01 03:00:00+00:00,17,8.0,healthdb_secure.sqlite
11,2020-04-01 11:00:00+00:00,2020-04-02 02:00:00+00:00,15,8.0,healthdb_secure.sqlite
12,2020-04-02 10:00:00+00:00,2020-04-03 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
13,2020-04-03 10:00:00+00:00,2020-04-03 21:00:00+00:00,11,209.0,healthdb_secure.sqlite
14,2020-04-12 14:00:00+00:00,2020-04-12 20:00:00+00:00,6,14.0,healthdb_secure.sqlite
15,2020-04-13 10:00:00+00:00,2020-04-14 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
16,2020-04-14 10:00:00+00:00,2020-04-15 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
17,2020-04-15 10:00:00+00:00,2020-04-16 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
18,2020-04-16 10:00:00+00:00,2020-04-16 23:00:00+00:00,13,6187.0,healthdb_secure.sqlite
19,2020-12-30 18:00:00+00:00,2021-01-01 01:00:00+00:00,31,2.0,healthdb_secure.sqlite

📊 Total Worn Periods: 48

======================================================================
⌚ WATCH WORN DATA REPORT - iOS 17
======================================================================

,Start Time,Last Worn Time,Hours Worn,Hours Off Before Next,Source Database
0,2020-03-22 00:00:00+00:00,2020-03-22 03:00:00+00:00,3,8.0,healthdb_secure.sqlite
1,2020-03-22 11:00:00+00:00,2020-03-23 03:00:00+00:00,16,7.0,healthdb_secure.sqlite
2,2020-03-23 10:00:00+00:00,2020-03-24 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
3,2020-03-24 10:00:00+00:00,2020-03-25 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
4,2020-03-25 10:00:00+00:00,2020-03-26 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
5,2020-03-26 10:00:00+00:00,2020-03-27 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
6,2020-03-27 10:00:00+00:00,2020-03-28 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
7,2020-03-28 10:00:00+00:00,2020-03-29 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
8,2020-03-29 10:00:00+00:00,2020-03-30 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
9,2020-03-30 10:00:00+00:00,2020-03-31 03:00:00+00:00,17,7.0,healthdb_secure.sqlite
10,2020-03-31 10:00:00+00:00,2020-04-01 03:00:00+00:00,17,8.0,healthdb_secure.sqlite
11,2020-04-01 11:00:00+00:00,2020-04-02 02:00:00+00:00,15,8.0,healthdb_secure.sqlite
12,2020-04-02 10:00:00+00:00,2020-04-03 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
13,2020-04-03 10:00:00+00:00,2020-04-03 21:00:00+00:00,11,209.0,healthdb_secure.sqlite
14,2020-04-12 14:00:00+00:00,2020-04-12 20:00:00+00:00,6,14.0,healthdb_secure.sqlite
15,2020-04-13 10:00:00+00:00,2020-04-14 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
16,2020-04-14 10:00:00+00:00,2020-04-15 02:00:00+00:00,16,8.0,healthdb_secure.sqlite
17,2020-04-15 10:00:00+00:00,2020-04-16 01:00:00+00:00,15,9.0,healthdb_secure.sqlite
18,2020-04-16 10:00:00+00:00,2020-04-16 23:00:00+00:00,13,6187.0,healthdb_secure.sqlite
19,2020-12-30 18:00:00+00:00,2021-01-01 01:00:00+00:00,31,2.0,healthdb_secure.sqlite

📊 Total Worn Periods: 52

# **Fitur Weight**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR WEIGHT
# ============================================================

print()
print("=" * 70)
print("⚖️ VERIFIKASI WEIGHT")
print("=" * 70)


weight_required_tables = [
    "samples",
    "quantity_samples"
]


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]


    print()
    print(
        f"📱 {version}"
    )


    for table_name in weight_required_tables:

        if table_name in secure_tables:

            print(
                f"   📂 {table_name:<20}: ✅ Ditemukan"
            )

        else:

            print(
                f"   📂 {table_name:<20}: ❌ Tidak ditemukan"
            )


print()
print("=" * 70)

======================================================================
⚖️ VERIFIKASI WEIGHT
======================================================================

📱 iOS 13.3.1
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan

📱 iOS 13.4.1
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan

📱 iOS 15
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan

📱 iOS 16
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan

📱 iOS 17
   📂 samples             : ✅ Ditemukan
   📂 quantity_samples    : ✅ Ditemukan

======================================================================

In [ ]:
# ============================================================
# EXTRACTOR WEIGHT
# ============================================================


def extract_weight(
    secure_database_path
):

    """
    Extract Apple Health Weight data.

    Database:
        healthdb_secure.sqlite

    Tables:
        samples
        quantity_samples

    Health data_type:
        3 = Weight

    Output:
        start_date
        weight_kg_str
        stone_int
        pounds_int
        weight_lbs_str
    """

    conn = open_sqlite_readonly(
        secure_database_path
    )


    query = """

    SELECT

        t.start_date
            AS start_date,

        t.kg_str
            AS weight_kg_str,

        t.stone_int
            AS stone_int,

        t.pounds_int
            AS pounds_int,

        t.lbs_str
            AS weight_lbs_str


    FROM (

        SELECT

            s.start_date
                AS start_date,


            substr(
                qs.quantity,
                1,
                5
            ) AS kg_str,


            CAST(
                qs.quantity / 6.35029317
                AS INT
            ) AS stone_int,


            CAST(

                (
                    (
                        (
                            qs.quantity / 6.35029317
                        )
                        -
                        CAST(
                            qs.quantity / 6.35029317
                            AS INT
                        )
                    )
                    * 14
                )
                + 0.5

                AS INT

            ) AS pounds_int,


            substr(
                qs.quantity * 2.20462262,
                1,
                6
            ) AS lbs_str


        FROM samples s


        JOIN quantity_samples qs

            ON s.data_id =
               qs.data_id


        WHERE

            s.data_type IN (3, '3')

            AND qs.quantity IS NOT NULL

    ) t


    ORDER BY
        t.start_date DESC

    """


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    return df


print(
    "✅ Extractor Weight siap."
)

✅ Extractor Weight siap.

In [ ]:
# ============================================================
# EKSTRAKSI WEIGHT
# ============================================================


weight_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_db_path = dataset[
        "healthdb_secure"
    ]


    print()
    print("=" * 70)

    print(
        f"⚖️ WEIGHT - {version}"
    )

    print("=" * 70)


    try:

        df_weight = extract_weight(
            secure_db_path
        )


        weight_results[
            version
        ] = df_weight


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Weight Records: "
            f"{len(df_weight)}"
        )

        print(
            "📂 Source: "
            "healthdb_secure.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Error: {e}"
        )

======================================================================
⚖️ WEIGHT - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Weight Records: 1105
📂 Source: healthdb_secure.sqlite

======================================================================
⚖️ WEIGHT - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Weight Records: 1109
📂 Source: healthdb_secure.sqlite

======================================================================
⚖️ WEIGHT - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Weight Records: 1113
📂 Source: healthdb_secure.sqlite

======================================================================
⚖️ WEIGHT - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Weight Records: 1113
📂 Source: healthdb_secure.sqlite

======================================================================
⚖️ WEIGHT - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Weight Records: 1113
📂 Source: healthdb_secure.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW WEIGHT
# ============================================================


for version, df_weight in weight_results.items():

    print()
    print("=" * 70)

    print(
        f"⚖️ RAW WEIGHT - {version}"
    )

    print("=" * 70)


    display(
        df_weight.head(20)
    )


    print()

    print(
        f"📊 Total Weight Records: "
        f"{len(df_weight)}"
    )

======================================================================
⚖️ RAW WEIGHT - iOS 13.3.1
======================================================================

      start_date weight_kg_str  stone_int  pounds_int weight_lbs_str
0   6.083568e+08         81.64         12          12         180.00
1   6.082704e+08         81.64         12          12         180.00
2   6.081840e+08         81.64         12          12         180.00
3   6.080976e+08         81.64         12          12         180.00
4   6.080112e+08         81.64         12          12         180.00
5   6.079248e+08         81.64         12          12         180.00
6   6.078384e+08         81.64         12          12         180.00
7   6.077520e+08         81.64         12          12         180.00
8   6.076656e+08         81.64         12          12         180.00
9   6.076310e+08         81.64         12          12         179.99
10  6.075792e+08         81.64         12          12         180.00
11  6.074928e+08         81.64         12          12         180.00
12  6.074064e+08         81.64         12          12         180.00
13  6.073200e+08         81.64         12          12         180.00
14  6.072336e+08         81.64         12          12         180.00
15  6.071472e+08         81.64         12          12         180.00
16  6.070608e+08         81.64         12          12         180.00
17  6.069744e+08         81.64         12          12         180.00
18  6.068880e+08         81.64         12          12         180.00
19  6.068016e+08         81.64         12          12         180.00

📊 Total Weight Records: 1105

======================================================================
⚖️ RAW WEIGHT - iOS 13.4.1
======================================================================

      start_date weight_kg_str  stone_int  pounds_int weight_lbs_str
0   6.087024e+08         81.64         12          12         180.00
1   6.086160e+08         81.64         12          12         180.00
2   6.085296e+08         81.64         12          12         180.00
3   6.084432e+08         81.64         12          12         180.00
4   6.083568e+08         81.64         12          12         180.00
5   6.082704e+08         81.64         12          12         180.00
6   6.081840e+08         81.64         12          12         180.00
7   6.080976e+08         81.64         12          12         180.00
8   6.080112e+08         81.64         12          12         180.00
9   6.079248e+08         81.64         12          12         180.00
10  6.078384e+08         81.64         12          12         180.00
11  6.077520e+08         81.64         12          12         180.00
12  6.076656e+08         81.64         12          12         180.00
13  6.076310e+08         81.64         12          12         179.99
14  6.075792e+08         81.64         12          12         180.00
15  6.074928e+08         81.64         12          12         180.00
16  6.074064e+08         81.64         12          12         180.00
17  6.073200e+08         81.64         12          12         180.00
18  6.072336e+08         81.64         12          12         180.00
19  6.071472e+08         81.64         12          12         180.00

📊 Total Weight Records: 1109

======================================================================
⚖️ RAW WEIGHT - iOS 15
======================================================================

      start_date weight_kg_str  stone_int  pounds_int weight_lbs_str
0   6.327215e+08         78.01         12           4         171.99
1   6.089616e+08         81.64         12          12         180.00
2   6.088752e+08         81.64         12          12         180.00
3   6.087888e+08         81.64         12          12         180.00
4   6.087024e+08         81.64         12          12         180.00
5   6.086160e+08         81.64         12          12         180.00
6   6.085296e+08         81.64         12          12         180.00
7   6.084432e+08         81.64         12          12         180.00
8   6.083568e+08         81.64         12          12         180.00
9   6.082704e+08         81.64         12          12         180.00
10  6.081840e+08         81.64         12          12         180.00
11  6.080976e+08         81.64         12          12         180.00
12  6.080112e+08         81.64         12          12         180.00
13  6.079248e+08         81.64         12          12         180.00
14  6.078384e+08         81.64         12          12         180.00
15  6.077520e+08         81.64         12          12         180.00
16  6.076656e+08         81.64         12          12         180.00
17  6.076310e+08         81.64         12          12         179.99
18  6.075792e+08         81.64         12          12         180.00
19  6.074928e+08         81.64         12          12         180.00

📊 Total Weight Records: 1113

======================================================================
⚖️ RAW WEIGHT - iOS 16
======================================================================

      start_date weight_kg_str  stone_int  pounds_int weight_lbs_str
0   6.327215e+08         78.01         12           4         171.99
1   6.089616e+08         81.64         12          12         180.00
2   6.088752e+08         81.64         12          12         180.00
3   6.087888e+08         81.64         12          12         180.00
4   6.087024e+08         81.64         12          12         180.00
5   6.086160e+08         81.64         12          12         180.00
6   6.085296e+08         81.64         12          12         180.00
7   6.084432e+08         81.64         12          12         180.00
8   6.083568e+08         81.64         12          12         180.00
9   6.082704e+08         81.64         12          12         180.00
10  6.081840e+08         81.64         12          12         180.00
11  6.080976e+08         81.64         12          12         180.00
12  6.080112e+08         81.64         12          12         180.00
13  6.079248e+08         81.64         12          12         180.00
14  6.078384e+08         81.64         12          12         180.00
15  6.077520e+08         81.64         12          12         180.00
16  6.076656e+08         81.64         12          12         180.00
17  6.076310e+08         81.64         12          12         179.99
18  6.075792e+08         81.64         12          12         180.00
19  6.074928e+08         81.64         12          12         180.00

📊 Total Weight Records: 1113

======================================================================
⚖️ RAW WEIGHT - iOS 17
======================================================================

      start_date weight_kg_str  stone_int  pounds_int weight_lbs_str
0   6.327215e+08         78.01         12           4         171.99
1   6.089616e+08         81.64         12          12         180.00
2   6.088752e+08         81.64         12          12         180.00
3   6.087888e+08         81.64         12          12         180.00
4   6.087024e+08         81.64         12          12         180.00
5   6.086160e+08         81.64         12          12         180.00
6   6.085296e+08         81.64         12          12         180.00
7   6.084432e+08         81.64         12          12         180.00
8   6.083568e+08         81.64         12          12         180.00
9   6.082704e+08         81.64         12          12         180.00
10  6.081840e+08         81.64         12          12         180.00
11  6.080976e+08         81.64         12          12         180.00
12  6.080112e+08         81.64         12          12         180.00
13  6.079248e+08         81.64         12          12         180.00
14  6.078384e+08         81.64         12          12         180.00
15  6.077520e+08         81.64         12          12         180.00
16  6.076656e+08         81.64         12          12         180.00
17  6.076310e+08         81.64         12          12         179.99
18  6.075792e+08         81.64         12          12         180.00
19  6.074928e+08         81.64         12          12         180.00

📊 Total Weight Records: 1113

In [ ]:
# ============================================================
# HELPER FORMAT STONE / POUNDS
# ============================================================


def format_stone_pounds(
    stone_value,
    pounds_value
):

    """
    Format weight sebagai:
        X Stone Y Pounds

    Meniru _FormatStonePounds pada plugin Plaso.
    """

    try:

        stone = (
            int(stone_value)
            if pd.notna(stone_value)
            else 0
        )

        pounds = (
            int(pounds_value)
            if pd.notna(pounds_value)
            else 0
        )


        # Carry 14 pounds menjadi 1 stone

        if pounds == 14:

            stone += 1

            pounds = 0


        return (
            f"{stone} Stone "
            f"{pounds} Pounds"
        )


    except (
        TypeError,
        ValueError
    ):

        return None


print(
    "✅ Helper Stone/Pounds siap."
)

✅ Helper Stone/Pounds siap.

In [ ]:
# ============================================================
# FORMAT LAPORAN WEIGHT
# ============================================================


weight_reports = {}


for version, df_weight in weight_results.items():

    df_report = pd.DataFrame()


    # ========================================================
    # TIMESTAMP
    # ========================================================

    df_report[
        "Timestamp"
    ] = (

        df_weight[
            "start_date"
        ]
        .apply(
            parse_cocoa_datetime
        )

    )


    # ========================================================
    # WEIGHT KG
    # ========================================================

    df_report[
        "Weight (kg)"
    ] = (

        df_weight[
            "weight_kg_str"
        ]

    )


    # ========================================================
    # WEIGHT LBS
    # ========================================================

    df_report[
        "Weight (lbs)"
    ] = (

        df_weight[
            "weight_lbs_str"
        ]

    )


    # ========================================================
    # WEIGHT STONE / POUNDS
    # ========================================================

    df_report[
        "Weight (Stone/Pounds)"
    ] = [

        format_stone_pounds(
            stone,
            pounds
        )

        for stone, pounds in zip(

            df_weight[
                "stone_int"
            ],

            df_weight[
                "pounds_int"
            ]

        )

    ]


    # ========================================================
    # SOURCE DATABASE
    # ========================================================

    df_report[
        "Source Database"
    ] = (
        "healthdb_secure.sqlite"
    )


    weight_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Weight selesai."
)

✅ Format laporan Weight selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT WEIGHT
# ============================================================


for version, df_report in weight_reports.items():

    print()
    print("=" * 70)

    print(
        f"⚖️ WEIGHT REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Weight Records: "
        f"{len(df_report)}"
    )

======================================================================
⚖️ WEIGHT REPORT - iOS 13.3.1
======================================================================

,Timestamp,Weight (kg),Weight (lbs),Weight (Stone/Pounds),Source Database
0,2020-04-12 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
1,2020-04-11 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
2,2020-04-10 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
3,2020-04-09 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
4,2020-04-08 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
5,2020-04-07 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
6,2020-04-06 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
7,2020-04-05 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
8,2020-04-04 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
9,2020-04-03 18:23:55.320479+00:00,81.64,179.99,12 Stone 12 Pounds,healthdb_secure.sqlite
10,2020-04-03 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
11,2020-04-02 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
12,2020-04-01 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
13,2020-03-31 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
14,2020-03-30 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
15,2020-03-29 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
16,2020-03-28 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
17,2020-03-27 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
18,2020-03-26 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
19,2020-03-25 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite

📊 Total Weight Records: 1105

======================================================================
⚖️ WEIGHT REPORT - iOS 13.4.1
======================================================================

,Timestamp,Weight (kg),Weight (lbs),Weight (Stone/Pounds),Source Database
0,2020-04-16 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
1,2020-04-15 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
2,2020-04-14 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
3,2020-04-13 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
4,2020-04-12 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
5,2020-04-11 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
6,2020-04-10 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
7,2020-04-09 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
8,2020-04-08 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
9,2020-04-07 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
10,2020-04-06 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
11,2020-04-05 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
12,2020-04-04 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
13,2020-04-03 18:23:55.320479+00:00,81.64,179.99,12 Stone 12 Pounds,healthdb_secure.sqlite
14,2020-04-03 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
15,2020-04-02 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
16,2020-04-01 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
17,2020-03-31 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
18,2020-03-30 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
19,2020-03-29 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite

📊 Total Weight Records: 1109

======================================================================
⚖️ WEIGHT REPORT - iOS 15
======================================================================

,Timestamp,Weight (kg),Weight (lbs),Weight (Stone/Pounds),Source Database
0,2021-01-19 03:58:56.051184+00:00,78.01,171.99,12 Stone 4 Pounds,healthdb_secure.sqlite
1,2020-04-19 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
2,2020-04-18 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
3,2020-04-17 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
4,2020-04-16 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
5,2020-04-15 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
6,2020-04-14 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
7,2020-04-13 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
8,2020-04-12 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
9,2020-04-11 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
10,2020-04-10 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
11,2020-04-09 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
12,2020-04-08 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
13,2020-04-07 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
14,2020-04-06 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
15,2020-04-05 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
16,2020-04-04 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
17,2020-04-03 18:23:55.320479+00:00,81.64,179.99,12 Stone 12 Pounds,healthdb_secure.sqlite
18,2020-04-03 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
19,2020-04-02 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite

📊 Total Weight Records: 1113

======================================================================
⚖️ WEIGHT REPORT - iOS 16
======================================================================

,Timestamp,Weight (kg),Weight (lbs),Weight (Stone/Pounds),Source Database
0,2021-01-19 03:58:56.051184+00:00,78.01,171.99,12 Stone 4 Pounds,healthdb_secure.sqlite
1,2020-04-19 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
2,2020-04-18 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
3,2020-04-17 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
4,2020-04-16 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
5,2020-04-15 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
6,2020-04-14 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
7,2020-04-13 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
8,2020-04-12 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
9,2020-04-11 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
10,2020-04-10 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
11,2020-04-09 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
12,2020-04-08 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
13,2020-04-07 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
14,2020-04-06 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
15,2020-04-05 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
16,2020-04-04 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
17,2020-04-03 18:23:55.320479+00:00,81.64,179.99,12 Stone 12 Pounds,healthdb_secure.sqlite
18,2020-04-03 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
19,2020-04-02 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite

📊 Total Weight Records: 1113

======================================================================
⚖️ WEIGHT REPORT - iOS 17
======================================================================

,Timestamp,Weight (kg),Weight (lbs),Weight (Stone/Pounds),Source Database
0,2021-01-19 03:58:56.051184+00:00,78.01,171.99,12 Stone 4 Pounds,healthdb_secure.sqlite
1,2020-04-19 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
2,2020-04-18 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
3,2020-04-17 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
4,2020-04-16 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
5,2020-04-15 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
6,2020-04-14 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
7,2020-04-13 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
8,2020-04-12 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
9,2020-04-11 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
10,2020-04-10 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
11,2020-04-09 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
12,2020-04-08 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
13,2020-04-07 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
14,2020-04-06 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
15,2020-04-05 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
16,2020-04-04 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
17,2020-04-03 18:23:55.320479+00:00,81.64,179.99,12 Stone 12 Pounds,healthdb_secure.sqlite
18,2020-04-03 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite
19,2020-04-02 04:00:00+00:00,81.64,180.00,12 Stone 12 Pounds,healthdb_secure.sqlite

📊 Total Weight Records: 1113

# **Fitur Workouts**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR WORKOUTS
# ============================================================

print()
print("=" * 70)
print("🏋️ VERIFIKASI WORKOUTS")
print("=" * 70)


legacy_secure_tables = [
    "workouts",
    "samples"
]


latest_secure_tables = [
    "workout_activities",
    "workouts",
    "workout_statistics",
    "samples",
    "metadata_keys",
    "metadata_values",
    "objects",
    "data_provenances"
]


latest_healthdb_tables = [
    "source_devices",
    "sources"
]


for dataset in target_datasets:

    version = dataset["version"]

    major_version = get_ios_major_version(
        version
    )

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()
    print(
        f"📱 {version}"
    )


    # ========================================================
    # IOS 16-17
    # ========================================================

    if major_version in (16, 17):

        print(
            "   🔎 Struktur: "
            "Workout Activities iOS 16-17"
        )

        print(
            "   📂 healthdb_secure.sqlite"
        )

        for table_name in latest_secure_tables:

            if table_name in secure_tables:

                print(
                    f"      {table_name:<22}: ✅"
                )

            else:

                print(
                    f"      {table_name:<22}: ❌"
                )


        print(
            "   📂 healthdb.sqlite"
        )

        for table_name in latest_healthdb_tables:

            if table_name in healthdb_tables:

                print(
                    f"      {table_name:<22}: ✅"
                )

            else:

                print(
                    f"      {table_name:<22}: ❌"
                )


    # ========================================================
    # IOS 13-15
    # ========================================================

    else:

        print(
            "   🔎 Struktur: "
            "Legacy Workouts iOS 13-15"
        )

        print(
            "   📂 healthdb_secure.sqlite"
        )

        for table_name in legacy_secure_tables:

            if table_name in secure_tables:

                print(
                    f"      {table_name:<22}: ✅"
                )

            else:

                print(
                    f"      {table_name:<22}: ❌"
                )


print()
print("=" * 70)

======================================================================
🏋️ VERIFIKASI WORKOUTS
======================================================================

📱 iOS 13.3.1
   🔎 Struktur: Legacy Workouts iOS 13-15
   📂 healthdb_secure.sqlite
      workouts              : ✅
      samples               : ✅

📱 iOS 13.4.1
   🔎 Struktur: Legacy Workouts iOS 13-15
   📂 healthdb_secure.sqlite
      workouts              : ✅
      samples               : ✅

📱 iOS 15
   🔎 Struktur: Legacy Workouts iOS 13-15
   📂 healthdb_secure.sqlite
      workouts              : ✅
      samples               : ✅

📱 iOS 16
   🔎 Struktur: Workout Activities iOS 16-17
   📂 healthdb_secure.sqlite
      workout_activities    : ✅
      workouts              : ✅
      workout_statistics    : ✅
      samples               : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
      objects               : ✅
      data_provenances      : ✅
   📂 healthdb.sqlite
      source_devices        : ✅
      sources               : ✅

📱 iOS 17
   🔎 Struktur: Workout Activities iOS 16-17
   📂 healthdb_secure.sqlite
      workout_activities    : ✅
      workouts              : ✅
      workout_statistics    : ✅
      samples               : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
      objects               : ✅
      data_provenances      : ✅
   📂 healthdb.sqlite
      source_devices        : ✅
      sources               : ✅

======================================================================

In [ ]:
# ============================================================
# ENUMERATION HELPERS WORKOUTS
# ============================================================


WORKOUT_ACTIVITY_LABELS = {

    1: "AMERICAN FOOTBALL",
    2: "ARCHERY",
    3: "AUSTRALIAN FOOTBALL",
    4: "BADMINTON",
    5: "BASEBALL",
    6: "BASKETBALL",
    7: "BOWLING",
    8: "BOXING",
    9: "CLIMBING",
    10: "CRICKET",
    11: "CROSS TRAINING",
    12: "CURLING",
    13: "CYCLING",

    16: "ELLIPTICAL",
    17: "EQUESTRIAN SPORTS",
    18: "FENCING",
    19: "FISHING",
    20: "FUNCTION STRENGTH TRAINING",
    21: "GOLF",
    22: "GYMNASTICS",
    23: "HANDBALL",
    24: "HIKING",
    25: "HOCKEY",
    26: "HUNTING",
    27: "LACROSS",
    28: "MARTIAL ARTS",
    29: "MIND AND BODY",

    31: "PADDLE SPORTS",
    32: "PLAY",
    33: "PREPARATION AND RECOVERY",
    34: "RACQUETBALL",
    35: "ROWING",
    36: "RUGBY",
    37: "RUNNING",
    38: "SAILING",
    39: "SKATING SPORTS",
    40: "SNOW SPORTS",
    41: "SOCCER",
    42: "SOFTBALL",
    43: "SQUASH",
    44: "STAIRSTEPPER",
    45: "SURFING SPORTS",
    46: "SWIMMING",
    47: "TABLE TENNIS",
    48: "TENNIS",
    49: "TRACK AND FIELD",
    50: "TRADITIONAL STRENGTH TRAINING",
    51: "VOLLEYBALL",
    52: "WALKING",
    53: "WATER FITNESS",
    54: "WATER POLO",
    55: "WATER SPORTS",
    56: "WRESTLING",
    57: "YOGA",
    58: "BARRE",
    59: "CORE TRAINING",
    60: "CROSS COUNTRY SKIING",
    61: "DOWNHILL SKIING",
    62: "FLEXIBILITY",
    63: "HIGH INTENSITY INTERVAL TRAINING (HIIT)",
    64: "JUMP ROPE",
    65: "KICKBOXING",
    66: "PILATES",
    67: "SNOWBOARDING",
    68: "STAIRS",
    69: "STEP TRAINING",
    70: "WHEELCHAIR WALK PACE",
    71: "WHEELCHAIR RUN PACE",
    72: "TAI CHI",
    73: "MIXED CARDIO",
    74: "HAND CYCLING",
    75: "DISC SPORTS",
    76: "FITNESS GAMING",
    77: "DANCE",
    78: "SOCIAL DANCE",
    79: "PICKLEBALL",
    80: "COOLDOWN",

    3000: "OTHER"
}


WORKOUT_GOAL_LABELS = {

    0: "Open",
    1: "Distance in meters",
    2: "Time in seconds",
    3: "Kilocalories"

}


WORKOUT_LOCATION_LABELS = {

    2: "Indoor",
    3: "Outdoor"

}


def get_workout_enum_label(
    value,
    mapping,
    default_value
):

    """
    Konversi RAW enumeration code menjadi label.
    """

    if value is None:

        return default_value


    try:

        if pd.isna(value):

            return default_value

    except TypeError:

        pass


    try:

        key = int(
            float(value)
        )

    except (
        TypeError,
        ValueError
    ):

        return default_value


    return mapping.get(
        key,
        default_value
    )


print(
    "✅ Enumeration helper Workouts siap."
)

✅ Enumeration helper Workouts siap.

In [ ]:
# ============================================================
# HELPER CROSS DATABASE WORKOUTS
# ============================================================

import sqlite3

from pathlib import Path


def open_workouts_cross_database_readonly(
    secure_database_path,
    health_database_path=None
):

    """
    Membuka database Workouts secara read-only.

    secure_db:
        healthdb_secure.sqlite

    health_db:
        healthdb.sqlite
    """

    conn = sqlite3.connect(
        ":memory:",
        uri=True
    )


    secure_uri = (
        Path(
            secure_database_path
        )
        .resolve()
        .as_uri()
        +
        "?mode=ro"
    )


    conn.execute(
        "ATTACH DATABASE ? AS secure_db",
        (
            secure_uri,
        )
    )


    if health_database_path is not None:

        health_uri = (
            Path(
                health_database_path
            )
            .resolve()
            .as_uri()
            +
            "?mode=ro"
        )


        conn.execute(
            "ATTACH DATABASE ? AS health_db",
            (
                health_uri,
            )
        )


    return conn


print(
    "✅ Helper cross-database Workouts siap."
)

✅ Helper cross-database Workouts siap.

In [ ]:
# ============================================================
# EXTRACTOR WORKOUTS ADAPTIVE
# ============================================================


def extract_workouts(
    secure_database_path,
    health_database_path,
    ios_version
):

    """
    Extract Apple Health Workouts.

    iOS 13-15:
        legacy workouts schema

    iOS 16-17:
        workout_activities schema
        + cross database sources/source_devices
    """

    major_version = get_ios_major_version(
        ios_version
    )


    # ========================================================
    # IOS 16-17
    # ========================================================

    if major_version in (16, 17):

        print(
            "   🔎 Struktur terdeteksi: "
            "iOS 16-17 Workout Activities"
        )


        conn = open_workouts_cross_database_readonly(
            secure_database_path,
            health_database_path
        )


        query = """

        SELECT

            wa.start_date
                AS start_cocoa,

            wa.end_date
                AS end_cocoa,

            wa.activity_type
                AS activity_type_code,

            wa.location_type
                AS location_type_code,

            wa.duration
                AS duration_seconds,


            s.start_date
                AS sample_start_cocoa,

            s.end_date
                AS sample_end_cocoa,


            w.total_distance
                AS total_distance_km,

            w.goal_type
                AS goal_type_code,

            w.goal
                AS goal_value,


            MAX(

                CASE

                    WHEN ws.data_type = 10

                    THEN ROUND(
                        ws.quantity,
                        2
                    )

                END

            ) AS total_active_kcal,


            MAX(

                CASE

                    WHEN ws.data_type = 9

                    THEN ROUND(
                        ws.quantity,
                        2
                    )

                END

            ) AS total_resting_kcal,


            MAX(

                CASE

                    WHEN mk.key = 'HKAverageMETs'

                    THEN ROUND(
                        mv.numerical_value,
                        1
                    )

                END

            ) AS avg_mets,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutMinHeartRate'

                    THEN CAST(

                        ROUND(
                            mv.numerical_value * 60
                        )

                        AS INT

                    )

                END

            ) AS min_hr_bpm,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutMaxHeartRate'

                    THEN CAST(

                        ROUND(
                            mv.numerical_value * 60
                        )

                        AS INT

                    )

                END

            ) AS max_hr_bpm,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutAverageHeartRate'

                    THEN CAST(

                        ROUND(
                            mv.numerical_value * 60
                        )

                        AS INT

                    )

                END

            ) AS avg_hr_bpm,


            MAX(

                CASE

                    WHEN mk.key =
                    'HKWeatherTemperature'

                    THEN ROUND(
                        mv.numerical_value,
                        2
                    )

                END

            ) AS temp_f,


            MAX(

                CASE

                    WHEN mk.key =
                    'HKWeatherHumidity'

                    THEN CAST(
                        mv.numerical_value
                        AS INT
                    )

                END

            ) AS humidity_pct,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutWeatherLocationCoordinatesLatitude'

                    THEN mv.numerical_value

                END

            ) AS lat,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutWeatherLocationCoordinatesLongitude'

                    THEN mv.numerical_value

                END

            ) AS lon,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutMinGroundElevation'

                    THEN ROUND(
                        mv.numerical_value,
                        2
                    )

                END

            ) AS min_elev_m,


            MAX(

                CASE

                    WHEN mk.key =
                    '_HKPrivateWorkoutMaxGroundElevation'

                    THEN ROUND(
                        mv.numerical_value,
                        2
                    )

                END

            ) AS max_elev_m,


            sd.hardware
                AS hardware,


            src.name
                AS source_name,


            dp.source_version
                AS software_version,


            dp.tz_name
                AS timezone_name,


            o.creation_date
                AS added_cocoa


        FROM secure_db.workout_activities AS wa


        LEFT JOIN secure_db.workouts AS w

            ON w.data_id =
               wa.owner_id


        LEFT JOIN secure_db.workout_statistics AS ws

            ON ws.workout_activity_id =
               wa.ROWID


        LEFT JOIN secure_db.samples AS s

            ON s.data_id =
               w.data_id


        LEFT JOIN secure_db.metadata_values AS mv

            ON mv.object_id =
               wa.owner_id


        LEFT JOIN secure_db.metadata_keys AS mk

            ON mk.ROWID =
               mv.key_id


        LEFT JOIN secure_db.objects AS o

            ON o.data_id =
               wa.owner_id


        LEFT JOIN secure_db.data_provenances AS dp

            ON dp.ROWID =
               o.provenance


        LEFT JOIN health_db.source_devices AS sd

            ON sd.ROWID =
               dp.device_id


        LEFT JOIN health_db.sources AS src

            ON src.ROWID =
               dp.source_id


        GROUP BY
            wa.ROWID


        ORDER BY
            wa.start_date

        """


        df = pd.read_sql_query(
            query,
            conn
        )


        df[
            "workout_schema"
        ] = (
            "Workout Activities iOS 16-17"
        )


        conn.close()


        return df


    # ========================================================
    # IOS 13-15
    # ========================================================

    print(
        "   🔎 Struktur terdeteksi: "
        "iOS 13-15 Legacy Workouts"
    )


    conn = open_workouts_cross_database_readonly(
        secure_database_path
    )


    query = """

    SELECT

        samples.start_date
            AS start_date,

        samples.end_date
            AS end_date,

        workouts.activity_type
            AS activity_type,

        workouts.duration
            AS duration,

        workouts.total_distance
            AS total_distance,

        workouts.total_energy_burned
            AS total_energy_burned,

        workouts.total_basal_energy_burned
            AS total_basal_energy_burned,

        workouts.goal_type
            AS goal_type,

        workouts.goal
            AS goal

    FROM secure_db.workouts AS workouts


    LEFT JOIN secure_db.samples AS samples

        ON samples.data_id =
           workouts.data_id


    GROUP BY
        workouts.data_id


    ORDER BY
        samples.start_date

    """


    df = pd.read_sql_query(
        query,
        conn
    )


    df[
        "workout_schema"
    ] = (
        "Legacy Workouts iOS 13-15"
    )


    conn.close()


    return df


print(
    "✅ Extractor Workouts adaptive siap."
)

✅ Extractor Workouts adaptive siap.

In [ ]:
# ============================================================
# EKSTRAKSI WORKOUTS
# ============================================================


workouts_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]


    print()
    print("=" * 70)

    print(
        f"🏋️ WORKOUTS - {version}"
    )

    print("=" * 70)


    try:

        secure_db_path = dataset[
            "healthdb_secure"
        ]


        major_version = get_ios_major_version(
            version
        )


        # ====================================================
        # IOS 16-17
        # ====================================================

        if major_version in (16, 17):

            healthdb_path = dataset[
                "healthdb"
            ]


        # ====================================================
        # IOS 13-15
        # ====================================================

        else:

            healthdb_path = None


        df_workouts = extract_workouts(

            secure_db_path,

            healthdb_path,

            version

        )


        workouts_results[
            version
        ] = df_workouts


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Workouts: "
            f"{len(df_workouts)}"
        )


        if major_version in (16, 17):

            print(
                "📂 Source: "
                "healthdb_secure.sqlite "
                "+ healthdb.sqlite"
            )

        else:

            print(
                "📂 Source: "
                "healthdb_secure.sqlite"
            )


    except Exception as e:

        print(
            f"❌ Error {version}: "
            f"{type(e).__name__}: {e}"
        )

======================================================================
🏋️ WORKOUTS - iOS 13.3.1
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15 Legacy Workouts
✅ Ekstraksi berhasil
📊 Total Workouts: 6
📂 Source: healthdb_secure.sqlite

======================================================================
🏋️ WORKOUTS - iOS 13.4.1
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15 Legacy Workouts
✅ Ekstraksi berhasil
📊 Total Workouts: 6
📂 Source: healthdb_secure.sqlite

======================================================================
🏋️ WORKOUTS - iOS 15
======================================================================
   🔎 Struktur terdeteksi: iOS 13-15 Legacy Workouts
✅ Ekstraksi berhasil
📊 Total Workouts: 16
📂 Source: healthdb_secure.sqlite

======================================================================
🏋️ WORKOUTS - iOS 16
======================================================================
   🔎 Struktur terdeteksi: iOS 16-17 Workout Activities
✅ Ekstraksi berhasil
📊 Total Workouts: 25
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

======================================================================
🏋️ WORKOUTS - iOS 17
======================================================================
   🔎 Struktur terdeteksi: iOS 16-17 Workout Activities
✅ Ekstraksi berhasil
📊 Total Workouts: 29
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW WORKOUTS
# ============================================================


for version, df_workouts in workouts_results.items():

    print()
    print("=" * 70)

    print(
        f"🏋️ RAW WORKOUTS - {version}"
    )

    print("=" * 70)


    display(
        df_workouts.head(20)
    )


    print()

    print(
        f"📊 Total Workouts: "
        f"{len(df_workouts)}"
    )

======================================================================
🏋️ RAW WORKOUTS - iOS 13.3.1
======================================================================

,start_date,end_date,activity_type,duration,total_distance,total_energy_burned,total_basal_energy_burned,goal_type,goal,workout_schema
0,6.070283e+08,6.070293e+08,37,1080.120497,3.247980,208.572061,26.335518,0,None,Legacy Workouts iOS 13-15
1,6.070993e+08,6.071003e+08,37,1039.280670,3.235360,203.107030,25.337790,0,None,Legacy Workouts iOS 13-15
2,6.072650e+08,6.072666e+08,37,1591.066217,4.845504,302.580232,38.851842,0,None,Legacy Workouts iOS 13-15
3,6.073739e+08,6.073755e+08,37,1572.253775,4.864848,302.861407,38.321723,0,None,Legacy Workouts iOS 13-15
4,6.075418e+08,6.075434e+08,37,1550.327887,4.853044,301.889198,37.967227,0,None,Legacy Workouts iOS 13-15
5,6.076339e+08,6.076355e+08,37,1580.992556,4.862750,369.850771,46.008878,0,None,Legacy Workouts iOS 13-15

📊 Total Workouts: 6

======================================================================
🏋️ RAW WORKOUTS - iOS 13.4.1
======================================================================

,start_date,end_date,activity_type,duration,total_distance,total_energy_burned,total_basal_energy_burned,goal_type,goal,workout_schema
0,6.070283e+08,6.070293e+08,37,1080.120497,3.247980,208.572061,26.335518,0,None,Legacy Workouts iOS 13-15
1,6.070993e+08,6.071003e+08,37,1039.280670,3.235360,203.107030,25.337790,0,None,Legacy Workouts iOS 13-15
2,6.072650e+08,6.072666e+08,37,1591.066217,4.845504,302.580232,38.851842,0,None,Legacy Workouts iOS 13-15
3,6.073739e+08,6.073755e+08,37,1572.253775,4.864848,302.861407,38.321723,0,None,Legacy Workouts iOS 13-15
4,6.075418e+08,6.075434e+08,37,1550.327887,4.853044,301.889198,37.967227,0,None,Legacy Workouts iOS 13-15
5,6.076339e+08,6.076355e+08,37,1580.992556,4.862750,369.850771,46.008878,0,None,Legacy Workouts iOS 13-15

📊 Total Workouts: 6

======================================================================
🏋️ RAW WORKOUTS - iOS 15
======================================================================

,start_date,end_date,activity_type,duration,total_distance,total_energy_burned,total_basal_energy_burned,goal_type,goal,workout_schema
0,6.070283e+08,6.070293e+08,37,1080.120497,3.247980,208.572061,26.335518,0,None,Legacy Workouts iOS 13-15
1,6.070993e+08,6.071003e+08,37,1039.280670,3.235360,203.107030,25.337790,0,None,Legacy Workouts iOS 13-15
2,6.072650e+08,6.072666e+08,37,1591.066217,4.845504,302.580232,38.851842,0,None,Legacy Workouts iOS 13-15
3,6.073739e+08,6.073755e+08,37,1572.253775,4.864848,302.861407,38.321723,0,None,Legacy Workouts iOS 13-15
4,6.075418e+08,6.075434e+08,37,1550.327887,4.853044,301.889198,37.967227,0,None,Legacy Workouts iOS 13-15
5,6.076339e+08,6.076355e+08,37,1580.992556,4.862750,369.850771,46.008878,0,None,Legacy Workouts iOS 13-15
6,6.331986e+08,6.332000e+08,37,1365.501957,4.889449,357.637087,38.153640,0,None,Legacy Workouts iOS 13-15
7,6.337255e+08,6.337269e+08,37,1359.062002,4.977984,364.691713,37.884673,0,None,Legacy Workouts iOS 13-15
8,6.337269e+08,6.337277e+08,52,788.744113,1.214734,91.217789,21.733643,0,None,Legacy Workouts iOS 13-15
9,6.343359e+08,6.343369e+08,52,979.505124,1.372000,77.074838,27.055633,0,None,Legacy Workouts iOS 13-15
10,6.352828e+08,6.352835e+08,37,713.734009,2.486180,154.000000,NaN,0,None,Legacy Workouts iOS 13-15
11,6.352836e+08,6.352842e+08,52,605.827026,0.920650,99.000000,NaN,0,None,Legacy Workouts iOS 13-15
12,7.032621e+08,7.032636e+08,37,1561.053955,5.304890,439.000000,NaN,0,None,Legacy Workouts iOS 13-15
13,7.033563e+08,7.033578e+08,37,1462.031982,4.988870,397.000000,NaN,0,None,Legacy Workouts iOS 13-15
14,7.034376e+08,7.034392e+08,37,1563.767944,5.357910,372.000000,NaN,0,None,Legacy Workouts iOS 13-15
15,7.035290e+08,7.035305e+08,37,1535.352051,5.318550,345.000000,NaN,0,None,Legacy Workouts iOS 13-15

📊 Total Workouts: 16

======================================================================
🏋️ RAW WORKOUTS - iOS 16
======================================================================

,start_cocoa,end_cocoa,activity_type_code,location_type_code,duration_seconds,sample_start_cocoa,sample_end_cocoa,total_distance_km,goal_type_code,goal_value,...,lat,lon,min_elev_m,max_elev_m,hardware,source_name,software_version,timezone_name,added_cocoa,workout_schema
0,6.070283e+08,6.070293e+08,37,3,1080.120497,6.070283e+08,6.070293e+08,3.247980,0,None,...,35.659314,-78.872689,96.41,106.80,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.070293e+08,Workout Activities iOS 16-17
1,6.070993e+08,6.071003e+08,37,3,1039.280670,6.070993e+08,6.071003e+08,3.235360,0,None,...,35.659018,-78.872687,92.30,109.85,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.071003e+08,Workout Activities iOS 16-17
2,6.072650e+08,6.072666e+08,37,3,1591.066217,6.072650e+08,6.072666e+08,4.845504,0,None,...,35.659337,-78.873288,77.75,110.21,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.072666e+08,Workout Activities iOS 16-17
3,6.073739e+08,6.073755e+08,37,3,1572.253775,6.073739e+08,6.073755e+08,4.864848,0,None,...,35.659270,-78.873146,78.00,109.59,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.073755e+08,Workout Activities iOS 16-17
4,6.075418e+08,6.075434e+08,37,3,1550.327887,6.075418e+08,6.075434e+08,4.853044,0,None,...,35.659283,-78.873450,79.27,109.78,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.075434e+08,Workout Activities iOS 16-17
5,6.076339e+08,6.076355e+08,37,3,1580.992556,6.076339e+08,6.076355e+08,4.862750,0,None,...,35.659174,-78.873293,77.93,111.20,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.076355e+08,Workout Activities iOS 16-17
6,6.331986e+08,6.332000e+08,37,3,1365.501957,6.331986e+08,6.332000e+08,4.889449,0,None,...,35.659582,-78.871507,71.76,110.90,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.332000e+08,Workout Activities iOS 16-17
7,6.337255e+08,6.337269e+08,37,3,1359.062002,6.337255e+08,6.337269e+08,4.977984,0,None,...,35.659680,-78.871654,73.94,111.78,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.337269e+08,Workout Activities iOS 16-17
8,6.337269e+08,6.337277e+08,52,3,788.744113,6.337269e+08,6.337277e+08,1.214734,0,None,...,35.660179,-78.875737,100.52,106.43,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.337277e+08,Workout Activities iOS 16-17
9,6.343359e+08,6.343369e+08,52,3,979.505124,6.343359e+08,6.343369e+08,1.372000,0,None,...,35.660257,-78.877898,94.99,102.39,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.343369e+08,Workout Activities iOS 16-17
10,6.352828e+08,6.352835e+08,37,3,713.734009,6.352828e+08,6.352835e+08,2.486180,0,None,...,NaN,NaN,NaN,NaN,,Connect,31,America/New_York,6.355226e+08,Workout Activities iOS 16-17
11,6.352836e+08,6.352842e+08,52,3,605.827026,6.352836e+08,6.352842e+08,0.920650,0,None,...,NaN,NaN,NaN,NaN,,Connect,31,America/New_York,6.355226e+08,Workout Activities iOS 16-17
12,7.032621e+08,7.032636e+08,37,3,1561.053955,7.032621e+08,7.032636e+08,5.304890,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
13,7.033563e+08,7.033578e+08,37,3,1462.031982,7.033563e+08,7.033578e+08,4.988870,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
14,7.034376e+08,7.034392e+08,37,3,1563.767944,7.034376e+08,7.034392e+08,5.357910,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
15,7.035290e+08,7.035305e+08,37,3,1535.352051,7.035290e+08,7.035305e+08,5.318550,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
16,7.105096e+08,7.105112e+08,37,3,1529.868309,7.105096e+08,7.105112e+08,4.885788,0,None,...,35.659590,-78.868503,90.06,122.67,"Watch4,3",Apple Watch,8.8.1,America/New_York,7.105112e+08,Workout Activities iOS 16-17
17,7.106824e+08,7.106839e+08,37,3,1517.245751,7.106824e+08,7.106839e+08,4.930922,0,None,...,35.659579,-78.868339,90.30,121.84,"Watch4,3",Apple Watch,8.8.1,America/New_York,7.106839e+08,Workout Activities iOS 16-17
18,7.109417e+08,7.109432e+08,37,3,1528.775067,7.109417e+08,7.109432e+08,4.904850,0,None,...,35.659336,-78.868688,89.75,122.14,"Watch4,3",Apple Watch,8.8.1,America/New_York,7.109432e+08,Workout Activities iOS 16-17
19,7.114582e+08,7.114597e+08,37,3,1551.982217,7.114582e+08,7.114597e+08,4.892269,0,None,...,35.659359,-78.868656,91.20,122.01,"Watch4,3",Apple Watch,8.8.1,America/New_York,7.114597e+08,Workout Activities iOS 16-17

📊 Total Workouts: 25

======================================================================
🏋️ RAW WORKOUTS - iOS 17
======================================================================

,start_cocoa,end_cocoa,activity_type_code,location_type_code,duration_seconds,sample_start_cocoa,sample_end_cocoa,total_distance_km,goal_type_code,goal_value,...,lat,lon,min_elev_m,max_elev_m,hardware,source_name,software_version,timezone_name,added_cocoa,workout_schema
0,6.070283e+08,6.070293e+08,37,3,1080.120497,6.070283e+08,6.070293e+08,3.247980,0,None,...,35.659314,-78.872689,96.41,106.80,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.070293e+08,Workout Activities iOS 16-17
1,6.070993e+08,6.071003e+08,37,3,1039.280670,6.070993e+08,6.071003e+08,3.235360,0,None,...,35.659018,-78.872687,92.30,109.85,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.071003e+08,Workout Activities iOS 16-17
2,6.072650e+08,6.072666e+08,37,3,1591.066217,6.072650e+08,6.072666e+08,4.845504,0,None,...,35.659337,-78.873288,77.75,110.21,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.072666e+08,Workout Activities iOS 16-17
3,6.073739e+08,6.073755e+08,37,3,1572.253775,6.073739e+08,6.073755e+08,4.864848,0,None,...,35.659270,-78.873146,78.00,109.59,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.073755e+08,Workout Activities iOS 16-17
4,6.075418e+08,6.075434e+08,37,3,1550.327887,6.075418e+08,6.075434e+08,4.853044,0,None,...,35.659283,-78.873450,79.27,109.78,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.075434e+08,Workout Activities iOS 16-17
5,6.076339e+08,6.076355e+08,37,3,1580.992556,6.076339e+08,6.076355e+08,4.862750,0,None,...,35.659174,-78.873293,77.93,111.20,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,6.076355e+08,Workout Activities iOS 16-17
6,6.331986e+08,6.332000e+08,37,3,1365.501957,6.331986e+08,6.332000e+08,4.889449,0,None,...,35.659582,-78.871507,71.76,110.90,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.332000e+08,Workout Activities iOS 16-17
7,6.337255e+08,6.337269e+08,37,3,1359.062002,6.337255e+08,6.337269e+08,4.977984,0,None,...,35.659680,-78.871654,73.94,111.78,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.337269e+08,Workout Activities iOS 16-17
8,6.337269e+08,6.337277e+08,52,3,788.744113,6.337269e+08,6.337277e+08,1.214734,0,None,...,35.660179,-78.875737,100.52,106.43,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.337277e+08,Workout Activities iOS 16-17
9,6.343359e+08,6.343369e+08,52,3,979.505124,6.343359e+08,6.343369e+08,1.372000,0,None,...,35.660257,-78.877898,94.99,102.39,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,6.343369e+08,Workout Activities iOS 16-17
10,6.352828e+08,6.352835e+08,37,3,713.734009,6.352828e+08,6.352835e+08,2.486180,0,None,...,NaN,NaN,NaN,NaN,,Connect,31,America/New_York,6.355226e+08,Workout Activities iOS 16-17
11,6.352836e+08,6.352842e+08,52,3,605.827026,6.352836e+08,6.352842e+08,0.920650,0,None,...,NaN,NaN,NaN,NaN,,Connect,31,America/New_York,6.355226e+08,Workout Activities iOS 16-17
12,7.032621e+08,7.032636e+08,37,3,1561.053955,7.032621e+08,7.032636e+08,5.304890,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
13,7.033563e+08,7.033578e+08,37,3,1462.031982,7.033563e+08,7.033578e+08,4.988870,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
14,7.034376e+08,7.034392e+08,37,3,1563.767944,7.034376e+08,7.034392e+08,5.357910,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
15,7.035290e+08,7.035305e+08,37,3,1535.352051,7.035290e+08,7.035305e+08,5.318550,0,None,...,NaN,NaN,NaN,NaN,,Connect,36,America/New_York,7.036218e+08,Workout Activities iOS 16-17
16,7.105096e+08,7.105112e+08,37,3,1529.868309,7.105096e+08,7.105112e+08,4.885788,0,None,...,35.659590,-78.868503,90.06,122.67,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,7.105112e+08,Workout Activities iOS 16-17
17,7.106824e+08,7.106839e+08,37,3,1517.245751,7.106824e+08,7.106839e+08,4.930922,0,None,...,35.659579,-78.868339,90.30,121.84,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,7.106839e+08,Workout Activities iOS 16-17
18,7.109417e+08,7.109432e+08,37,3,1528.775067,7.109417e+08,7.109432e+08,4.904850,0,None,...,35.659336,-78.868688,89.75,122.14,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,7.109432e+08,Workout Activities iOS 16-17
19,7.114582e+08,7.114597e+08,37,3,1551.982217,7.114582e+08,7.114597e+08,4.892269,0,None,...,35.659359,-78.868656,91.20,122.01,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,7.114597e+08,Workout Activities iOS 16-17

📊 Total Workouts: 29

In [ ]:
# ============================================================
# HELPER FORMAT WORKOUTS
# ============================================================


def workout_seconds_to_hms(
    seconds_value
):

    """
    Konversi detik menjadi HH:MM:SS.
    """

    try:

        if pd.isna(
            seconds_value
        ):

            return None


        total = int(
            float(seconds_value)
        )


    except (
        TypeError,
        ValueError
    ):

        return None


    hours = (
        total // 3600
    )

    minutes = (
        total % 3600
    ) // 60

    seconds = (
        total % 60
    )


    return (
        f"{hours:02d}:"
        f"{minutes:02d}:"
        f"{seconds:02d}"
    )



def workout_km_to_miles(
    km_value
):

    """
    Konversi kilometer menjadi miles.
    """

    try:

        if pd.isna(
            km_value
        ):

            return None


        return round(
            float(km_value)
            * 0.621371,
            2
        )


    except (
        TypeError,
        ValueError
    ):

        return None



def workout_fahrenheit_to_celsius(
    temp_f
):

    """
    Konversi Fahrenheit menjadi Celsius.
    """

    try:

        if pd.isna(
            temp_f
        ):

            return None


        return round(

            (
                float(temp_f)
                -
                32.0
            )
            *
            (
                5.0 / 9.0
            ),

            2

        )


    except (
        TypeError,
        ValueError
    ):

        return None


print(
    "✅ Helper format Workouts siap."
)

✅ Helper format Workouts siap.

In [ ]:
# ============================================================
# FORMAT LAPORAN WORKOUTS
# ============================================================


workouts_reports = {}


for version, df_workouts in workouts_results.items():

    df_report = pd.DataFrame()


    major_version = get_ios_major_version(
        version
    )


    # ========================================================
    # IOS 16-17
    # ========================================================

    if major_version in (16, 17):


        # ----------------------------------------------------
        # TIMESTAMPS
        # ----------------------------------------------------

        df_report[
            "Start Timestamp"
        ] = (

            df_workouts[
                "start_cocoa"
            ]
            .apply(
                parse_cocoa_datetime
            )

        )


        df_report[
            "End Timestamp"
        ] = (

            df_workouts[
                "end_cocoa"
            ]
            .apply(
                parse_cocoa_datetime
            )

        )


        df_report[
            "Added Timestamp"
        ] = (

            df_workouts[
                "added_cocoa"
            ]
            .apply(
                parse_cocoa_datetime
            )

        )


        # ----------------------------------------------------
        # ACTIVITY
        # ----------------------------------------------------

        df_report[
            "Activity Type Code"
        ] = (

            df_workouts[
                "activity_type_code"
            ]

        )


        df_report[
            "Activity"
        ] = [

            get_workout_enum_label(
                value,
                WORKOUT_ACTIVITY_LABELS,
                "OTHER"
            )

            for value in df_workouts[
                "activity_type_code"
            ]

        ]


        # ----------------------------------------------------
        # LOCATION
        # ----------------------------------------------------

        df_report[
            "Location Type Code"
        ] = (

            df_workouts[
                "location_type_code"
            ]

        )


        df_report[
            "Location"
        ] = [

            get_workout_enum_label(
                value,
                WORKOUT_LOCATION_LABELS,
                "Unknown"
            )

            for value in df_workouts[
                "location_type_code"
            ]

        ]


        # ----------------------------------------------------
        # DURATION
        # ----------------------------------------------------

        duration_seconds = pd.to_numeric(

            df_workouts[
                "duration_seconds"
            ],

            errors="coerce"

        )


        df_report[
            "Workout Duration"
        ] = (

            duration_seconds
            .apply(
                workout_seconds_to_hms
            )

        )


        # ----------------------------------------------------
        # TOTAL SAMPLE TIME
        # ----------------------------------------------------

        sample_start = pd.to_numeric(

            df_workouts[
                "sample_start_cocoa"
            ],

            errors="coerce"

        )


        sample_end = pd.to_numeric(

            df_workouts[
                "sample_end_cocoa"
            ],

            errors="coerce"

        )


        sample_duration = (

            sample_end
            -
            sample_start

        )


        df_report[
            "Total Time Duration"
        ] = (

            sample_duration
            .apply(
                workout_seconds_to_hms
            )

        )


        # ----------------------------------------------------
        # DISTANCE
        # ----------------------------------------------------

        distance_km = pd.to_numeric(

            df_workouts[
                "total_distance_km"
            ],

            errors="coerce"

        )


        df_report[
            "Total Distance (km)"
        ] = (

            distance_km.round(
                2
            )

        )


        df_report[
            "Total Distance (miles)"
        ] = (

            distance_km
            .apply(
                workout_km_to_miles
            )

        )


        # ----------------------------------------------------
        # GOAL
        # ----------------------------------------------------

        df_report[
            "Goal Type Code"
        ] = (

            df_workouts[
                "goal_type_code"
            ]

        )


        df_report[
            "Goal Type"
        ] = [

            get_workout_enum_label(
                value,
                WORKOUT_GOAL_LABELS,
                "Unknown"
            )

            for value in df_workouts[
                "goal_type_code"
            ]

        ]


        df_report[
            "Goal"
        ] = (

            df_workouts[
                "goal_value"
            ]

        )


        # ----------------------------------------------------
        # ENERGY
        # ----------------------------------------------------

        df_report[
            "Total Active Energy (kcal)"
        ] = (

            pd.to_numeric(
                df_workouts[
                    "total_active_kcal"
                ],
                errors="coerce"
            )

        )


        df_report[
            "Total Resting Energy (kcal)"
        ] = (

            pd.to_numeric(
                df_workouts[
                    "total_resting_kcal"
                ],
                errors="coerce"
            )

        )


        # ----------------------------------------------------
        # METS
        # ----------------------------------------------------

        df_report[
            "Average METs"
        ] = (

            df_workouts[
                "avg_mets"
            ]

        )


        # ----------------------------------------------------
        # HEART RATE
        # ----------------------------------------------------

        df_report[
            "Min Heart Rate (BPM)"
        ] = (

            df_workouts[
                "min_hr_bpm"
            ]

        )


        df_report[
            "Max Heart Rate (BPM)"
        ] = (

            df_workouts[
                "max_hr_bpm"
            ]

        )


        df_report[
            "Average Heart Rate (BPM)"
        ] = (

            df_workouts[
                "avg_hr_bpm"
            ]

        )


        # ----------------------------------------------------
        # WEATHER
        # ----------------------------------------------------

        df_report[
            "Temperature (F)"
        ] = (

            df_workouts[
                "temp_f"
            ]

        )


        df_report[
            "Temperature (C)"
        ] = (

            df_workouts[
                "temp_f"
            ]
            .apply(
                workout_fahrenheit_to_celsius
            )

        )


        df_report[
            "Humidity (%)"
        ] = (

            df_workouts[
                "humidity_pct"
            ]

        )


        # ----------------------------------------------------
        # LOCATION COORDINATES
        # ----------------------------------------------------

        df_report[
            "Latitude"
        ] = (

            df_workouts[
                "lat"
            ]

        )


        df_report[
            "Longitude"
        ] = (

            df_workouts[
                "lon"
            ]

        )


        # ----------------------------------------------------
        # ELEVATION
        # ----------------------------------------------------

        df_report[
            "Min Ground Elevation (m)"
        ] = (

            df_workouts[
                "min_elev_m"
            ]

        )


        df_report[
            "Max Ground Elevation (m)"
        ] = (

            df_workouts[
                "max_elev_m"
            ]

        )


        # ----------------------------------------------------
        # PROVENANCE
        # ----------------------------------------------------

        df_report[
            "Hardware"
        ] = (

            df_workouts[
                "hardware"
            ]

        )


        df_report[
            "Source"
        ] = (

            df_workouts[
                "source_name"
            ]

        )


        df_report[
            "Software Version"
        ] = (

            df_workouts[
                "software_version"
            ]

        )


        df_report[
            "Timezone"
        ] = (

            df_workouts[
                "timezone_name"
            ]

        )


        # ----------------------------------------------------
        # LEGACY ONLY FIELDS
        # ----------------------------------------------------

        df_report[
            "Total Energy Burned (kcal)"
        ] = None

        df_report[
            "Total Basal Energy Burned (kcal)"
        ] = None


    # ========================================================
    # IOS 13-15
    # ========================================================

    else:


        # ----------------------------------------------------
        # TIMESTAMP
        # ----------------------------------------------------

        df_report[
            "Start Timestamp"
        ] = (

            df_workouts[
                "start_date"
            ]
            .apply(
                parse_cocoa_datetime
            )

        )


        df_report[
            "End Timestamp"
        ] = (

            df_workouts[
                "end_date"
            ]
            .apply(
                parse_cocoa_datetime
            )

        )


        df_report[
            "Added Timestamp"
        ] = None


        # ----------------------------------------------------
        # ACTIVITY
        # ----------------------------------------------------

        df_report[
            "Activity Type Code"
        ] = (

            df_workouts[
                "activity_type"
            ]

        )


        df_report[
            "Activity"
        ] = [

            get_workout_enum_label(
                value,
                WORKOUT_ACTIVITY_LABELS,
                "OTHER"
            )

            for value in df_workouts[
                "activity_type"
            ]

        ]


        # Legacy tidak menyediakan location_type

        df_report[
            "Location Type Code"
        ] = None

        df_report[
            "Location"
        ] = None


        # ----------------------------------------------------
        # DURATION
        # ----------------------------------------------------

        duration_seconds = pd.to_numeric(

            df_workouts[
                "duration"
            ],

            errors="coerce"

        )


        df_report[
            "Workout Duration"
        ] = (

            duration_seconds
            .apply(
                workout_seconds_to_hms
            )

        )


        # Legacy plugin tidak menghasilkan field ini

        df_report[
            "Total Time Duration"
        ] = None


        # ----------------------------------------------------
        # DISTANCE
        # ----------------------------------------------------

        distance_km = pd.to_numeric(

            df_workouts[
                "total_distance"
            ],

            errors="coerce"

        )


        df_report[
            "Total Distance (km)"
        ] = (

            distance_km
            .round(2)

        )


        df_report[
            "Total Distance (miles)"
        ] = (

            distance_km
            .apply(
                workout_km_to_miles
            )

        )


        # ----------------------------------------------------
        # GOAL
        # ----------------------------------------------------

        df_report[
            "Goal Type Code"
        ] = (

            df_workouts[
                "goal_type"
            ]

        )


        df_report[
            "Goal Type"
        ] = [

            get_workout_enum_label(
                value,
                WORKOUT_GOAL_LABELS,
                "Unknown"
            )

            for value in df_workouts[
                "goal_type"
            ]

        ]


        df_report[
            "Goal"
        ] = (

            df_workouts[
                "goal"
            ]

        )


        # ----------------------------------------------------
        # LEGACY ENERGY
        # ----------------------------------------------------

        df_report[
            "Total Energy Burned (kcal)"
        ] = (

            df_workouts[
                "total_energy_burned"
            ]

        )


        df_report[
            "Total Basal Energy Burned (kcal)"
        ] = (

            df_workouts[
                "total_basal_energy_burned"
            ]

        )


        # ----------------------------------------------------
        # IOS 16-17 ONLY FIELDS
        # ----------------------------------------------------

        df_report[
            "Total Active Energy (kcal)"
        ] = None

        df_report[
            "Total Resting Energy (kcal)"
        ] = None

        df_report[
            "Average METs"
        ] = None

        df_report[
            "Min Heart Rate (BPM)"
        ] = None

        df_report[
            "Max Heart Rate (BPM)"
        ] = None

        df_report[
            "Average Heart Rate (BPM)"
        ] = None

        df_report[
            "Temperature (F)"
        ] = None

        df_report[
            "Temperature (C)"
        ] = None

        df_report[
            "Humidity (%)"
        ] = None

        df_report[
            "Latitude"
        ] = None

        df_report[
            "Longitude"
        ] = None

        df_report[
            "Min Ground Elevation (m)"
        ] = None

        df_report[
            "Max Ground Elevation (m)"
        ] = None

        df_report[
            "Hardware"
        ] = None

        df_report[
            "Source"
        ] = None

        df_report[
            "Software Version"
        ] = None

        df_report[
            "Timezone"
        ] = None


    # ========================================================
    # COMMON REPORT FIELDS
    # ========================================================

    df_report[
        "Workout Schema"
    ] = (

        df_workouts[
            "workout_schema"
        ]

    )


    if major_version in (16, 17):

        df_report[
            "Source Database"
        ] = (
            "healthdb_secure.sqlite + healthdb.sqlite"
        )

    else:

        df_report[
            "Source Database"
        ] = (
            "healthdb_secure.sqlite"
        )


    workouts_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Workouts selesai."
)

✅ Format laporan Workouts selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT WORKOUTS
# ============================================================


for version, df_report in workouts_reports.items():

    print()
    print("=" * 70)

    print(
        f"🏋️ WORKOUTS REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Workouts: "
        f"{len(df_report)}"
    )

======================================================================
🏋️ WORKOUTS REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Activity Type Code,Activity,Location Type Code,Location,Workout Duration,Total Time Duration,Total Distance (km),...,Latitude,Longitude,Min Ground Elevation (m),Max Ground Elevation (m),Hardware,Source,Software Version,Timezone,Workout Schema,Source Database
0,2020-03-27 18:57:39.362805+00:00,2020-03-27 19:15:39.483302+00:00,None,37,RUNNING,None,None,00:18:00,None,3.25,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
1,2020-03-28 14:41:25.478880+00:00,2020-03-28 14:58:44.759550+00:00,None,37,RUNNING,None,None,00:17:19,None,3.24,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
2,2020-03-30 12:44:04.342283+00:00,2020-03-30 13:10:35.408500+00:00,None,37,RUNNING,None,None,00:26:31,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
3,2020-03-31 18:58:47.617404+00:00,2020-03-31 19:24:59.871179+00:00,None,37,RUNNING,None,None,00:26:12,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
4,2020-04-02 17:36:41.455536+00:00,2020-04-02 18:02:31.783423+00:00,None,37,RUNNING,None,None,00:25:50,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
5,2020-04-03 19:11:28.755963+00:00,2020-04-03 19:37:49.748519+00:00,None,37,RUNNING,None,None,00:26:20,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite

📊 Total Workouts: 6

======================================================================
🏋️ WORKOUTS REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Activity Type Code,Activity,Location Type Code,Location,Workout Duration,Total Time Duration,Total Distance (km),...,Latitude,Longitude,Min Ground Elevation (m),Max Ground Elevation (m),Hardware,Source,Software Version,Timezone,Workout Schema,Source Database
0,2020-03-27 18:57:39.362805+00:00,2020-03-27 19:15:39.483302+00:00,None,37,RUNNING,None,None,00:18:00,None,3.25,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
1,2020-03-28 14:41:25.478880+00:00,2020-03-28 14:58:44.759550+00:00,None,37,RUNNING,None,None,00:17:19,None,3.24,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
2,2020-03-30 12:44:04.342283+00:00,2020-03-30 13:10:35.408500+00:00,None,37,RUNNING,None,None,00:26:31,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
3,2020-03-31 18:58:47.617404+00:00,2020-03-31 19:24:59.871179+00:00,None,37,RUNNING,None,None,00:26:12,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
4,2020-04-02 17:36:41.455536+00:00,2020-04-02 18:02:31.783423+00:00,None,37,RUNNING,None,None,00:25:50,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
5,2020-04-03 19:11:28.755963+00:00,2020-04-03 19:37:49.748519+00:00,None,37,RUNNING,None,None,00:26:20,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite

📊 Total Workouts: 6

======================================================================
🏋️ WORKOUTS REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Activity Type Code,Activity,Location Type Code,Location,Workout Duration,Total Time Duration,Total Distance (km),...,Latitude,Longitude,Min Ground Elevation (m),Max Ground Elevation (m),Hardware,Source,Software Version,Timezone,Workout Schema,Source Database
0,2020-03-27 18:57:39.362805+00:00,2020-03-27 19:15:39.483302+00:00,None,37,RUNNING,None,None,00:18:00,None,3.25,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
1,2020-03-28 14:41:25.478880+00:00,2020-03-28 14:58:44.759550+00:00,None,37,RUNNING,None,None,00:17:19,None,3.24,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
2,2020-03-30 12:44:04.342283+00:00,2020-03-30 13:10:35.408500+00:00,None,37,RUNNING,None,None,00:26:31,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
3,2020-03-31 18:58:47.617404+00:00,2020-03-31 19:24:59.871179+00:00,None,37,RUNNING,None,None,00:26:12,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
4,2020-04-02 17:36:41.455536+00:00,2020-04-02 18:02:31.783423+00:00,None,37,RUNNING,None,None,00:25:50,None,4.85,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
5,2020-04-03 19:11:28.755963+00:00,2020-04-03 19:37:49.748519+00:00,None,37,RUNNING,None,None,00:26:20,None,4.86,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
6,2021-01-24 16:30:31.596173+00:00,2021-01-24 16:53:17.098130+00:00,None,37,RUNNING,None,None,00:22:45,None,4.89,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
7,2021-01-30 18:52:14.496385+00:00,2021-01-30 19:14:53.558387+00:00,None,37,RUNNING,None,None,00:22:39,None,4.98,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
8,2021-01-30 19:15:11.708411+00:00,2021-01-30 19:28:20.452524+00:00,None,52,WALKING,None,None,00:13:08,None,1.21,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
9,2021-02-06 20:24:32.990701+00:00,2021-02-06 20:40:52.495825+00:00,None,52,WALKING,None,None,00:16:19,None,1.37,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
10,2021-02-17 19:27:12+00:00,2021-02-17 19:39:05.734009+00:00,None,37,RUNNING,None,None,00:11:53,None,2.49,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
11,2021-02-17 19:40:01+00:00,2021-02-17 19:50:06.827026+00:00,None,52,WALKING,None,None,00:10:05,None,0.92,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
12,2023-04-15 14:34:28+00:00,2023-04-15 15:00:29.053955+00:00,None,37,RUNNING,None,None,00:26:01,None,5.30,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
13,2023-04-16 16:45:40+00:00,2023-04-16 17:10:02.031982+00:00,None,37,RUNNING,None,None,00:24:22,None,4.99,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
14,2023-04-17 15:19:54+00:00,2023-04-17 15:45:57.767944+00:00,None,37,RUNNING,None,None,00:26:03,None,5.36,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite
15,2023-04-18 16:42:39+00:00,2023-04-18 17:08:14.352051+00:00,None,37,RUNNING,None,None,00:25:35,None,5.32,...,None,None,None,None,None,None,None,None,Legacy Workouts iOS 13-15,healthdb_secure.sqlite

📊 Total Workouts: 16

======================================================================
🏋️ WORKOUTS REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Activity Type Code,Activity,Location Type Code,Location,Workout Duration,Total Time Duration,Total Distance (km),...,Min Ground Elevation (m),Max Ground Elevation (m),Hardware,Source,Software Version,Timezone,Total Energy Burned (kcal),Total Basal Energy Burned (kcal),Workout Schema,Source Database
0,2020-03-27 18:57:39.362805+00:00,2020-03-27 19:15:39.483302+00:00,2020-03-27 19:15:40.176325+00:00,37,RUNNING,3,Outdoor,00:18:00,00:18:00,3.25,...,96.41,106.80,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
1,2020-03-28 14:41:25.478880+00:00,2020-03-28 14:58:44.759550+00:00,2020-03-28 14:58:45.376565+00:00,37,RUNNING,3,Outdoor,00:17:19,00:17:19,3.24,...,92.30,109.85,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
2,2020-03-30 12:44:04.342283+00:00,2020-03-30 13:10:35.408500+00:00,2020-03-30 13:10:36.200997+00:00,37,RUNNING,3,Outdoor,00:26:31,00:26:31,4.85,...,77.75,110.21,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
3,2020-03-31 18:58:47.617404+00:00,2020-03-31 19:24:59.871179+00:00,2020-03-31 19:25:00.662640+00:00,37,RUNNING,3,Outdoor,00:26:12,00:26:12,4.86,...,78.00,109.59,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
4,2020-04-02 17:36:41.455536+00:00,2020-04-02 18:02:31.783423+00:00,2020-04-02 18:02:32.804978+00:00,37,RUNNING,3,Outdoor,00:25:50,00:25:50,4.85,...,79.27,109.78,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
5,2020-04-03 19:11:28.755963+00:00,2020-04-03 19:37:49.748519+00:00,2020-04-03 19:37:50.647402+00:00,37,RUNNING,3,Outdoor,00:26:20,00:26:20,4.86,...,77.93,111.20,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
6,2021-01-24 16:30:31.596173+00:00,2021-01-24 16:53:17.098130+00:00,2021-01-24 16:53:17.888833+00:00,37,RUNNING,3,Outdoor,00:22:45,00:22:45,4.89,...,71.76,110.90,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
7,2021-01-30 18:52:14.496385+00:00,2021-01-30 19:14:53.558387+00:00,2021-01-30 19:14:54.492565+00:00,37,RUNNING,3,Outdoor,00:22:39,00:22:39,4.98,...,73.94,111.78,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
8,2021-01-30 19:15:11.708411+00:00,2021-01-30 19:28:20.452524+00:00,2021-01-30 19:28:21.009356+00:00,52,WALKING,3,Outdoor,00:13:08,00:13:08,1.21,...,100.52,106.43,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
9,2021-02-06 20:24:32.990701+00:00,2021-02-06 20:40:52.495825+00:00,2021-02-06 20:40:53.361849+00:00,52,WALKING,3,Outdoor,00:16:19,00:16:19,1.37,...,94.99,102.39,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
10,2021-02-17 19:27:12+00:00,2021-02-17 19:39:05.734009+00:00,2021-02-20 14:03:16.810504+00:00,37,RUNNING,3,Outdoor,00:11:53,00:11:53,2.49,...,NaN,NaN,,Connect,31,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
11,2021-02-17 19:40:01+00:00,2021-02-17 19:50:06.827026+00:00,2021-02-20 14:03:16.790732+00:00,52,WALKING,3,Outdoor,00:10:05,00:10:05,0.92,...,NaN,NaN,,Connect,31,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
12,2023-04-15 14:34:28+00:00,2023-04-15 15:00:29.053955+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:26:01,00:26:01,5.30,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
13,2023-04-16 16:45:40+00:00,2023-04-16 17:10:02.031982+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:24:22,00:24:22,4.99,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
14,2023-04-17 15:19:54+00:00,2023-04-17 15:45:57.767944+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:26:03,00:26:03,5.36,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
15,2023-04-18 16:42:39+00:00,2023-04-18 17:08:14.352051+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:25:35,00:25:35,5.32,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
16,2023-07-08 11:47:19.070725+00:00,2023-07-08 12:12:48.939034+00:00,2023-07-08 12:12:49.680085+00:00,37,RUNNING,3,Outdoor,00:25:29,00:25:29,4.89,...,90.06,122.67,"Watch4,3",Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
17,2023-07-10 11:46:53.102611+00:00,2023-07-10 12:12:10.348362+00:00,2023-07-10 12:12:11.096117+00:00,37,RUNNING,3,Outdoor,00:25:17,00:25:17,4.93,...,90.30,121.84,"Watch4,3",Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
18,2023-07-13 11:47:37.424167+00:00,2023-07-13 12:13:06.199234+00:00,2023-07-13 12:13:06.992652+00:00,37,RUNNING,3,Outdoor,00:25:28,00:25:28,4.90,...,89.75,122.14,"Watch4,3",Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
19,2023-07-19 11:16:13.397017+00:00,2023-07-19 11:42:05.379234+00:00,2023-07-19 11:42:06.158009+00:00,37,RUNNING,3,Outdoor,00:25:51,00:25:51,4.89,...,91.20,122.01,"Watch4,3",Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Workouts: 25

======================================================================
🏋️ WORKOUTS REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Added Timestamp,Activity Type Code,Activity,Location Type Code,Location,Workout Duration,Total Time Duration,Total Distance (km),...,Min Ground Elevation (m),Max Ground Elevation (m),Hardware,Source,Software Version,Timezone,Total Energy Burned (kcal),Total Basal Energy Burned (kcal),Workout Schema,Source Database
0,2020-03-27 18:57:39.362805+00:00,2020-03-27 19:15:39.483302+00:00,2020-03-27 19:15:40.176325+00:00,37,RUNNING,3,Outdoor,00:18:00,00:18:00,3.25,...,96.41,106.80,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
1,2020-03-28 14:41:25.478880+00:00,2020-03-28 14:58:44.759550+00:00,2020-03-28 14:58:45.376565+00:00,37,RUNNING,3,Outdoor,00:17:19,00:17:19,3.24,...,92.30,109.85,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
2,2020-03-30 12:44:04.342283+00:00,2020-03-30 13:10:35.408500+00:00,2020-03-30 13:10:36.200997+00:00,37,RUNNING,3,Outdoor,00:26:31,00:26:31,4.85,...,77.75,110.21,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
3,2020-03-31 18:58:47.617404+00:00,2020-03-31 19:24:59.871179+00:00,2020-03-31 19:25:00.662640+00:00,37,RUNNING,3,Outdoor,00:26:12,00:26:12,4.86,...,78.00,109.59,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
4,2020-04-02 17:36:41.455536+00:00,2020-04-02 18:02:31.783423+00:00,2020-04-02 18:02:32.804978+00:00,37,RUNNING,3,Outdoor,00:25:50,00:25:50,4.85,...,79.27,109.78,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
5,2020-04-03 19:11:28.755963+00:00,2020-04-03 19:37:49.748519+00:00,2020-04-03 19:37:50.647402+00:00,37,RUNNING,3,Outdoor,00:26:20,00:26:20,4.86,...,77.93,111.20,"Watch4,3",This Is’s Apple Watch,6.1.3,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
6,2021-01-24 16:30:31.596173+00:00,2021-01-24 16:53:17.098130+00:00,2021-01-24 16:53:17.888833+00:00,37,RUNNING,3,Outdoor,00:22:45,00:22:45,4.89,...,71.76,110.90,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
7,2021-01-30 18:52:14.496385+00:00,2021-01-30 19:14:53.558387+00:00,2021-01-30 19:14:54.492565+00:00,37,RUNNING,3,Outdoor,00:22:39,00:22:39,4.98,...,73.94,111.78,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
8,2021-01-30 19:15:11.708411+00:00,2021-01-30 19:28:20.452524+00:00,2021-01-30 19:28:21.009356+00:00,52,WALKING,3,Outdoor,00:13:08,00:13:08,1.21,...,100.52,106.43,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
9,2021-02-06 20:24:32.990701+00:00,2021-02-06 20:40:52.495825+00:00,2021-02-06 20:40:53.361849+00:00,52,WALKING,3,Outdoor,00:16:19,00:16:19,1.37,...,94.99,102.39,"Watch4,3",This Is’s Apple Watch,7.2,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
10,2021-02-17 19:27:12+00:00,2021-02-17 19:39:05.734009+00:00,2021-02-20 14:03:16.810504+00:00,37,RUNNING,3,Outdoor,00:11:53,00:11:53,2.49,...,NaN,NaN,,Connect,31,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
11,2021-02-17 19:40:01+00:00,2021-02-17 19:50:06.827026+00:00,2021-02-20 14:03:16.790732+00:00,52,WALKING,3,Outdoor,00:10:05,00:10:05,0.92,...,NaN,NaN,,Connect,31,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
12,2023-04-15 14:34:28+00:00,2023-04-15 15:00:29.053955+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:26:01,00:26:01,5.30,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
13,2023-04-16 16:45:40+00:00,2023-04-16 17:10:02.031982+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:24:22,00:24:22,4.99,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
14,2023-04-17 15:19:54+00:00,2023-04-17 15:45:57.767944+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:26:03,00:26:03,5.36,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
15,2023-04-18 16:42:39+00:00,2023-04-18 17:08:14.352051+00:00,2023-04-19 18:30:14.216442+00:00,37,RUNNING,3,Outdoor,00:25:35,00:25:35,5.32,...,NaN,NaN,,Connect,36,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
16,2023-07-08 11:47:19.070725+00:00,2023-07-08 12:12:48.939034+00:00,2023-07-08 12:12:49.680085+00:00,37,RUNNING,3,Outdoor,00:25:29,00:25:29,4.89,...,90.06,122.67,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
17,2023-07-10 11:46:53.102611+00:00,2023-07-10 12:12:10.348362+00:00,2023-07-10 12:12:11.096117+00:00,37,RUNNING,3,Outdoor,00:25:17,00:25:17,4.93,...,90.30,121.84,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
18,2023-07-13 11:47:37.424167+00:00,2023-07-13 12:13:06.199234+00:00,2023-07-13 12:13:06.992652+00:00,37,RUNNING,3,Outdoor,00:25:28,00:25:28,4.90,...,89.75,122.14,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite
19,2023-07-19 11:16:13.397017+00:00,2023-07-19 11:42:05.379234+00:00,2023-07-19 11:42:06.158009+00:00,37,RUNNING,3,Outdoor,00:25:51,00:25:51,4.89,...,91.20,122.01,"Watch4,3",This Is’s Apple Watch,8.8.1,America/New_York,None,None,Workout Activities iOS 16-17,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Workouts: 29

# **Fitur Wrist Temperature**

In [ ]:
# ============================================================
# VERIFIKASI STRUKTUR WRIST TEMPERATURE
# ============================================================

print()
print("=" * 70)
print("🌡️ VERIFIKASI WRIST TEMPERATURE")
print("=" * 70)


wrist_temp_secure_tables = [
    "samples",
    "quantity_samples",
    "objects",
    "data_provenances",
    "metadata_keys",
    "metadata_values"
]


wrist_temp_healthdb_tables = [
    "sources",
    "source_devices"
]


for dataset in target_datasets:

    version = dataset[
        "version"
    ]

    secure_tables = dataset[
        "healthdb_secure_tables"
    ]

    healthdb_tables = dataset[
        "healthdb_tables"
    ]


    print()
    print(
        f"📱 {version}"
    )


    # ========================================================
    # HEALTHDB_SECURE.SQLITE
    # ========================================================

    print(
        "   📂 healthdb_secure.sqlite"
    )


    for table_name in wrist_temp_secure_tables:

        if table_name in secure_tables:

            print(
                f"      {table_name:<22}: ✅"
            )

        else:

            print(
                f"      {table_name:<22}: ❌"
            )


    # ========================================================
    # HEALTHDB.SQLITE
    # ========================================================

    print(
        "   📂 healthdb.sqlite"
    )


    for table_name in wrist_temp_healthdb_tables:

        if table_name in healthdb_tables:

            print(
                f"      {table_name:<22}: ✅"
            )

        else:

            print(
                f"      {table_name:<22}: ❌"
            )


print()
print("=" * 70)

======================================================================
🌡️ VERIFIKASI WRIST TEMPERATURE
======================================================================

📱 iOS 13.3.1
   📂 healthdb_secure.sqlite
      samples               : ✅
      quantity_samples      : ✅
      objects               : ✅
      data_provenances      : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
   📂 healthdb.sqlite
      sources               : ✅
      source_devices        : ✅

📱 iOS 13.4.1
   📂 healthdb_secure.sqlite
      samples               : ✅
      quantity_samples      : ✅
      objects               : ✅
      data_provenances      : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
   📂 healthdb.sqlite
      sources               : ✅
      source_devices        : ✅

📱 iOS 15
   📂 healthdb_secure.sqlite
      samples               : ✅
      quantity_samples      : ✅
      objects               : ✅
      data_provenances      : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
   📂 healthdb.sqlite
      sources               : ✅
      source_devices        : ✅

📱 iOS 16
   📂 healthdb_secure.sqlite
      samples               : ✅
      quantity_samples      : ✅
      objects               : ✅
      data_provenances      : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
   📂 healthdb.sqlite
      sources               : ✅
      source_devices        : ✅

📱 iOS 17
   📂 healthdb_secure.sqlite
      samples               : ✅
      quantity_samples      : ✅
      objects               : ✅
      data_provenances      : ✅
      metadata_keys         : ✅
      metadata_values       : ✅
   📂 healthdb.sqlite
      sources               : ✅
      source_devices        : ✅

======================================================================

In [ ]:
# ============================================================
# HELPER TIMESTAMP WRIST TEMPERATURE
# ============================================================


def parse_wrist_cocoa_datetime(
    value
):

    """
    Parse Cocoa timestamp Wrist Temperature.

    Mendukung:
        Cocoa timestamp normal
        nilai timestamp besar > 1e12
    """

    if value is None:

        return None


    try:

        if pd.isna(value):

            return None

    except TypeError:

        pass


    try:

        timestamp = float(
            value
        )

    except (
        TypeError,
        ValueError
    ):

        return None


    # Sesuai logika plugin Plaso

    if timestamp > 1e12:

        timestamp = (
            timestamp
            /
            1e9
        )


    if timestamp == 0:

        return None


    return parse_cocoa_datetime(
        timestamp
    )


print(
    "✅ Helper timestamp Wrist Temperature siap."
)

✅ Helper timestamp Wrist Temperature siap.

In [ ]:
# ============================================================
# HELPER CLEAN TEXT WRIST TEMPERATURE
# ============================================================


def clean_wrist_text(
    value
):

    """
    Membersihkan text artifact pada metadata device/source.
    """

    if value is None:

        return None


    try:

        if pd.isna(value):

            return None

    except TypeError:

        pass


    text = (
        str(value)
        .replace(
            "\xa0",
            " "
        )
        .strip()
    )


    try:

        fixed = (

            text
            .encode(
                "latin-1",
                errors="ignore"
            )
            .decode(
                "utf-8",
                errors="ignore"
            )

        )


        if (
            fixed
            and
            len(fixed) >= len(text) - 1
        ):

            text = fixed


    except (
        UnicodeEncodeError,
        UnicodeDecodeError
    ):

        pass


    return (
        text
        if text
        else None
    )


print(
    "✅ Helper clean text Wrist Temperature siap."
)

✅ Helper clean text Wrist Temperature siap.

In [ ]:
# ============================================================
# TAHAP 110 - EXTRACTOR WRIST TEMPERATURE
# ============================================================


def extract_wrist_temperature(
    secure_database_path,
    health_database_path
):

    """
    Extract Apple Health Wrist Temperature.

    Databases:
        healthdb_secure.sqlite
        healthdb.sqlite

    healthdb_secure.sqlite:
        samples
        quantity_samples
        objects
        data_provenances
        metadata_keys
        metadata_values

    healthdb.sqlite:
        sources
        source_devices

    data_type:
        70
    """


    conn = open_workouts_cross_database_readonly(
        secure_database_path,
        health_database_path
    )


    query = """

    WITH surface_temp AS (

        SELECT

            mv.object_id,

            mv.numerical_value

        FROM secure_db.metadata_values AS mv


        JOIN secure_db.metadata_keys AS mk

            ON mv.key_id =
               mk.ROWID


        WHERE

            mk.key =
            '_HKPrivateMetadataKeySkinSurfaceTemperature'

    ),


    alg_ver AS (

        SELECT

            mv.object_id,

            mv.numerical_value

        FROM secure_db.metadata_values AS mv


        JOIN secure_db.metadata_keys AS mk

            ON mv.key_id =
               mk.ROWID


        WHERE

            mk.key =
            'HKAlgorithmVersion'

    )


    SELECT

        samples.start_date
            AS start_date,


        samples.end_date
            AS end_date,


        objects.creation_date
            AS creation_date,


        quantity_samples.quantity
            AS wrist_temp_c,


        (
            quantity_samples.quantity
            * 1.8
        )
        + 32
            AS wrist_temp_f,


        src.name
            AS source,


        alg_ver.numerical_value
            AS alg_version,


        surface_temp.numerical_value
            AS surf_temp_c,


        (
            surface_temp.numerical_value
            * 1.8
        )
        + 32
            AS surf_temp_f,


        sd.name
            AS device_name,


        sd.manufacturer
            AS device_manufacturer,


        sd.model
            AS device_model,


        sd.hardware
            AS hardware_version,


        sd.software
            AS software_version


    FROM secure_db.samples AS samples


    LEFT JOIN secure_db.quantity_samples
        AS quantity_samples

        ON quantity_samples.data_id =
           samples.data_id


    LEFT JOIN secure_db.objects
        AS objects

        ON samples.data_id =
           objects.data_id


    LEFT JOIN secure_db.data_provenances
        AS data_provenances

        ON objects.provenance =
           data_provenances.ROWID


    LEFT JOIN surface_temp

        ON surface_temp.object_id =
           samples.data_id


    LEFT JOIN alg_ver

        ON alg_ver.object_id =
           samples.data_id


    LEFT JOIN health_db.sources AS src

        ON src.ROWID =
           data_provenances.source_id


    LEFT JOIN health_db.source_devices AS sd

        ON sd.ROWID =
           data_provenances.device_id


    WHERE

        samples.data_type = 70


    ORDER BY

        samples.start_date DESC

    """


    df = pd.read_sql_query(
        query,
        conn
    )


    conn.close()


    return df


print(
    "✅ Extractor Wrist Temperature siap."
)

✅ Extractor Wrist Temperature siap.

In [ ]:
# ============================================================
# EKSTRAKSI WRIST TEMPERATURE
# ============================================================


wrist_temperature_results = {}


for dataset in target_datasets:

    version = dataset[
        "version"
    ]


    print()
    print("=" * 70)

    print(
        f"🌡️ WRIST TEMPERATURE - {version}"
    )

    print("=" * 70)


    try:

        secure_db_path = dataset[
            "healthdb_secure"
        ]

        healthdb_path = dataset[
            "healthdb"
        ]


        df_wrist_temp = extract_wrist_temperature(

            secure_db_path,

            healthdb_path

        )


        wrist_temperature_results[
            version
        ] = df_wrist_temp


        print(
            "✅ Ekstraksi berhasil"
        )

        print(
            f"📊 Total Wrist Temperature Records: "
            f"{len(df_wrist_temp)}"
        )

        print(
            "📂 Source: "
            "healthdb_secure.sqlite "
            "+ healthdb.sqlite"
        )


    except Exception as e:

        print(
            f"❌ Error {version}: "
            f"{type(e).__name__}: {e}"
        )

======================================================================
🌡️ WRIST TEMPERATURE - iOS 13.3.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Wrist Temperature Records: 213
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

======================================================================
🌡️ WRIST TEMPERATURE - iOS 13.4.1
======================================================================
✅ Ekstraksi berhasil
📊 Total Wrist Temperature Records: 266
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

======================================================================
🌡️ WRIST TEMPERATURE - iOS 15
======================================================================
✅ Ekstraksi berhasil
📊 Total Wrist Temperature Records: 1230
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

======================================================================
🌡️ WRIST TEMPERATURE - iOS 16
======================================================================
✅ Ekstraksi berhasil
📊 Total Wrist Temperature Records: 1603
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

======================================================================
🌡️ WRIST TEMPERATURE - iOS 17
======================================================================
✅ Ekstraksi berhasil
📊 Total Wrist Temperature Records: 1688
📂 Source: healthdb_secure.sqlite + healthdb.sqlite

In [ ]:
# ============================================================
# PREVIEW RAW WRIST TEMPERATURE
# ============================================================


for version, df_wrist_temp in wrist_temperature_results.items():

    print()
    print("=" * 70)

    print(
        f"🌡️ RAW WRIST TEMPERATURE - {version}"
    )

    print("=" * 70)


    display(
        df_wrist_temp.head(20)
    )


    print()

    print(
        f"📊 Total Records: "
        f"{len(df_wrist_temp)}"
    )

======================================================================
🌡️ RAW WRIST TEMPERATURE - iOS 13.3.1
======================================================================

,start_date,end_date,creation_date,wrist_temp_c,wrist_temp_f,source,alg_version,surf_temp_c,surf_temp_f,device_name,device_manufacturer,device_model,hardware_version,software_version
0,608407200.0,608410800.0,6.084107e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
1,608403600.0,608407200.0,6.084059e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
2,608400000.0,608403600.0,6.084010e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
3,608396400.0,608400000.0,6.083991e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
4,608392800.0,608396400.0,6.083958e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
5,607636800.0,607640400.0,6.076368e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
6,607633200.0,607636800.0,6.076333e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
7,607629600.0,607633200.0,6.076301e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
8,607626000.0,607629600.0,6.076267e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
9,607622400.0,607626000.0,6.076224e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
10,607618800.0,607622400.0,6.076189e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
11,607615200.0,607618800.0,6.076159e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
12,607611600.0,607615200.0,6.076128e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
13,607608000.0,607611600.0,6.076081e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
14,607604400.0,607608000.0,6.076061e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
15,607600800.0,607604400.0,6.076034e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
16,607564800.0,607568400.0,6.075649e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
17,607561200.0,607564800.0,6.075613e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
18,607557600.0,607561200.0,6.075613e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3
19,607554000.0,607557600.0,6.075541e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3

📊 Total Records: 213

======================================================================
🌡️ RAW WRIST TEMPERATURE - iOS 13.4.1
======================================================================

,start_date,end_date,creation_date,wrist_temp_c,wrist_temp_f,source,alg_version,surf_temp_c,surf_temp_f,device_name,device_manufacturer,device_model,hardware_version,software_version
0,608742000.0,608745600.0,6.087424e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
1,608738400.0,608742000.0,6.087393e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
2,608734800.0,608738400.0,6.087348e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
3,608731200.0,608734800.0,6.087320e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
4,608727600.0,608731200.0,6.087313e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
5,608724000.0,608727600.0,6.087265e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
6,608688000.0,608691600.0,6.086901e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
7,608684400.0,608688000.0,6.086849e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
8,608680800.0,608684400.0,6.086810e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
9,608677200.0,608680800.0,6.086776e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
10,608673600.0,608677200.0,6.086740e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
11,608670000.0,608673600.0,6.086704e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
12,608666400.0,608670000.0,6.086669e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
13,608662800.0,608666400.0,6.086635e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
14,608659200.0,608662800.0,6.086598e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
15,608655600.0,608659200.0,6.086570e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
16,608652000.0,608655600.0,6.086537e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
17,608648400.0,608652000.0,6.086485e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
18,608644800.0,608648400.0,6.086451e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1
19,608641200.0,608644800.0,6.086448e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1

📊 Total Records: 266

======================================================================
🌡️ RAW WRIST TEMPERATURE - iOS 15
======================================================================

,start_date,end_date,creation_date,wrist_temp_c,wrist_temp_f,source,alg_version,surf_temp_c,surf_temp_f,device_name,device_manufacturer,device_model,hardware_version,software_version
0,635281200.0,635284800.0,6.353658e+08,None,None,iPhone,None,None,None,__NONE__,,,,
1,635281200.0,635284800.0,6.353658e+08,None,None,iPhone,None,None,None,__NONE__,,,,
2,635281200.0,635284800.0,6.353616e+08,None,None,iPhone,None,None,None,__NONE__,,,,
3,635281200.0,635284800.0,6.353614e+08,None,None,iPhone,None,None,None,__NONE__,,,,
4,635281200.0,635284800.0,6.353612e+08,None,None,iPhone,None,None,None,__NONE__,,,,
5,635281200.0,635284800.0,6.353612e+08,None,None,iPhone,None,None,None,__NONE__,,,,
6,634777200.0,634780800.0,6.347774e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
7,634773600.0,634777200.0,6.347742e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
8,634770000.0,634773600.0,6.347701e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
9,634766400.0,634770000.0,6.347699e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
10,634762800.0,634766400.0,6.347649e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
11,634759200.0,634762800.0,6.347598e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
12,634755600.0,634759200.0,6.347584e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
13,634752000.0,634755600.0,6.347521e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
14,634748400.0,634752000.0,6.347520e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
15,634744800.0,634748400.0,6.347448e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
16,634741200.0,634744800.0,6.347413e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
17,634737600.0,634741200.0,6.347383e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
18,634734000.0,634737600.0,6.347358e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2
19,634698000.0,634701600.0,6.347016e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2

📊 Total Records: 1230

======================================================================
🌡️ RAW WRIST TEMPERATURE - iOS 16
======================================================================

,start_date,end_date,creation_date,wrist_temp_c,wrist_temp_f,source,alg_version,surf_temp_c,surf_temp_f,device_name,device_manufacturer,device_model,hardware_version,software_version
0,711932400.0,711936000.0,7.119334e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
1,711928800.0,711932400.0,7.119291e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
2,711925200.0,711928800.0,7.119261e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
3,711921600.0,711925200.0,7.119251e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
4,711918000.0,711921600.0,7.119188e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
5,711914400.0,711918000.0,7.119148e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
6,711910800.0,711914400.0,7.119118e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
7,711907200.0,711910800.0,7.119098e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
8,711903600.0,711907200.0,7.119037e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
9,711900000.0,711903600.0,7.119007e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
10,711896400.0,711900000.0,7.118965e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
11,711892800.0,711896400.0,7.118928e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
12,711889200.0,711892800.0,7.118903e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
13,711885600.0,711889200.0,7.118892e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
14,711882000.0,711885600.0,7.118856e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
15,711878400.0,711882000.0,7.118822e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
16,711874800.0,711878400.0,7.118786e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
17,711871200.0,711874800.0,7.118751e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
18,711867600.0,711871200.0,7.118713e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1
19,711864000.0,711867600.0,7.118677e+08,None,None,Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1

📊 Total Records: 1603

======================================================================
🌡️ RAW WRIST TEMPERATURE - iOS 17
======================================================================

,start_date,end_date,creation_date,wrist_temp_c,wrist_temp_f,source,alg_version,surf_temp_c,surf_temp_f,device_name,device_manufacturer,device_model,hardware_version,software_version
0,743691600.0,743695200.0,7.436919e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
1,743688000.0,743691600.0,7.436891e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
2,743684400.0,743688000.0,7.436853e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
3,743680800.0,743684400.0,7.436844e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
4,743677200.0,743680800.0,7.436808e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
5,743673600.0,743677200.0,7.436773e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
6,743670000.0,743673600.0,7.436736e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
7,743666400.0,743670000.0,7.436701e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
8,743662800.0,743666400.0,7.436668e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
9,743659200.0,743662800.0,7.436631e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
10,743655600.0,743659200.0,7.436595e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
11,743652000.0,743655600.0,7.436556e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
12,743637600.0,743641200.0,7.436377e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
13,743634000.0,743637600.0,7.436340e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
14,743630400.0,743634000.0,7.436317e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
15,743626800.0,743630400.0,7.436269e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
16,743623200.0,743626800.0,7.436237e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
17,743619600.0,743623200.0,7.436198e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
18,743616000.0,743619600.0,7.436192e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3
19,743612400.0,743616000.0,7.436154e+08,None,None,This Is’s Apple Watch,None,None,None,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3

📊 Total Records: 1688

In [ ]:
# ============================================================
# FORMAT LAPORAN WRIST TEMPERATURE
# ============================================================


wrist_temperature_reports = {}


for version, df_wrist_temp in wrist_temperature_results.items():

    df_report = pd.DataFrame()


    # ========================================================
    # TIMESTAMPS
    # ========================================================

    df_report[
        "Start Timestamp"
    ] = (

        df_wrist_temp[
            "start_date"
        ]
        .apply(
            parse_wrist_cocoa_datetime
        )

    )


    df_report[
        "End Timestamp"
    ] = (

        df_wrist_temp[
            "end_date"
        ]
        .apply(
            parse_wrist_cocoa_datetime
        )

    )


    df_report[
        "Date Added"
    ] = (

        df_wrist_temp[
            "creation_date"
        ]
        .apply(
            parse_wrist_cocoa_datetime
        )

    )


    # ========================================================
    # WRIST TEMPERATURE
    # ========================================================

    df_report[
        "Wrist Temperature (C)"
    ] = (

        pd.to_numeric(
            df_wrist_temp[
                "wrist_temp_c"
            ],
            errors="coerce"
        )

    )


    df_report[
        "Wrist Temperature (F)"
    ] = (

        pd.to_numeric(
            df_wrist_temp[
                "wrist_temp_f"
            ],
            errors="coerce"
        )

    )


    # ========================================================
    # ALGORITHM VERSION
    # ========================================================

    df_report[
        "Algorithm Version"
    ] = (

        df_wrist_temp[
            "alg_version"
        ]

    )


    # ========================================================
    # SURFACE TEMPERATURE
    # ========================================================

    df_report[
        "Surface Temperature (C)"
    ] = (

        pd.to_numeric(
            df_wrist_temp[
                "surf_temp_c"
            ],
            errors="coerce"
        )

    )


    df_report[
        "Surface Temperature (F)"
    ] = (

        pd.to_numeric(
            df_wrist_temp[
                "surf_temp_f"
            ],
            errors="coerce"
        )

    )


    # ========================================================
    # SOURCE
    # ========================================================

    df_report[
        "Source"
    ] = (

        df_wrist_temp[
            "source"
        ]
        .apply(
            clean_wrist_text
        )

    )


    # ========================================================
    # DEVICE
    # ========================================================

    df_report[
        "Device Name"
    ] = (

        df_wrist_temp[
            "device_name"
        ]
        .apply(
            clean_wrist_text
        )

    )


    df_report[
        "Device Manufacturer"
    ] = (

        df_wrist_temp[
            "device_manufacturer"
        ]
        .apply(
            clean_wrist_text
        )

    )


    df_report[
        "Device Model"
    ] = (

        df_wrist_temp[
            "device_model"
        ]
        .apply(
            clean_wrist_text
        )

    )


    df_report[
        "Hardware Version"
    ] = (

        df_wrist_temp[
            "hardware_version"
        ]
        .apply(
            clean_wrist_text
        )

    )


    df_report[
        "Software Version"
    ] = (

        df_wrist_temp[
            "software_version"
        ]
        .apply(
            clean_wrist_text
        )

    )


    # ========================================================
    # SOURCE DATABASE
    # ========================================================

    df_report[
        "Source Database"
    ] = (
        "healthdb_secure.sqlite + healthdb.sqlite"
    )


    wrist_temperature_reports[
        version
    ] = df_report


print(
    "✅ Format laporan Wrist Temperature selesai."
)

✅ Format laporan Wrist Temperature selesai.

In [ ]:
# ============================================================
# PREVIEW REPORT WRIST TEMPERATURE
# ============================================================


for version, df_report in wrist_temperature_reports.items():

    print()
    print("=" * 70)

    print(
        f"🌡️ WRIST TEMPERATURE REPORT - {version}"
    )

    print("=" * 70)


    display(
        df_report.head(20)
    )


    print()

    print(
        f"📊 Total Records: "
        f"{len(df_report)}"
    )

======================================================================
🌡️ WRIST TEMPERATURE REPORT - iOS 13.3.1
======================================================================

,Start Timestamp,End Timestamp,Date Added,Wrist Temperature (C),Wrist Temperature (F),Algorithm Version,Surface Temperature (C),Surface Temperature (F),Source,Device Name,Device Manufacturer,Device Model,Hardware Version,Software Version,Source Database
0,2020-04-12 18:00:00+00:00,2020-04-12 19:00:00+00:00,2020-04-12 18:58:43.327600+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
1,2020-04-12 17:00:00+00:00,2020-04-12 18:00:00+00:00,2020-04-12 17:38:16.726913+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
2,2020-04-12 16:00:00+00:00,2020-04-12 17:00:00+00:00,2020-04-12 16:16:33.563748+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
3,2020-04-12 15:00:00+00:00,2020-04-12 16:00:00+00:00,2020-04-12 15:44:54.348847+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
4,2020-04-12 14:00:00+00:00,2020-04-12 15:00:00+00:00,2020-04-12 14:50:03.591781+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
5,2020-04-03 20:00:00+00:00,2020-04-03 21:00:00+00:00,2020-04-03 20:00:49.975758+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
6,2020-04-03 19:00:00+00:00,2020-04-03 20:00:00+00:00,2020-04-03 19:01:03.407034+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
7,2020-04-03 18:00:00+00:00,2020-04-03 19:00:00+00:00,2020-04-03 18:08:51.259661+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
8,2020-04-03 17:00:00+00:00,2020-04-03 18:00:00+00:00,2020-04-03 17:11:25.848258+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
9,2020-04-03 16:00:00+00:00,2020-04-03 17:00:00+00:00,2020-04-03 16:00:48.721076+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
10,2020-04-03 15:00:00+00:00,2020-04-03 16:00:00+00:00,2020-04-03 15:02:14.238483+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
11,2020-04-03 14:00:00+00:00,2020-04-03 15:00:00+00:00,2020-04-03 14:11:39.949821+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
12,2020-04-03 13:00:00+00:00,2020-04-03 14:00:00+00:00,2020-04-03 13:19:18.228193+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
13,2020-04-03 12:00:00+00:00,2020-04-03 13:00:00+00:00,2020-04-03 12:01:30.105042+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
14,2020-04-03 11:00:00+00:00,2020-04-03 12:00:00+00:00,2020-04-03 11:28:44.764410+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
15,2020-04-03 10:00:00+00:00,2020-04-03 11:00:00+00:00,2020-04-03 10:43:49.474864+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
16,2020-04-03 00:00:00+00:00,2020-04-03 01:00:00+00:00,2020-04-03 00:02:15.988152+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
17,2020-04-02 23:00:00+00:00,2020-04-03 00:00:00+00:00,2020-04-02 23:02:29.564946+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
18,2020-04-02 22:00:00+00:00,2020-04-02 23:00:00+00:00,2020-04-02 23:01:38.489841+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite
19,2020-04-02 21:00:00+00:00,2020-04-02 22:00:00+00:00,2020-04-02 21:01:02.201109+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.1.3,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Records: 213

======================================================================
🌡️ WRIST TEMPERATURE REPORT - iOS 13.4.1
======================================================================

,Start Timestamp,End Timestamp,Date Added,Wrist Temperature (C),Wrist Temperature (F),Algorithm Version,Surface Temperature (C),Surface Temperature (F),Source,Device Name,Device Manufacturer,Device Model,Hardware Version,Software Version,Source Database
0,2020-04-16 15:00:00+00:00,2020-04-16 16:00:00+00:00,2020-04-16 15:06:51.871307+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
1,2020-04-16 14:00:00+00:00,2020-04-16 15:00:00+00:00,2020-04-16 14:15:07.768917+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
2,2020-04-16 13:00:00+00:00,2020-04-16 14:00:00+00:00,2020-04-16 13:00:37.532451+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
3,2020-04-16 12:00:00+00:00,2020-04-16 13:00:00+00:00,2020-04-16 12:13:46.492723+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
4,2020-04-16 11:00:00+00:00,2020-04-16 12:00:00+00:00,2020-04-16 12:01:54.268142+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
5,2020-04-16 10:00:00+00:00,2020-04-16 11:00:00+00:00,2020-04-16 10:41:57.433875+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
6,2020-04-16 00:00:00+00:00,2020-04-16 01:00:00+00:00,2020-04-16 00:35:39.323171+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
7,2020-04-15 23:00:00+00:00,2020-04-16 00:00:00+00:00,2020-04-15 23:08:15.598599+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
8,2020-04-15 22:00:00+00:00,2020-04-15 23:00:00+00:00,2020-04-15 22:03:14.349897+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
9,2020-04-15 21:00:00+00:00,2020-04-15 22:00:00+00:00,2020-04-15 21:06:13.519618+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
10,2020-04-15 20:00:00+00:00,2020-04-15 21:00:00+00:00,2020-04-15 20:06:01.388398+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
11,2020-04-15 19:00:00+00:00,2020-04-15 20:00:00+00:00,2020-04-15 19:06:52.926552+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
12,2020-04-15 18:00:00+00:00,2020-04-15 19:00:00+00:00,2020-04-15 18:07:34.433065+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
13,2020-04-15 17:00:00+00:00,2020-04-15 18:00:00+00:00,2020-04-15 17:11:37.780578+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
14,2020-04-15 16:00:00+00:00,2020-04-15 17:00:00+00:00,2020-04-15 16:09:50.949995+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
15,2020-04-15 15:00:00+00:00,2020-04-15 16:00:00+00:00,2020-04-15 15:23:51.431397+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
16,2020-04-15 14:00:00+00:00,2020-04-15 15:00:00+00:00,2020-04-15 14:28:32.640255+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
17,2020-04-15 13:00:00+00:00,2020-04-15 14:00:00+00:00,2020-04-15 13:02:27.954891+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
18,2020-04-15 12:00:00+00:00,2020-04-15 13:00:00+00:00,2020-04-15 12:04:27.453434+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite
19,2020-04-15 11:00:00+00:00,2020-04-15 12:00:00+00:00,2020-04-15 12:00:37.623511+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",6.2.1,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Records: 266

======================================================================
🌡️ WRIST TEMPERATURE REPORT - iOS 15
======================================================================

,Start Timestamp,End Timestamp,Date Added,Wrist Temperature (C),Wrist Temperature (F),Algorithm Version,Surface Temperature (C),Surface Temperature (F),Source,Device Name,Device Manufacturer,Device Model,Hardware Version,Software Version,Source Database
0,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 18:30:46.085136+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
1,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 18:30:45.994616+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
2,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 17:19:17.273025+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
3,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 17:15:59.058992+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
4,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 17:13:58.698879+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
5,2021-02-17 19:00:00+00:00,2021-02-17 20:00:00+00:00,2021-02-18 17:13:58.679805+00:00,NaN,NaN,None,NaN,NaN,iPhone,__NONE__,None,None,None,None,healthdb_secure.sqlite + healthdb.sqlite
6,2021-02-11 23:00:00+00:00,2021-02-12 00:00:00+00:00,2021-02-11 23:04:05.961454+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
7,2021-02-11 22:00:00+00:00,2021-02-11 23:00:00+00:00,2021-02-11 22:09:32.408359+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
8,2021-02-11 21:00:00+00:00,2021-02-11 22:00:00+00:00,2021-02-11 21:02:13.195881+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
9,2021-02-11 20:00:00+00:00,2021-02-11 21:00:00+00:00,2021-02-11 20:57:55.329997+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
10,2021-02-11 19:00:00+00:00,2021-02-11 20:00:00+00:00,2021-02-11 19:34:16.085269+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
11,2021-02-11 18:00:00+00:00,2021-02-11 19:00:00+00:00,2021-02-11 18:10:41.638495+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
12,2021-02-11 17:00:00+00:00,2021-02-11 18:00:00+00:00,2021-02-11 17:46:46.849127+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
13,2021-02-11 16:00:00+00:00,2021-02-11 17:00:00+00:00,2021-02-11 16:02:11.279087+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
14,2021-02-11 15:00:00+00:00,2021-02-11 16:00:00+00:00,2021-02-11 16:00:11.193493+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
15,2021-02-11 14:00:00+00:00,2021-02-11 15:00:00+00:00,2021-02-11 14:00:49.388298+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
16,2021-02-11 13:00:00+00:00,2021-02-11 14:00:00+00:00,2021-02-11 13:02:16.246798+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
17,2021-02-11 12:00:00+00:00,2021-02-11 13:00:00+00:00,2021-02-11 12:12:08.004026+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
18,2021-02-11 11:00:00+00:00,2021-02-11 12:00:00+00:00,2021-02-11 11:29:26.900245+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite
19,2021-02-11 01:00:00+00:00,2021-02-11 02:00:00+00:00,2021-02-11 02:00:20.412994+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",7.2,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Records: 1230

======================================================================
🌡️ WRIST TEMPERATURE REPORT - iOS 16
======================================================================

,Start Timestamp,End Timestamp,Date Added,Wrist Temperature (C),Wrist Temperature (F),Algorithm Version,Surface Temperature (C),Surface Temperature (F),Source,Device Name,Device Manufacturer,Device Model,Hardware Version,Software Version,Source Database
0,2023-07-24 23:00:00+00:00,2023-07-25 00:00:00+00:00,2023-07-24 23:17:11.925372+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
1,2023-07-24 22:00:00+00:00,2023-07-24 23:00:00+00:00,2023-07-24 22:05:07.107679+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
2,2023-07-24 21:00:00+00:00,2023-07-24 22:00:00+00:00,2023-07-24 21:15:46.008675+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
3,2023-07-24 20:00:00+00:00,2023-07-24 21:00:00+00:00,2023-07-24 20:57:56.065636+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
4,2023-07-24 19:00:00+00:00,2023-07-24 20:00:00+00:00,2023-07-24 19:13:56.057842+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
5,2023-07-24 18:00:00+00:00,2023-07-24 19:00:00+00:00,2023-07-24 18:06:19.323911+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
6,2023-07-24 17:00:00+00:00,2023-07-24 18:00:00+00:00,2023-07-24 17:17:13.036421+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
7,2023-07-24 16:00:00+00:00,2023-07-24 17:00:00+00:00,2023-07-24 16:43:15.587573+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
8,2023-07-24 15:00:00+00:00,2023-07-24 16:00:00+00:00,2023-07-24 15:02:07.416230+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
9,2023-07-24 14:00:00+00:00,2023-07-24 15:00:00+00:00,2023-07-24 14:10:56.323571+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
10,2023-07-24 13:00:00+00:00,2023-07-24 14:00:00+00:00,2023-07-24 13:01:34.403480+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
11,2023-07-24 12:00:00+00:00,2023-07-24 13:00:00+00:00,2023-07-24 12:00:15.933027+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
12,2023-07-24 11:00:00+00:00,2023-07-24 12:00:00+00:00,2023-07-24 11:18:24.966465+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
13,2023-07-24 10:00:00+00:00,2023-07-24 11:00:00+00:00,2023-07-24 11:00:12.173037+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
14,2023-07-24 09:00:00+00:00,2023-07-24 10:00:00+00:00,2023-07-24 10:00:36.504496+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
15,2023-07-24 08:00:00+00:00,2023-07-24 09:00:00+00:00,2023-07-24 09:03:34.169255+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
16,2023-07-24 07:00:00+00:00,2023-07-24 08:00:00+00:00,2023-07-24 08:02:38.930103+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
17,2023-07-24 06:00:00+00:00,2023-07-24 07:00:00+00:00,2023-07-24 07:05:19.775803+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
18,2023-07-24 05:00:00+00:00,2023-07-24 06:00:00+00:00,2023-07-24 06:01:48.090936+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite
19,2023-07-24 04:00:00+00:00,2023-07-24 05:00:00+00:00,2023-07-24 05:01:34.269623+00:00,NaN,NaN,None,NaN,NaN,Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",8.8.1,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Records: 1603

======================================================================
🌡️ WRIST TEMPERATURE REPORT - iOS 17
======================================================================

,Start Timestamp,End Timestamp,Date Added,Wrist Temperature (C),Wrist Temperature (F),Algorithm Version,Surface Temperature (C),Surface Temperature (F),Source,Device Name,Device Manufacturer,Device Model,Hardware Version,Software Version,Source Database
0,2024-07-26 13:00:00+00:00,2024-07-26 14:00:00+00:00,2024-07-26 13:04:31.530627+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
1,2024-07-26 12:00:00+00:00,2024-07-26 13:00:00+00:00,2024-07-26 12:17:48.485391+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
2,2024-07-26 11:00:00+00:00,2024-07-26 12:00:00+00:00,2024-07-26 11:14:36.238916+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
3,2024-07-26 10:00:00+00:00,2024-07-26 11:00:00+00:00,2024-07-26 11:00:02.788227+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
4,2024-07-26 09:00:00+00:00,2024-07-26 10:00:00+00:00,2024-07-26 10:00:10.546567+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
5,2024-07-26 08:00:00+00:00,2024-07-26 09:00:00+00:00,2024-07-26 09:02:23.191897+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
6,2024-07-26 07:00:00+00:00,2024-07-26 08:00:00+00:00,2024-07-26 08:00:34.732430+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
7,2024-07-26 06:00:00+00:00,2024-07-26 07:00:00+00:00,2024-07-26 07:01:24.129199+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
8,2024-07-26 05:00:00+00:00,2024-07-26 06:00:00+00:00,2024-07-26 06:06:35.239022+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
9,2024-07-26 04:00:00+00:00,2024-07-26 05:00:00+00:00,2024-07-26 05:05:07.903552+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
10,2024-07-26 03:00:00+00:00,2024-07-26 04:00:00+00:00,2024-07-26 04:05:01.711017+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
11,2024-07-26 02:00:00+00:00,2024-07-26 03:00:00+00:00,2024-07-26 03:00:07.706336+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
12,2024-07-25 22:00:00+00:00,2024-07-25 23:00:00+00:00,2024-07-25 22:01:00.993584+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
13,2024-07-25 21:00:00+00:00,2024-07-25 22:00:00+00:00,2024-07-25 21:00:25.899848+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
14,2024-07-25 20:00:00+00:00,2024-07-25 21:00:00+00:00,2024-07-25 20:22:12.933797+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
15,2024-07-25 19:00:00+00:00,2024-07-25 20:00:00+00:00,2024-07-25 19:02:20.440447+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
16,2024-07-25 18:00:00+00:00,2024-07-25 19:00:00+00:00,2024-07-25 18:07:40.798094+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
17,2024-07-25 17:00:00+00:00,2024-07-25 18:00:00+00:00,2024-07-25 17:03:21.577280+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
18,2024-07-25 16:00:00+00:00,2024-07-25 17:00:00+00:00,2024-07-25 16:54:02.576617+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite
19,2024-07-25 15:00:00+00:00,2024-07-25 16:00:00+00:00,2024-07-25 15:50:35.835786+00:00,NaN,NaN,None,NaN,NaN,This Iss Apple Watch,Apple Watch,Apple Inc.,Watch,"Watch4,3",9.6.3,healthdb_secure.sqlite + healthdb.sqlite

📊 Total Records: 1688

# **Membuat Laporan Linimasa Forensik File Excel**

In [ ]:
# ============================================================
# FOLDER OUTPUT
# ============================================================

output_folder = "/content/apple_health_output"

os.makedirs(
    output_folder,
    exist_ok=True
)


# ============================================================
# FUNGSI KONVERSI TIMESTAMP UNTUK EXCEL
# ============================================================

def datetime_to_excel_string(value):
    """
    Mengubah datetime timezone-aware menjadi string.

    Contoh:
    2020-04-03 19:37:50+00:00

    Hal ini diperlukan karena Excel tidak dapat
    menyimpan datetime yang masih memiliki timezone.
    """

    if pd.isna(value):
        return None

    try:
        return value.strftime(
            "%Y-%m-%d %H:%M:%S+00:00"
        )

    except (AttributeError, ValueError):
        return str(value)


# ============================================================
# SUMMARY DATA
# ============================================================

summary_data = []

**Achievements**

In [ ]:
# ============================================================
# SIAPKAN ACHIEVEMENTS
# ============================================================

all_achievement_reports = []


for version, df_report in achievement_reports.items():

    df_export = df_report.copy()


    # --------------------------------------------------------
    # Timestamp → String
    # --------------------------------------------------------

    if "Created Timestamp" in df_export.columns:

        df_export[
            "Created Timestamp"
        ] = (
            df_export[
                "Created Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Tambahkan versi iOS
    # --------------------------------------------------------

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_achievement_reports.append(
        df_export
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Achievements",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


# Gabungkan seluruh versi
df_achievements_excel = pd.concat(
    all_achievement_reports,
    ignore_index=True
)

/tmp/ipykernel_26837/1740167284.py:69: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_achievements_excel = pd.concat(

**All Watch Sleep**

In [ ]:
# ============================================================
# SIAPKAN ALL WATCH SLEEP
# ============================================================

all_sleep_reports = []


for version, df_report in all_watch_sleep_reports.items():

    df_export = df_report.copy()


    # --------------------------------------------------------
    # Start Timestamp
    # --------------------------------------------------------

    if "Start Timestamp" in df_export.columns:

        df_export[
            "Start Timestamp"
        ] = (
            df_export[
                "Start Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # End Timestamp
    # --------------------------------------------------------

    if "End Timestamp" in df_export.columns:

        df_export[
            "End Timestamp"
        ] = (
            df_export[
                "End Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Tambahkan versi iOS
    # --------------------------------------------------------

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_sleep_reports.append(
        df_export
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "All Watch Sleep",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


# Gabungkan seluruh versi
df_sleep_excel = pd.concat(
    all_sleep_reports,
    ignore_index=True
)

**Headphone Audio Levels**

In [ ]:
# ============================================================
# SIAPKAN HEADPHONE AUDIO LEVELS
# ============================================================

all_headphone_audio_reports = []


for version, df_report in headphone_audio_reports.items():

    df_export = df_report.copy()


    # --------------------------------------------------------
    # Start Timestamp
    # --------------------------------------------------------

    if "Start Timestamp" in df_export.columns:

        df_export[
            "Start Timestamp"
        ] = (
            df_export[
                "Start Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # End Timestamp
    # --------------------------------------------------------

    if "End Timestamp" in df_export.columns:

        df_export[
            "End Timestamp"
        ] = (
            df_export[
                "End Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Tambahkan versi iOS
    # --------------------------------------------------------

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_headphone_audio_reports.append(
        df_export
    )


    # --------------------------------------------------------
    # Summary
    #
    # Fitur ini mengambil data dari 2 database.
    # --------------------------------------------------------

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Headphone Audio Levels",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite + healthdb.sqlite"

    })


# Gabungkan seluruh versi
df_headphone_audio_excel = pd.concat(
    all_headphone_audio_reports,
    ignore_index=True
)

**Heart Rate**

In [ ]:
# ============================================================
# SIAPKAN HEART RATE UNTUK EXCEL
# ============================================================

all_heart_rate_reports = []


for version, df_report in heart_rate_reports.items():

    df_export = df_report.copy()


    # --------------------------------------------------------
    # Start Timestamp
    # --------------------------------------------------------

    if "Start Timestamp" in df_export.columns:

        df_export[
            "Start Timestamp"
        ] = (
            df_export[
                "Start Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # End Timestamp
    # --------------------------------------------------------

    if "End Timestamp" in df_export.columns:

        df_export[
            "End Timestamp"
        ] = (
            df_export[
                "End Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Added Timestamp
    # --------------------------------------------------------

    if "Added Timestamp" in df_export.columns:

        df_export[
            "Added Timestamp"
        ] = (
            df_export[
                "Added Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Tambahkan versi iOS
    # --------------------------------------------------------

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_heart_rate_reports.append(
        df_export
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Heart Rate",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite + healthdb.sqlite"

    })


# Gabungkan semua versi
df_heart_rate_excel = pd.concat(
    all_heart_rate_reports,
    ignore_index=True
)

**Height**

In [ ]:
# ============================================================
# SIAPKAN HEIGHT UNTUK EXCEL
# ============================================================

all_height_reports = []


for version, df_report in height_reports.items():

    df_export = df_report.copy()


    # --------------------------------------------------------
    # Timestamp
    # --------------------------------------------------------

    if "Timestamp" in df_export.columns:

        df_export[
            "Timestamp"
        ] = (
            df_export[
                "Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )
        )


    # --------------------------------------------------------
    # Tambahkan versi iOS
    # --------------------------------------------------------

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_height_reports.append(
        df_export
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Height",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


# Gabungkan semua versi
df_height_excel = pd.concat(
    all_height_reports,
    ignore_index=True
)

**Resting Heart Rate**

In [ ]:
# ============================================================
# SIAPKAN RESTING HEART RATE UNTUK EXCEL
# ============================================================


all_resting_hr_reports = []


for version, df_report in resting_hr_reports.items():


    df_export = df_report.copy()



    for col in [

        "Start Timestamp",

        "End Timestamp",

        "Added Timestamp"

    ]:


        if col in df_export.columns:


            df_export[col] = (

                df_export[col]
                .apply(
                    datetime_to_excel_string
                )

            )



    df_export.insert(
        0,
        "iOS Version",
        version
    )



    all_resting_hr_reports.append(
        df_export
    )



    summary_data.append({

        "iOS Version":
            version,


        "Feature":
            "Resting Heart Rate",


        "Total Events":
            len(df_report),


        "Source Database":
            "healthdb_secure.sqlite + healthdb.sqlite"

    })



df_resting_hr_excel = pd.concat(

    all_resting_hr_reports,

    ignore_index=True

)

**Source Devices**

In [ ]:
# ============================================================
# SIAPKAN SOURCE DEVICES UNTUK EXCEL
# ============================================================


all_source_devices_reports = []


for version, df_report in source_devices_reports.items():


    df_export = df_report.copy()



    if "Creation Timestamp" in df_export.columns:


        df_export[
            "Creation Timestamp"
        ] = (

            df_export[
                "Creation Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )



    df_export.insert(

        0,

        "iOS Version",

        version

    )



    all_source_devices_reports.append(
        df_export
    )



    summary_data.append({

        "iOS Version":

            version,


        "Feature":

            "Source Devices",


        "Total Events":

            len(df_report),


        "Source Database":

            "healthdb.sqlite"

    })



df_source_devices_excel = pd.concat(

    all_source_devices_reports,

    ignore_index=True

)

**Steps**

In [ ]:
# ============================================================
# SIAPKAN STEPS UNTUK EXCEL
# ============================================================


all_steps_reports = []


for version, df_report in steps_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT START TIMESTAMP
    # ========================================================

    if "Start Timestamp" in df_export.columns:

        df_export[
            "Start Timestamp"
        ] = (

            df_export[
                "Start Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # FORMAT END TIMESTAMP
    # ========================================================

    if "End Timestamp" in df_export.columns:

        df_export[
            "End Timestamp"
        ] = (

            df_export[
                "End Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # TAMBAHKAN VERSI IOS
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_steps_reports.append(
        df_export
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Steps",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


df_steps_excel = pd.concat(
    all_steps_reports,
    ignore_index=True
)


print(
    "✅ Data Steps siap untuk Excel."
)

✅ Data Steps siap untuk Excel.

**Watch by Sleep Period**

In [ ]:
# ============================================================
# SIAPKAN WATCH BY SLEEP PERIOD UNTUK EXCEL
# ============================================================


all_watch_sleep_reports = []


for version, df_report in watch_sleep_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT START TIMESTAMP
    # ========================================================

    if "Start Timestamp" in df_export.columns:

        df_export[
            "Start Timestamp"
        ] = (

            df_export[
                "Start Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # FORMAT END TIMESTAMP
    # ========================================================

    if "End Timestamp" in df_export.columns:

        df_export[
            "End Timestamp"
        ] = (

            df_export[
                "End Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # IOS VERSION
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_watch_sleep_reports.append(
        df_export
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Watch By Sleep Period",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


df_watch_sleep_excel = pd.concat(
    all_watch_sleep_reports,
    ignore_index=True
)


print(
    "✅ Watch By Sleep Period siap untuk Excel."
)

✅ Watch By Sleep Period siap untuk Excel.

/tmp/ipykernel_26837/544433468.py:91: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_watch_sleep_excel = pd.concat(

**Watch Worn Data**

In [ ]:
# ============================================================
# SIAPKAN WATCH WORN DATA UNTUK EXCEL
# ============================================================


all_watch_worn_reports = []


for version, df_report in watch_worn_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT START TIME
    # ========================================================

    if "Start Time" in df_export.columns:

        df_export[
            "Start Time"
        ] = (

            df_export[
                "Start Time"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # FORMAT LAST WORN TIME
    # ========================================================

    if "Last Worn Time" in df_export.columns:

        df_export[
            "Last Worn Time"
        ] = (

            df_export[
                "Last Worn Time"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # IOS VERSION
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_watch_worn_reports.append(
        df_export
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Watch Worn Data",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


df_watch_worn_excel = pd.concat(
    all_watch_worn_reports,
    ignore_index=True
)


print(
    "✅ Watch Worn Data siap untuk Excel."
)

✅ Watch Worn Data siap untuk Excel.

**Weight**

In [ ]:
# ============================================================
# SIAPKAN WEIGHT UNTUK EXCEL
# ============================================================


all_weight_reports = []


for version, df_report in weight_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT TIMESTAMP
    # ========================================================

    if "Timestamp" in df_export.columns:

        df_export[
            "Timestamp"
        ] = (

            df_export[
                "Timestamp"
            ]
            .apply(
                datetime_to_excel_string
            )

        )


    # ========================================================
    # IOS VERSION
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_weight_reports.append(
        df_export
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Weight",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite"

    })


df_weight_excel = pd.concat(
    all_weight_reports,
    ignore_index=True
)


print(
    "✅ Weight siap untuk Excel."
)

✅ Weight siap untuk Excel.

**Workouts**

In [ ]:
# ============================================================
# SIAPKAN WORKOUTS UNTUK EXCEL
# ============================================================


all_workouts_reports = []


for version, df_report in workouts_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT TIMESTAMPS
    # ========================================================

    timestamp_columns = [

        "Start Timestamp",

        "End Timestamp",

        "Added Timestamp"

    ]


    for column_name in timestamp_columns:

        if column_name in df_export.columns:

            df_export[
                column_name
            ] = (

                df_export[
                    column_name
                ]
                .apply(
                    datetime_to_excel_string
                )

            )


    # ========================================================
    # IOS VERSION
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_workouts_reports.append(
        df_export
    )


    # ========================================================
    # SOURCE DATABASE SUMMARY
    # ========================================================

    major_version = get_ios_major_version(
        version
    )


    if major_version in (16, 17):

        source_database = (
            "healthdb_secure.sqlite + healthdb.sqlite"
        )

    else:

        source_database = (
            "healthdb_secure.sqlite"
        )


    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Workouts",

        "Total Events":
            len(df_report),

        "Source Database":
            source_database

    })


df_workouts_excel = pd.concat(
    all_workouts_reports,
    ignore_index=True
)


print(
    "✅ Workouts siap untuk Excel."
)

✅ Workouts siap untuk Excel.

/tmp/ipykernel_26837/2310991228.py:102: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_workouts_excel = pd.concat(

**Wrist Temperature**

In [ ]:
# ============================================================
# SIAPKAN WRIST TEMPERATURE UNTUK EXCEL
# ============================================================


all_wrist_temperature_reports = []


for version, df_report in wrist_temperature_reports.items():

    df_export = df_report.copy()


    # ========================================================
    # FORMAT TIMESTAMPS
    # ========================================================

    timestamp_columns = [

        "Start Timestamp",

        "End Timestamp",

        "Date Added"

    ]


    for column_name in timestamp_columns:

        if column_name in df_export.columns:

            df_export[
                column_name
            ] = (

                df_export[
                    column_name
                ]
                .apply(
                    datetime_to_excel_string
                )

            )


    # ========================================================
    # IOS VERSION
    # ========================================================

    df_export.insert(
        0,
        "iOS Version",
        version
    )


    all_wrist_temperature_reports.append(
        df_export
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    summary_data.append({

        "iOS Version":
            version,

        "Feature":
            "Wrist Temperature",

        "Total Events":
            len(df_report),

        "Source Database":
            "healthdb_secure.sqlite + healthdb.sqlite"

    })


df_wrist_temperature_excel = pd.concat(

    all_wrist_temperature_reports,

    ignore_index=True

)


print(
    "✅ Wrist Temperature siap untuk Excel."
)

✅ Wrist Temperature siap untuk Excel.

In [ ]:
# ============================================================
# BUAT DATAFRAME SUMMARY
# ============================================================

df_summary = pd.DataFrame(
    summary_data
)

In [ ]:
# ============================================================
# HITUNG TOTAL EVENT
# ============================================================

total_achievement_events = len(
    df_achievements_excel
)

total_sleep_events = len(
    df_sleep_excel
)

total_headphone_events = len(
    df_headphone_audio_excel
)

total_heart_rate_events = len(
    df_heart_rate_excel
)

total_height_events = len(
    df_height_excel
)

total_resting_hr_events = len(
    df_resting_hr_excel
)

total_source_devices_events = len(
    df_source_devices_excel
)

total_steps_events = len(
    df_steps_excel
)

total_watch_sleep_events = len(
    df_watch_sleep_excel
)

total_watch_worn_events = len(
    df_watch_worn_excel
)

total_weight_events = len(
    df_weight_excel
)

total_workouts_events = len(
    df_workouts_excel
)

total_wrist_temperature_events = len(
    df_wrist_temperature_excel
)


total_all_events = (

    total_achievement_events
    +
    total_sleep_events
    +
    total_headphone_events
    +
    total_heart_rate_events
    +
    total_height_events
    +
    total_resting_hr_events
    +
    total_source_devices_events
    +
    total_steps_events
    +
    total_watch_sleep_events
    +
    total_watch_worn_events
    +
    total_weight_events
    +
    total_workouts_events
    +
    total_wrist_temperature_events

)

In [ ]:
# ============================================================
# 9. TENTUKAN NAMA FILE
# ============================================================

if pilihan_ios == "Semua Versi (Semua Dataset)":

    output_filename = (
        "Apple_Health_Forensic_Report_All_iOS.xlsx"
    )

else:

    ios_filename = (
        pilihan_ios
        .replace(" ", "_")
        .replace(".", "_")
    )


    output_filename = (
        f"Apple_Health_Forensic_Report_{ios_filename}.xlsx"
    )


output_path = os.path.join(
    output_folder,
    output_filename
)

In [ ]:
# ============================================================
# 10. EXPORT KE FILE EXCEL
# ============================================================

with pd.ExcelWriter(
    output_path,
    engine="openpyxl"
) as writer:


    # --------------------------------------------------------
    # SHEET 1 - SUMMARY
    # --------------------------------------------------------

    df_summary.to_excel(
        writer,
        sheet_name="Summary",
        index=False
    )


    # --------------------------------------------------------
    # SHEET 2 - ACHIEVEMENTS
    # --------------------------------------------------------

    df_achievements_excel.to_excel(
        writer,
        sheet_name="Achievements",
        index=False
    )


    # --------------------------------------------------------
    # SHEET 3 - ALL WATCH SLEEP
    # --------------------------------------------------------

    df_sleep_excel.to_excel(
        writer,
        sheet_name="All Watch Sleep",
        index=False
    )


    # --------------------------------------------------------
    # SHEET 4 - HEADPHONE AUDIO
    # --------------------------------------------------------

    df_headphone_audio_excel.to_excel(
        writer,
        sheet_name="Headphone Audio",
        index=False
    )


    # --------------------------------------------------------
    # SHEET 5 - HEART RATE
    # --------------------------------------------------------

    df_heart_rate_excel.to_excel(
        writer,
        sheet_name="Heart Rate",
        index=False
    )


    # --------------------------------------------------------
    # SHEET 6 - HEIGHT
    # --------------------------------------------------------

    df_height_excel.to_excel(
        writer,
        sheet_name="Height",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 7 - RESTING HEART RATE
    # --------------------------------------------------------

    df_resting_hr_excel.to_excel(
        writer,
        sheet_name="Resting Heart Rate",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 8 - SOURCE DEVICES
    # --------------------------------------------------------

    df_source_devices_excel.to_excel(
        writer,
        sheet_name="Source Devices",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 9 - STEPS
    # --------------------------------------------------------

    df_steps_excel.to_excel(
        writer,
        sheet_name="Steps",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 10 - WATCH BY SLEEP PERIOD
    # --------------------------------------------------------

    df_watch_sleep_excel.to_excel(
        writer,
        sheet_name="Watch Sleep Period",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 11 - WATCH WORN DATA
    # --------------------------------------------------------

    df_watch_worn_excel.to_excel(
        writer,
        sheet_name="Watch Worn Data",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 12 - WEIGHT
    # --------------------------------------------------------

    df_weight_excel.to_excel(
        writer,
        sheet_name="Weight",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 13 - WORKOUTS
    # --------------------------------------------------------

    df_workouts_excel.to_excel(
        writer,
        sheet_name="Workouts",
        index=False
    )

    # --------------------------------------------------------
    # SHEET 14 - WRIST TEMPERATURE
    # --------------------------------------------------------

    df_wrist_temperature_excel.to_excel(
        writer,
        sheet_name="Wrist Temperature",
        index=False
    )

In [ ]:
# ============================================================
# 11. INFORMASI HASIL EXPORT
# ============================================================

print()
print("=" * 70)
print("📄 LAPORAN APPLE HEALTH BERHASIL DIBUAT")
print("=" * 70)

print(
    f"📁 File : {output_filename}"
)

print(
    f"📍 Path : {output_path}"
)

print()

print(
    f"🏆 Achievements Events       : "
    f"{total_achievement_events}"
)

print(
    f"😴 All Watch Sleep Events    : "
    f"{total_sleep_events}"
)

print(
    f"🎧 Headphone Audio Events    : "
    f"{total_headphone_events}"
)

print(
    f"❤️ Heart Rate Events         : "
    f"{total_heart_rate_events}"
)

print(
    f"📏 Height Events             : "
    f"{total_height_events}"
)

print(
    f"❤️‍🩹 Resting HR Events         : "
    f"{total_resting_hr_events}"
)

print(
    f"📱 Source Devices Events     : "
    f"{total_source_devices_events}"
)

print(
    f"🚶 Steps Events              : "
    f"{total_steps_events}"
)

print(
    f"⌚ Watch Sleep Period Events : "
    f"{total_watch_sleep_events}"
)

print(
    f"⌚ Watch Worn Data Events    : "
    f"{total_watch_worn_events}"
)

print(
    f"⚖️ Weight Events             : "
    f"{total_weight_events}"
)

print(
    f"🏋️ Workouts Events           : "
    f"{total_workouts_events}"
)

print(
    f"🌡️ Wrist Temperature Events   : "
    f"{total_wrist_temperature_events}"
)

print("-" * 70)

print(
    f"📊 TOTAL EVENTS              : "
    f"{total_all_events}"
)

print("=" * 70)

======================================================================
📄 LAPORAN APPLE HEALTH BERHASIL DIBUAT
======================================================================
📁 File : Apple_Health_Forensic_Report_All_iOS.xlsx
📍 Path : /content/apple_health_output/Apple_Health_Forensic_Report_All_iOS.xlsx

🏆 Achievements Events       : 84
😴 All Watch Sleep Events    : 723
🎧 Headphone Audio Events    : 86
❤️ Heart Rate Events         : 100828
📏 Height Events             : 5
❤️‍🩹 Resting HR Events         : 317
📱 Source Devices Events     : 77
🚶 Steps Events              : 58762
⌚ Watch Sleep Period Events : 27
⌚ Watch Worn Data Events    : 171
⚖️ Weight Events             : 5553
🏋️ Workouts Events           : 82
🌡️ Wrist Temperature Events : 5000
----------------------------------------------------------------------
📊 TOTAL EVENTS              : 171715
======================================================================

In [ ]:
# ============================================================
# FORMAT FILE EXCEL
# ============================================================

from openpyxl import load_workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Alignment,
    Border,
    Side
)


# Buka workbook yang tadi dibuat
workbook = load_workbook(
    output_path
)


# Warna header
header_fill = PatternFill(
    fill_type="solid",
    fgColor="1F4E78"
)

header_font = Font(
    color="FFFFFF",
    bold=True
)

thin_border = Border(
    bottom=Side(
        style="thin",
        color="D9D9D9"
    )
)


# ------------------------------------------------------------
# FORMAT SEMUA SHEET
# ------------------------------------------------------------

for worksheet in workbook.worksheets:

    # Freeze header
    worksheet.freeze_panes = "A2"

    # Aktifkan filter
    worksheet.auto_filter.ref = (
        worksheet.dimensions
    )


    # Format header
    for cell in worksheet[1]:

        cell.fill = header_fill
        cell.font = header_font

        cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )


    # Format isi
    for row in worksheet.iter_rows(
        min_row=2
    ):

        for cell in row:

            cell.alignment = Alignment(
                vertical="top"
            )

            cell.border = thin_border


    # Auto width sederhana
    for column_cells in worksheet.columns:

        max_length = 0

        column_letter = (
            column_cells[0].column_letter
        )


        for cell in column_cells:

            try:

                cell_length = len(
                    str(cell.value)
                )

                if cell_length > max_length:
                    max_length = cell_length

            except:
                pass


        # Batasi agar kolom tidak terlalu lebar
        adjusted_width = min(
            max_length + 2,
            45
        )

        worksheet.column_dimensions[
            column_letter
        ].width = adjusted_width


workbook.save(
    output_path
)


print(
    "✅ Format Excel berhasil dirapikan."
)

✅ Format Excel berhasil dirapikan.

In [ ]:
# ============================================================
# DOWNLOAD FILE EXCEL
# ============================================================

from google.colab import files


print(
    f"⬇️ Downloading: {output_filename}"
)


files.download(
    output_path
)

⬇️ Downloading: Apple_Health_Forensic_Report_All_iOS.xlsx